### DISCUSSION TITLE
Official github actions to setup poetry and project in github actions?

### DISCUSSION THREAD

**Discussion by trim21** [python-poetry/poetry#10039] [General]
pdm has https://github.com/pdm-project/setup-pdm and uv has https://github.com/astral-sh/setup-uv

Is is possible to have a setup-poetry to install a poetry, install packages to virtualenv/use system python and handle cache?

I can work on it, if it's an acceptable idea.

**Comment by abn** [comment]
You could do something like this right now perhaps?

```yaml
name: Poetry Project Testing

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Bootstrap Poetry
      uses: python-poetry/poetry/.github/actions/bootstrap-poetry@main
      
    - name: Install Project
      uses: python-poetry/poetry/.github/actions/poetry-install@main
```
