### DISCUSSION TITLE
Support for Conditional Script Installation in pyproject.toml

### DISCUSSION THREAD

**Discussion by samidarko** [python-poetry/poetry#10099] [General]
I'm seeking guidance on configuring `pyproject.toml` to conditionally install specific command-line scripts based on the installation context. In my project, I have several scripts defined under `[tool.poetry.scripts]`:

```toml
[tool.poetry.scripts]
dbk = 'dbk:main'
coverage-report = 'scripts:coverage_report'
format = 'scripts:code_format'
format-check = 'scripts:code_format_check'
lint = 'scripts:lint'
test = 'scripts:test'
type-check = 'scripts:type_check'
```

When installing the package using `pipx`, all these commands become globally available. However, I intend for only the `dbk` command to be accessible in this context, while the other commands should remain available for development and continuous integration (CI) environments.

I understand that Poetry currently installs all scripts specified in `[tool.poetry.scripts]` without conditional inclusion. Is there an existing method or a recommended best practice to achieve this selective script installation? If not, would it be feasible to consider implementing a feature that allows for conditional script installation based on extras or environment markers?

This functionality would enhance the flexibility of package installations, ensuring that end-users receive only the necessary command-line tools, while developers and CI pipelines retain access to the full suite of scripts.

I appreciate any insights or suggestions the community can provide on this matter.
