### DISCUSSION TITLE
dependency-groups - pep vs poetry(v2)

### DISCUSSION THREAD

**Discussion by etele** [python-poetry/poetry#10101] [General] [answered]
Hi,

[Pep](https://peps.python.org/pep-0735/#rationale) an [packaging user guide](https://packaging.python.org/en/latest/specifications/dependency-groups/#specification) has a specification how `dependency-groups` should be organized in pyproject.toml. 
Poetry 2.0 got closer to these PEPs specifications, but this is not so.

how poetry has it:
```toml
[tool.poetry.group.dev.dependencies]
mypy = "^1.14.1"
```

how it would be according to PEP-0735:
```toml
[dependency-groups]
dev = [
    "mypy>=1.14.1",
]
```
it would be nice to have it according to PEP, would be compatible with other tools.

Can we expect this in the future? 
Or is there a reason not to do as pep states?

thanks in advance
