### DISCUSSION TITLE
Plugin to migrate pyproject.toml from Poetry v1 to v2 (PEP-621 compliant)

### DISCUSSION THREAD

**Discussion by zyf722** [python-poetry/poetry#10115] [Show and tell]
Hello to the community!

I've created a simple plugin for Poetry that helps you migrate your `pyproject.toml` files from Poetry v1 to v2 with [PEP-621 standards](https://python-poetry.org/blog/announcing-poetry-2.0.0/#supporting-the-project-section-in-pyprojecttoml-pep-621).

With `poetry migrate` and an interactive CLI, you can easily migrate your `pyproject.toml` files from:

```toml
[tool.poetry]
name = "simple-project"
version = "1.2.3"
description = "Test project for poetry-plugin-migrate"
license = "MIT"
authors = [
    "Dev Guy <dev.guy@example.com>",
    "Test Guy <test.guy@example.com>",
]
maintainers = [
    "Maintainer One <maintainer.one@example.com>",
]
readme = "README.md"
homepage = "https://example.com/"
repository = "https://github.com/zyf722/poetry-plugin-migrate"
keywords = ["we", "just", "need", "some", "keywords"]
classifiers = [
    "Development Status :: 4 - Beta",
]

[tool.poetry.scripts]
main = "simple_project.__main__:main"

[[tool.poetry.source]]
name = "private"
url = "http://a.source.too.secret/simple"
priority = "supplemental"

[tool.poetry.dependencies]
python = "^3.9"
private-package = { version = "^1.0", source = "private" }
requests = "^2.0"
httpx = { version = "^0.23", python = "^3.9" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

to

```toml
[tool.poetry]
version = "1.2.3"
classifiers = [
    "Development Status :: 4 - Beta",
]
requires-poetry = '>=2.0.0,<3.0.0'

[[tool.poetry.source]]
name = "private"
url = "http://a.source.too.secret/simple"
priority = "supplemental"

[tool.poetry.dependencies]
python = "^3.9"
private-package = {  source = "private" }

[build-system]
requires = ['poetry-core (>=2.0.0,<3.0.0)']
build-backend = "poetry.core.masonry.api"

[project]
name = "simple-project"
description = "Test project for poetry-plugin-migrate"
license = "MIT"
keywords = ["we", "just", "need", "some", "keywords"]
dynamic = ["version", "classifiers"]
readme = "README.md"
authors = [{name = "Test Guy", email = "test.guy@example.com"}, {name = "Dev Guy", email = "dev.guy@example.com"}]
maintainers = [{name = "Maintainer One", email = "maintainer.one@example.com"}]
requires-python = '>=3.9,<4.0'
dependencies = ['private-package (>=1.0,<2.0)', 'requests (>=2.0,<3.0)', 'httpx (>=0.23,<0.24) ; python_version >= "3.9" and python_version < "4.0"']

[project.urls]
homepage = "https://example.com/"
repository = "https://github.com/zyf722/poetry-plugin-migrate"

[project.scripts]
main = "simple_project.__main__:main"
```

Feel free to check it out if you think it could be useful: https://github.com/zyf722/poetry-plugin-migrate
