### DISCUSSION TITLE
How to use poetry 2.1.1 in an offline environment?

### DISCUSSION THREAD

**Discussion by rydy** [python-poetry/poetry#10288] [Q&A]
Hi，
I need to use Poetry (version 2.1.1) in an offline environment. All project dependencies are stored in the vendor directory. My pyproject.toml is configured as follows:

```toml
[project]
name = "equipment-software-server"
version = "0.1.0"
description = ""
authors = [
    {name = "yangrui"}
]
readme = "README.txt"
requires-python = ">=3.10"
dependencies = [
    "grpcio @ vendor/prj_deps/grpc/grpcio-1.71.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "protobuf @ vendor/prj_deps/grpc/protobuf-5.29.3-cp38-abi3-manylinux2014_x86_64.whl",

    "jsonpointer @ vendor/prj_deps/redfish/jsonpointer-3.0.0-py2.py3-none-any.whl",
    "requests @ vendor/prj_deps/redfish/requests-2.32.3-py3-none-any.whl",
    "requests_toolbelt @ vendor/prj_deps/redfish/requests_toolbelt-1.0.0-py2.py3-none-any.whl",
    "requests_unixsocket @ vendor/prj_deps/redfish/requests_unixsocket-0.4.1-py3-none-any.whl",
    "jsonpatch @ vendor/prj_deps/redfish/jsonpatch-1.33-py2.py3-none-any.whl",
    "ply @ vendor/prj_deps/redfish/ply-3.11-py2.py3-none-any.whl",
    "decorator @ vendor/prj_deps/redfish/decorator-5.2.1-py3-none-any.whl",
    "six @ vendor/prj_deps/redfish/six-1.17.0-py2.py3-none-any.whl",
    "charset_normalizer @ vendor/prj_deps/redfish/charset_normalizer-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "idna @ vendor/prj_deps/redfish/idna-3.10-py3-none-any.whl",
    "urllib3 @ vendor/prj_deps/redfish/urllib3-2.3.0-py3-none-any.whl",
    "certifi @ vendor/prj_deps/redfish/certifi-2025.1.31-py3-none-any.whl",
    "redfish @ vendor/prj_deps/redfish/redfish-3.2.9-py3-none-any.whl"
]

[tool.poetry.group.dev.dependencies]
setuptools = {path = "vendor/prj_deps/grpc/setuptools-76.0.0-py3-none-any.whl"}
grpcio-tools = {path = "vendor/prj_deps/grpc/grpcio_tools-1.71.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"}

exceptiongroup = {path = "vendor/prj_deps/pytest/exceptiongroup-1.2.2-py3-none-any.whl"}
iniconfig = {path = "vendor/prj_deps/pytest/iniconfig-2.0.0-py3-none-any.whl"}
packaging = {path = "vendor/prj_deps/pytest/packaging-24.2-py3-none-any.whl"}
pluggy = {path = "vendor/prj_deps/pytest/pluggy-1.5.0-py3-none-any.whl"}
tomli = {path = "vendor/prj_deps/pytest/tomli-2.2.1-py3-none-any.whl"}
pytest = {path = "vendor/prj_deps/pytest/pytest-8.3.5-py3-none-any.whl"}

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
```

When running poetry update, Poetry attempts to connect to PyPI and fails. How do I configure Poetry to work offline?

```
poetry update
Updating dependencies
Resolving dependencies... (7.5s)

All attempts to connect to pypi.org failed.

Probable Causes:
    - the server is not responding to requests at the moment
    - the hostname cannot be resolved by your DNS
    - your network is not connected to the internet

You can also run your poetry command with -v to see more information.
```

Thanks.
