### DISCUSSION TITLE
When trying to run 'poetry shell' on github CI, I get a   (25, 'Inappropriate ioctl for device') error

### DISCUSSION THREAD

**Discussion by assuiedmilan** [python-poetry/poetry#3526] [Q&A] [answered]
I am trying to run the following python-package.yl script:

```
name: Python package

on:
  push:
    branches:
    - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        python -m poetry install
    - name: Lint with pylint
      run: |
        poetry shell
        pylint numeric_matrix_processor --rcfile=.pylintrc
        pylint tests --rcfile=.pylintrc
    - name: Test with pytest
      run: |
        poetry shell
        pytest
    - name: Build wheel
      run: |
        poetry build
```

At the line, `poetry shell` I have the following error:

> Run poetry shell
> Spawning shell within /home/runner/.cache/pypoetry/virtualenvs/numericmatrixprocessor-Gxa0VRVS-py3.8
> 
>   error
> 
>   (25, 'Inappropriate ioctl for device')
> 
>   at /opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/pexpect/pty_spawn.py:788 in interact
>       784│         # Flush the buffer.
>       785│         self.write_to_stdout(self.buffer)
>       786│         self.stdout.flush()
>       787│         self._buffer = self.buffer_type()
>     → 788│         mode = tty.tcgetattr(self.STDIN_FILENO)
>       789│         tty.setraw(self.STDIN_FILENO)
>       790│         if escape_character is not None and PY3:
>       791│             escape_character = escape_character.encode('latin-1')
>       792│         try:
> Error: Process completed with exit code 1.

Why is that ?
