### DISCUSSION TITLE
How can I include all packages from `src` automatically ?

### DISCUSSION THREAD

**Discussion by aahnik** [python-poetry/poetry#3923] [Q&A] [answered]
I am currently doing this: (using the `src` layout. and my `src` directory has multiple packages)

```toml
# pyproject.toml
name = "custom-learn-p"
packages = [
    {include = "another_p",from="src"},
    {include = "custom_learn_p",from="src"}
            ]
```

is there a way to automatically include all the packages inside src, except the excluded ones obviously?

Like, below is the `setup.py` equivalent.

```python
# setup.py
setup(
    [...]
    packages=find_packages(where="src"),
    package_dir={"": "src"},
)
```

I am planning to use the `src` layout after reading this: https://hynek.me/articles/testing-packaging/ by @hynek 

I would love to know more about effectively using the `src` layout with `poetry`. 

If you have some experience with packaging in this layout, with `poetry` please tell me (or link) some tips and pitfalls.

Thanks a lot for your time.
