### DISCUSSION TITLE
Remove dependencies not listed in --extras

### DISCUSSION THREAD

**Discussion by NixBiks** [python-poetry/poetry#4069] [Q&A]
Currently if you do `poetry install` then you install both dependencies and dev dependencies. If you then do `poetry install --no-dev` then dev dependencies are removed.

It is a different behavior when using `--extras`. Imagine I have toml like this

```toml
[tool.poetry.dependencies]
python = "^3.9"
fastapi = {version = "^0.65.1", optional = true}
uvicorn = {version = "^0.13.4", optional = true}
gunicorn = {version = "^20.1.0", optional = true}
pydantic = {version = "^1.8.2", optional = true}

[tool.poetry.extras]
all = ["fastapi", "uvicorn", "gunicorn", "pydantic"]
models = ["pydantic"]
http = ["fastapi", "uvicorn", "gunicorn"]

[tool.poetry.dev-dependencies]
black = {version = "^21.5b1", allow-prereleases = true}
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

If I go with `poetry install --extras all` then all dependencies are installed. Then if I do `poetry install --extras models` nothing happens (since models are already installed). Is there any way to remove all the optional packages not listed in `models` if they are installed already?
