### DISCUSSION TITLE
No .venv on AppVeyor Linux? (But works on AppVeyor Windows)

### DISCUSSION THREAD

**Discussion by KyleKing** [python-poetry/poetry#4141] [Q&A] [answered]
Has anyone run into an issue with poetry *not* installing a `.venv` when configured for `in-project`?

Relevant AppVeyor Snippet Below ([Full `appveyor.yaml` file](https://github.com/KyleKing/calcipy/blob/cf7c2377dbd7d72d850f40df0c58e44b44d65914/appveyor.yml))

- AppVeyor Linux Output (Doesn't work): https://ci.appveyor.com/project/KyleKing/calcipy/build/job/kssdpgfgb6mmdwe4
- AppVeyor Windows Output (Works as Expected): https://ci.appveyor.com/project/KyleKing/calcipy/build/job/ot1vp49t4ahvtn7e

```yaml
install:
  # Set Python paths based on environment variable from matrix
  - cmd: set PATH=%PYTHON_WIN%/Scripts;%PYTHON_WIN%;%PATH%
  - python --version
  # Install pipx to manage CLI installations (poetry, codecov)
  - python -m pip install pipx
  # Manually set the path because "pipx ensurepath" needs a reload to apply
  - cmd: set PATH=%USERPROFILE%\.local\bin;%PATH%
  - sh: PATH=~/.local/bin:$PATH
  # Install poetry and configure
  - pipx install poetry
  - poetry config virtualenvs.create true
  - poetry config virtualenvs.in-project true
  - poetry config --list
  # Install project-specific dependencies and extras
  - poetry install -E dev -E lint -E test -E commitizen_legacy
  - poetry env list
  - sh: ls -a
```

I'm using `pipx` to install poetry, which is what I use on both Mac and Windows, but I haven't tested on Linux (outside of AppVeyor). `poetry env list` isn't returning anything to STDOUT, so `poetry` is likely using the global Python

Any help would be appreciated! I looked around on Google, SO, Github/poetry, and didn't find anyone having the same type of issues

*Update*: I tried using the official method (`curl`) instead of `pipx` in order to [mimic how the `poetry` CI is configured](https://github.com/python-poetry/poetry/blob/6bd4f1a6c6416d18749c6a230fb85c61f7ebd2a0/.github/workflows/main.yml), but that didn't work either and the `.venv` directory wasn't created ([Logs](https://ci.appveyor.com/project/KyleKing/calcipy/builds/39463658/job/mjwylobwfwc4cr6c?fullLog=true))

Other things I plan to try:

- ~~Could be that poetry detects an activated virtual environment (https://github.com/python-poetry/poetry/issues/2937#issuecomment-770620099) - could try `deactivate`?~~
    - ~~Try modifying or removing the env variable: https://github.com/python-poetry/poetry/issues/1945#issuecomment-672951452. This looks to be a path to the current activated environment and probably what is causing issues in AppVeyor (`echo.%VIRTUAL_ENV%` and `echo $VIRTUAL_ENV`)~~
- ~~Nice discussion on CI, but no comments on AppVeyor and this edge case (https://github.com/python-poetry/poetry/issues/366#issuecomment-691412462)~~
- ~~Maybe try `export POETRY_VIRTUALENVS_CREATE=1`~~
- ~~Use `-vvv` on install - probably won't provide any insight, but worth a try~~
- ~~Could also try `poetry show -v`~~
- For the Ubuntu image, `stack` creates a virtual environment that poetry uses instead of the local one. Haven't figured out a way to override poetry using that environment
