### DISCUSSION TITLE
How to convert this pip install command to poetry?

### DISCUSSION THREAD

**Discussion by uduse** [python-poetry/poetry#4274] [Q&A] [answered]
The command for installing `jax` on my platform is `pip install "jax[cuda110]" -f https://storage.googleapis.com/jax-releases/jax_releases.html`, but I'm not sure how to use it with poetry. Can someone help me with this?

Related issue: #1391

**Comment by abn** [comment]
Find links is not supported yet. As a workaround, you can install using the direct url to the wheel or sdist.

```sh
poetry add "$WHEEL_URL[cuda110]"
```

The drawback of this approach is that poetry will not manage version updates for you. And there will not be a way for you to install the correct cuda version or CPU version in different environments. However, you can specify [environment markers](https://python-poetry.org/docs/dependency-specification/#using-environment-markers) in your dependency specification to make sure platform specific (linux, windows, mac) wheels are chosen.

**Comment by vvsotnikov** [comment, marked as answer]
Hi! Are there any updates since the last reply? :eyes: 

UPD: it's now supported via `poetry source add jax https://storage.googleapis.com/jax-releases/jax_releases.html`
https://python-poetry.org/docs/master/repositories/#single-page-link-source

**Reply by uduse** [reply]
@vvsotnikov After reading all docs, related issues and discussions, I am still not exactly sure how to use this. I have the following `pyproject.toml` and it's only installing the regular version of JAX:
```toml
[tool.poetry]
......

[tool.poetry.dependencies]
......
jax = { extras = ["gpu"], version = "0.4.3", source = "jax" }
jaxlib = { extras = ["gpu"], version = "0.4.3", source = "jax" }

[[tool.poetry.source]]
name = "jax"
url = "https://storage.googleapis.com/jax-releases/jax_releases.html"
default = false
secondary = false
```
