### DISCUSSION TITLE
how do I express passthrough extras?

### DISCUSSION THREAD

**Discussion by graingert** [python-poetry/poetry#4313] [Q&A]
how do I express:
```
install_requires = ["kombu ~= 5.1"],
extras_require = {
    "sqs": "kombu[sqs] ~= 5.1",
} 
```
In poetry?

Another Example in the wild https://github.com/dask/s3fs/pull/362/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R26

For full context, I'm trying to port celery from setuptools to poetry https://github.com/celery/celery/pull/6874/files

https://github.com/celery/celery/blob/master/requirements/extras/sqs.txt#L1 that's the current implementation but I'm not sure how to port to poetry

**Comment by graingert** [comment]
Not an answer:

Seems related https://github.com/python-poetry/poetry/issues/2868

**Reply by graingert** [reply]
And another https://github.com/python-poetry/poetry/issues/834

**Comment by qsineu** [comment]
I faced the same challenge and found this (not that intuitive) solution which seems to work:
```
[tool.poetry.dependencies]
....
kombu = [
    {version = "~5.1", extras = ["sqs"], markers="extra=='sqs'"}, # marker-extra is the extra of your package
    {version = "~5.1", markers="extra!='sqs'"},
]	
...
[tool.poetry.extras]
sqs = [... ] # No need to declare kobu here
```
I Adapted your example above without testing. But it worked with my similar case.

**Reply by phgz** [reply]
Just a note for future reference: it works when packaging a project to be installed with `pip`, but it fails when installed with poetry.

**Reply by DaanRademaker** [reply]
I was so excited to try this out, but @philipGaudreau is right. This does not work with poetry install :( I really need this feature. Hope there is some solution to this.

**Reply by timelfrink** [reply]
I'm also facing this issue right now, did you solve it in the end @DaanRademaker ?

**Reply by charleswilmot** [reply]
```toml
[tool.poetry.dependencies]
python = ">=3.10"
hydra-core=">=1.3"
flax = "^0.9.0"
jax = [
  {version="^0.4.31", markers="extra!='gpu'"},
  {extras=["cuda12"], version="^0.4.31", markers="extra=='gpu'"},
]
tensorflow = "^2.17.0"
wandb = "^0.17.8"
optax = "^0.2.3"
pandas = "^2.2.2"
matplotlib = "^3.9.2"


[tool.poetry.extras]
gpu = ["jax"]
```

Followed by

```
poetry install --extras gpu
```

or


```
poetry install
```

Results in the expected behavior for me with `poetry v1.8.2`
