### DISCUSSION TITLE
Develop multiple projects locally and with GitHub

### DISCUSSION THREAD

**Discussion by jaymegordo** [python-poetry/poetry#4849] [Q&A]
Say I have three projects using poetry:

- `project_a`
- `project_b`
- `project_c` (generic utils to be shared between a + b)

I would like to be able to develop them all in tandem locally, without having to push every little change in `project_c` to GitHub and re sync changes with `project_a` or `project_b`.

I can accomplish this by using a local path dependency:
```toml
# project_a

[tool.poetry.dependencies]
project_c = {path = "../project_c", develop = true}
```

BUT I would also like to be able to share this `project_a` or `project_b` with other people without having to have them also clone `project_c` in the appropriate location.

Is there any way to have something that would work like:
```toml
# project_a

[tool.poetry.dependencies]
project_c = {path = "../project_c", git = "https://github.com/github_user/project_c.git", develop = true}
```

Where the GitHub repo is used as a "fallback" in cases where `project_c` does not exist locally?

Any options using install scripts? (I don't have experience with this)

Any other workflow tips to accomplish what basically comes down to:
"Share code between multiple projects, locally if available, else GitHub"?
