### DISCUSSION TITLE
How do you convert `pip.ini` to `pyproject.toml`? And the `poetry` command, using `add` or `install`?

### DISCUSSION THREAD

**Discussion by gusbemacbe** [python-poetry/poetry#4869] [Q&A]
Hello general!

For example:

```ini
[global]
index-url = http://bank.cloud.br/artifactory/api/pypi/python-devel/simple
trusted-host = bank.cloud.br
extra-index-url = http://bank.cloud.br/artifactory/api/pypi/private-bank-technology-pypi/simple
user = true

[install]
trusted-host = bank.cloud.br
user = false
```

Only this is possible:

```toml
[[tool.poetry.source]]
name = "bank"
url = "http://bank.cloud.br/artifactory/api/pypi/python-devel/simple"
default = true
```
