### DISCUSSION TITLE
Can this `entry_point` be done in `pyproject.toml`?

### DISCUSSION THREAD

**Discussion by tony** [python-poetry/poetry#4953] [Q&A] [answered]
Is this possible yet? With 1.1? 1.2? If not, is it on the roadmap?

The reason why I ask is I haven't seen this specific type of entry expressed yet in documentation for `pyproject.toml`

Context: This is [flake8-import-order](https://pypi.org/project/flake8-import-order/) ([github](https://github.com/PyCQA/flake8-import-order))

Here is the `setup.py`:

```python
from setuptools import find_packages, setup
setup(
    entry_points={
        'flake8_import_order.styles': ['mystyle = someproject.import_order:MyStyle']
    },
   # the rest
    name='someproject',
    packages=find_packages('src')),
    package_dir={'': 'src', 'other': 'other'},
    include_package_data=True,
)
```

`src/someproject/import_order.py` is:

```python
from flake8_import_order import ImportType
from flake8_import_order.styles import Google

class MyStyle(Google):
    accepts_application_package_names = True
```

`pyproject.toml` as it stands:

```toml
[tool.poetry]
name = "someproject"
version = "1.0.0"
description = "My description"
authors = ["The Authors"]
packages = [
    { include = "someproject", from = "src" },
] 
```

My current workaround is to use `pip install -e .` to run `setup.py` to set the entry point.

If I answer this my self down the road I will update here. If not it's unsolved.

**Comment by finswimmer** [comment, marked as answer]
Hello @tony,

I think you are looking for [plugins](https://python-poetry.org/docs/pyproject/#plugins):

```toml
[tool.poetry.plugins."flake8_import_order.styles"]
"mystyle" = "someproject.import_order:MyStyle"
```

fin swimmer
