### DISCUSSION TITLE
How does the Poetry team manage changelog and release notes? Manually?

### DISCUSSION THREAD

**Discussion by trallnag** [python-poetry/poetry#4969] [Q&A]
Looking at the [`release.yaml`](https://github.com/python-poetry/poetry/blob/master/.github/workflows/release.yml) workflow, I don't see anything related to generation of changelog or release notes.

```yaml
- name: Create Release
  uses: ncipollo/release-action@v1
  with:
    artifacts: "dist/*"
    token: ${{ secrets.GITHUB_TOKEN }}
    draft: false
    prerelease: steps.check-version.outputs.prerelease == 'true'
```

**So my question is: How does the release process look like?**

Maybe like this?

1. Adding Git tag and push
2. Workflow runs
3. Manually adding text to release notes

What supports my the steps above is that the initial email send out on a new release contains no release notes:

![image](https://user-images.githubusercontent.com/24834206/147860415-552e3819-ad82-4e1a-b338-07eee3c2b73a.png) 

Why am I asking? Currently just wondering how projects like Poetry manage releases
