### DISCUSSION TITLE
`python ^3.10.1 is not valid`

### DISCUSSION THREAD

**Discussion by UltiRequiem** [python-poetry/poetry#5284] [Q&A]
How would be the correct way to do set any python version bigger than `X`.

Currently, I'm doing

```toml
[tool.poetry.dependencies]
python = "^3.10.1"
# ...
```
With this, I got this error 👇🏽 
```
^3.10.1 is not valid, please specify an exact Python version (e.g. 3.8.1) in your pyproject.toml (and thus poetry.lock)
```
