### DISCUSSION TITLE
Why is this package forbidden?

### DISCUSSION THREAD

**Discussion by BeyondEvil** [python-poetry/poetry#5365] [Q&A] [answered]
```
$ python --version
Python 3.9.10
```
```
$ poetry add pytest-metadata
Using version ^2.0.1 for pytest-metadata

Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  The current project's Python requirement (>=3.9,<4.0) is not compatible with some of the required packages Python requirement:
    - pytest-metadata requires Python >=3.7.0,<3.11.0, so it will not be satisfied for Python >=3.11.0,<4.0

  Because no versions of pytest-metadata match >2.0.1,<3.0.0
   and pytest-metadata (2.0.1) requires Python >=3.7.0,<3.11.0, pytest-metadata is forbidden.
  So, because testing depends on pytest-metadata (^2.0.1), version solving failed.
```

Package [toml](https://github.com/pytest-dev/pytest-metadata/blob/master/pyproject.toml)

Project toml:
```toml
[tool.poetry]
name = "testing"
version = "0.1.0"
description = ""
authors = ["Jim Brännlund <jim.brannlund@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Project python is `3.9.10` which is within the package requirement of `>=3.7.0,<3.11.0`, so why is it "forbidden"?
