### DISCUSSION TITLE
StickyWheel a plugin to rewrite path dependencies to version dependencies at build time

### DISCUSSION THREAD

**Discussion by danielknell** [python-poetry/poetry#5865] [General]
I wrote a plugin to rewrite path depenedencies to version dependencies when you build wheels/sdists

https://github.com/artisanofcode/poetry-stickywheel-plugin

This plugin will rewrite folder dependencies in your poetry projects dependencies with version dependencies.

The version will be extracted from the dependencies pyproject.toml and applied as a semver match.

Assuming a `pyproject.toml` such as:

```toml
[tool.poetry]
name = "a"
version = "0.1.0"

[tool.poetry.dependencies]
b = {path = "../b", develop = true}
```

and the dependency `pyproject.toml`

```toml
[tool.poetry]
name = "b"
version = "1.2.3"
```

the dependency will be rewritten at build time as if it had been defined as:

```toml
[tool.poetry]
name = "a"
version = "0.1.0"

[tool.poetry.dependencies]
b = "^1.2.3"
```

This is useful when you have a bunch of poetry packages in a monorepo and want to be able to build working, relocatable wheels from them.

I was surprised how straight forward it was, i was expecting to have to do some nasty business like monkey patching, but i was able to just manipulate the loaded package data before the build command runs.
