### DISCUSSION TITLE
Editable dependency in DEV mode

### DISCUSSION THREAD

**Discussion by drorata** [python-poetry/poetry#6846] [Q&A]
I am trying to understand what the best practice in the following scenario is. Assume that a team develops a `utils` package and a project `great_proj` depend on this common package. While developing features of `great_proj` it is often the case that additions and maybe even changes have to be made in `utils`. This is why it is desired to have `utils` installed in "editable" mode (and point to a local path where `utils` resides) in the virtual environment where the development takes place. However, when `great_proj` has to be productized, the dependency on `utils` has to be resolved differently. In this case, `utils` has to be installed from probably a remote location (git/pypi/private repo/etc.) and a specific version has to be specified. 

My idea is to have the following `pyproject.toml`:

```toml
[tool.poetry]
name = "great_proj"
version = "0.1.0"
description = "It is a great project indeed."
authors = ["Dror Atariah"]
readme = "README.md"
packages = [{include = "great_proj"}]

[tool.poetry.dependencies]
python = "^3.10"
my_utils= "1.2.3"  # Assuming a specific version is available on PyPi

[tool.poetry.group.dev.dependencies]
my_utils = { path = "../utils", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Is this the right (poetic) way to go? How can I actually tell `Poetry` which dependency to use for example when building a docker image that will have `great_proj` installed in it?

What I tried so far, is to use the following `pyproject.toml`:

```toml
[tool.poetry]
name = "great_proj"
version = "0.1.0"
description = "It is a great project indeed."
authors = ["Dror Atariah"]
readme = "README.md"
packages = [{include = "great_proj"}]

[tool.poetry.dependencies]
python = "^3.10"
my_utils= { path = "../utils", develop = false }

[tool.poetry.group.dev.dependencies]
my_utils = { path = "../utils", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Next, I tried to run `poetry install --without=dev` expecting to have a non-editable installation of `utils`, but it didn't work. The dependency `utils` was still available in the environment *in editable mode*.

NB: I realized that if I delete the local environment and create it again with the `--without dev` flag, then the new environment has `utils` available in a "static" way. I wonder if there's a better way? Is it the right way?
