### DISCUSSION TITLE
Poetry + Pyenv, create new project

### DISCUSSION THREAD

**Discussion by david-vicente** [python-poetry/poetry#7059] [Q&A] [answered]
Consider the following situation: I'm using `pyenv` to manage my python versions and want to start a new project using `poetry`.

I thought that if I ran

``` shell
$ pyenv versions
* system
  3.11.0 
```

``` shell
$ pyenv shell 3.11.0
```

Then using poetry to start a new project, like

``` shell
$ poetry new myproject
```

would create a new folder with all the relevant stuff inside, and file `pyproject.toml` would be

``` toml
[tool.poetry]
name = "myproject"
version = "0.1.0"
description = ""
authors = ["Me <my@email.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
notice the python version. However this is not the case as `poetry new <project name>` seems to ignore the active python version and go with the system one. 

Is this the intended behavior? Shouldn't `poetry new` and `poetry init` take into consideration the active python version?

I'm aware of other issues with similar questions:

- #5252 for example is about the command `poetry install` considering the active python version, so it regards the virtualenvs managed by poetry but not the `pyproject.toml` file.
