### DISCUSSION TITLE
Lookup only at PyPi if a source is unspecified for a dependency

### DISCUSSION THREAD

**Discussion by simon-liebehenschel** [python-poetry/poetry#7164] [Q&A] [answered]
Documentations says:

> All package sources (including secondary sources) will be searched during the package lookup process. These network requests will occur for all sources, regardless of if the package is found at one or more sources.

E.g. if I have
```toml
[tool.poetry.dependencies]
python = "3.10.9"
requests = "1.0.0"
foo = "1.0.0"
bar = "1.0.0"
spam = "1.0.0"
eggs = "1.0.0"
my_private_package = {version = "1.0.0", source = "my-private-source"}

[[tool.poetry.source]]
name = "my-private-source"
url = "https://does-not-matter-for-this-example"
default = false
secondary = true
```
how can I ask Poetry to do not waste  time and resources by redundant requests to my "my-private-source" when looking for packages ("requests", etc.) that are available at PyPi?

Is the only solution is to specify `source = "pypi"` per every public dependency? This solution is not well scalable.

### Versions

- Poetry 1.2.2
