### DISCUSSION TITLE
Can I install a project (and dependancies) that used Poetry v1.4.1 with Python 3.6?

### DISCUSSION THREAD

**Discussion by joshhoughton** [python-poetry/poetry#7730] [Q&A]
I have a Python package that needs to be able to run on Python 3.6.8, all the way up to Python 3.9. The package is managed using the latest version of Poetry (v1.4.1), and [Poetry dropped support for Python 3.6 from v1.2.0+](https://python-poetry.org/history/#:~:text=Drop%20python3.6%20support%20(%235055).). 

I've attempted to implement a GitHub Action in order to run unit tests on Python 3.6. This requires the ability to install the project on Python versions 3.6.8 to 3.9, but this isn't possible due to a couple of reasons:

The most up-to-date version of Poetry that I can install on Python 3.6 is v1.1.5.

- This means that when I attempt to `poetry install`, I get `Additional properties are not allowed ('group' was unexpected)`. This is due to  my `pyproject.toml` containing a dependency group which wasn't supported until after v1.1.5
- I've tried to manually remove this line from the pyproject.toml when running on Python 3.6 with `grep -v "\[tool.poetry.group.dev.dependencies\]" pyproject.toml > temp && mv temp pyproject.toml`, to proceed with all the dependencies being installed under the 'main group'
- Poetry v1.1.5 is then able to read my `pyproject.toml`, but it cannot read my `poetry.lock` file, I get `The lock file is not compatible with the current version of Poetry.`.
- To work around this, I've simply added `rm poetry.lock` to attempt to force a regeneration of the lock file (not ideal I know...). As expected, this allows the Action to pass, but takes around 5 minutes each time to regenerate the lock file each time.

I understand why Python 3.6 is depreciated, however I still need to support this version due to some organisational constraints. I've attached below the full GitHub Action configuration for further context.

**Is there a way to read a v1.4.1 `poetry.lock` when using Poetry v1.1.5 _without_ having to regenerate the file?**

```yaml
name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]

jobs:
  build-python-36:
    runs-on: ubuntu-20.04 #Python 3.6 is not available past 20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry
        grep -v "\[tool.poetry.group.dev.dependencies\]" pyproject.toml > temp && mv temp pyproject.toml
        rm poetry.lock
        cat pyproject.toml
        poetry install

    - name: Run unit tests
      run: |
        poetry run pytest

  build-others:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --with dev
    - name: Run unit tests
      run: |
        poetry run pytest
```
