### DISCUSSION TITLE
Include project files when installing

### DISCUSSION THREAD

**Discussion by williamhCode** [python-poetry/poetry#7732] [Q&A] [answered]
I just started using Poetry, but I'm having trouble emulating `pip install -e .`. 
When I run my project, it throws:
```python
FileNotFoundError: [Errno 2] No such file or directory: 'cyclone/shaders/all.vert'
```
Basically, the files in `cyclone/shaders` are not included.  
I can't for the life of me figure out how to include the shader files. Why doesn't Poetry include all the files in my package by default?

This is my toml file:
```toml
[tool.poetry]
name = "cyclone"
version = "0.1.0"
description = "A 2D batch renderer written in Cython, Python, and OpenGL."
authors = ["williamhCode <83525937+williamhCode@users.noreply.github.com>"]
license = "LGPL-3.0-or-later"
readme = "README.md"
include = [
    "cyclone/shaders/*",
]

[tool.poetry.dependencies]
python = "^3.11"
Cython = "^0.29.33"
cython-lint = "^0.14.0"
pyglm = "^2.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
