### DISCUSSION TITLE
Exposing a dependency's extra as main packages extra

### DISCUSSION THREAD

**Discussion by ena-cradle** [python-poetry/poetry#7773] [General]
I'm developing a package, that depends on package **A**. Package **A** provides an extra: **a** that I would like to expose as my own extra. How would I go about it?

-----------
#### Option 1: Using `[]` in extra specification
```toml
[tool.poetry.dependencies]
A = {version = ... }

[tool.poetry.extras]
with_a = [ "A[a]" ]
``` 
Apart from being a bit confusing and not explicit/expressive enough in my opinion (what if I want a different version of A[a], etc.), this 
gives me:
```
[extras.with_a.0] 'A[a]' does not match '^[a-zA-Z-_.0-9]+$'
```

#### Option 2: Naming the A dependency different based on whether it includes the extra 
```toml
[tool.poetry.dependencies]
A = {version = ...}
A_with_a = {version = ..., extras = ["a"], optional = true}

[tool.poetry.extras]
with_a = [ "A_with_a" ]
``` 
gives me 
```
The dependency name for A-with-a does not match the actual package's name: A
```

#### Option 3: Using groups
```
[tool.poetry.dependencies]
A = {version = ...}

[tool.poetry.group.extra_a]
optional = true

[tool.poetry.group.extra_a.dependencies]
A = {version=..., extras=[a]}

[tool.poetry.extras]
with_a = [ "extra_a" ]
``` 

This doesn't seem to be supported (see discussion [here](https://github.com/python-poetry/poetry/issues/4842)) but looks like what would solve the issue. Additionally, if I understand [this comment](https://github.com/python-poetry/poetry/issues/4842#issuecomment-1332186895), extras need to be specified in the main dependency group which in my case leads to naming issues.

---------------
Is there something I'm missing?
