### DISCUSSION TITLE
Poetry poject name same as package name with entry point defined, does not work

### DISCUSSION THREAD

**Discussion by smprather** [python-poetry/poetry#7834] [General]
This is an offshoot of my talking-to-myself Q&A #7830 .

Is it true that this structure will not work consistently with an entry point defined like this? As I discuss in #7830, it will work either with `poetry run` or inside a `poetry shell`, but not both ways. If I change the name of `apl_cockpit.py` to anything else, it all works.

```toml
[tool.poetry.scripts]
apl_cockpit = "apl_cockpit.aplcockpit:main"
```

```
$ tree
.
├── README.md
├── poetry.lock
├── pyproject.toml
├── src
│   └── apl_cockpit
│       ├── __init__.py
│       └── apl_cockpit.py
```
