### DISCUSSION TITLE
How should poetry handle private dependencies when pip-installing from src?

### DISCUSSION THREAD

**Discussion by meahow** [python-poetry/poetry#7913] [Q&A] [answered]
I have a private gitlab repository configured in pyproject.toml like so
```toml
[[tool.poetry.source]]
name = "gitlab"
url = "https://gitlab.example.com/api/v4/projects/123/packages/pypi/simple"
default = true
secondary = false
```
and one of my project's dependencies is present only in this private repository:
```toml
[tool.poetry.dependencies]
python = "^3.7.2"
private-dep = { version = "^0", source = "gitlab" }
```
and this works fine if I use poetry for my development
But when I want to pip-install it from the source (`pip install /source/to/my/repo`) it fails on not finding the private dependency on the global PyPI. This looks like a bug to me.

Should it (poetry-core as this is set up as a build-backend) export the private dependency as pep508-compliant URL dependency (something like `private-dep@https://gitlab.example.com/api/v4/projects/123/packages/pypi/files/<sha>/<whlfile>` in a `Requires-Dist` header in package metadata)?

The use case here is that I want this repository to be a pre-commit hook and what pre-commit does when installing the hook env is exactly the above - `pip install <src_dir>`. How would I go about this otherwise?
