### DISCUSSION TITLE
Poetry can not resolve dependencies when `priority = "explicit"` is set for a private package registry

### DISCUSSION THREAD

**Discussion by simon-liebehenschel** [python-poetry/poetry#7988] [General] [answered]
## Versions

- poetry 1.5.0

## Working 'pyproject.toml`
```toml
[tool.poetry.dependencies]
foo = {version = "*", source = "gitlab-private-package-registry"}
bar = {version = "*", source = "gitlab-private-package-registry"}

[[tool.poetry.source]]
name = "gitlab-private-package-registry"
url = "https://gitlab.com/api/v4/projects/<MASKED>/packages/pypi/simple/"
default = false
secondary = true
```

## Broken `pyproject.toml`
Let's add `priority = "explicit"`:

```toml
[tool.poetry.dependencies]
foo = {version = "*", source = "gitlab-private-package-registry"}
bar = {version = "*", source = "gitlab-private-package-registry"}

[[tool.poetry.source]]
name = "gitlab-private-package-registry"
url = "https://gitlab.com/api/v4/projects/<MASKED>/packages/pypi/simple/"
priority = "explicit"
```
Error output:
```
  Because no versions of foo match !=1.0.0
   and foo (1.0.0) depends on bar (*), every version of foo requires bar (*).
  So, because no versions of bar match *
   and compute depends on foo (*), version solving failed.
```

**Comment by dimbleby** [comment]
you didn't read the documentation about package sources that tells you this is working exactly as expected

**Reply by simon-liebehenschel** [reply]
I am reading [repositories documentation](https://python-poetry.org/docs/repositories/) carefully. The page says:

> By default, Poetry discovers and installs packages from PyPI. But, you want to install a dependency to your project for a simple API repository? Let’s do it.
> First, configure the package source as a supplemental (or explicit) package source to your project.

Done on my side. I have defined a private source, and I added `priority = "explicit"` to it:
```toml
[[tool.poetry.source]]
name = "gitlab-private-package-registry"
url = "https://gitlab.com/api/v4/projects/<MASKED>/packages/pypi/simple/"
priority = "explicit"
```

> Explicit sources are considered only for packages that explicitly indicate their source.

Done on my side. I have defined 
```toml
foo = {version = "*", source = "gitlab-private-package-registry"}
```

---

Either I still do not see something, or the migration from `default = false` `secondary = true` to `priority = "explicit"` is not described well.

Note that I am not trying to setup Poetry for the first time. I used to use it since `1.1`. I just wonder how this new feature in the `1.5` version should work.

**Reply by dimbleby** [reply]
Hmm, maybe this is more interesting.  Even though you have configured `bar` with an explicit source it looks as though poetry doesn't respect that when it is looking for `bar` as a dependency of `foo`.  is that right?

Sounds like a bug if so, meanwhile a supplemental source should work

**Reply by simon-liebehenschel** [reply]
> Even though you have configured bar with an explicit source it looks as though poetry doesn't respect that when it is looking for bar as a dependency of foo. is that right?

Exactly.

> Sounds like a bug if so, meanwhile a supplemental source should work

Yes, defining `"supplemental"`
```toml
[[tool.poetry.source]]
name = "gitlab-private-package-registry"
url = "https://gitlab.com/api/v4/projects/<MASKED>/packages/pypi/simple/"
priority = "supplemental"
```
works as a temporary workaround for the not working `"explicit"`.

---

By the way, Poetry still looks at PyPI even when the `source` is specified explicitly:
```shell
Source (PyPI): 0 packages found for <MY-PACKAGE-NAME> *
```

**Comment by dimbleby** [comment]
that is how supplemental sources are supposed to work

**Reply by simon-liebehenschel** [reply]
It you comment my this statement

> By the way, Poetry still looks at PyPI even when the source is specified explicitly:
> Source (PyPI): 0 packages found for <MY-PACKAGE-NAME> *

then I  want to clarify that it happened with 

```toml
[tool.poetry.dependencies]
foo = {version = "*", source = "gitlab-private-package-registry"}

[[tool.poetry.source]]
name = "gitlab-private-package-registry"
url = "https://gitlab.com/api/v4/projects/<MASKED>/packages/pypi/simple/"
priority = "explicit"
```
