### DISCUSSION TITLE
Disable PyPI as source

### DISCUSSION THREAD

**Discussion by gaborbernat** [python-poetry/poetry#8013] [Q&A] [answered]
Given:

```toml
[tool.poetry]
source = [{name = "A", url = "https://magic.com/pypi/simple",  priority = "primary"}]
```

The latest Poetry will print:

```
Warning: In a future version of Poetry, PyPI will be disabled automatically if at least one custom source is configured with another priority than 'explicit'. In order to avoid a breaking change and make your pyproject.toml forward compatible, add PyPI explicitly via 'poetry source add pypi'. By the way, this has the advantage that you can set the priority of PyPI as with any other source.
```

Can I disable the warning or disable PyPI today? 🤔 I'm happy to do so.
