### DISCUSSION TITLE
Why poetry doesn't create virtualenv with required python version using system default?

### DISCUSSION THREAD

**Discussion by tony-sol** [python-poetry/poetry#8140] [Q&A]
I have a brew-installed poetry with python@3.11 and virtualenv as dependencies,
and project with pyproject.toml with 
```toml
[virtualenvs]
create = true
in-project = true

[tool.poetry.dependencies]
python = "3.9.16"
```
But when i try to run `poetry install` i've got an error:
```
The currently activated Python version 3.11.4 is not supported by the project (3.9.16).
Trying to find and use a compatible version.

Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
```
What does it mean? Do i need to setup virtual environment to setup ANOTHER virtual environment?!

Looks like the whole point of virtualenvs, no matter what my system python version is - to create an environment with required by pyproject.toml version both python and packages, am i right?
