### DISCUSSION TITLE
How do I specify conditional extras based on platform?

### DISCUSSION THREAD

**Discussion by NeilGirdhar** [python-poetry/poetry#8195] [Q&A]
I tried:
```toml
[build-system]
requires = ['setuptools', 'poetry_core>=1.0']
build-backend = 'poetry.core.masonry.api'

[tool.poetry]
name = 'a'
version = '1.0'
description = ""
authors = ['Me <a@b.com>']

[tool.poetry.dependencies]
python = '>=3.10, <3.12'
jax = [
    {version = '>=0.4.13', extras = ['cuda'], platform = 'linux'},
    {version = '>=0.4.13', platform = 'darwin'}
    # {version = '>=0.4.13', extras = ['cuda'], markers = "sys_platform == 'linux'" },
    # {version = '>=0.4.13', markers = "sys_platform == 'darwin'" }
]
```
But on Darwin, it gives:
```
Because no versions of jax match >0.4.13
 and jax (0.4.13) depends on jaxlib (0.4.13+cuda11.cudnn86), jax (>=0.4.13) requires jaxlib (0.4.13+cuda11.cudnn86).
So, because no versions of jaxlib match 0.4.13+cuda11.cudnn86
 and a depends on jax (>=0.4.13), version solving failed.
```
