### DISCUSSION TITLE
different package source for a particular platform_version

### DISCUSSION THREAD

**Discussion by ClementPinard** [python-poetry/poetry#8351] [Q&A] [answered]
Hi, this discussion is about having different sources for a package, depending on environment markers.
My setup is similar to this one : https://github.com/python-poetry/poetry/issues/8303

I am on poetry 1.6.1, python 3.11

Except my problem is to differentiate two different linux versions. So instead of having two complementary markers with `platform_machine` i need to work with `platform_version`. Here the version I want a specific source for is `#1 SMP Wed Jun 16 20:00:10 PDT 2021`. So I have one entry with `"platform_version == '#1 SMP Wed Jun 16 20:00:10 PDT 2021'"` and one entry with the opposite i.e. `"platform_version != '#1 SMP Wed Jun 16 20:00:10 PDT 2021'"`

And this is sadly not working and gets me this error when I call the `poetry lock` command
```
$> poetry lock       

Updating dependencies
Resolving dependencies... (0.0s)

list index out of range
```

Here is the test file

```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Clément Pinard <clement.pinard@xxii.fr>"]
readme = "README.md"

[[tool.poetry.source]]
name = "piwheels"
url = "https://www.piwheels.org/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.dependencies]
python = "^3.9"
kivy = [
  { version = "^2.2.1", markers = "platform_version == '#1 SMP Wed Jun 16 20:00:10 PDT 2021'", source = "piwheels" },
  { version = "^2.2.1", markers = "platform_version != '#1 SMP Wed Jun 16 20:00:10 PDT 2021'", source = "PyPI" }
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

With some investigation, I can see that the problem is happening here : https://github.com/python-poetry/poetry/blob/master/src/poetry/puzzle/provider.py#L636 , mostly because the `deps` list is empty.

I can also see that putting a dummy platform version like `aaa`  make the lock work. So I suspect some special character is not recognized.

Any though on that ? Do i need to escape some character to make it work ?
