### DISCUSSION TITLE
is it possible to have a package directory name different from the name of the module that should be imported?

### DISCUSSION THREAD

**Discussion by vmgustavo** [python-poetry/poetry#8352] [Q&A]
I see it is possible to have a package name different from the directory containing the source files (https://github.com/python-poetry/poetry/issues/705).

Using an example `pyproject.toml` file:

```toml
[tool.poetry]
name = "pkg_name"
# ...
packages = [
    {include = "pkg_module"}
]
```

In this case I would import the module using `import pkg_module` and not `pkg_name`. Is it possible to have the name different from the directory name and yet import the module using `pkg_import_name` or something similar? Am I forced to rename the source directory to the name I want the user to import?
