### DISCUSSION TITLE
Optimize Docker Layers While Ignoring Pyproject.toml Changes (except dependencies)

### DISCUSSION THREAD

**Discussion by GuyGooL5** [python-poetry/poetry#8414] [General]
Hi everyone, I'm facing a situation where I have a `Dockerfile` that is quite well optimized regarding layers.
My only problem is this line

```dockerfile
# ... installed poetry and stuff
COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root
# ... rest of the dockerfile incl' copying the project and installing it
```

It works fine and all but every time I'm bumping the version of my project in `pyproject.toml` this whole layer is getting invalidated and being re-run.
This is really annoying since most of the work is downloading packages. I don't want to use global installs (I'm using in-project virtualenv for staged-builds).

My question is that if is there a good practice of versioning poetry-managed packages outside of `pyproject.toml` file, or even managing the dependencies in a different way.

All I want to have is a sanely versioned project and an expensive layer cached and invalidated only when really necessary.

**Comment by dimbleby** [comment]
https://python-poetry.org/docs/faq/#poetry-busts-my-docker-cache-because-it-requires-me-to-copy-my-source-files-in-before-installing-3rd-party-dependencies

**Reply by GuyGooL5** [reply]
I've been through this documentation, yet in this snippet
```dockerfile
FROM python
COPY pyproject.toml poetry.lock .
RUN pip install poetry && poetry install --no-root --no-directory
COPY src/ ./src
RUN poetry install --no-dev
```

the 2nd line `COPY pyproject.toml poetry.lock .` invalidates the layers because `pyproject.toml` has been changed

**Reply by dimbleby** [reply]
too bad, then.  

You can't expect to change pyproject.toml without invalidating the layer that includes pyproject.toml; and that is always going to come before the things that rely on pyprojec.toml

**Reply by GuyGooL5** [reply]
Guess there's no way of avoiding it 😕

**Reply by adriangb** [reply]
My advice: don't version your services via a version in pyproject.toml.

**Reply by atemate** [reply]
> don't version your services via a version in pyproject.toml.

I don't think it's possible, `version` attribute is required in pyproject.toml in a package mode

**Reply by adriangb** [reply]
You can set that to 0.0.0 or whatever. What matters is the tag on your container images, the version in your logs/traces/metrics, etc. For that I recommend you use the git sha.

**Comment by MarcelWilson** [comment]
AFAIK, the only real thing you can do is ensure all the steps in the dockerfile that can be cached occur first and run the `poetry install` step as late as possible.

Also, a little trick I learned is I didn't need to copy my whole project into the dockerfile (thus incurring a new cache layer with every change).  I use a volume mapping to point to the local directory where my project resides.  I still have to copy the pyproject.toml & lock but everything else sits outside the image.  The image is only the runtime environment.  YMMV of course.

I use docker compose, but you could accomplish the same thing with commandline when running the image.
```yml
services:
    name_of_your_service:
        build:
            context: .
            dockerfile: wherever_you_keep_your_dockerfiles/Dockerfile
        image: name_of_your_image
        volumes:
            # This is the mapping.  localhost_path:image_path
            # ./ is the root of the project on the localhost
            # /localfolder is an alias of the directory within the image.
            - ./:/localfolder
```

```dockerfile
COPY pyproject.toml poetry.lock* ./
RUN poetry install

WORKDIR /localfolder/tests
# from here you can still execute scripts in the ./tests without ever having to copy them into the image
```
