### DISCUSSION TITLE
What is the meaning of `type = "console"` in scripts example

### DISCUSSION THREAD

**Discussion by evilhamsterman** [python-poetry/poetry#8436] [Q&A]
I the pyproject.toml documentation where is talks about making scripts dependent on optional extras https://python-poetry.org/docs/pyproject/#scripts it give the example 

```toml
[tool.poetry.scripts]
devtest = { reference = "mypackage:test.run_tests", extras = ["test"], type = "console" }
```

I get what `reference` and `extras` are for, but there is no documentation for what type means. It appears appears it was added in commit 98b8ffb3244267d6421bb7dfc8b706efe583e129 by @edgarrmondragon updating from the deprecated `callable` to `reference` two months ago. But nothing about type
