### DISCUSSION TITLE
Error Installing Pytorch+cuda121 in Poetry

### DISCUSSION THREAD

**Discussion by schosdas** [python-poetry/poetry#8577] [Q&A]
I am looking to use the yolov5 model and opencv in my project. I am currently using Poetry as the virtual environment for my project. 

In order to operate yolov5 with gpu rather than cpu, I am looking to install cuda. I am trying to download the Cuda 12.1 version from https://pytorch.org/. For this, I have configured my pyproject.toml as follows:

```toml
[tool.poetry]
name = "yolo-test"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"
packages = [{include = "yolo_test"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
opencv-python = "^4.8.0.74"
pyinstaller = "^6.1.0"
pillow = "^10.1.0"
pandas = "^2.1.1"
requests = "^2.31.0"
ultralytics = "^8.0.201"
logging = "^0.4.9.6"

# Cuda installation test
[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Afterwards, I tried to install it in the poetry virtual environment using the following command:

```bash
poetry add torch torchvision torchaudio --source pytorch
```

However, during the installation, I observed the following error logs:

```
Source (pytorch): Authorization error accessing https://download.pytorch.org/whl/cu121/pefile/
Source (pytorch): Authorization error accessing https://download.pytorch.org/whl/cu121/macholib/
Source (pytorch): Authorization error accessing https://download.pytorch.org/whl/cu121/logging/
Source (pytorch): Authorization error accessing https://download.pytorch.org/whl/cu121/ultralytics/
...
```

Additionally, I used `print(torch.__version__)` for verification, and as an output, I observed `2.1.0+cpu`. 
Could anyone assist me on how to install the Pytorch Cuda version in Poetry? 

Thank you.
