### DISCUSSION TITLE
Plugin - Ignore Build Script

### DISCUSSION THREAD

**Discussion by bsdz** [python-poetry/poetry#8610] [Show and tell]
This plugin allows one to create either platform specific or pure python wheels. If you use Poetry's experimental (?) build script feature to generate binary wheels for your project, i.e.

```toml
[tool.poetry.build]
script = "build.py"
generate-setup-file = true
```

and you wish to also generate non platform specific wheel, then this plugin adds a new command line switch,

```bash
poetry build --ignore-build-script
```

It can be found at https://pypi.org/project/poetry-plugin-ignore-build-script/.

This works around the issue highlighted in #8039.
