### DISCUSSION TITLE
Minimum-Supported-Version (MSV) strategy for dependency version

### DISCUSSION THREAD

**Discussion by T-256** [python-poetry/poetry#8624] [Ideas]
```toml
[dependencies]
mydep = { msv = "1.0.0" }
```
**Why not** `version = "^1.0.0"`?
1. `mydep` release version 2 and 3, but our crate still supports version 1 and both of new majors.
2. Maintaining costs.

**What should we do when `mydep` released incompatible version?**

For example, assume it released incompatible "1.2.3", Then we should release a patch version for our package with considering one of these scenarios:

- If they didn't still fix incompatibility:
  ```toml
  [dependencies]
  mydep = { msv = "1.0.0", conflict = ">=1.2.3" }
  ```
- They fixed incompatibility in "1.5.0":
  ```toml
  [dependencies]
  mydep = { msv = "1.0.0", conflict = ">=1.2.3, <1.5" }
  ```

We should also keep these conflicts until `msv` exceed each of them.

## Notes
- `msv` and `conflict` could have better naming.
- `msv` doesn't accept version specifiers (e.g. ">=")
- `conflict` only supports comma-saparated of `>= <= > <`.
- It is more simple, readable than befor in my POV.

This idea actually inspired from [here](https://github.com/openlawlibrary/pygls/issues/406#issuecomment-1793601176).

I didn't find the best equality of `{ msv = "1.0.0", conflict = ">=1.2.3, <1.5" }` in version specifiers. WDYT?
