### DISCUSSION TITLE
Can a single package define two modules inside a namespace package?

### DISCUSSION THREAD

**Discussion by tibbe** [python-poetry/poetry#8703] [Q&A]
Directory structure:
```
src/
  ns/
    pkg_a/
      __init__.py
      foo.py
    pkg_b/
      __init__.py
      bar.py
```

pyproject.toml:
```toml
[tool.poetry]
name = "pkg_a"
packages = [{include = "ns", from = "src"}]
```

This seems to work (i.e. I can `poetry install` this) but I see problems in other tools. For example, mypy reports

```
poetry run mypy -p ns.pkg_b                                              
Can't find package 'ns.pkg_b'
```

Now I don't expect this group to debug mypy issues but I'm just trying to understand if my package is a valid one. Can you have a package export two modules (`pkg_a` and `pkg_b`) under one namespace package (`ns`)?
