### DISCUSSION TITLE
ModuleNotFoundError for local dependency

### DISCUSSION THREAD

**Discussion by eakirtas** [python-poetry/poetry#8784] [General]
Hey, 

I am including a local library in dependencies at `pyproject.toml` as following:

```toml
[tool.poetry.dependencies]
...
torch = "^2.1.1"
torchvision = "^0.16.1"
numpy = "^1.26.2"
tabulate = "^0.9.0"
matplotlib = "^3.8.2"
pandas = "^2.1.3"
wandb = "^0.16.0"
train_utils = { path = ".../../train_utils/.", develop = true }
...
``` 
However, when I run the python script with `poetry run myproject/run.py` , I receive   
```
ModuleNotFoundError: No module named 'train_utils'
```

That's makes no sense is that in both `poetry show` and `.venv/bin/pip freeze` the local library is appeared. 
```bash
poetry show
# ...
# train-utils`               0.0.0.1 ../../train_utils 
# ...

pip freeze
# ...
# train-utils @ git+git@github.com:eakirtas/train_utils.git@<hash>
# ...
```

The train_utils library is not a poetry project, but has the following setup.py file 

```python
from setuptools import find_packages, setup

setup(name='train_utils', version='0.0.0.1', packages=find_packages())
```

What wrong with that?
