### DISCUSSION TITLE
Keyring in pre-commit hook

### DISCUSSION THREAD

**Discussion by Gitznik** [python-poetry/poetry#8844] [Q&A] [answered]
Hey there,

I have a private package in the google artifact registry. I'm able to load this package into my poetry project after running `poetry self add keyrings.google-artifactregistry-auth -n`. 
When running a `poetry lock` pre-commit hook, it says it can't find the package, so I assume the poetry version in the pre-commit hook does not have that keyring installed? The error is an Authorization Error.

Any way of fixing that?

This is the hook I'm using:
```
  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.1"
    hooks:
      - id: poetry-lock
```

**Comment by abn** [comment, marked as answer]
I haven't looked at this in a while, but have you tried adding it as an additional dependency?

https://pre-commit.com/index.html#config-additional_dependencies

**Reply by Gitznik** [reply]
Duh, yeah that fixed it. Thank you!
For future reference, this is the definition that worked:

```yaml
  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.1"
    hooks:
      - id: poetry-lock
        additional_dependencies: ['keyrings.google-artifactregistry-auth']
```
