### DISCUSSION TITLE
Discrepancy between pip and Poetry file

### DISCUSSION THREAD

**Discussion by seanswyi** [python-poetry/poetry#9315] [Q&A]
I'm currently trying to install PyTorch and PyTorch-XLA using a Poetry file but am finding out that it doesn't work. However, when I try to install the packages via pip it does. I'm trying to figure out why it doesn't work for my Poetry configuration.

The pip command that I'm running is taken from [the official PyTorch-XLA repository](https://github.com/pytorch/xla?tab=readme-ov-file#getting-started):

```Shell
pip install torch~=2.2.0 torch_xla[tpu]~=2.2.0 -f https://storage.googleapis.com/libtpu-releases/index.html
```

My `pyproject.toml` file looks like this:

```TOML
[tool.poetry]
name = "xla-test"
version = "0.1.0"
description = ""
authors = ["John Doe"]
readme = "README.md"

[[tool.poetry.source]]
name = "libtpu"
url = "https://storage.googleapis.com/libtpu-releases/index.html"
priority = "supplemental"

[tool.poetry.dependencies]
python = "^3.8"
datasets = "^2.18.0"
torch = { url = "https://download.pytorch.org/whl/cu118/torch-2.2.0%2Bcu118-cp38-cp38-linux_x86_64.whl" }
torch_xla = { version = "~2.2.0", extras = ["tpu"], source = "libtpu" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

When I run `poetry install` I get the following error message:

```
Repository "libtpu" does not exist.
```

When I try to change the priorty of libtpu to being primary rather than supplemental, Poetry complains that it can't find a compatible version of `datasets`, which I'm assuming means that it's not searching PyPI.

When I try to add PyPI explicitly as a supplemental source, Poetry complains that libtpu doesn't exist.

Is Poetry not appropriate for this, or am I doing something wrong?

### Edit

I forgot to mention that you have to run `pip install --upgrade pip` first, as mentioned here: https://github.com/pytorch/xla/issues/5802
