### DISCUSSION TITLE
Extra name capitalization in pyproject.toml

### DISCUSSION THREAD

**Discussion by ryancausey** [python-poetry/poetry#9324] [Q&A]
I was attempting to use this extras definition in my pyproject.toml:

```toml
[tool.poetry.extras]
AWS = ["pytest-aws-fixtures"]
```

However, this led to no extras being installed when running `poetry install --all-extras` or `poetry install --extra AWS`. I had to change the configuration to the following:

```toml
[tool.poetry.extras]
aws = ["pytest-aws-fixtures"]
```

Then it worked once the "aws" was all lowercase. Is this expected behavior?
