### DISCUSSION TITLE
How to install package from git repository with non python file(e.g jinja2 template files)

### DISCUSSION THREAD

**Discussion by pocket7878** [python-poetry/poetry#9411] [Q&A]
Hello!

I am using Poetry to manage dependencies in my project and I'm trying to include a Jinja2 template file from a private repository. Despite configuring my `pyproject.toml` and confirming the inclusion of the template file in the build, I'm encountering an issue where the template cannot be found when the package is installed.

Here's how I have set up my `pyproject.toml`:

```toml
[tool.poetry]
name = "my_utils_py"
version = "0.1.0"
description = "My own utils"
authors = ["Pocket7878 <poketo7878@gmail.com>"]
readme = "README.md"
include = [
    { path = "src/foo/templates/bar.jinja2", format=["sdist", "wheel"] }
]
```

I have confirmed that the `bar.jinja2` file is indeed included in the local build using `poetry build`. However, after installing the package in another project with the following dependency specification:

```toml
[tool.poetry.dependencies]
python = "^3.12"
my-utils = {git = "https://github.com/pocket7878/my_utils_py.git", branch="main"}
```

Jinja2 raises a "template not found" error, and I cannot find the `template` directory in the path `.venv/lib/python3.12/site-packages/my_utils_py`.

Could anyone advise on how to properly include a template file in a package managed by Poetry? Thank you in advance for your help!

**Comment by radoering** [comment]
If the file is in the wheel at `src/foo/templates`, it will probably be in the same path in your venv: `.venv/lib/python3.12/site-packages/src/foo/templates`

**Reply by pocket7878** [reply]
Thank you for your quick response! But still I can't find templates files in site-package. Although templates directory is exists under `.venv/src/my_utils_py/`.

**Comment by Secrus** [comment]
`importlib.resources` might be helpful here. That use case is what it was made for

**Comment by pocket7878** [comment]
I have confirmed that installing from the wheel file by copying the `poetry build` artifact and specifying it as a file dependency successfully includes the templates directory.

**Comment by pocket7878** [comment]
I've found my library project missing the [build-system] section.
When I updated the [build-system] section as follows:

```toml
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

I've confirmed that my template directory is inside site-packages.
I apologize for any confusion this may have caused.
