### DISCUSSION TITLE
How to make one dependency group require another dependency group

### DISCUSSION THREAD

**Discussion by MaddyGuthridge** [python-poetry/poetry#9451] [Q&A] [answered]
I have two groups of dependencies:

```toml
[tool.poetry.group.build.dependencies]
# Build dependencies -- required to build the library
transdoc = "^0.2.2"
griffe = "^0.45.2"

[tool.poetry.group.docs.dependencies]
# Docs depdnencies -- required to build documentation site
# Note build dependencies are also required
mkdocs = "^1.4.2"
mkdocs-gen-files = "^0.5.0"
mkdocs-material = "^9.5.0"
mkdocstrings = { version = ">=0.24,<0.26", extras = ["python"] }
mkdocs-awesome-pages-plugin = "^2.9.2"
mkdocs-section-index = "^0.3.8"
```

In this case, the process of building docs requires building the library, so I want to specify `--with build` to be also required for `--with docs`. Is there a way that I can do this without copy-pasting my `build` dependencies into my `docs` dependencies?
