### DISCUSSION TITLE
Installing PySMILE with Poetry

### DISCUSSION THREAD

**Discussion by WesleySoftware** [python-poetry/poetry#9473] [Q&A]
Good Morning,

I am looking to format my pyproject.toml to install pysmile.

I unfortunately am not sure what to do because they distribute it as python version specific and platform specific wheel file urls, and I can't seem to get poetry to install only the version for the current system.

https://support.bayesfusion.com/pysmile-A/pysmile/.

My first attempt was a pyproject.toml like this:
```toml
[tool.poetry]
name = "smile"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
pysmile = [
    { platform = "win64", url = "https://support.bayesfusion.com/pysmile-A/pysmile/pysmile-2.2.5-cp312-cp312-win_amd64.whl" },
    { platform = "linux64", url = "https://support.bayesfusion.com/pysmile-A/pysmile/pysmile-2.2.5-cp312-cp312-linux_x86_64.whl" },
    { platform = "darwin", url = "https://support.bayesfusion.com/pysmile-A/pysmile/pysmile-2.2.5-cp312-cp312-macosx_12_0_universal2.whl" },
]
python = "3.12.*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

But then when I run `poetry install` it tries to install all 3 wheel files.

Am I using the wrong directive?

Thanks
