### DISCUSSION TITLE
Are extra requirements analyzed recursively?

### DISCUSSION THREAD

**Discussion by mcarnerero** [python-poetry/poetry#9509] [Q&A]
I work in a complex project containing several modules. The use of each of those modules depends on the configuration. Also, each module requires different libraries. I defined extra dependencies as follows:

```toml
[tool.poetry.extras]
mod-a = ["lib-1", "lib-2"]
mod-b = ["lib-1", "lib-3"]
mod-c = ["lib-2", "lib-4"]
collectors = ["mod-a", "mod-b"]
generators = ["mod-c"]
all = ["collectors", "generators"]
```

I was hoping that to install my app with the modules related with collection it would be enough the command:

```bash
pip install my-app[collectors]
```

It is not working at all. Is it supported what I was trying to do? 

Thank you in advance.
