### DISCUSSION TITLE
Analyze extra requirements recursively

### DISCUSSION THREAD

**Discussion by mcarnerero** [python-poetry/poetry#9511] [Ideas]
Hi!

It could be interesting to be able of writing extra requirements based on other extra requirements. I work in a complex project containing several modules. The use of each of those modules depends on the configuration. Also, each module requires different libraries. I defined extra dependencies as follows:

```toml
[tool.poetry.extras]
mod-a = ["lib-1", "lib-2"]
mod-b = ["lib-1", "lib-3"]
mod-c = ["lib-2", "lib-4"]
collectors = ["mod-a", "mod-b"]
generators = ["mod-c"]
all = ["collectors", "generators"]
```

That way I could install my app with the modules related with collection executing the command:

```bash
pip install my-app[collectors]
```

What do you think?
