### DISCUSSION TITLE
Poetry solves `--without` dependency group

### DISCUSSION THREAD

**Discussion by mripani** [python-poetry/poetry#9545] [Q&A]
I have a group which is called `ssh` so when installing my project within a `Dockerfile` I can use `--without ssh` command and avoid installing the group of dependency that requires an SSH key. 

Even though within my `Dockerfile` I use the command `--without` in order to avoid that specific group, the dependency solver still tries to solve those dependency and fails because of no permissions.

Is it the normal poetry behavior that even solves the dependency conflicts of those avoided groups?

Here is an example of the code:

```Dockerfile

RUN poetry config virtualenvs.create true \
    && poetry config virtualenvs.in-project true \
    && poetry install --without ssh --sync \
    && poetry lock

````

This is an example of the `pyproject.toml` that I try to install

```toml
[tool.poetry]
name = "my-package"
version = "0.1.0"
description = "My project"
authors = ["mail@gmail.com"]


[tool.poetry.dependencies]
python = "~3.11"

[tool.poetry.group.ssh.dependencies]
my-private-project1 = { git = "ssh://git@github.com/myorg/myrepo1.git", rev = "main" }
my-private-project2 = { git = "ssh://git@github.com/myorg/myrepo2.git", rev = "main" }

```

Poetry version: `poetry=1.8.3`
