### DISCUSSION TITLE
Installing Python package prompts Python conflict issue

### DISCUSSION THREAD

**Discussion by zlpmetyou** [python-poetry/poetry#9575] [General]
my pyproject.toml as:

```toml
[tool.poetry]
name = "model-service"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.3.1"
transformers = "^4.42.4"
fastapi = "^0.111.1"


[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

when i want to install a new package, 

 `poetry add unstructured[pdf]`

cause error:

> The current project's supported Python range (>=3.11,<4.0) is not compatible with some of the required packages Python requirement:
>   - unstructured requires Python >=3.9.0,<3.13, so it will not be satisfied for Python >=3.13,<4.0
>
> Because no versions of unstructured match >0.15.0,<0.16.0
>  and unstructured[pdf] (0.15.0) requires Python >=3.9.0,<3.13, unstructured is forbidden.
> So, because model-service depends on unstructured[pdf] (^0.15.0), version solving failed.
>
>   • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
>
> For unstructured, a possible solution would be to set the `python` property to ">=3.11,<3.13"
>
> https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
> https://python-poetry.org/docs/dependency-specification/#using-environment-markers

my python version is 3.11, between 3.9.0 and 3.13, Why is there a mistake
What should I do?
