### DISCUSSION TITLE
Installing from private source on pre-commit hook

### DISCUSSION THREAD

**Discussion by UncleGoogle** [python-poetry/poetry#9625] [Q&A]
Hey, I saw this thread: https://github.com/orgs/python-poetry/discussions/8844

but what I'm trying to do is to run poetry-lock pre-commit hook on the CI when having a explicit private source.

It looks that it is not possible to use env variables for authentication https://python-poetry.org/docs/configuration/#using-environment-variables (see https://github.com/pre-commit/pre-commit/issues/758) nor using `poetry config ....` as there is no place to run it in pre-commit config.

Did anyone have similar problem? How to solve that?

**Comment by UncleGoogle** [comment]
Ah, I didn't spot that after adding runtime env variables in gitlab-ci.yaml

```yaml
pre-commit:
  variables:
    POETRY_HTTP_BASIC_GITLAB_USERNAME: build-pipeline-deploy-token
    POETRY_HTTP_BASIC_GITLAB_PASSWORD: $DEPLOY_TOKEN
```

my gitlab pipeline is failing because of DIFFERENT (and real) reason.
`poetry cache clear PyPI --all` relocking locally, solved the problem
