### DISCUSSION TITLE
Poetry not installing current project in docker build

### DISCUSSION THREAD

**Discussion by tom-whitehead** [python-poetry/poetry#9907] [Q&A] [answered]
Hi, need some help. I have a poetry project that runs well locally. When I do `poetry install` it installs the current project and I can import my files as an installed Python module (e.g `from mymodule.dtos import MyObject`, rather than than using a relative import). However, when I build a docker image and try to run it, I get a module not found error and it doesn't run. 

This is my `pyproject.toml`:
```toml
[tool.poetry]
name = "my-project"
version = "0.1.0"
description = ""
readme = "README.md"
packages = [{include = "my_module"}]

[tool.poetry.dependencies]
python = "^3.13"
boto3 = "^1.35.78"
motor = "^3.6.0"
pymysql = "^1.1.1"
types-pymysql = "^1.1.0.20241103"
openai = "^1.57.4"
numpy = "^2.2.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.8.2"
mypy = "^1.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

And this is my Docker file:
```dockerfile
ROM public.ecr.aws/docker/library/python:3.13-slim

RUN apt-get update \
    && apt-get install -y curl build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://install.python-poetry.org | python -
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

COPY my-project/pyproject.toml my-project/poetry.lock ./

RUN poetry config virtualenvs.create false \
    && poetry install --without dev 

COPY my-project/* ./my-project/

CMD ["poetry", "run", "python", "my_module/app.py"]
```

Any help from someone with experience with using docker and Poetry would be much appreciated. Ideally I want to keep my module as an installed to make testing and CI easier down the line.
