### DISCUSSION TITLE
How to fix `tool.poetry.source` missing `url` in the TOML schema for PyPI source

### DISCUSSION THREAD

**Discussion by rafrafek** [python-poetry/poetry#9909] [Q&A] [answered]
Hello,

I have recently started receiving this schema error in my `pyproject.toml` file:

```
"url" is a required property
```

for this section:

```toml
[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
```

The schema is being validated by the `Even Better TOML` extension.

<img width="424" alt="image" src="https://github.com/user-attachments/assets/554f13b9-4b59-4c00-a5b2-898671ff7d5b" />

How can I fix it? Shouldn't the schema allow the missing url in case it's the default PyPI source?

**Comment by Secrus** [comment]
There is no need to redefine `PyPI` as a source unless you overwrite the URL with your index/mirror.

**Reply by rafrafek** [reply]
Thank you for your quick answer. Could this behavior be reflected in the TOML schema definition?

**Reply by rafrafek** [reply]
I mean, something like this is allowed, right?

```toml
[[tool.poetry.source]]
name = "private_source"
url = "https://example.com/python/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
```

Could the TOML schema check if it's the PyPI source which url is already known and not require the url field?
