### DISCUSSION TITLE
minor ci problem, concurrency doesn't work as expected

### DISCUSSION THREAD

**Discussion by trim21** [python-poetry/poetry#9947] [General]
I update (force push) my PR but old workflow run is not canceled

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
```

not sure what cause this, may be something wrong with github scheduler.

![image](https://github.com/user-attachments/assets/dfde50a1-0e21-4975-9c21-1fee08555e3f)

![image](https://github.com/user-attachments/assets/6079e0cf-6079-4e30-a6f4-885ac58a62f6)
