### ISSUE TITLE
After the migration to `poetry v2.0.0` some dependencies are missing in the `poetry.lock` file

### ISSUE THREAD

**Issue by Github-dm-CDE** [python-poetry/poetry#10004]
### Description

I am currently trying to migrate some of our projects to poetry v2.0.0. I have noticed that after changing the `pyproject.toml` and then running `poetry update`, some of the dependencies in the `poetry.lock` file are missing, which were previously correctly listed there with poetry 1.x.

Here is an example of one of our `pyproject.toml` files:
```toml
[project]
name = "bda-management"
dynamic = [ "version", "classifiers", "dependencies"]
description = "This project is the central place to manage CDE BDA metadata."
readme = "README.md"
authors = [{name = "Some Name", email = "some.name@mail.de"}]
requires-python = "~3.11"

[project.scripts]
bda-management = 'modules.cli.cli:main'
bda-management-helper = 'modules.cli.helper_cli:main'

[project.optional-dependencies]
ansible = ["ansible"]

[tool.poetry]
version = "0.0.0"
package-mode = false
packages = [{include = "modules"}]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.11",
]

[tool.poetry.dependencies]
python = "~3.11"
pydantic = "2.10.4"
jinja2 = "3.1.5"
pyyaml = "6.0.2"
click = "8.1.8"
rich = "13.9.4"
ansible = { version = "9.12.0", optional = true }
dm-webhdfs = {version = "10.1.4", source = "ck-pypi"}
dm-hive = {version = "3.1.3", source = "ck-pypi"}
dm-knox-token = { version = "3.1.2", source = "ck-pypi" }
gitpython = "3.1.44"

[tool.poetry.group.build.dependencies]
pex = "2.28.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "4.0.1"
pytest = "8.3.4"
pytest-cov = "6.0.0"
# We include flask and pytest-flaskserver explicitly instead of using the
# dm-webhdfs extras, because we want to avoid including those dependencies
# in the production package.
flask = "3.1.0"
pytest-flaskserver = "2.0.16"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[[tool.poetry.source]]
name = "dm-artifactory-pypi"
url = "https://some/private/pypi/mirror/"
priority = "supplemental"

[[tool.poetry.source]]
name = "ck-pypi"
url = "https://some/private/repo/"
priority = "primary"

```

After the changeover, all our internal projects such as `dm-webhdfs`, `dm-hive` and `dm-knox-token` are missing from the `poetry.lock` file. But also some public projects such as `pydantic` or `gitpython` (which is a transitive dependency) are no longer be listed there.

### Workarounds

Not known

### Poetry Installation Method

pipx

### Operating System

Red Hat Universal Base Image 8

### Poetry Version

Poetry (version 2.0.0)

### Poetry Configuration

```bash session
I will submit it later if possible. Currently the whole thing runs in a gitlab runner and has to be changed accordingly to get the information
```

### Poetry Runtime Logs

```bash session
I will submit it later if possible. Currently the whole thing runs in a gitlab runner and has to be changed accordingly to get the information
```
