### ISSUE TITLE
In package mode, Poetry 2.0.x doesn't recognize 'authors', 'description', 'name', 'version' in `pyproject.toml`

### ISSUE THREAD

**Issue by bolinocroustibat** [python-poetry/poetry#10029]
### Description

Even though the project has fields 'authors', 'description', 'name', 'version' in `pyproject.toml`, Poetry 2.0.1 throw the error `- The fields ['authors', 'description', 'name', 'version'] are required in package mode.`

### Workarounds

No workaround so far.

### Poetry Installation Method

system package manager (eg: dnf, apt etc.)

### Operating System

Debian 12

### Poetry Version

2.0.1

### Poetry Configuration

```bash session
Since it's a CI runner (GitHub Actions CI), we can't get the full config.
```

### Python Sysconfig

<details>
  <summary>sysconfig.log</summary>
  

  ```
  Paste the output of 'python -m sysconfig', over this line.
  ```
</details>

### Example pyproject.toml

```TOML
[project]
name = "MyName"
version = "2.0.6.dev"
description = "My Description"
authors = [{ name = "author", email = "author@author.com" }]
dependencies = [
...
]
requires-python = ">=3.11,<3.13"
license = { text = "MIT" }
readme = "README.md"

[project.optional-dependencies]
dev = [
...
]

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

<details>
  <summary>poetry-runtime.log</summary>
  

  ```
  Paste the output of 'poetry -vvv <command>', over this line.
  ```
</details>

**Comment by finswimmer** [comment]
Hey @bolinocroustibat,

I cannot reproduce your issue. So please add the full output of `poetry -vvv <command>`.

Guess: The command doesn't run the folder you expect it to run.

fin swimmer

**Comment by jymchng** [comment]
This is similar to the issue I raised [here](https://github.com/astral-sh/uv/issues/10569).

Here is the `pyproject.toml` for easy reference:

```toml
[project]
name = "pure-python-lib"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Jim Chng", email = "jimchng@outlook.com" }
]
readme = "README.md"
requires-python = ">=3.8"

[tool.poetry]
name = "pure-python-lib"
version = "0.1.0"
description = "Add your description here"
authors = ["Jim Chng <jimchng@outlook.com>"]
readme = "README.md"
requires-python = ">=3.8"

[build-system] # poetry-dynamic-versioning
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry.build]
script = "build.py"
generate-setup-file = false
```

The intent is to have `uv` as the package manager and complete build tool but using the `poetry` build backend because I don't think `uv` supports build script (e.g. `build.py`).

But when `package-mode = true`, `poetry` requires `[tool.poetry]` while `uv` only recognizes `[project]`, hence now I have two ugly chucks (`[project]` and `[tool.poetry]`) which are duplicates.
