### ISSUE TITLE
poetry 2.0.1 issue - Package does not contain any element

### ISSUE THREAD

**Issue by bhdew** [python-poetry/poetry#10030]
### Description

While installing poetry, we are facing with the error - /app/bq_life_cycle does not contain any element.
Although installation and writing lock file is being completed we are getting the error - ERROR: failed to solve: process "/bin/sh -c poetry install" did not complete successfully: exit code: 1.

### Workarounds

Using poetry with previous version

### Poetry Installation Method

pip

### Operating System

Linux

### Poetry Version

2.0.1

### Poetry Configuration

```bash session
#12 0.614 cache-dir = "/root/.cache/pypoetry"
#12 0.615 installer.max-workers = null
#12 0.615 installer.no-binary = null
#12 0.615 installer.only-binary = null
#12 0.615 installer.parallel = true
#12 0.615 installer.re-resolve = true
#12 0.615 keyring.enabled = true
#12 0.615 requests.max-retries = 0
#12 0.615 solver.lazy-wheel = true
#12 0.615 system-git-client = false
#12 0.615 virtualenvs.create = false
#12 0.615 virtualenvs.in-project = null
#12 0.615 virtualenvs.options.always-copy = false
#12 0.615 virtualenvs.options.no-pip = false
#12 0.615 virtualenvs.options.system-site-packages = false
#12 0.615 virtualenvs.path = "{cache-dir}/virtualenvs"  # /root/.cache/pypoetry/virtualenvs
#12 0.616 virtualenvs.prompt = "{project_name}-py{python_version}"
#12 0.616 virtualenvs.use-poetry-python = false
```

### Example pyproject.toml

```TOML
[project]
name = "bq_life_cycle"
version = "2.0.0"
description = "Bigquery Data retention"
requires-python = ">=3.9"
authors = [
    { name = "You", email = "you@example1.com" },
]
dependencies = []

[tool.poetry]
packages = [
    { include = "bq_life_cycle" }
    ]
requires-poetry = ">=2.0"


[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
fastapi = "^0.109.1"
pyyaml = "6.0.1"
httpx= "0.25.0"
pytest = "^7.1.1"
unittest2 = "1.1.0"
google = "3.0.0"
google-cloud = "0.34.0"
urllib3 = "^2.2.2"
google-cloud-bigquery = "3.12.0"
google-cloud-error-reporting = "1.9.2"
uvicorn = "^0.23.2"
auth = "0.5.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

 > [7/7] RUN poetry install:
9.905   - Installing pytest (7.4.4)
9.917   - Installing pyyaml (6.0.1)
9.991   - Installing unittest2 (1.1.0)
10.02   - Installing uvicorn (0.23.2)
10.31 
10.31 Writing lock file
10.31 
10.31 Installing the current project: bq_life_cycle (2.0.0)
10.31 
10.32 /app/bq_life_cycle does not contain any element
------
Dockerfile:17
--------------------
  15 |     RUN pip3 install poetry
  16 |     RUN poetry config virtualenvs.create false
  17 | >>> RUN poetry install
  18 |     
  19 |     # Run the web service on container startup. Here we use the gunicorn
--------------------
ERROR: failed to solve: process "/bin/sh -c poetry install" did not complete successfully: exit code: 1
