### ISSUE TITLE
Poetry v2 attaches the epoch timestamp to all files in the sdist .tar.gz file

### ISSUE THREAD

**Issue by pronovic** [python-poetry/poetry#10083]
### Description

I noticed this when I went to package [cedar-backup3 v3.9.1](https://github.com/pronovic/cedar-backup3/releases/tag/v3.9.1) for Debian.  I built and uploaded the `.deb`, and then Debian FTP Masters rejected the upload because some files were too old.  It looks like Poetry attaches the epoch timestamp (1970-01-01 00:00) to all of the files in the sdist `.tar.gz` file generated via `poetry build`:

```
$ poetry build
Building cedar-backup3 (3.9.1+1.e205215)
  - Building sdist
  - Built cedar_backup3-3.9.1+1.e205215.tar.gz
  - Building wheel
  - Built cedar_backup3-3.9.1+1.e205215-py3-none-any.whl
 
$ tar ztvf dist/cedar_backup3-3.9.1+1.e205215.tar.gz | head -5
-rw-r--r-- 0/0           45086 1970-01-01 00:00 cedar_backup3-3.9.1+1.e205215/Changelog
-rw-r--r-- 0/0           17989 1970-01-01 00:00 cedar_backup3-3.9.1+1.e205215/LICENSE
-rw-r--r-- 0/0            9056 1970-01-01 00:00 cedar_backup3-3.9.1+1.e205215/NOTICE
-rw-r--r-- 0/0            2823 1970-01-01 00:00 cedar_backup3-3.9.1+1.e205215/PyPI.md
-rw-r--r-- 0/0            6336 1970-01-01 00:00 cedar_backup3-3.9.1+1.e205215/README.md
```

I've reproduced this behavior using Poetry v2.0.1 on both Linux and Windows, with and without my plugins enabled, so it doesn't seem to be environment-specific.

### Workarounds

Seems like I can use this as a workaround:

```
SOURCE_DATE_EPOCH=$(date +%s) poetry build
```

However, I don't think I should have to set `$SOURCE_DATE_EPOCH` to make this work.  I would expect the dates in the sdist `.tar.gz` to match the source files on my filesystem &mdash; or if not that, the date of the build itself &mdash; without me doing anything special.

### Poetry Installation Method

pipx

### Operating System

Debian stable, Windows 10

### Poetry Version

Poetry (version 2.0.1)

### Poetry Configuration

```bash session
cache-dir = "/home/pronovic/.cache/pypoetry"
installer.max-workers = null
installer.no-binary = null
installer.only-binary = null
installer.parallel = true
installer.re-resolve = true
keyring.enabled = false
requests.max-retries = 0
solver.lazy-wheel = true
system-git-client = false
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/pronovic/.cache/pypoetry/virtualenvs
virtualenvs.prompt = "{project_name}-py{python_version}"
virtualenvs.use-poetry-python = false
```

### Example pyproject.toml

```TOML
[build-system]
requires = ["poetry-core (>=2.0.0)", "poetry-dynamic-versioning (>=1.5.2,<2.0.0)"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry]
requires-poetry = ">=2.0.0"
packages = [ { include="CedarBackup3", from="src" } ]
include = [
   { path='Changelog', format='sdist' },
   { path='NOTICE', format='sdist' },
   { path='LICENSE', format='sdist' },
   { path='README.md', format='sdist' },
   { path='docs', format='sdist' },
   { path='manpages', format='sdist' },
   { path='samples', format='sdist' },
   { path='tests', format='sdist' },
]
classifiers = [
   "Development Status :: 5 - Production/Stable",
   "Operating System :: OS Independent",
   "Environment :: Console",
   "Intended Audience :: System Administrators",
   "Natural Language :: English",
   "Topic :: Software Development :: Libraries",
   "Topic :: System :: Archiving :: Backup",
   "Topic :: Utilities",
]
version = "0.0.0"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version=">=1.5.2,<2.0.0", extras=["plugin"] }

# Published version is managed using Git tags
# We get either the tag (like "0.24.1") or a snapshot-type version (like "0.24.1+3.e8319c4")
[tool.poetry-dynamic-versioning]
enable = true
pattern = '^[vV](?P<base>\d+\.\d+\.\d+)'  # this extracts the version from our vX.Y.Z tag format
format-jinja = "{% if distance == 0 and not dirty %}{{ base }}{% else %}{{ base }}+{{ distance }}.{{ commit }}{% endif %}"

[project]
name = "cedar-backup3"
requires-python = ">=3.10,<4"
description = "Implements local and remote backups to CD/DVD and Amazon S3"
keywords = [ 'local', 'remote', 'backup', 'scp' ]
authors = [ { name="Kenneth J. Pronovici", email="pronovic@ieee.org" } ]
license = "GPL-2.0-only"
readme = "PyPI.md"
dynamic = [ "classifiers", "version" ]
dependencies = [
   "chardet (>=5.2.0,<6.0.0)",            # Debian trixie has 5.2.0
   "importlib-metadata (>=8.5.0,<9.0.0)", # Debian trixie has 8.5.0
]

[project.urls]
homepage = "https://pypi.org/project/cedar-backup3/"
repository = "https://github.com/pronovic/cedar-backup3"

[project.optional-dependencies]
docs = [
   "sphinx (>=8.1.3,<9.0.0)",              # Debian trixie has 8.1.3
   "sphinx-autoapi (>=3.3.3,<4.0.0)",      # Debian trixie has 3.3.3
]

[tool.poetry.group.dev.dependencies]
coverage = ">=7.4.4,<8.0.0"
pylint = ">=3.0.1,<4.0.0"
pre-commit = ">=4.0.1,<5.0.0"
black = ">=24.2.0,<25.0.0"
isort = ">=5.12.0,<6.0.0"
colorama = ">=0.4.6,<1.0.0"

[tool.poetry.scripts]
cback3 = 'CedarBackup3.scripts:cback3' 
cback3-amazons3-sync = 'CedarBackup3.scripts:amazons3' 
cback3-span = 'CedarBackup3.scripts:span' 

[tool.black]
line-length = 132
target-version = [ 'py310', 'py311', 'py312', 'py313' ]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | __pycache__
  | \.tox
  | \.venv
  | \.poetry
  | build
  | dist
  | docs
  | notes
)/
'''

[tool.isort]
profile = "black"
line_length = 132
skip_glob = [ "docs", "notes", ".poetry" ]

[tool.coverage.paths]
source = [ "src" ]

[tool.coverage.run]
branch = true
source = [ "src/CedarBackup3" ]

[tool.coverage.report]
show_missing = false
precision = 1
```

### Poetry Runtime Logs

<details>
  <summary>poetry-runtime.log</summary>
  

  ```
Loading configuration file /home/pronovic/projects/repos/cedar-backup3/poetry.toml
Using virtualenv: /home/pronovic/projects/repos/cedar-backup3/.venv
Building cedar-backup3 (3.9.1+1.e205215)
  - Building sdist
SOURCE_DATE_EPOCH environment variable is not set, using mtime=0

(Many "Ignoring:" lines removed...)
   
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/__init__.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/action.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/actions/__init__.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/actions/collect.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/actions/constants.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/actions/initialize.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/actions/purge.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/actions/rebuild.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/actions/stage.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/actions/store.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/actions/util.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/actions/validate.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/cli.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/config.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/customize.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/extend/__init__.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/extend/amazons3.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/extend/capacity.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/extend/encrypt.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/extend/mbox.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/extend/mysql.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/extend/postgresql.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/extend/split.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/extend/subversion.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/extend/sysinfo.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/filesystem.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/image.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/knapsack.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/peer.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/release.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/scripts.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/testutil.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/tools/__init__.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/tools/amazons3.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/tools/span.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/util.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/writer.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/writers/__init__.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/writers/cdwriter.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/writers/dvdwriter.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/writers/util.py
  - Adding: /home/pronovic/projects/repos/cedar-backup3/src/CedarBackup3/xmlutil.py
SOURCE_DATE_EPOCH environment variable not set, setting zipinfo date to default=(2016, 1, 1, 0, 0, 0)
  - Built cedar_backup3-3.9.1+1.e205215-py3-none-any.whl
  ```
</details>
