### ISSUE TITLE
PyTorch Custom Source with Optional Dependencies Not Working with `poetry lock` and `poetry remove`

### ISSUE THREAD

**Issue by sobhanAhmadian** [python-poetry/poetry#10086]
### Description
When using Poetry with **PyTorch's custom package sources and optional dependencies**, and **using `sentence-transformers` library as dependency**, the `poetry lock` and `poetry remove` commands fail with "torch not found" errors, even though the package is properly installed and visible via `pip list`.

When using `poetry install --extras "cuda"` the dependencies will be installed and the lock file will be generated. However, later if we want to use `poetry lock` or `poetry remove <some-package>` we'll receive an error that "torch not found".

### Current Behavior
Using the following configuration in `pyproject.toml`:

```TOML
[project]
name = "test"
version = "0.1.0"
description = ""
authors = [
    { name = "Sobhan Ahmadian", email = "" },
]
requires-python = ">=3.12,<4.0"
dependencies = [
    "pandas~=2.2.3",
    "sentence-transformers~=3.3.1",
]

[project.optional-dependencies]
cpu = ["torch (==2.5.1+cpu)"]
cuda = ["torch (==2.5.1+cu124)"]

[tool.poetry]
requires-poetry = ">=2.0"

[tool.poetry.dependencies]
torch = [
    { markers = "extra == 'cpu' and extra != 'cuda'", source = "pytorch-cpu" },
    { markers = "extra == 'cuda' and extra != 'cpu'", source = "pytorch-cuda" },
]

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[[tool.poetry.source]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu124"
priority = "explicit"

```

When running `poetry install --extras "cuda"` or `poetry install --extras "cpu"` every thing is OK, and the package is properly installed and visible via pip:
```bash
$ pip list | grep torch
torch                    2.5.1+cu124
```

However, when running `poetry lock` or `poetry remove`, I get the following error:
```
Package torch (2.5.1+cu124) not found.
```

### Steps to Reproduce
1. Create a new Poetry project
2. Add the toml file I've provided above.
3. Run `poetry install --extras "cuda"`.
5. Try to run `poetry lock` or `poetry remove pandas`
6. Observe the "Package not found" error

### Workarounds

We should delete lock file every time and use `poetry install --extras "cuda"` agian

### Poetry Installation Method

Poetry's official installer script

### Operating System

Ubuntu 24.04

### Poetry Version

2.0.1

### Poetry Configuration

```bash session
cache-dir = "/home/sobhan/.cache/pypoetry"
installer.max-workers = null
installer.no-binary = null
installer.only-binary = null
installer.parallel = true
installer.re-resolve = true
keyring.enabled = true
repositories.pytorch-cpu.url = "https://download.pytorch.org/whl/cpu"
repositories.pytorch-cuda.url = "https://download.pytorch.org/whl/cu124"
requests.max-retries = 0
solver.lazy-wheel = true
system-git-client = false
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/sobhan/.cache/pypoetry/virtualenvs
virtualenvs.prompt = "{project_name}-py{python_version}"
virtualenvs.use-poetry-python = false
```

### Python Sysconfig

<details>
  <summary>sysconfig.log</summary>
  

 [sysconfigoutput.txt](https://github.com/user-attachments/files/18491239/sysconfigoutput.txt)
 
</details>

### Example pyproject.toml

```TOML
[project]
name = "test"
version = "0.1.0"
description = ""
authors = [
    { name = "Sobhan Ahmadian", email = "sobhan@cartesianlabs.io" },
]
requires-python = ">=3.12,<4.0"
dependencies = [
    "pandas~=2.2.3",
    "sentence-transformers~=3.3.1",
]

[project.optional-dependencies]
cpu = ["torch (==2.5.1+cpu)"]
cuda = ["torch (==2.5.1+cu124)"]

[tool.poetry]
requires-poetry = ">=2.0"

[tool.poetry.dependencies]
torch = [
    { markers = "extra == 'cpu' and extra != 'cuda'", source = "pytorch-cpu" },
    { markers = "extra == 'cuda' and extra != 'cpu'", source = "pytorch-cuda" },
]

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[[tool.poetry.source]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu124"
priority = "explicit"
```

### Poetry Runtime Logs

<details>
  <summary>poetry-runtime.log</summary>
  

[poetrylock.log](https://github.com/user-attachments/files/18503001/poetrylock.log)

</details>
