### ISSUE TITLE
Poetry 2.1.0 Regression: Could not parse version constraint: ==*

### ISSUE THREAD

**Issue by medley56** [python-poetry/poetry#10184]
### Description

Today's Poetry release 2.1.0 breaks on `poetry install` citing `Could not parse version constraint: ==*` (note that the exact version string cited is probably variable depending on your `pyproject.toml` file). This version, `==*` does not appear in `pyproject.toml` (see below).

### Workarounds

Downgrade to poetry 2.0.1
```
poetry self update 2.0.1
```

### Poetry Installation Method

install.python-poetry.org

### Operating System

MacOS 15.3

### Poetry Version

Poetry (version 2.1.0)

### Poetry Configuration

```bash session
❯ poetry config --list
cache-dir = "/Users/game1390/Library/Caches/pypoetry"
data-dir = "/Users/game1390/Library/Application Support/pypoetry"
installer.max-workers = null
installer.no-binary = null
installer.only-binary = null
installer.parallel = true
installer.re-resolve = true
keyring.enabled = true
python.installation-dir = "{data-dir}/python"  # /Users/game1390/Library/Application Support/pypoetry/python
requests.max-retries = 0
solver.lazy-wheel = true
system-git-client = false
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/game1390/Library/Caches/pypoetry/virtualenvs
virtualenvs.prompt = "{project_name}-py{python_version}"
virtualenvs.use-poetry-python = false
```

### Python Sysconfig

[sysconfig.log](https://github.com/user-attachments/files/18812419/sysconfig.log)

### Example pyproject.toml

```TOML
[tool.poetry]
name = "my_package"
version = "5.1.0rc1"
description = "blah"
license = "BSD-3-Clause"
readme = "README.md"
include = ["LICENSE.txt", "CITATION.cff"]


[tool.poetry.dependencies]
python = ">=3.9"
lxml = ">=4.8.0"
click = "^8.0"
rich = "^13.0"
# Extras dependencies
xarray = { version = ">2024.0.0", optional = true }
numpy = { version = "^2.0.0", optional = true }
pre-commit = { version = "*", optional = true }
pytest = { version = "*", optional = true }
pytest-benchmark = { version = "*", optional = true }
pytest-randomly = { version = "*", optional = true }
pytest-cov = { version = "*", optional = true }
pyyaml = { version = "*", optional = true }
ruff = { version = "*", optional = true }
sphinx = { version = "*", optional = true }
myst-parser = { version = "*", optional = true }
sphinx-autoapi = { version = "*", optional = true }
sphinx-rtd-theme = { version = "*", optional = true }

[tool.poetry.group.dev.dependencies]
pre-commit = "*"
pytest = "*"
pytest-benchmark = "*"
pytest-randomly = "*"
pytest-cov = "*"
pyyaml = "*"
ruff = "*"
sphinx = "*"
myst-parser = "*"
sphinx-autoapi = "*"
sphinx-rtd-theme = "*"
coverage = "*"

[tool.poetry.group.examples]
optional = true

[tool.poetry.group.examples.dependencies]
matplotlib = ">=3.4"
memory-profiler = "^0.61.0"

[tool.poetry.extras]
xarray = ["xarray", "numpy"]
test = ["pytest", "pytest-benchmark", "pytest-randomly", "pytest-cov"]
dev = ["xarray", "numpy", "pre-commit", "pytest", "pytest-benchmark", "pytest-randomly",
       "pytest-cov", "ruff", "pyyaml", "sphinx", "myst-parser", "sphinx-autoapi", "sphinx-rtd-theme"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

<details>
  <summary>poetry-runtime.log</summary>
  

  ```
  Loading configuration file /Users/game1390/Library/Application Support/pypoetry/config.toml
Using virtualenv: /Users/game1390/Workspace/space_packet_parser/.venv
Checking keyring availability: Checking if keyring is available
[keyring:keyring.backend] Loading KWallet
[keyring:keyring.backend] Loading SecretService
[keyring:keyring.backend] Loading Windows
[keyring:keyring.backend] Loading chainer
[keyring:keyring.backend] Loading libsecret
[keyring:keyring.backend] Loading macOS
Using keyring backend 'macOS Keyring'
Available
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 0 installs, 0 updates, 0 removals, 50 skipped

  - Installing alabaster (0.7.16): Skipped for the following reason: Already installed
  - Installing astroid (3.3.8): Skipped for the following reason: Already installed
  - Installing babel (2.17.0): Skipped for the following reason: Already installed
  - Installing certifi (2025.1.31): Skipped for the following reason: Already installed
  - Installing cfgv (3.4.0): Skipped for the following reason: Already installed
  - Installing charset-normalizer (3.4.1): Skipped for the following reason: Already installed
  - Installing click (8.1.8): Skipped for the following reason: Already installed
  - Installing coverage (7.6.12): Skipped for the following reason: Already installed
  - Installing distlib (0.3.9): Skipped for the following reason: Already installed
  - Installing docutils (0.21.2): Skipped for the following reason: Already installed
  - Installing filelock (3.17.0): Skipped for the following reason: Already installed
  - Installing identify (2.6.7): Skipped for the following reason: Already installed
  - Installing idna (3.10): Skipped for the following reason: Already installed
  - Installing imagesize (1.4.1): Skipped for the following reason: Already installed
  - Installing iniconfig (2.0.0): Skipped for the following reason: Already installed
  - Installing jinja2 (3.1.5): Skipped for the following reason: Already installed
  - Installing lxml (5.3.1): Skipped for the following reason: Already installed
  - Installing markdown-it-py (3.0.0): Skipped for the following reason: Already installed
  - Installing markupsafe (3.0.2): Skipped for the following reason: Already installed
  - Installing mdit-py-plugins (0.4.2): Skipped for the following reason: Already installed
  - Installing mdurl (0.1.2): Skipped for the following reason: Already installed
  - Installing myst-parser (3.0.1): Skipped for the following reason: Already installed
  - Installing nodeenv (1.9.1): Skipped for the following reason: Already installed
  - Installing packaging (24.2): Skipped for the following reason: Already installed
  - Installing platformdirs (4.3.6): Skipped for the following reason: Already installed
  - Installing pluggy (1.5.0): Skipped for the following reason: Already installed
  - Installing pre-commit (4.1.0): Skipped for the following reason: Already installed
  - Installing py-cpuinfo (9.0.0): Skipped for the following reason: Already installed
  - Installing pygments (2.19.1): Skipped for the following reason: Already installed
  - Installing pytest (8.3.4): Skipped for the following reason: Already installed
  - Installing pytest-benchmark (5.1.0): Skipped for the following reason: Already installed
  - Installing pytest-cov (6.0.0): Skipped for the following reason: Already installed
  - Installing pytest-randomly (3.16.0): Skipped for the following reason: Already installed
  - Installing pyyaml (6.0.2): Skipped for the following reason: Already installed
  - Installing requests (2.32.3): Skipped for the following reason: Already installed
  - Installing rich (13.9.4): Skipped for the following reason: Already installed
  - Installing ruff (0.9.6): Skipped for the following reason: Already installed
  - Installing snowballstemmer (2.2.0): Skipped for the following reason: Already installed
  - Installing sphinx (7.4.7): Skipped for the following reason: Already installed
  - Installing sphinx-autoapi (3.5.0): Skipped for the following reason: Already installed
  - Installing sphinx-rtd-theme (3.0.2): Skipped for the following reason: Already installed
  - Installing sphinxcontrib-applehelp (2.0.0): Skipped for the following reason: Already installed
  - Installing sphinxcontrib-devhelp (2.0.0): Skipped for the following reason: Already installed
  - Installing sphinxcontrib-htmlhelp (2.1.0): Skipped for the following reason: Already installed
  - Installing sphinxcontrib-jquery (4.1): Skipped for the following reason: Already installed
  - Installing sphinxcontrib-jsmath (1.0.1): Skipped for the following reason: Already installed
  - Installing sphinxcontrib-qthelp (2.0.0): Skipped for the following reason: Already installed
  - Installing sphinxcontrib-serializinghtml (2.0.0): Skipped for the following reason: Already installed
  - Installing urllib3 (2.3.0): Skipped for the following reason: Already installed
  - Installing virtualenv (20.29.2): Skipped for the following reason: Already installed

Installing the current project: space_packet_parser (5.1.0rc1)
  - Building package space-packet-parser in editable mode
  - Removed space_packet_parser-5.1.0rc1.dist-info directory from /Users/game1390/Workspace/space_packet_parser/.venv/lib/python3.12/site-packages
  - Adding space_packet_parser.pth to /Users/game1390/Workspace/space_packet_parser/.venv/lib/python3.12/site-packages for /Users/game1390/Workspace/space_packet_parser
  - Adding the spp script to /Users/game1390/Workspace/space_packet_parser/.venv/bin
  - Adding the space_packet_parser-5.1.0rc1.dist-info directory to /Users/game1390/Workspace/space_packet_parser/.venv/lib/python3.12/site-packages
  ```
</details>
