### ISSUE TITLE
Editable installs fail to recognize nested package structure with explicit path mapping

### ISSUE THREAD

**Issue by Fmajor** [python-poetry/poetry#10211]
### Description

**Environment**:
- Python version: 3.12.8
- Poetry: 1.8.5
- Poetry-core: 1.9.1

**Problem Description**:
When migrating from setuptools to Poetry, we're experiencing inconsistent behavior between regular installs (`pip install .`) and editable installs (`pip install -e .`) for plugin-style package structures. While regular installs work correctly, editable installs fail to recognize the nested package structure.

**Previous setuptools Configuration**:
```toml
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"project.plugins.plug_name" = "src"}
packages = ["project.plugins.plug_name"]
```

**Current Poetry Attempts**:
```toml
# pyproject.toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]

# Attempt 1: Flat structure
# .
# ├── pyproject.toml
# └── src/
#     ├── __init__.py
#     └── module.py
packages = [
    { include = "*", from = "src", to = "project/plugins/plug_name" }
]

# Attempt 2: Nested structure
# .
# ├── pyproject.toml
# └── src/
#    └── project/
#        └── plugins/
#            └── plug_name/
#                  ├── __init__.py
#                  └── module.py
packages = [
    { include = "project/plugins/plug_name", from = "src" }
]
```

**Reproduction Steps**:
1. Create package with above structure (for plugin package)
2. Regular install: `pip install .` for both main package and plugin package→ `import project.plugins.plug_name` works
3. Editable install: `pip install -e .` for both main package and plugin package→ `ImportError: No module named 'project.plugins.plug_name'`

**Expected Behavior**:
Both installation methods should allow importing the nested package structure:
```python
import project.plugins.plug_name
```

**Actual Behavior**:
Editable installs fail to recognize the nested package path, while regular installs work as expected.

**Additional Context**:
This pattern is critical for our plugin architecture where:
- Main package (`project`) provides core functionality
- Plugins (`plug_name`) are developed as separate packages
- Need to maintain namespace isolation between plugins
- Editable installs are essential during plugin development

### Workarounds

No

### Poetry Installation Method

pip

### Operating System

Gentoo

### Poetry Version

1.8.5

### Poetry Configuration

```bash session
cache-dir = "/home/user/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/user/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Python Sysconfig

<details>
  <summary>sysconfig.log</summary>
  

  ```
  Paste the output of 'python -m sysconfig', over this line.
  ```
</details>

### Example pyproject.toml

```TOML

```

### Poetry Runtime Logs

<details>
  <summary>poetry-runtime.log</summary>
  

  ```
  Paste the output of 'poetry -vvv <command>', over this line.
  ```
</details>

**Comment by dimbleby** [comment]
Eg https://github.com/python-poetry/poetry-core/blob/eee84d755cf3ac4573efa552cec283d4e7f8758e/pyproject.toml#L32

**Comment by Fmajor** [comment]
I do more tests on it, here is the results

# test poetry bug of nested packages in editable mode

```
# file structure
.
├── main
│   ├── makefile
│   ├── pyproject.toml
│   └── src
│       └── project
│           ├── __init__.py
│           └── plugins
│               └── __init__.py
├── plugin
│   ├── makefile
│   ├── pyproject.toml
│   └── src
│       └── project
│           └── plugins
│               └── plugin
│                   └── __init__.py
├── makefile
└── tests.py
```

``` toml
# main/pyproject.toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.poetry]
name = "project-main"
authors = [ "SomeOne <someone@example.com>" ]
version = '0.0.1'

packages = [
    { include = "project", from = "src" }
]
```

``` toml
# plugin/pyproject.toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "project-plugin"
authors = [
  "SomeOne <someone@example.com>"
]
version = '0.0.1'

packages = [
    { include = "project/plugins/plugin", from = "src" }
]
```

``` python
# tests.py
import os
PYENV_VIRTUAL_ENV = os.environ['PYENV_VIRTUAL_ENV']
PWD = os.environ['PWD']
try:
  import project
  print("project is", str(project).replace(PWD, "${PWD}").replace(PYENV_VIRTUAL_ENV, "${PYENV}"))
  print("project.__version__ is", project.__version__)
except Exception as e:
  print(f"project error: {e}")

try:
  import project.plugins.plugin
  print("project.plugins.plugin is ", str(project.plugins.plugin).replace(PWD, "${PWD}").replace(PYENV_VIRTUAL_ENV, "${PYENV}"))
  print("project.plugins.plugin.__version__ is ", project.plugins.plugin.__version__)
except Exception as e:
  print(f"project.plugins.plugin error: {e}")
```

``` makefile
# test makefile
no-install:
        ipython tests.py
main-install-plugin-install:
        pip install ./main
        pip install ./plugin
        ipython tests.py
main-dev-plugin-dev:
        pip install -e ./main
        pip install -e ./plugin
        ipython tests.py
plugin-dev-only:
        pip install -e ./plugin
        ipython tests.py

uninstall:
        pip uninstall -y project-plugin
        pip uninstall -y project-main
```

## test results

``` bash
# test before install main and plugin
$ make no-install
ipython tests.py
project error: No module named 'project'
project.plugins.plugin error: No module named 'project'

# test after install main and plugin
$ make main-install-plugin-install
pip install ./main
Processing ./main
...
Successfully installed project-main-0.0.1

pip install ./plugin
Processing ./plugin
...
Successfully installed project-plugin-0.0.1

ipython tests.py
project is <module 'project' from '${PYENV}/lib/python3.12/site-packages/project/__init__.py'>
project.__version__ is version of main
project.plugins.plugin is  <module 'project.plugins.plugin' from '${PYENV}/lib/python3.12/site-packages/project/plugins/plugin/__init__.py'>
project.plugins.plugin.__version__ is version of plugin

$ make uninstall # clean environment for next test

# test after install main and plugin both in editable mode
$ make main-dev-plugin-dev
pip install -e ./main
...
Successfully installed project-main-0.0.1

pip install -e ./plugin
...
Successfully installed project-plugin-0.0.1

ipython tests.py
project is <module 'project' from '${PWD}/main/src/project/__init__.py'>
project.__version__ is version of main
project.plugins.plugin error: No module named 'project.plugins.plugin'

$ make uninstall # clean environment for next test

# only install plugin in editable mode
$ make plugin-dev-only
pip install -e ./plugin
...
Successfully installed project-plugin-0.0.1

ipython tests.py
project is <module 'project' (namespace) from ['${PWD}/plugin/src/project']>
project error: module 'project' has no attribute '__version__'
project.plugins.plugin is  <module 'project.plugins.plugin' from '${PWD}/plugin/src/project/plugins/plugin/__init__.py'>
project.plugins.plugin.__version__ is version of plugin
```
# conclusion
* these cases are good
  * no installs
    * can NOT `import project` and `import project.plugins.plugin`
  * `pip install ./main` and `pip install ./plugin`
    * CAN BOTH `import project` and `import project.plugins.plugin`
  * `pip install -e ./plugin`
    * CAN `import project` (just namespace, no content)
    * CAN `import project.plugins.plugin`
* this case has BUG
  * `pip install -e ./main` and `pip install -e ./plugin`
    * can `import project`
    * BUT can NOT `import project.plugins.plugin`

**Comment by dimbleby** [comment]
you did not follow the example I pointed you at.  Please try again, and then close this out.

**Comment by Fmajor** [comment]
> you did not follow the example I pointed you at. Please try again, and then close this out.

sorry, I can't understant the point of your example.

the `main` pacakge has no problem, in both `pip install .` or `pip install -e .`, the `pyproject.toml` just follow your example
```
# main/pyproject.toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.poetry]
name = "project-main"
authors = [ "SomeOne <someone@example.com>" ]
version = '0.0.1'

packages = [
    { include = "project", from = "src" }
]
```

The bug appear only when your `pip install -e .` both the `main` and the `plugin` package, just as i show above

**Comment by dimbleby** [comment]
The file I linked does not belong to the main project

**Comment by Fmajor** [comment]
> The file I linked does not belong to the main project

ok, follow the example of `poetry-core` (take it as plugin package of `poetry`), I modify the pyproject.toml of the plugin package

``` toml
# plugin/pyproject.toml

# old
packages = [
    { include = "project/plugins/plugin", from = "src" }
]

# new
packages = [
    { include = "project", from = "src" }
]

```

but still get the same result
  * after `pip install -e .` both main and plugin package, I can not `import project.plugins.plugin`
  * while `pip install .` both, i can `import project.plugins.plugin`)
