### ISSUE TITLE
Poetry 2.x optional dependencies are not optional if a custom source is used

### ISSUE THREAD

**Issue by GytisBraz** [python-poetry/poetry#10223]
### Description

Using Poetry 2.x, if a package is specified as an optional dependency (under `[project.optional-dependencies]`) AND if the package comes from a custom source, then the package is installed with or without `--extras` argument. In other words, an optional package always gets installed if it comes from a custom source.

See the attached `pyproject.toml` file - if you run `poetry install` it will install the `colorama` package even though it's specified as optional.

Commenting out the `[tool.poetry.dependencies]` and `[[tool.poetry.source]]` sections and running `poetry install` produces expected behavior and the optional package is not installed.

### Workarounds

One workaround is to not use `[project.optional-dependencies]` and specify `optional = true` for the package under the `[tool.poetry.dependencies]` section. But that's the deprecated approach.

### Poetry Installation Method

pipx

### Operating System

macOS 14.6

### Poetry Version

2.1.1

### Poetry Configuration

```bash session
cache-dir = "/Users/gytis/Library/Caches/pypoetry"
data-dir = "/Users/gytis/Library/Application Support/pypoetry"
installer.max-workers = null
installer.no-binary = null
installer.only-binary = null
installer.parallel = true
installer.re-resolve = true
keyring.enabled = true
python.installation-dir = "{data-dir}/python"  # /Users/gytis/Library/Application Support/pypoetry/python
repositories.testpypi.url = "https://test.pypi.org/simple/"
requests.max-retries = 0
solver.lazy-wheel = true
system-git-client = false
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/gytis/Library/Caches/pypoetry/virtualenvs
virtualenvs.prompt = "{project_name}-py{python_version}"
virtualenvs.use-poetry-python = false
```

### Python Sysconfig

<details>
  <summary>sysconfig.log</summary>
  

  ```
  Paste the output of 'python -m sysconfig', over this line.
  ```
</details>

### Example pyproject.toml

```TOML
[project]
authors = [
  { name = "author", email = "name@example.com" }
]
description = "Example description"
name = "some-package"
readme = "README.md"
version = "0.0.1"
requires-python = ">=3.10,<3.13"
dependencies = [
  "PyGithub",
]
[project.optional-dependencies]
something-optional = ["colorama"]

[tool.poetry.dependencies]
colorama = {source = "testpypi"}

[[tool.poetry.source]]
name = "testpypi"
priority = "explicit"
url = "https://test.pypi.org/simple/"
```

### Poetry Runtime Logs

No particular command is failing, but the pasted `pyproject.toml` file generates a `poetry.lock` file which has the optional package show up as non-optional:

```
[[package]]
name = "colorama"
version = "0.4.6"
description = "Cross-platform colored terminal text."
optional = false
python-versions = "!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,!=3.5.*,!=3.6.*,>=2.7"
groups = ["main"]
files = [
    {file = "colorama-0.4.6-py2.py3-none-any.whl", hash = "sha256:4f1d9991f5acc0ca119f9d443620b77f9d6b33703e51011c16baf57afb285fc6"},
    {file = "colorama-0.4.6.tar.gz", hash = "sha256:08695f5cb7ed6e0531a20572697297273c47b8cae5a63ffc6d6ed5c201be6e44"},
]
```

**Comment by GytisBraz** [comment]
> [tool.poetry.dependencies]
> colorama = {source = "testpypi"}
> you have made colorama a non-optional dependency, the source has nothing to do with it. Putting `colorama = "*"` here would be just the same

Thanks for the quick reply. The documentation says

`
For example, if you want to define additional information that is not required for building but only for locking (for example an explicit source), you can enrich dependency information in the tool.poetry section.
`

so I sort of assumed that I can use `[tool.poetry.dependencies]` to enrich the dependency with the source info but I suppose I misinterpreted this.

How would you advise to specify optional dependencies with a custom source without using deprecated syntax?

**Comment by dimbleby** [comment]
custom sources are a poetry special and cannot be expressed in standard metadata.

You probably just want to add `optional = true` in the obvious place

**Comment by GytisBraz** [comment]
I tried it with e.g. the following `pyproject.toml` file:

```toml
[project]
authors = [
  { name = "author", email = "name@example.com" }
]
description = "Example description"
name = "some-package"
readme = "README.md"
version = "0.0.1"
requires-python = ">=3.10,<3.13"
dependencies = [
  "PyGithub",
]

[project.optional-dependencies]
something-optional = ["colorama"]

[tool.poetry.dependencies]
colorama = {source = "testpypi", optional = true}

[[tool.poetry.source]]
name = "testpypi"
priority = "explicit"
url = "https://test.pypi.org/simple/"
```

But this fails when running `poetry lock` (or `poetry check`) with:

```
The Poetry configuration is invalid:
  - tool.poetry.dependencies.colorama must be valid exactly by one definition (0 matches found)
```
so seems like `optional = true` cannot be included like this 🤔
