### ISSUE TITLE
Poetry 2.1.1 hangs after debug output "Tried 1 solutions."

### ISSUE THREAD

**Issue by vsavenkov** [python-poetry/poetry#10250]
### Description

`poetry lock`  hangs indefinitely after printing "Tried 1 solutions."  with no further output.  What could be the reason for this behavior? 

### Workarounds

Using poetry 1.8.5

### Poetry Installation Method

pipx

### Operating System

Windows 11

### Poetry Version

2.1.1

### Poetry Configuration

```bash session
cache-dir = "C:/Users/[...]/AppData/Local/pypoetry/Cache"
data-dir = "C:\\Users\\[...]\\AppData\\Roaming\\pypoetry"
installer.max-workers = null
installer.no-binary = null
installer.only-binary = null
installer.parallel = true
installer.re-resolve = false
keyring.enabled = true
python.installation-dir = "{data-dir}\\python"  
repositories.lkww-pypi.url = "https://europe-west1-python.pkg.dev/[...]/py/simple/"       
requests.max-retries = 0
solver.lazy-wheel = true
system-git-client = false
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}\\virtualenvs"  
virtualenvs.prompt = "{project_name}-py{python_version}"
virtualenvs.use-poetry-python = false
```

### Example pyproject.toml

```TOML

[tool.poetry]
name = "tried_1_solution_then_died"
version = "0.0.1"
description = "sample project to illustrate poetry 2.1.1 hanging on complex markers"
authors = []


[tool.poetry.dependencies]
python = ">=3.9, <3.12"

tensorflow = {version = "^2.16.2", markers="sys_platform != 'darwin' or platform_machine != 'arm64'" } 
statsmodels = {version = "^0.13.5"}

```

### Poetry Runtime Logs

  ```
 >  poetry lock -vvv

 [...]
 Version solving took 1.728 seconds. 
 Tried 1 solutions.
  ```
