### ISSUE TITLE
Project isn't updated to the directory set by "directory" argument

### ISSUE THREAD

**Issue by Levelleor** [python-poetry/poetry#10287]
### Description

It looks like a bug, when I run `poetry --directory path/to/project build` I get an error:

> WARNING: No build backend defined. Please define one in the pyproject.toml.
> ...

(backend is set under "path/to/project/pyproject.toml")

> ...
> Readme path `path/to/project/README.md` does not exist.

It's weird because if I run Poetry from said directory by changing directory on shell it does work correctly without any issues: `poetry build`.

### Workarounds

1. Changing directory to project manually and running build works: `cd path/to/project && poetry build`
2. Appending `--project ./` seems to work as well. This is weird, I'd assume project is automatically set to "currect directory" when it is changed with `--directory` but it's not. So you have to manually switch it by doing something like this:
```
poetry --directory path/to/project --project ./ build
```
which seems to work correctly as well.

### Poetry Installation Method

pip

### Operating System

RHEL9

### Poetry Version

2.1.1

### Poetry Configuration

```bash session
Fully vanilla config, only changes are source repositories which are PyPi mirrors.
```

### Example pyproject.toml

```TOML
[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["My name", "email@example.net"]
readme = "README.md"
package-mode = true
packages = [
  { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.35.54"
poethepoet = "^0.33.0"
requests = "^2.32.3"

[[tool.poetry.source]]
name = "nexus"
url = "https://nexus.net/repo/repository/pypi/simple/"
priority = "primary"

[tool.poetry.group.dev.dependencies]
nox = "^2024.10.9"
poethepoet = "^0.33.0"
pytest = "^8.3.5"
nox-poetry = "^1.2.0"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

Sorry, I can't get these right now, let me know if these are mandatory.
