### ISSUE TITLE
Error: Attempted to convert a callback into a command twice.

### ISSUE THREAD

**Issue by romanin-rf** [python-poetry/poetry#10321]
### Description

After the update poetry stopped working, it just displays the following error when entering:
```
python -m poetry
```
Output:
```
Attempted to convert a callback into a command twice.
```
It seems like this error comes from the `click` library.

### Workarounds

I don't know...

### Poetry Installation Method

pip

### Operating System

Windows 10

### Poetry Version

2.1.2

### Poetry Configuration

```bash session
When entering any command, it displays:
`Attempted to convert a callback into a command twice.`
```

### Python Sysconfig

<details>
  <summary>sysconfig.log</summary>
  

 Platform: "win-amd64"
Python version: "3.12"
Current installation scheme: "nt"

Paths:
        data = "C:\Program Files\Python312"
        include = "C:\Program Files\Python312\Include"
        platinclude = "C:\Program Files\Python312\Include"
        platlib = "C:\Program Files\Python312\Lib\site-packages"
        platstdlib = "C:\Program Files\Python312\Lib"
        purelib = "C:\Program Files\Python312\Lib\site-packages"
        scripts = "C:\Program Files\Python312\Scripts"
        stdlib = "C:\Program Files\Python312\Lib"

Variables:
        BINDIR = "C:\Program Files\Python312"
        BINLIBDEST = "C:\Program Files\Python312\Lib"
        EXE = ".exe"
        EXT_SUFFIX = ".cp312-win_amd64.pyd"
        INCLUDEPY = "C:\Program Files\Python312\Include"
        LIBDEST = "C:\Program Files\Python312\Lib"
        TZPATH = ""
        VERSION = "312"
        VPATH = "..\.."
        abiflags = ""
        base = "C:\Program Files\Python312"
        exec_prefix = "C:\Program Files\Python312"
        installed_base = "C:\Program Files\Python312"
        installed_platbase = "C:\Program Files\Python312"
        platbase = "C:\Program Files\Python312"
        platlibdir = "DLLs"
        prefix = "C:\Program Files\Python312"
        projectbase = "C:\Program Files\Python312"
        py_version = "3.12.8"
        py_version_nodot = "312"
        py_version_nodot_plat = "312"
        py_version_short = "3.12"
        srcdir = "C:\Program Files\Python312"
        userbase = "C:\Users\instruktazh\AppData\Roaming\Python"
</details>

### Example pyproject.toml

```TOML
[tool.poetry]
name = "nsmlogmgr"
version = "1.0.11"
description = "..."
authors = ["Romanin"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
typing-extensions = "^4.12.2"
dearpygui = "^2.0.0"
sqlalchemy = "^2.0.36"
pydantic = "^2.10.3"
rich-click = "^1.8.5"
python-dateutil = "^2.9.0.post0"
dearpygui-managers = {git = "https://git.smokeofanarchy.ru/Romanin/dearpygui-managers.git"}
properties-py = "^1.2.1"
loguru = "^0.7.3"
platformdirs = "^4.3.7"
rich = "^13.9.4"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.11.1"
pyinstaller-builder = {git = "https://git.smokeofanarchy.ru/Romanin/pyinstaller-builder.git"}
nuitka = "^2.6.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

<details>
  <summary>poetry-runtime.log</summary>
  

  Stack trace:

  10  ~\AppData\Roaming\Python\Python312\site-packages\cleo\application.py:327 in run
       325│
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

   9  ~\AppData\Roaming\Python\Python312\site-packages\poetry\console\application.py:254 in _run
       252│         self._configure_global_options(io)
       253│
     → 254│         self._load_plugins(io)
       255│
       256│         exit_code: int = 1

   8  ~\AppData\Roaming\Python\Python312\site-packages\poetry\console\application.py:630 in _load_plugins
       628│         if not self._disable_plugins:
       629│             from poetry.plugins.application_plugin import ApplicationPlugin
     → 630│             from poetry.plugins.plugin_manager import PluginManager
       631│
       632│             PluginManager.add_project_plugin_path(self.project_directory)

   7  ~\AppData\Roaming\Python\Python312\site-packages\poetry\plugins\plugin_manager.py:18 in <module>
        16│
        17│ from poetry.__version__ import __version__
     →  18│ from poetry.installation import Installer
        19│ from poetry.packages import Locker
        20│ from poetry.plugins.application_plugin import ApplicationPlugin

   6  ~\AppData\Roaming\Python\Python312\site-packages\poetry\installation\__init__.py:3 in <module>
         1│ from __future__ import annotations
         2│
     →   3│ from poetry.installation.installer import Installer
         4│
         5│

   5  ~\AppData\Roaming\Python\Python312\site-packages\poetry\installation\installer.py:9 in <module>
         7│ from packaging.utils import canonicalize_name
         8│
     →   9│ from poetry.installation.executor import Executor
        10│ from poetry.puzzle.transaction import Transaction
        11│ from poetry.repositories import Repository

   4  ~\AppData\Roaming\Python\Python312\site-packages\poetry\installation\executor.py:20 in <module>
        18│
        19│ from poetry.console.exceptions import PoetryRuntimeError
     →  20│ from poetry.installation.chef import Chef
        21│ from poetry.installation.chooser import Chooser
        22│ from poetry.installation.operations import Install

   3  ~\AppData\Roaming\Python\Python312\site-packages\poetry\installation\chef.py:11 in <module>
         9│
        10│ from poetry.utils.helpers import extractall
     →  11│ from poetry.utils.isolated_build import isolated_builder
        12│
        13│

   2  ~\AppData\Roaming\Python\Python312\site-packages\poetry\utils\isolated_build.py:11 in <module>
         9│ from typing import TYPE_CHECKING
        10│
     →  11│ from build import BuildBackendException
        12│ from build.env import IsolatedEnv as BaseIsolatedEnv
        13│

   1  build.py:14 in <module>
        12│ # ! Main > Preparing
        13│
     →  14│ @click.command('preparing')
        15│
        16│ # ! Main

  TypeError

  Attempted to convert a callback into a command twice.

  at ~\AppData\Roaming\Python\Python312\site-packages\click\decorators.py:214 in decorator
      210│         cls = t.cast(t.Type[CmdType], Command)
      211│
      212│     def decorator(f: _AnyCallable) -> CmdType:
      213│         if isinstance(f, Command):
    → 214│             raise TypeError("Attempted to convert a callback into a command twice.")
      215│
      216│         attr_params = attrs.pop("params", None)
      217│         params = attr_params if attr_params is not None else []
      218│
</details>
