### ISSUE TITLE
Specifying by path in tool.poetry.dependencies does not work.

### ISSUE THREAD

**Issue by yassun7010** [python-poetry/poetry#10320]
### Description

The way it was written used to work, but when migrating in v2, this means that bbb/ccc will no longer be included in the lock file when poetry lock is performed.

```toml
[project]
name = "aaa"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
authors = []
dependencies = [
  "pydantic (>=2.11.2,<3.0.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "aaa", from = "src" }]

[tool.poetry.dependencies]
bbb = { path = "../bbb", develop = true }
ccc = { path = "../ccc", develop = true }
```

### Workarounds

If you do poetry add, I get the following: 

```toml
[project]
name = "aaa"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
authors = []
dependencies = [
  "bbb @ file:///Users/****/workspace/poetry_bug/bbb",
  "ccc @ file:///Users/****/workspace/poetry_bug/ccc",
  "pydantic (>=2.11.2,<3.0.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "aaa", from = "src" }]

[tool.poetry.dependencies]
bbb = { develop = true }
ccc = { develop = true }
```

This is an absolute path and cannot be operated by the team.

### Poetry Installation Method

pipx

### Operating System

macOS 15.3.2

### Poetry Version

2.1.2

### Poetry Configuration

```bash session
cache-dir = "/Users/****/Library/Caches/pypoetry"
data-dir = "/Users/****/Library/Application Support/pypoetry"
installer.max-workers = null
installer.no-binary = null
installer.only-binary = null
installer.parallel = true
installer.re-resolve = true
keyring.enabled = true
python.installation-dir = "{data-dir}/python"  # /Users/****/Library/Application Support/pypoetry/python
requests.max-retries = 0
solver.lazy-wheel = true
system-git-client = false
virtualenvs.create = true
virtualenvs.in-project = false
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/****/Library/Caches/pypoetry/virtualenvs
virtualenvs.prompt = "{project_name}-py{python_version}"
virtualenvs.use-poetry-python = false
warnings.export = false
```

### Example pyproject.toml

```TOML
[project]
name = "aaa"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
authors = []
dependencies = [
  "pydantic (>=2.11.2,<3.0.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "aaa", from = "src" }]

[tool.poetry.dependencies]
bbb = { path = "../bbb", develop = true }
ccc = { path = "../ccc", develop = true }
```

### Poetry Runtime Logs

Path /Users/****/workspace/poetry_bug/aaa/poetry_bug/bbb for bbb does not exist
Path /Users/****/workspace/poetry_bug/aaa/poetry_bug/ccc for ccc does not exist
[findpython:findpython] Running script: ['/Users/****/.rye/shims/python', '-EsSc', 'import sys; print(sys.executable)']
Found: /Users/****/.pyenv/versions/3.11.9/bin/python
[findpython:findpython] Running script: ['/Users/****/.rye/shims/python', '-EsSc', 'import platform; print(platform.python_version())']
Using virtualenv: /Users/****/Library/Caches/pypoetry/virtualenvs/aaa--RcEULjb-py3.11
Loading environment variables.
Checking keyring availability: Checking if keyring is available
[keyring:keyring.backend] Loading KWallet
[keyring:keyring.backend] Loading SecretService
[keyring:keyring.backend] Loading Windows
[keyring:keyring.backend] Loading chainer
[keyring:keyring.backend] Loading libsecret
[keyring:keyring.backend] Loading macOS
Using keyring backend 'macOS Keyring'
Available
Resolving dependencies...
   1: fact: aaa is 0.1.0
   1: derived: aaa
   1: fact: aaa depends on pydantic (>=2.11.2,<3.0.0)
   1: selecting aaa (0.1.0)
   1: derived: pydantic (>=2.11.2,<3.0.0)
   1: fact: pydantic (2.11.2) depends on annotated-types (>=0.6.0)
   1: fact: pydantic (2.11.2) depends on pydantic-core (2.33.1)
   1: fact: pydantic (2.11.2) depends on typing-extensions (>=4.12.2)
   1: fact: pydantic (2.11.2) depends on typing-inspection (>=0.4.0)
   1: selecting pydantic (2.11.2)
   1: derived: typing-inspection (>=0.4.0)
   1: derived: typing-extensions (>=4.12.2)
   1: derived: pydantic-core (==2.33.1)
   1: derived: annotated-types (>=0.6.0)
   1: fact: typing-inspection (0.4.0) depends on typing-extensions (>=4.12.0)
   1: selecting typing-inspection (0.4.0)
   1: fact: pydantic-core (2.33.1) depends on typing-extensions (>=4.6.0,<4.7.0 || >4.7.0)
   1: selecting pydantic-core (2.33.1)
   1: selecting typing-extensions (4.13.1)
   1: selecting annotated-types (0.7.0)
   1: Version solving took 0.005 seconds.
   1: Tried 1 solutions.
