### ISSUE TITLE
Dev group dependency develop not locking as editable

### ISSUE THREAD

**Issue by njgrisafi** [python-poetry/poetry#10332]
### Description

PEP 621 develop group dependencies are not locked as editable.

Example pyproject

```toml
[project]
name = "example"
description = "Example"
version = "0.2.0"
requires-python = ">=3.11.8"
authors = []
dependencies = [
    "my-package",
]

[project.optional-dependencies]
dev = [
    "my-dev-package",
]

[tool.poetry.dependencies]
my-package = { path = "my-package", develop = true }

[tool.poetry.group.dev.dependencies]
my-dev-package = { path = "my-dev-package", develop = true }

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
```

The package in main group are correct
```toml
[[package]]
name = "my-package"
version = "0.1.0"
description = ""
optional = false
python-versions = "^3.11"
groups = ["main"]
files = []
develop = true
```

however, the package in the group dev are not correct
```toml
[[package]]
name = "my-dev-package"
version = "0.1.0"
description = ""
optional = false
python-versions = ">=3.11.0,<=3.11.8"
groups = ["main", "dev"]
files = []
develop = false
```

I understand the docs mention to just use `tool.poetry` for editable dependencies but it's odd how it works for main but not other groups. Also it would be nice to define it in pep 621 dependency sections so other tools can perform an install.

### Workarounds

Remove the package from the group and just keep it in `tool.poetry`

```toml
[project]
name = "example"
description = "Example"
version = "0.2.0"
requires-python = ">=3.11.8"
authors = []
dependencies = [
    "my-package",
]

# [project.optional-dependencies]
# dev = [
#     "my-dev-package",
# ]

[tool.poetry.dependencies]
my-package = { path = "my-package", develop = true }

[tool.poetry.group.dev.dependencies]
my-dev-package = { path = "my-dev-package", develop = true }

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
```

Now the lock file is correct for this package

```toml
[[package]]
name = "my-dev-package"
version = "0.1.0"
description = ""
optional = false
python-versions = ">=3.11.0,<=3.11.8"
groups = ["dev"]
files = []
develop = true
```

### Poetry Installation Method

install.python-poetry.org

### Operating System

Debian 11

### Poetry Version

2.1.1

### Poetry Configuration

```bash session
installer.max-workers = null
installer.no-binary = null
installer.only-binary = null
installer.parallel = true
installer.re-resolve = true
keyring.enabled = true
requests.max-retries = 0
solver.lazy-wheel = true
system-git-client = false
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.system-site-packages = false
virtualenvs.prompt = "{project_name}-py{python_version}"
virtualenvs.use-poetry-python = false
```

### Example pyproject.toml

```TOML
[project]
name = "example"
description = "Example"
version = "0.2.0"
requires-python = ">=3.11.8"
authors = []
dependencies = [
    "my-package",
]

[project.optional-dependencies]
dev = [
    "my-dev-package",
]

[tool.poetry.dependencies]
my-package = { path = "my-package", develop = true }

[tool.poetry.group.dev.dependencies]
my-dev-package = { path = "my-dev-package", develop = true }

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

Cannot share my whole logs.

But I do see things like this in `poetry -vvv lock`

```
   0: Duplicate dependencies for my-dev-package
   0: Merging requirements for my-dev-package
```

**Comment by hartungstenio** [comment]
I think the issue is that `project.optional-dependencies` and `tool.poetry.group.dev.dependencies` are actually different things. 

`project.optional-dependencies` are main optional dependencies, so it would be something like
```toml
[tool.poetry.dependencies]
my-package = { path = "my-package", develop = true } 
my-dev-package = { path = "my-dev-package", optional = true, develop = true }
```

PEP 735 is the equivalent to 
Poetry dependency groups (under `tool.poetry.group.dev.dependencies`), but poetry does not support it yet.
