### ISSUE TITLE
Invalid platform marker boolean operator usage in generated poetry.lock

### ISSUE THREAD

**Issue by felixhuttmann-tng** [python-poetry/poetry#10439]
### Description

With my pyproject.toml (given below), poetry generates a lock file that has invalid boolean expressions on the platform marker:
```
markers = "sys_platform != \"darwin\" or  and  or platform_machine != \"arm64\" and platform_machine != \"aarch64\" and platform_machine != \"x86_64\""
```
(specifically ` or  and  or ` with no expression in between`)

This does not seem to bother poetry install, but it does block using `poetry export` which we need for vulnerability and license scans:
```
poetry export --format="requirements.txt" > requirements.txt

Unexpected token Token('BOOL_OP', 'and') at line 1, column 30.
Expected one of:
	* ESCAPED_STRING
	* L_PAREN
	* SINGLE_QUOTED_STRING
	* MARKER_NAME
Previous tokens: [Token('BOOL_OP', 'or')]
```

Essentially the same pyproject.toml worked with poetry 1.8.5 and the built-in export functionality of poetry 1.8.5.

### Workarounds

Stay on poetry 1.x.

### Poetry Installation Method

other

### Operating System

Mac OS

### Poetry Version

Poetry (version 2.1.3)

### Poetry Configuration

```bash session
cache-dir = "/Users/felix/Library/Caches/pypoetry"
data-dir = "/Users/felix/Library/Application Support/pypoetry"
installer.max-workers = null
installer.no-binary = null
installer.only-binary = null
installer.parallel = true
installer.re-resolve = true
keyring.enabled = true
python.installation-dir = "{data-dir}/python"  # /Users/felix/Library/Application Support/pypoetry/python
requests.max-retries = 0
solver.lazy-wheel = true
system-git-client = false
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/felix/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = true
virtualenvs.prompt = "{project_name}-py{python_version}"
virtualenvs.use-poetry-python = false
```

### Python Sysconfig

[python_sysconfig.txt](https://github.com/user-attachments/files/20818549/python_sysconfig.txt)

### Example pyproject.toml

```TOML
[tool.poetry]
name = "poetry-export-bug-repro"
version = "0.1.0"
description = ""
authors = ["Felix Huttmann <felix.huttmann@tngtech.com>"]
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

requires-poetry = "== 2.1.3"

[tool.poetry.requires-plugins]
poetry-plugin-export = "==1.9.0"

[tool.poetry.dependencies]
python = "~3.11"


[tool.poetry.group.cli]
optional = false

[tool.poetry.group.cli.dependencies]
llm = "~0.21"

[tool.poetry.group.platform]
optional = true

[tool.poetry.group.platform.dependencies]
#  torch needed for unstructured document processing
torch = [
  { url = "https://download.pytorch.org/whl/cpu/torch-2.4.1%2Bcpu-cp311-cp311-linux_x86_64.whl", markers = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
  { url = "https://download.pytorch.org/whl/cpu/torch-2.4.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", markers = "sys_platform == 'linux' and (platform_machine == 'arm64' or platform_machine == 'aarch64')" },
  { url = "https://download.pytorch.org/whl/cpu/torch-2.4.1%2Bcpu-cp311-cp311-win_amd64.whl", markers = "sys_platform == 'win32'" },
  { url = "https://download.pytorch.org/whl/cpu/torch-2.4.1-cp311-none-macosx_11_0_arm64.whl", markers = "sys_platform == 'darwin' and platform_machine == 'arm64'" }
]
torchvision = [
  { url = "https://download.pytorch.org/whl/cpu/torchvision-0.19.1%2Bcpu-cp311-cp311-linux_x86_64.whl", markers = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
  { url = "https://download.pytorch.org/whl/cpu/torchvision-0.19.1-cp311-cp311-linux_aarch64.whl", markers = "sys_platform == 'linux' and (platform_machine == 'arm64' or platform_machine == 'aarch64')" },
  { url = "https://download.pytorch.org/whl/cpu/torchvision-0.19.1%2Bcpu-cp311-cp311-win_amd64.whl", markers = "sys_platform == 'win32'" },
  { url = "https://download.pytorch.org/whl/cpu/torchvision-0.19.1-cp311-cp311-macosx_11_0_arm64.whl", markers = "sys_platform == 'darwin' and platform_machine == 'arm64'" }
]
pypandoc-binary = [
  { version = "^1.12", markers = "sys_platform == 'linux'" },
  { version = "^1.12", markers = "sys_platform == 'win32'" },
  { version = "^1.12", markers = "sys_platform == 'darwin' and platform_machine == 'x86_64'" },
]
pypandoc = [
  { version = "^1.12", markers = "sys_platform == 'darwin' and platform_machine == 'arm64'" }
]
```

### Poetry Runtime Logs

[poetry_runtime_logs.txt](https://github.com/user-attachments/files/20818570/poetry_runtime_logs.txt)
