### ISSUE TITLE
unable to load spyder into poetry project.

### ISSUE THREAD

**Issue by rapidregression** [python-poetry/poetry#10440]
### Description

I am required to use poetry and am brand new to it. OS is MAcBook Pro M3 Sequoia 15.5 Pandas 2.3.0. Python 3.12.10. When I add spyder the default is 6.0.7 but it won't load and throws an error of unknown metadata version: 2.4.  Is there a specific spyder I can add that should work in this poetry build I am married to, or is this some other issue going over my head. 

`Unknown metadata version: 2.4`

It says it is `resolving dependencies and parsing as 2.3` but it never loads.

### Workarounds

none that I found

### Poetry Installation Method

other

### Operating System

M3 Sequoia 15.5

### Poetry Version

1.8.4

### Poetry Configuration

```bash session
cache-dir = "/Users/################/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /var/empty
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Python Sysconfig

[python build.txt](https://github.com/user-attachments/files/20821297/python.build.txt)

### Example pyproject.toml

```TOML
[tool.poetry]
name = "test-spyder"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

couldn't run

zsh: parse error near `\n'
