### ISSUE TITLE
Poetry allows multiline descriptions which causes problems with pip installing extras

### ISSUE THREAD

**Issue by OK-UNDP** [python-poetry/poetry#1372]
- [X] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Poetry version**: 1.0.0b1
- **Link to pyproject.toml file**: https://github.com/undp/MsGraphExporter/blob/e75b59102d31225b12f6181ea3118ad65cfb22b9/pyproject.toml

## Issue
The issue was discovered while publishing docs from [undp/MsGraphExporter](https://github.com/undp/MsGraphExporter) on ReadTheDocs. When `pyproject.toml` option `description` has a multi-line string enclosed in `"""` ([which is perfectly legit for a string in TOML](https://github.com/toml-lang/toml#string)), it causes `poetry` to build the package with multi-line `Summary` in `info/METADATA` which does not seem to be valid according to https://github.com/pypa/pip/issues/7010#issuecomment-531068027

Perhaps `poetry` could just truncate the multi-line `description`, make it a single-lined one or flag the issue with `poetry check`.

_Originally posted by @OK-UNDP in https://github.com/readthedocs/readthedocs.org/issues/6151#issuecomment-531048562_

**Comment by rrei** [comment]
@sdispater thank you very much for creating poetry! I am absolutely in love with this tool ❤️ 

Any news on this topic? I just spent way too much time banging my head against the wall because of this... 😭 

According to this link (https://packaging.python.org/specifications/core-metadata/#summary) and what @OK-UNDP said, **I believe poetry should enforce a single-line `description` field** (during `poetry build` and `poetry check`). Also, it would be nice if this restriction was mentioned in the documentation (https://python-poetry.org/docs/pyproject/#description).

As it stands now, no error occurs when building, `poetry check` says everything is okay, and pip only installs my library and none of its dependencies, but it doesn't display any errors either, which makes it extremely hard to find the source of the error. Worse still, pip installing the sdist **does** install dependencies!

A simple example that breaks without any useful feedback (I am using Poetry 1.0.5):

```toml
[tool.poetry]
name = "example-lib"
version = "0.1.0"
description = """
First line
Second line (BOOOOOM)"""
authors = ["John Doe <john.doe@example.org>"]
packages = [{ include = "example", from = "src" }]

[tool.poetry.dependencies]
python = "^3.8"
addict = "^2.2.1"
loguru = "^0.5.0"
typer = {extras = ["all"], version = "^0.2.1"}
wcmatch = "^6.0.1"
```

@sdispater if you agree with my suggestion to enforce the single-line `description` field, I'd be happy to give it a try and submit a PR 😃
