### ISSUE TITLE
Conditional requirements incorrectly written to extras_require

### ISSUE THREAD

**Issue by janrg** [python-poetry/poetry#1462]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 0.12.17

## Issue
Steps to reproduce:
- `poetry new my-package`
- add conditional dependency to `[tool.poetry.dependencies]`, e.g. `enum34 = [{version = "^1.1", python = "<3.4"}]`
- `poetry build`
- `setup.py` will list the dependency under `extras_require`
- if instead the dependency is given as `enum34 = "^1.1"`, it correctly is written to `install_requires`

**Comment by Golyo88** [comment]
Any update on this?

**Comment by Fizzadar** [comment]
We are also encountering this problem, leading to potentially installing completely incorrect dependency versions!

```toml
[tool.poetry.dependencies]
python = '^3.5'
kombu = {version = '^=4.5', optional = true}

[tool.poetry.extras]
queue = ['kombu']
```

Generates a `setup.py`:

```py
```
