### ISSUE TITLE
Impossible to install Black 19.3b0

### ISSUE THREAD

**Issue by Xowap** [python-poetry/poetry#1505]
- **OS version and name**: `elementary OS 0.4.1 Loki`
- **Poetry version**: `0.12.17`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/Xowap/typefit/blob/develop/pyproject.toml

## Issue
I'm trying to install Black, and I'm kind of succeeding thanks to comments in #767. However, the version of Black I'm getting is not the latest one:

```
> poetry run black --version
black, version 18.9b0
```

The latest one being [`19.3b0`](https://github.com/psf/black/releases/tag/stable).

I was wondering if this could be due to black not respecting semver, so I put the version number manually to see what happens, but turns out it's not helping much.

```toml
black = {version = "19.3b0", allows-prereleases = true}
```

```
[SolverProblemError]                                                                    
Because typefit depends on black (19.3b0) which doesn't match any versions, version solving failed.
```

Thanks for your help!

**Comment by n8sty** [comment]
I'm running 1.0.0b3 and I can successfully install `black`. What happens if you upgrade to a newer, preview version of poetry?

**Comment by Xowap** [comment]
Interestingly enough, I'm getting this

```
> poetry run black --version
Poetry version 1.0.0b3
```

But I guess it's another bug on its own.

To answer the actual question:

```
> poetry show black
name         : black
version      : 18.9b0
description  : The uncompromising code formatter.

dependencies
 - appdirs *
 - attrs >=17.4.0
 - click >=6.5
 - toml >=0.9.4
```

**Comment by b0g3r** [comment]
Do you create a lock file before installing?

**Comment by Xowap** [comment]
I believe that I tried many things. Latest attempts had a lock file but in order to make sure I've tried to reproduce the problem from scratch.

Using poetry 0.12.17 and Python 3.8.0, I went to an empty folder and did a `poetry init` which gave the following file:

```toml
[tool.poetry]
name = "test-poetry"
version = "0.1.0"
description = ""
authors = ["Rémy Sanchez <remy.sanchez@hyperthese.net>"]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Then I ran `poetry add -D --allow-prereleases black` and it still did...

```  - Installing black (18.9b0)```

That's pretty accurately reproducible for me. On this machine, on my other one or when using Python `3.6` instead of `3.8`
