### ISSUE TITLE
Aliasing prod dependencies in dev

### ISSUE THREAD

**Issue by blaggacao** [python-poetry/poetry#1715]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

- Packages provide _API namespaces_
- API namepsaces are _mostly_ identified by the package name
- A package name _mostly_ resolves to a package source
- Yet, there are _valid_ exceptions to bost norms:
  - A package should resolve to an alternate _local_ source for dev (eg. `python-poetry/semver` to `python-poetry/poetry`)
  - A package namespace can be provided in different flavors by different packages (e.g. `psycopg2` & `psycopg2-binary`)

Therefore, add `[tool.poetry.dev-alternates]` with exactly the same syntax as `[tool.poetry.dependencies]` yet with an optional `aliases` field on the dep object, to inform which production package's namespace is provided through this package during dev. If `aliases` is not specified, it shall be inferred by the dep name itself.

Example covering both cases:

```toml
[tool.poetry.dependencies]
python = "^3.7"
dodoo = "^2.0"
psycopg2 = "^2.8"

[tool.poetry.dev-alternates]
psycopg2-binary = {aliases = psycopg2, version = "^2.8"}
dodoo = {path = "../dodoo"}
```

It could be considered to make this a sub-path of `[tool.poetry.dev-dependencies]`, however the author consideres, flat rymes are part of poetry's rythm, so stick with the groove.
