### ISSUE TITLE
Extras not installed for a git repository in dev-dependencies

### ISSUE THREAD

**Issue by albireox** [python-poetry/poetry#1813]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15
- **Poetry version**: 1.0.0

## Issue

The following configuration seems to work fine

```toml
[tool.poetry.dependencies]
sdsstools = "^0.1.0"

[tool.poetry.dev-dependencies]
sdsstools = {version="^0.1.0", extras=["dev"]}
```

i.e., `sdsstools` gets installed as a dependency, but if you're installing the dev dependencies, then `sdsstools` is installed with `dev` (which ultimately just installs `invoke`). However, the following does not work

```toml
[tool.poetry.dependencies]
sdsstools = {git="https://github.com/sdss/sdsstools.git"}

[tool.poetry.dev-dependencies]
sdsstools = {git="https://github.com/sdss/sdsstools.git", extras=["dev"]}
```

`sdsstools` gets installed but not the `[dev]` extras, either by doing `poetry update` or `poetry install`. If I add `sdsstools = {git="https://github.com/sdss/sdsstools.git", extras=["dev"]}` to `[tool.poetry.dependencies]` then the `dev` dependencies do get installed.
