### ISSUE TITLE
Export wrong dependencies when using optional=true

### ISSUE THREAD

**Issue by linw1995** [python-poetry/poetry#1921]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: 10.15.2 macOS
- **Poetry version**: 1.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/linw1995/3132491fd3adabccc4adaf48ab51544a#file-pyproject-toml

## Issue

<details>
<summary>
<b>Execute</b>
<code>cat pyproject.toml</code>
</summary>

```toml
[tool.poetry]
name = "tmp"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest-cov = {version = "^2.8.1", optional = true}

[tool.poetry.dev-dependencies]
coverage = "^5.0.3"

[tool.poetry.extras]
dev = ["pytest-cov"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

</details>

<details>
<summary>
<b>Execute</b>
<code>poetry show --tree</code>
</summary>

```
coverage 5.0.3 Code coverage measurement for Python
pytest-cov 2.8.1 Pytest plugin for measuring coverage.
├── coverage >=4.4
└── pytest >=3.6
    ├── atomicwrites >=1.0
    ├── attrs >=17.4.0
    ├── colorama *
    ├── more-itertools >=4.0.0
    ├── packaging *
    │   ├── pyparsing >=2.0.2
    │   └── six *
    ├── pluggy >=0.12,<1.0
    ├── py >=1.5.0
    └── wcwidth *
```

</details>

In this small demo, the only dependency in the section`[tool.poetry.dependencies]` is `pytest-cov`, and it's optional. After adding `coverage` (that is the sub dependency of `pytest-cov`) in the section `[tool.poetry.dev-dependencies]`, I execute `poetry export` without `--dev` option should output nothing but `coverage==5.0.3`.

```
$ poetry export -f requirements.txt --without-hashes
coverage==5.0.3
```
