### ISSUE TITLE
[Bug]: export in alphabet order cause extra package install 

### ISSUE THREAD

**Issue by Trim21** [python-poetry/poetry#1977]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: docker image `python:3.7.6`
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

```toml
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Trim21 <i@trim21.me>"]

[tool.poetry.dependencies]
python = "^3.7"

aiohttp = {version = "3.6.2", extras = ["speedups"]}

[tool.poetry.dev-dependencies]
```

## Issue

`poetry export --format requirements.txt > requirements.txt` got a requirements file in alphabet order.

```
...
brotlipy==0.7.0 \
...
cffi==1.13.2 \
...
```

in the `setup.py` of `brotlipy`

```python
    setup_requires=[
        "cffi>=1.0.0",
    ],
    install_requires=[
        "cffi>=1.0.0",
    ],
    extras_require={
        ':python_version == "2.7" or python_version == "3.3"': ['enum34>=1.0.4, <2'],
    },
```

which requires `cffi` in installing.

And I install it in an environment which has no access to pypi official.

So when I install it with `pip install --require-hashes --no-deps --no-cache-dir --index https://example.com/mirror/pypi -r /requirements.txt`

It fault when installing brotlipy.
