### ISSUE TITLE
Optional dependency also required by dev dependency always contained in export

### ISSUE THREAD

**Issue by languitar** [python-poetry/poetry#1989]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: archlinux
- **Poetry version**: 1.0.3

## Issue

Optional dependencies are always included in a `poetry export` call in case the same dependency is also a transitive dependency of a dev dependency.

Here is a minimal `pyproject.toml` to demonstrate the problem:

```toml
[tool.poetry]
name = "bug"
version = "1.0"
description = "poetry export bug"
authors = ["Johannes Wienke"]

[tool.poetry.dependencies]
python = "^3.7"
flask = { version = "^1.0", optional = true }

[tool.poetry.extras]
web = ["flask"]

[tool.poetry.dev-dependencies]
pytest-flask = "^0.15.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

When doing a `poetry lock; poetry export -f requirements.txt`, `flask` will always be included, despite not providing the extra `web` to `poetry export`. This seems to happen because `flask` is a transitive dependency of `pytest-flask`. Removing `pytest-flask` from the dev dependencies will result in `flask` being correctly marked as an optional dependency in the lock file. In the example, the `optional` flag is not set in the lock file for `flask`.
