### ISSUE TITLE
Lightweight core library

### ISSUE THREAD

**Issue by sdispater** [python-poetry/poetry#1993]
Currently, to build a Poetry project via the `PEP-517` build mechanism, you need this section:

```toml
[build-system]
requires = ["poetry>=1.0.3"]
build-backend = "poetry.masonry.api"
```

This works but this has the undesirable side-effect of pulling the full Poetry stack and its dependencies. Most of them are not needed to build the project and expose the metadata.

To prevent that, we need to extract parts of the Poetry stack into a more lightweight library with the sole purpose of building projects.

Ideally, this core library should not have any dependency to avoid errors to to circular build dependencies when using `pip install --no-binary :all:`.
