### ISSUE TITLE
Poetry cannot properly parse URL with Gitlab [deploy tokens]

### ISSUE THREAD

**Issue by xinbinhuang** [python-poetry/poetry#2062]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:   Ubuntu 18.04
- **Poetry version**:  1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Poetry cannot properly parse URL with gitlab [deploy tokens](https://docs.gitlab.com/ee/user/project/deploy_tokens/). The project is hosted on a internal hosted Gitlab server.

The same git URL worked before, but I am not sure since when it is failing.

Command I ran:

```
poetry add "git+https://<token-name>:<token-key>@<my-org-self-hosted-gitlab-url>/<repo-path>/<repo-name>.git" -vvv
```

Output 

```bash
[ValueError]
Invalid git url "git+https://<token-name>:<token-key>@<my-org-self-hosted-gitlab-url>/<repo-path>/<repo-name>.git"

Traceback (most recent call last):
  File "/home/binbin/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/binbin/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/binbin/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/binbin/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/binbin/.poetry/lib/poetry/console/commands/add.py", line 89, in handle
    packages, allow_prereleases=self.option('allow-prereleases')
  File "/home/binbin/.poetry/lib/poetry/console/commands/init.py", line 294, in _determine_requirements
    requires = self._parse_requirements(requires)
  File "/home/binbin/.poetry/lib/poetry/console/commands/init.py", line 371, in _parse_requirements
    parsed = ParsedUrl.parse(requirement)
  File "/home/binbin/.poetry/lib/poetry/vcs/git.py", line 118, in parse
    raise ValueError('Invalid git url "{}"'.format(url))
```

**Comment by xinbinhuang** [comment]
Just checked that it works when poetry is `<=1.0.2`. Maybe there is a incompatible change introduced in 1.0.3?

**Comment by finswimmer** [comment]
Hello @xinbinhuang,

thanks a lot for reporting. The git url parsing has changed significant within the last release to be more consistent. As I was not aware of something like deploy tokens, the regex will probably not match anymore.

I will take a closer look at this. Could you give me please an example how `<token-name>:<token-key>` looks like?

fin swimmer

**Comment by xinbinhuang** [comment]
Thanks for the quick response.

The Gitlab's doc is  [here](https://docs.gitlab.com/ee/user/project/deploy_tokens/).

I tried to generate a few different tokens until hitting an error. 
```bash
# This is Gitlab's format requirements: 
# Here Username == <token-name>
Username can contain only letters, digits, '_', '-', '+', and '.'
```
So something like this `[\w-\+\.]` should work for `<token-name>`

For the `<token-key>`, it is auto generated. So far, I have only seen alphanumeric (letters + digits) characters, but it may also contains the same pattern as the `<token-name>`.

Let me know if you would need extra information or help from me.

Thanks
Bin

**Comment by jedie** [comment]
I am also running into this issue :( Any update or work-a-round here?

**Comment by xinbinhuang** [comment]
@jedie , while waiting for the bug to be fixed. You can pin your poetry version in your `pyproject.toml`

For example
```                                                                                                                                       
[tool.poetry]
name = "new-package"
version = "0.1.0"
description = ""

...

[build-system]
requires = ["poetry<=0.12"]                 # this line: pin poetry to be <= 1.0.2
build-backend = "poetry.masonry.api"

```

**Comment by abn** [comment]
@xinbinhuang would making use of [gitcredentials](https://git-scm.com/docs/gitcredentials) be the better apporach here? This would work both in your development and deployment scenarios. As an additional benifit, would allow you to ensure seperation of privilleges using different credentials.

As for respecting the git url spec, I agree we should ensure that a url of the form `https://user:pass@example.com/repo.git` is accepted. However, I would not consider using these urls when adding dependencies the best practice. This is because that would mean that the credentials will end up in plain text in both your `peotry.lock` and `pyproject.toml` files. We should also considering logging warnings once this is fixed and a `password` is matched/detected.

A reasonable approach might be extend the URL validation to also include a new group "password". The user should stil consider `:` invalid.

**Comment by xinbinhuang** [comment]
@abn Thanks for the suggestion, I have not used gitcredentials before.

While I think your suggestion is valid in common scenarios for user passwords, it is a different case for [Gitlab Deploy Tokens](https://docs.gitlab.com/ee/user/project/deploy_tokens/). These deploy tokens are not user credentials and designed specifically by Gitlab with limited permission scopes (similar to service account). So in the context of Gitalb Deploy Tokens, I believe it's valid.

While security suggestion by warnings is good (with optional disabling it), I don't think poetry as a package management tool should by any means enforce this validation and should leave this as a choice for the users.

I haven't used Gitlab for a while now, so it doesn't affect me that much. I like poetry and hope it will be successful in the future, so I hope poetry can make good decisions along the way.

**Comment by jedie** [comment]
Any update here?

**Comment by ansar-sa** [comment]
Any update please. Pain point for gitlab users.

**Comment by dagap** [comment]
Same here. This is a major blocker now.

**Comment by jedie** [comment]
Still blocked because of https://github.com/python-poetry/poetry-core/pull/115 ?!?

**Comment by carlos-lm** [comment]
any solution or workaround? I have a deploy token similar to @xinbinhuang but currently poetry fails with invalid git url :grimacing:

**Comment by lstolcman** [comment]
@carlos-lm 

Unfortunately, gitlab deploy token url does not work when one wants to use a command `poetry add`.
We solved a problem by adding it straight to `pyproject.toml` and bypassing `poetry add`:

```toml
[tool.poetry.dependencies]
repo-name = {git = "https://gitlab+deploy-token-123:aabbddcceeff-ggh@git.example.com/repo_path/repo_name.git", tag = "1.0.0"}
# or
repo-name = {git = "https://gitlab+deploy-token-123:aabbddcceeff-ggh@git.example.com/repo_path/repo_name.git", rev = "aabbccdd"}
# or
repo-name = {git = "https://gitlab+deploy-token-123:aabbddcceeff-ggh@git.example.com/repo_path/repo_name.git", branch = "next"}
```

**Comment by EnriqueSoria** [comment]
For me it works if I expose my token in `pyproject.toml` 
```toml
[[tool.poetry.source]]
name = "<a_name>"
url = "https://<token_name>:<token>@gitlab.com/api/v4/projects/<project_id>/packages/pypi/simple"
```

**Comment by jedie** [comment]
I still run into the same error on gitlab CI:

![grafik](https://user-images.githubusercontent.com/71315/135441475-10c221ac-62df-4c73-b0a5-bea5eee68417.png)

Locally it works. Both used the same versions: Python 3.8, poetry v1.1.10

@EnriqueSoria This is for PyPi packages and not git source installation, isn't it?

**Comment by EnriqueSoria** [comment]
> I still run into the same error on gitlab CI:
> 
> ![grafik](https://user-images.githubusercontent.com/71315/135441475-10c221ac-62df-4c73-b0a5-bea5eee68417.png)
> 
> Locally it works. Both used the same versions: Python 3.8, poetry v1.1.10
> 
> @EnriqueSoria This is for PyPi packages and not git source installation, isn't it?

True, sorry

**Comment by lstolcman** [comment]
So I've looked into related PRs, and https://github.com/python-poetry/poetry-core/pull/115 resolves this issue.

One problem I encountered afterwards was that error message:
```sh
server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```
this was resolved by setting `git config http.sslverify false`
(source: https://forum.gitlab.com/t/server-certificate-verification-failed/7825)

**Comment by jedie** [comment]
Any news here?!?

**Comment by a1d4r** [comment]
Same issue here. 
`poetry install` fails in Gitlab CI with a package added with Gitlab Deploy Token. Locally it works fine.
I use Python 3.9 and Poetry version 1.1.11 in both environments.

**Comment by maresb** [comment]
In my case, I was able to use @EnriqueSoria's [workaround](https://github.com/python-poetry/poetry/issues/2062#issuecomment-931100580) of using GitLab's private PyPI repository, which allows me to use deploy tokens. Full details are as follows.

In the "source" project's repository (the project which you want to install into one or more "destination" projects), put the following verbatim into `.gitlab-ci.yml`. (The CI job token exists automatically, and none of the variables need to be modified. Simply copy-paste! I assume that `pyproject.toml` is in the repo's root.)

```yaml
# A pipeline for uploading the project as a package to GitLab's private PyPI repository.
# (This allows the project to be installed from Poetry as a URL dependency with a personal access token.)

# References:
#  <https://docs.gitlab.com/ee/user/packages/pypi_repository/index.html#authenticate-with-a-ci-job-token>
#  <https://github.com/python-poetry/poetry/issues/2062>

build-wheel:
  when: manual
  image: python:latest
  script:
    - pip install twine
    - pip wheel --no-deps .
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi *.whl
```

Then now you can publish a wheel to "Packages & Registries" → "Package Registry", by going to "CI/CD" → "Pipelines" and manually start the `build-wheel` pipeline.

To install this wheel to some "destination" project, in your destination project's `pyproject.toml` you should put

```toml
[tool.poetry.dependencies]
packagename = { url = "https://gitlab+deploy-token-123456:t0k3n@gitlab.com/api/v4/..." }
```

To adapt this snippet to your project, you will need the following pieces of information...

* The "source" project's Project ID number. This can be found right under the project name on the GitLab overview page. For me, it consists of 8 digits.

* The "source" project's name, as it appears in `pyproject.toml` under `[tool.poetry]` as `name = "..."`.

* A deploy token from the "source" project which has `read_package_registry` scope. This can be generated from the "source" project under "Settings" → "Repository" → "Deploy tokens". The token consists of a username and (secret) password.

First, in the destination project's `pyproject.toml`, modify my example by substituting `packagename` with the "source" project's name.

Finally, to determine the proper URL, visit `https://gitlab.com/api/v4/projects/12345678/packages/pypi/simple/projectname` in a browser, after substituting `12345678` with the "source" project's Project ID and `projectname` with the source project's name. From the resulting webpage, copy the desired link and paste it into your `pyproject.toml`, and between `https://` and `@gitlab.com` add your deploy token username and password, separated by `:`.

Now Poetry should be able to install your "source" package as a dependency.
