### ISSUE TITLE
poetry install --extras doesn't work

### ISSUE THREAD

**Issue by anentropic** [python-poetry/poetry#2073]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.6
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/anentropic/661458664b20923cf07f7e377972870b

## Issue

[The docs](https://python-poetry.org/docs/pyproject/#extras) show a pyproject.toml:
```toml
[tool.poetry]
name = "awesome"

[tool.poetry.dependencies]
# These packages are mandatory and form the core of this package’s distribution.
mandatory = "^1.0"

# A list of all of the optional dependencies, some of which are included in the
# below `extras`. They can be opted into by apps.
psycopg2 = { version = "^2.7", optional = true }
mysqlclient = { version = "^1.3", optional = true }

[tool.poetry.extras]
mysql = ["mysqlclient"]
pgsql = ["psycopg2"]
```
And then an example of installing the "extras":
```
poetry install --extras "mysql pgsql"
```
But pasting the relevant part of this example into my own pyproject.toml (see gist) it doesn't work:
```
$ poetry install --extras "mysql pgsql"
Installing dependencies from lock file

[ValueError]
Extra [mysql] is not specified.
```

**Comment by anentropic** [comment]
is there some caching of the pyproject.toml?

I had this problem with the extras I originally wanted to install, so I tried with the exact example from the docs before posting this issue

Neither worked (as shown above)...

Now I have gone back and replaced the docs example with my intended extras:
```toml
[tool.poetry.dependencies]
...
ipython = {version=">=7.10.1", optional=true}
ipdb = {version="*", optional=true}

[tool.poetry.extras]
devtools = ["ipython", "ipdb"]
```
and it works now 🤔 
```
$ poetry install --extras devtools
Installing dependencies from lock file


Package operations: 2 installs, 0 updates, 0 removals

  - Installing ipython (7.12.0)
  - Installing ipdb (0.12.3)
  - Installing waterloo (0.1.0)
```

After all that I did a `poetry build` and I realise what I am trying to do is not what `extras` is for anyway 🤦‍♂ ... `extras` is for the square-bracketed optional extra deps when installing my lib from pypi

I see now what I really wanted was #1644 ... I commonly have three groups of deps: "install", "test" (what's needed to run tests, what pipenv and poetry call dev dependencies) and "devtools" which are stuff like `ipython` and `ipdb` and other utils that are only useful to me working on the project and don't need to be installed on the CI

**Comment by anentropic** [comment]
what I am loving is no waiting minutes for `pipenv` to 'lock' though 👍

**Comment by JBKahn** [comment]
I'm having a similar issue when I go from `1.0.0` to `1.0.1`, extras are removed from my lockfile. I tried clearing the cache but that doesn't seem to help.

**Comment by JBKahn** [comment]
It still has a `[package.extras]` section like this, which is correct:
```
[package.extras]
first = ["A (>=3.0.0)"]
second = ["B (>=10.0.0)", "C (<3.0.0)", "D (>=6.0.0)"]
```

and 

```
[package.dependencies.D]
optional = true
version = ">=6.0.0"
```
etc for each but `D` is otherwise omitted from the lockfile.

**Comment by JBKahn** [comment]
`D` is also in the dependancy tree, so it's just whatever is exporting the lockfile is the issue

**Comment by JBKahn** [comment]
`poetry lock -vvv` also says:
`1: selecting D (10.0.0)`

So it's just an issue with lockfile generation for me

**Comment by JBKahn** [comment]
I've had to manually resort to copying `D` into my `pyproject.toml` for now. Without it, it omits from the lockfile and then refuses to install claiming it doesn't know how to resolve the dependancy that it omitted. Very strange.

**Comment by dekoza** [comment]
Any progress on this bug? It's a blocker.

**Comment by JBKahn** [comment]
Sadly I no longer have access to the old projects I was working with now that I'm with a new company so I'd need to find a way to reproduce it from scratch.

**Comment by dekoza** [comment]
My [django-getpaid](https://github.com/django-getpaid/django-getpaid) project has a `test` extra dependency group declared among others.

`poetry install` does not install pytest

`poetry install -E tests` does not install pytest either.

**Comment by matthijskooijman** [comment]
This might be a duplicate of #1145? Though that shows the extras being omitted, while this issue shows an error message about the extras being unknown...

**Comment by wshayes** [comment]
Looks like you can install multiple dependencies in a single set using the following approach:

poetry add -E api fastapi
poetry add -E api gunicorn
poetry add -E api uvicorn
resulting in the following changes to the pyproject.toml file:

fastapi = {version = "^0.61.0", extras = ["api"]}
gunicorn = {version = "^20.0.4", extras = ["api"]}
uvicorn = {version = "^0.11.8", extras = ["api"]}
But running poetry update; poetry install -E API doesn't work yet.

You need to add the following entry to the pyproject.toml file (NOTE you have to add the requirements specifier otherwise what gets passed to pip install complains and errors out):

[tool.poetry.extras]
api = ["fastapi^0.61.0", "gunicorn^20.0.4", "uvicorn^0.11.8"]

and then poetry update; poetry install -E API works fine.

**Comment by ndevenish** [comment]
> Looks like you can install multiple dependencies in a single set using the following approach:

Thanks - it's listed on `poetry add` which caused me to try and use it. But this (still!) doesn't appear to actually work.

**Comment by aprilahijriyan** [comment]
I highly recommend writing extras syntax like this:

```toml
[tool.poetry.extras.full]

django-extensions = {version = "^3.1.3" }
drf-yasg = {version = "^1.20.0"}

```
