### ISSUE TITLE
`scripts` does not seem to respect `packages`

### ISSUE THREAD

**Issue by dmohns** [python-poetry/poetry#2163]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.3
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Hello everyone,

I am trying to use Poetry in an existing project. The project's source is organised in a way that all source files are stored under `src/` (similar to for example https://github.com/pallets/flask). In this setup I cannot get `poetry scripts` to work properly.

I put together a minimum (not) working example to illustrate.

`src/my_package/cli.py`
```py
def cli():
    print("hi")
```

`src/my_package/main.py`
```py
from my_package.cli import cli


def main():
    cli()


if __name__ == "__main__":
    main()
```

`pyproject.toml`
```toml
[tool.poetry]
name = "poetry-scripts"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [
    {include = "my_package", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
test-cmd = "my_package.main:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

In this example running `poetry run test-cmd` yields
```
ModuleNotFoundError: No module named 'my_package'
```
Note, if I `poetry build` the example and then install the wheel the cli is properly recognized.
