### ISSUE TITLE
poetry update not updating included local packages

### ISSUE THREAD

**Issue by petobens** [python-poetry/poetry#2216]
Consider the following directory structure:
```
poetry-package/
├── foo
│   └── foo.py
├── pyproject.toml
└── setup.py
```
Where `foo.py` is empty, `setup.py` is simply:
```python
from setuptools import setup

setup(name='foo-package', version='0.0.1', packages=['foo'])
```
and `pyproject.toml` looks like:
```toml
[tool.poetry]
name = "foo-package-dev"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [{include = "foo"}]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
If I now run `poetry install` then the local `foo-package` version 0.0.1 is correctly installed since `poetry run pip list` gives:
```
Package     Version Location
----------- ------- ----------------------------------
foo-package 0.0.1   /home/pedro/Desktop/poetry-package
pip         19.2.3
setuptools  41.2.0
```
However if I now modify the `setup.py` bumping the version from `0.0.1` to `0.0.2` and then run `poetry update` the local package is not updated. On the other hand if run `poetry install` then the local package does indeed get updated (as per `poetry run pip list`). So my question is: is this a bug or a feature? I would've expected the `update` command to actually update the local included package but that isn't the case.

For the record I'm using poetry version 1.0.5
