### ISSUE TITLE
python version 3.6.9 or 3.6.10 doesn't match ^3.6.1

### ISSUE THREAD

**Issue by Trim21** [python-poetry/poetry#2243]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: `Linux-5.3.0-0.bpo.2-amd64-x86_64-with-debian-10.3`
- **Poetry version**: `1.0.5`

```toml
[tool.poetry]
name = "poetry-bug"
version = "0.1.0"
description = ""
authors = ["Trim21 <i@trim21.me>"]

[tool.poetry.dependencies]
python = "^3.5"

requests = { version = '^2.2.0', python='^3.6.1' }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

## Issue

I'm using python 3.6.10 in a virtualenv. And add a dependence `{ version = '^2.2.0', python='^3.6.1' }` 

But when I do `poetry install`, I got nothing installed or updated.

And I' sure `requests` is not installed by running `pip uninstall requests -y` got `requests as it is not installed.`

```bash
(poetry-bug-369) trim21@omv ~/proj/poetry-bug $ poetry install -vvv
Using virtualenv: /home/trim21/.pyenv/versions/3.6.9/envs/poetry-bug-369
Installing dependencies from lock file

No dependencies to install or update

  - Skipping certifi (2019.11.28) Not needed for the current environment
  - Skipping chardet (3.0.4) Not needed for the current environment
  - Skipping idna (2.9) Not needed for the current environment
  - Skipping urllib3 (1.25.8) Not needed for the current environment
  - Skipping requests (2.23.0) Not needed for the current environment
```
