### ISSUE TITLE
Optional URL dependency is locked as non-optional

### ISSUE THREAD

**Issue by tommilligan** [python-poetry/poetry#2255]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: See reproduction below.

## Issue

When adding an optional URL dependency to the project, I specify it like so:

```toml
[tool.poetry.dependencies]
rethinkdb = { optional = true, url = "https://github.com/tommilligan/rethinkdb-python/releases/download/v2.4.5.post1/rethinkdb-2.4.5.post1-py2.py3-none-any.whl" }
```

However, after locking, this results in a lockfile like:

```toml
[[package]]
category = "main"
description = "Python driver library for the RethinkDB database server."
name = "rethinkdb"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"
version = "2.4.5.post1"

[package.dependencies]
six = "*"
```

Note that the lock marks this package as **`optional = false`**. I would expect this to be **`true`**.
