### ISSUE TITLE
Support subprojects in a poetry project

### ISSUE THREAD

**Issue by abn** [python-poetry/poetry#2270]
### Background & Rationale
This request is inspired by [RPM Package Manger](https://rpm.org/)’s capability to build [subpackages](http://ftp.rpm.org/max-rpm/s1-rpm-subpack-spec-file-changes.html) from the same [Spec File](http://ftp.rpm.org/max-rpm/s1-rpm-build-creating-spec-file.html).

Here, I want to propose and discuss replication a version of this capability can be replicated within poetry to allow for simplified user experience for a python project maintainer, especially when either maintaining namespace packages and/or multi-project source trees. While strict project separation is a good thing in most cases, it might not always be the more pragmatic scenario for package maintainers.

For our purposes here, we can refer to each of theses packages as a subproject. And all subprojects are managed under a single poetry project. This means that there is only a single `pyproject.toml` file and a shared project root directory with either a shared source tree or independent source trees (subdirectory) for each subproject.

### Description
Let us consider the scenario of multiple namespace packages being maintained in a single repository with the following structure.

```console
    namespace-project/
    └── src
        └── namespace
            └── package
                ├── one
                │   └── __init__.py
                ├── three
                │   └── __init__.py
                └── two
                    └── __init__.py
```

Note that this will still apply even if different source directories exists within the root directory for each subproject.

Here the intention could be that we want to distribute 3 packages, namely,  `namespace-package-one` , `namespace-package-two` and `namespace-package-three`.

For the purpose of this example, let us assume that `namespace-package-three` depends on `namespace-package-one`. The `pyproject.toml` file could look something like this.

New sections are annotated with comments detailing them and expected behaviour.

```toml
[build-system]
requires = ["poetry-core>=1.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "namespace-package"
version = "1.0.0-alpha.0"
description = ""
authors = [
    "Bender Rodriguez <bender@planetexpress.com>"
]
license = "MIT"
readme = "README.md"
repository = "https://git.planetexpress.com/bender/python-namespace-package"
keywords = []
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
]

# this section remains as is, but now specifies shared dependencies
[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pre-commit = "^2.1"
flake8 = "^3.7"
black = "^19.10b0"
pytest = "^5.2"

# the following are package specific section
[tool.poetry.packages.one]
name = "namespace-package-one"  # this is optional as name would be derrived from <project.name>-<package name from section>
description = ""  # this will overide the description from the project for this package
readme = "README.one.md"  # this will overide the readme from the project for this package
packages = [  # this is mandatory for sub-packages
    # any package not included in a sub-package is added to the base package (ie. "namespace-package")
    # if the "packages" property is not explicitly configured in the base
    { include = "namespace.package.one", from = "src" }
]

[tool.poetry.packages.one.dependencies]
ujson = "^1.35"

[tool.poetry.packages.one.dev-dependencies]
pytest-mock = "^2.0"

[tool.poetry.packages.two]
packages = [ 
    { include = "namespace.package.two", from = "src" }
]

[tool.poetry.packages.two.dependencies]
psycopg2 = "^2.8.4"

[tool.poetry.packages.two.dev-dependencies]
pytest-postgresql = "^2.3.0"

[tool.poetry.packages.three]
requires = [ # this enables us to specify the relationships between sub-packages
    "one" # this could also be namespace-package-one
]
packages = [ 
    { include = "namespace.package.two", from = "src" }
]

[tool.poetry.packages.three.dependencies]
aiohttp = "^3.5"

[tool.poetry.packages.three.dev-dependencies]
beautifulsoup4 = "^4.8"
aioresponses = "^0.6"
pytest-asyncio = "^0.10"
```

Under this scenario, the following might be what the cli commands look like. Current behaviour will remain unaltered as these are additive changes.

```console
$ poetry add --package one <dependency>
.. <similar to current add output>

$ poetry packages list
namespace-package-one
namespace-package-two
namespace-package-three

$ poetry build
<builds all three packages>

$ poetry build --package one
<builds only namespace-package-one>

$ poetry publish --dry-run
...
Publishing namespace-package-one (1.0.0-alpha.0) to PyPI
  - Uploading namespace-package-one-1.0.0-alpha.0.tar.gz
  - Uploading namespace-package-one-1.0.0-alpha.0-py3-none-any.whl

Publishing namespace-package-two (1.0.0-alpha.0) to PyPI
  - Uploading namespace-package-two-1.0.0-alpha.0.tar.gz
  - Uploading namespace-package-two-1.0.0-alpha.0-py3-none-any.whl

Publishing namespace-package-three (1.0.0-alpha.0) to PyPI
  - Uploading namespace-package-three-1.0.0-alpha.0.tar.gz
  - Uploading namespace-package-three-1.0.0-alpha.0-py3-none-any.whl
```

### Variations
The above is an initial though of how it might work. That said there are variations to this that should be discussed.

1. **Does a per-package `dev-dependnecy` section make sense?**
This only really makes sense if we want to allow for developing a single package at a time. However, this will become tricky in cases like here where "three" depends on "one". This will mean that when developing "three", dev dependencies for "one" should also be installed. If isolation is required, then multiple virtual environments will be required, which might be overkill for majority use cases for this feature.

2. **Will all packages be installed under PEP-0517?**
Is it even possible to install only specific package when being installed under PEP-0517? One possible solution might be to make use of "extras" here as a way of specifying which package if any to install, but default to all.

### Extensions
1. **Optional Project Package**
As an extension to this, one might also want to optionally  distribute a a namespace only package `namespace-package` (let's call this the "project package" for now) that installs the core dependencies and also allow for "extras" as we do  today without requiring the distribution of the entire source tree with the binary distribution.

This means that if someone does `pip install namespace-package`, the maintainer might expect the the following to be installed:

1. The namespace `namepace.package`.
2. Packages `namespace-package-one` and `namespace-package-three`, which are required for the "default" install.

An end-user can also install the remaining package, like so - `pip install namespace-package[two]` which simply will install a dependency `namespace-package-two`.

This behaviour might not be desired in all cases, and can be considered opt-in.

**Comment by kapilt** [comment]
I recently went through converting over a mono repo with several packages over to poetry, and thought it might be useful to share what we did, and pain points and bug work arounds. Although also recognizing this proposal would hopefully make it all obsolete :-) Still this might provide some utility to those who want to do mono repos prior to native support in poetry.

first a few context/caveats, we don't use namespace packages vs a common prefix, and our fs layout is little different. that's non material to the techniques used, but perhaps relevant to the proposal.

```
main_pkg
tools/
   pkg_1
   pkg_2
   pkg_3
   ...  
```
   
at the moment all the packages under tools have dependencies on the main package declared as a path based dev-dependency.

```toml
[tool.poetry.dev-dependencies]
# setup in tree as a dev dependency                                                                                                                                                                                                                                                                                                                  
c7n = {path = "../..", develop = true}
```

i attempted to resolve it as a normal dependency caused a few issues with poetry build (issues #2046, partial fix #2047, also reported/pr by others).

so using as a dev dependency worked but also meant not using poetry directly as a build/publish tool to work around those issues and still needed the injection of the main_pkg as a regular project dep when publishing. we ended up using poetry metadata/api to generate setup/requirements for that purpose, converting dev dependencies to regular dependencies in the process. https://github.com/cloud-custodian/cloud-custodian/blob/master/tools/dev/poetrypkg.py#L121

unrelated to multi-project, but to the generation workaround, we ran into another issue that in that the masonry sdist builder didn't really support markdown readmes (pr #1994)

for handling ergonomics simplicity around multiple commands that needed to update versions/ or release, we added in makefile targets to frontend,

```make
pkg-update:
	poetry update
	for pkg in $(PKG_SET); do cd $$pkg && poetry update && cd ../..; done
```

we're also maintaining compatibility with tox/setuptools ecosystem for compatibility with developer workflows, there's a few more details on what we did here
https://cloudcustodian.io/docs/developer/packaging.html

**Comment by abn** [comment]
@kapilt thank you writing that up. It is extremely useful and insightful.

**Comment by dazza-codes** [comment]
This proposal is valuable.  As it is, poetry supports optional dependencies, but not optional packages
- https://python-poetry.org/docs/pyproject/#packages

The use of optional packages for a namespace project is really useful.  :+1 for including the optional-package as part of this proposal.

**Comment by djerraballi** [comment]
shared dependencies are very useful, but might make sense to inherit some of the logic from Maven regarding the shared block: 

1. Allow definitions of dependencies and versions in a shared block
2. only pull them into the package if that dependency name is explicitly used in the dependency. In this way we can define standard versions for certain dependencies across all packages, but not require all packages to install those packages at those versions. (Can be overriden in the package depenendency block). 

while it does complicate things the benefits are: 
1. No unneeded dependencies in modules of a multi-module project.
2. When multiple but not all packages have the same dependency, we can define the version once, but still explicitly pull the dep. 
3. Enabling overrides for versions for certain modules can be very useful and get people out of some hairy situations.

**Comment by xinbinhuang** [comment]
This proposal is really valuable! I wonder what's the latest status of this? Is this currently being working on?

**Comment by patrickelectric** [comment]
are we there yet ?

**Comment by johnwalz97** [comment]
Any updates? Really see some value for this!!!

**Comment by mrlucasrib** [comment]
Unfortunately there is nothing new about this yet, but I found a monorepo manager called Bazel, which is widely used and supports many languages. If your goal is to work only with Python Pants Build might be an easier solution.

**Comment by cognifloyd** [comment]
Maybe we could have `pyproject.toml` in each of the subprojects.
Then, add a poetry plugin that coordinates updating dependencies between the top-level `pyproject.toml` and the children.
That might mean adding a setting in each of the `pyproject.toml` to say whether they are a parent or a child.

**Comment by Woile** [comment]
Could the new [dependency groups](https://python-poetry.org/blog/announcing-poetry-1.2.0a2/#dependency-groups) be leveraged in a way to achieve this proposal? I have some intuition it could, but not sure how

**Comment by klDen** [comment]
> Maybe we could have `pyproject.toml` in each of the subprojects. Then, add a poetry plugin that coordinates updating dependencies between the top-level `pyproject.toml` and the children. That might mean adding a setting in each of the `pyproject.toml` to say whether they are a parent or a child.

This is what Maven does. Here's an example on how Maven provides the capability to share modules between projects: https://www.baeldung.com/maven-multi-module

**Comment by mr-bjerre** [comment]
Is it currently possible to have something like what [`yarn workspaces`](https://classic.yarnpkg.com/lang/en/docs/workspaces/) does?

So having `pyproject.toml` in each package but they can share dependencies from a root virtual environment.

**Comment by fredrikaverpil** [comment]
Have you tried to add a path dependency to another project, which contains its own pyproject.toml?

So for example;

```toml
[tool.poetry.dependencies]
subproject = {path = "subproject", develop = true}
```
