### ISSUE TITLE
poetry update does not install packages

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [python-poetry/poetry#2313]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option). (no exception occurred)

- **OS version and name**:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/ZelphirKaltstahl/718ebe4bdeb49eebf7b057292ae74432

## Issue

I think the behavior is buggy.

Install it with `poetry install` in the folder of the `pyproject.toml` file.
Activate the shell with `poetry shell`.
Then change it to the following:

```toml
[tool.poetry]
name = "replaced"
version = "0.1.0"
description = ""
authors = ["replaced"]

[tool.poetry.dependencies]
python = "^3.6"
pandas = [
    { version = "^1.0", python = "^3.6.1" },
    { version = "<1.0", python = "<3.6.1" }
]
requests = "2.23.0"
lxml = "4.5.0"

[tool.poetry.dev-dependencies]
pytest = "5.4.1"
requests = "2.23.0"
lxml = "4.5.0"
PyPDF2 = "1.26.0"
PyPDF4 = "1.27.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Then run `poetry update`, to also get `pandas`.
After that, Pandas  was not installed and I get import errors for it.
