### ISSUE TITLE
Dependency documentation for individual dependencies in Pyproject.toml

### ISSUE THREAD

**Issue by sondrelg** [python-poetry/poetry#2345]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hi,

This specifically related to adding dependencies to `pyproject.toml` using the `poetry add` command:

Would it be feasible to add a `--comment` flag for providing context to a dependency?

```toml
[tool.poetry.dependencies]
...
django = "2.2.6"
pyodbc = "4.0.28"                         # required for communicating with our MSSQL databases
whitenoise = "5.0.1"                      # required for serving static files in production
django-cors-headers = "3.2.1"             # adds CORS headers to responses to allow in-browser requests to Django application from other origins
django-auth-adfs = "1.3.1"                # enables Active Directory-auth
...
```

^ This is generally how my requirements-files would look, before I adopted Poetry, as it makes the requirements list self-documenting, and while I have no idea whether this would be easy to implement, I would think this might be useful for anyone working in a shared project.

I hope you see the benefit of this - at the same time, I understand if this is out of scope, or a bit too hacky. The implementation and argument names are obviously just a suggestion, so feel free to suggest alternative implementations,

Thanks for all the work put into Poetry already - it's a really nice tool 👏
