### ISSUE TITLE
Optional dependencies are generated as required in wheel

### ISSUE THREAD

**Issue by cutwater** [python-poetry/poetry#2357]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux 5.5.8-arch1-1
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/cutwater/65c1120890dc654e9968f8cdcf4cfde1
- **Related Issue**: python-poetry/poetry#24

## Issue

Optional dependencies are generated as required dependencies in wheel package produced by executing `poetry build`. Dependency list in sdist package does not include optional dependencies as expected. Please refer to the gist above for more details.

Steps to reproduce the issue:

```
$ poetry new example
$ cd example
$ poetry add --optional psycopg2
$ poetry build
```

**Comment by finswimmer** [comment]
Hello,

the problem here is, that the used syntax isn't correct. Any optional dependency must be assigned to an extra, e.g.:

```toml
[tool.poetry.dependencies]
python = "^3.10"
psycopg2 = {version = "^2.9.2", optional = true}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
pgsql = ["psycopg2"]
```

`poetry build` (and maybe other poetry commands) should fail if they detect an optional dependency that is not assigned to an extra.
