### ISSUE TITLE
prerelease version specifier changes when packaged with sdist

### ISSUE THREAD

**Issue by seansfkelley** [python-poetry/poetry#2605]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Mojave
- **Poetry version**: 1.0.9
- ~~**Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:~~

```toml
[tool.poetry]
name = "poetry-example"
version = "0.1.0-dev+d985ea3"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [
    { include = "example" }
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

## Issue

To repro this issue, also add an empty `example/__init__.py` next to the `pyproject.toml` so that there's something to package/publish.

When running `poetry build -f sdist`, Poetry builds a file named `poetry-example-0.1.0.dev0+d985ea3.tar.gz`, rather than the expected `poetry-example-0.1.0-dev+d985ea3.tar.gz`. The changed version string `0.1.0.dev0+d985ea3` is present both in the `PKG-INFO` and `setup.py` of the archive, though not the packaged `pyproject.toml`.

Surprisingly, using the original `0.1.0-dev+d985ea3` version string when trying to install the published package using Poetry actually works as expected, and it finds the published package with the _changed_ version string.

Changing the version string confuses some tooling (such as the PyPI version browser) as well as humans trying to publish or find prerelease versions.
