### ISSUE TITLE
[RuntimeError] maximum recursion depth exceeded installing python-benedict

### ISSUE THREAD

**Issue by fabiocaccamo** [python-poetry/poetry#2767]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: `macOS Catalina 10.15.6`
- **Poetry version**: `1.0.10`
- **pyproject.toml file**: 

```toml
[tool.poetry]
name = "poetrytest"
version = "0.1.0"
description = ""
authors = ["Fabio Caccamo <fabio.caccamo@gmail.com>"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
## Issue
I just installed `poetry`, but when I try to install [python-benedict](https://github.com/fabiocaccamo/python-benedict) I receive the following error:
**[RuntimeError] maximum recursion depth exceeded installing python-benedict**

Steps to reproduce the error:
- Run `poetry new poetrytest && cd poetrytest` 
- Run `poetry add python-benedict`
