### ISSUE TITLE
Poetry fails to install [build-system] dependency (poetry or poetry-core) from a private package repository

### ISSUE THREAD

**Issue by GuillaumeLegoy** [python-poetry/poetry#2831]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  macOS Catalina version 10.15.6
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/GuillaumeLegoy/1c637c449301153379891ddbc839b178

## UPDATE

I finally made it work using the following `pyproject.toml`. It appears I performed some earlier commands using the latest [pre-release](https://github.com/python-poetry/poetry/releases/tag/1.1.0b2). Simply adding the private repo as shown is enough.
Also it might be necessary to clear pip cache to avoid hash error messages. 

I'll leave the issue open for now in case someone wants to reply and explain to me the reason why it happened, otherwise it can be closed. Thanks folks.

```bash
[tool.poetry]
**** (redacted)

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[[tool.poetry.source]]
name = "lighthouse-analytics-packages"
url = "https://aws:****"
```

## Issue
Hello everyone,

First of all thank you for the great work and the amazing library that is poetry. Now on to the issue: I created a private library using `poetry build`, with the following pyproject.toml:

```bash
[tool.poetry]
**** (redacted)

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.14.30"
pandas = "^1.1.0"
psycopg2-binary = "^2.8.5"
dynaconf = "^3.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
moto = "^1.3.14"
networkx = "^2.4"
jsonschema = "^3.2.0"
junit_xml = "^1.9"
flake8 = "^3.8.3"
black = "^19.10b0"
twine = "^3.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

I then upload it as a `.tar.gz` file to [AWS Code Artifact](https://aws.amazon.com/codeartifact/). 

However if I use `poetry add privatepackage` with the above pyproject.toml file including a private repo, I constantly get the following error message:

```bash
command: /Users/guillaume/Library/Caches/pypoetry/virtualenvs/rr2-etl-n8E1IV99-py3.8/bin/python3 /Users/guillaume/Library/Caches/pypoetry/virtualenvs/rr2-etl-n8E1IV99-py3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/1_/09x2vsb96mzfd9fd0q026ztc0000gn/T/pip-build-env-f7xvenqa/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://aws:****@****/simple -- 'poetry>=0.12'
       cwd: None
  Complete output (4 lines):
  Looking in indexes: https://aws:****@****/simple
  Collecting poetry>=0.12
    ERROR: Could not find a version that satisfies the requirement poetry>=0.12 (from versions: none)
  ERROR: No matching distribution found for poetry>=0.12
```

Note how the failing command doesn't include `'--extra-index-url', 'https://pypi.org/'simple/`

All the other dependencies specified in the `[tool.poetry.dependencies]` section of the private package install properly.

## Related issues

* https://github.com/python-poetry/poetry/issues/1958 - closest
* https://github.com/python-poetry/poetry/issues/1101

## My guess

It looks like to me that poetry doesn't revert back to the official PyPi to install poetry as specified in the `[build-system]` section of the `pyproject.toml` file of this private package, whereas it happens when simply using pip (see below).

I also think I might greatly misunderstand how `[build-system]`  works. Do I need to add the `poetry` dependency to my private repository in the case of a private package? If so doesn't it defeat the purpose that poetry/pip will fall back to the official PyPi if it doesn't find said dependency?

## What works

* Using the following command works when I try to install it:

`poetry run python3 -m pip install  privatepackage==1.1.1 --no-cache-dir --extra-index-url https://pypi.org/simple`

* Removing the `[build-system]` section of the `pyproject.toml` file also works. 

## What else I've tried that didn't work

* I tried removing and recreating the virtual env.
* I tried to clear the caches.
* I tried using poetry-core instead of poetry in the `[build-system]`, same issue.
* Fiddled around with the `default` and `secondary` tags in repository settings in the `pyproject.toml` file
* Added and removed the PyPi official repo from `pyproject.toml`

**Comment by tropxy** [comment]
I think I have a similar issue as yours... This is my pyproject.toml

```toml
[tool.poetry]
***redacted

[tool.poetry.dependencies]
python = "^3.7"
asyncio-mqtt = "^0.11.0"
private-api = { version = "^0.2.0", source = "pypi-private"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-lazy-fixture = "^0.6.3"
pytest-cov = "^3.0.0"
pytest-pylint = "^0.18.0"
pytest-watch = "^4.2.0"
pytest-asyncio = "^0.16.0"
black = "21.11b1"
isort = "^5.10.1"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pypi-private"
url = "https://pypi.private.com/simple/"
default = false
secondary = true

[tool.poetry.scripts]
zeta = 'zeta.main:run'
```

I use this toml in a multi-stage Dockerfile where the goal is to at the first stage install all dependencies and run linting and tests and then it builds the .whl

On the next stage, I pass the .whl from the build stage and install it:
```Dockerfile
# Runtime image (which is smaller than the build one)
FROM python:3.10.0-buster

ARG PYPI_USER
ARG PYPI_PASS

WORKDIR /usr/src/app

# create virtualenv
RUN python -m venv /venv
# copy dependencies and wheel from the build stage
COPY --from=build /usr/src/app/dist/ dist/
RUN /venv/bin/pip install dist/*.whl

# This will run the entrypoint script defined in the pyproject.toml
CMD /venv/bin/zeta
```
The problem is that once it tries to install .whl, it does not find the `private-api` package and fails, i.e., whilst the installation of the .whl, the system expects that the `private-api` module is already installed.


My alternative was to install the dependencies directly in the last prod stage, but then `CMD /venv/bin/zeta` as zeta is not installed as module (even if, previously, I tried to install it with `RUN /venv/bin/pip install dist/*.whl`)
