### ISSUE TITLE
What to do in case of certain configurations of dependencies being both mandatory and optional?

### ISSUE THREAD

**Issue by a-recknagel** [python-poetry/poetry#2868]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Let's say I want to provide a `latest` extra for my package where certain dependencies are used with a higher version. For example something like this

```toml
[tool.poetry]
name = "example"
version = "0.1.0"
description = "Just an example"

[tool.poetry.dependencies]
python = "^3.8"
celery = "^3"
celery = { version="^4", optional = true }

[tool.poetry.extras]
latest= ["celery"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

This can't work because duplicate keys are not allowed. The docs at https://python-poetry.org/docs/pyproject/#extras also don't list this problem - maybe it's too niche, but I've seen it in the wild a couple of times already, for example by delegating extras down the chain (a `redis` extra installing `redis` and `celery[redis]`).

Am I missing something, or am I doing something wrong?
