### ISSUE TITLE
Easier extras generation

### ISSUE THREAD

**Issue by aviramha** [python-poetry/poetry#2878]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
I would like an option to automatically create an extra named "all" that is a combination of all existing extras.
This would make many pyproject.tomls easier to maintain - instead of doing always --extras and specifying each of the extras.
I'm thinking it should be an option under [tool.poetry] or under [tool.extra]. maybe "all" can be a variable name, but it's value is a const that marks it as an all extras specifier? for example
```toml
[tool.poetry.extras]
my_all = auto_all
```
Another idea is to make it smarter for instance:

```toml
[tool.poetry.extras]

redis =["redis"]
rabbit =["pika"]
kafka = ["kafka-python"]

small_all = redis + rabbit
all = *
```
I don't mind submitting a PR, but I would like initial approval for the feature :)
