### ISSUE TITLE
Version constraints fails to resolve, even if correctly defined

### ISSUE THREAD

**Issue by soderluk** [python-poetry/poetry#2989]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.5 LTS
- **Poetry version**: 1.0.10

```toml
[tool.poetry.dependencies]
aiohttp = "^3.6.2"
fastapi = "^0.47.1"
invoke = "^1.4.1"
python = ">=3.6.1"
requests = "^2.22.0"
ujson = "^1.35"
uvicorn = "^0.11.2"
openapi-to-fastapi = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = ">=6.0.1"
pytest-asyncio = ">=0.14.0"
snapshottest = "^0.5.1"
```

## Issue
Trying to add `isort` with `poetry add isort --dev` fails on `SolverProblemError`:
```bash
[SolverProblemError]
The current project's Python requirement (>=3.6.1) is not compatible with some of the required packages Python requirement:
  - isort requires Python >=3.6,<4.0

Because no versions of isort match >5.5.3,<6.0.0
 and isort (5.5.3) requires Python >=3.6,<4.0, isort is forbidden.
So, because project-x depends on isort (^5.5.3), version solving failed.
``` 
The project defines Python >=3.6.1 which IS indeed >=3.6,<4.0. So in this case there should be no reason for a conflict.
