### ISSUE TITLE
Changing `develop` option is not reflected

### ISSUE THREAD

**Issue by tamuhey** [python-poetry/poetry#3085]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS X 10.14.6
- **Poetry version**: 1.1.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/tamuhey/poetry111_bug_mvce (not gist)

## Issue

TLDR; changing `develop` of a dependency field and `poetry update` don't have any effect.

I have a project consists of two poetry project:

```
. --  foo/
  |     |- pyproject.toml
  |-- bar/
        |- pyproject.toml
```

`foo` depends on `bar` as follows: 

```toml
# pyproject.toml
...
[tool.poetry.dependencies]
python = "^3.8"
bar = {path="../bar"}
...
```

(Full example here: https://github.com/tamuhey/poetry111_bug_mvce/blob/master/foo/pyproject.toml)

Since the editable mode is false by default from poetry v1.1, `bar` is copied into another directory. It's ok.

But, after changing the dependency of `bar` to editable (`develop = true`) as follows and running `poetry update` don't change anything, as I expected that `bar` is changed to editable dependency.

```toml
# pyproject.toml
...
[tool.poetry.dependencies]
python = "^3.8"
bar = {path="../bar", develop=true}
...
```
