### ISSUE TITLE
poetry lock/export wrong with sys_platform (works fine on ver 1.0.10)

### ISSUE THREAD

**Issue by mozartilize** [python-poetry/poetry#3112]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.2 & 1.0.10
- pyproject.toml

```toml
[tool.poetry]
name = "testpoetry-pywin32"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "~3.8"
azureml-widgets = "1.15.0"
azureml-dataset-runtime = "^1.15.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

## Issue
run `poetry lock` then `poetry export --without-hashes`

version 1.0.10
```
pywin32==228; sys_platform == "win32" and python_version >= "3.6" or platform_system == "Windows" or sys_platform == "win32"
```

version 1.1.0 & above
```
pywin32==228
pywin32==228; platform_system == "Windows"
pywin32==228; sys_platform == "win32"
```
