### ISSUE TITLE
`extras_require` ignores version specifier

### ISSUE THREAD

**Issue by Fizzadar** [python-poetry/poetry#3163]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.15
- **Poetry version**: 1.1.2
- **pyproject.toml** / **setup.py**: https://gist.github.com/Fizzadar/a1b98304a2b86ee966dedea6479320bd

## Issue

The `extras_require` in the generated `setup.py` ignores the version specified in the `pyproject.toml`, leading to inconsistent/broken builds when installing a package with extras.

Gist above contains full info, but specifically:

```toml
[tool.poetry.dependencies]
kombu = {version = '^=4.5', optional = true}

[tool.poetry.extras]
queue = ['kombu']
```

Becomes:

```py
extras_require = \
{'queue': ['kombu']}
```

**Comment by abn** [comment]
@Fizzadar you can add the following to your `pyproject.toml` to avoid this altogether. Poetry will stop generating setup files by default in coming release.

```toml
[tool.poetry.build]
generate-setup-file = false
```
