### ISSUE TITLE
Poetry scripts in optimized mode

### ISSUE THREAD

**Issue by jeremysprofile** [python-poetry/poetry#3335]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I have a `pyproject.toml`:

```toml
[tool.poetry.scripts]
# aka entry points or console scripts for setup.py users
merge = 'mypackage.__main__:main'
```

`mypackage` contains some `assert` statements that I do not want run in production, but I would like to run these scripts in ["optimized" mode](https://docs.python.org/3/using/cmdline.html#cmdoption-o), aka `python -O mypackage.__main__`.

Is this possible to do with a poetry script? If not, is this easy to add?
[Originally asked on StackOverflow](https://stackoverflow.com/questions/64708695/run-poetry-installed-python-scripts-in-optimized-mode)
