### ISSUE TITLE
A new command: poetry test

### ISSUE THREAD

**Issue by ThatXliner** [python-poetry/poetry#3386]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Implement a `poetry test` command.

### Background
I've been using Makefiles (and sometimes just snippets of code) to manage testing over CIs and I'd like a `poetry test` command to ~~manage~~ centralize this (for some systems don't have GNU Make).

### Demonstration
To configure it, there should be a new section in the` pyproject.toml` stating what `poetry test` does, like this:

```toml
[tool.poetry.test]
command = "pytest -vvv --cov=package_name"
after_success = 'echo "Yay! All tests have passed!" '
```

### Implementation

Basically, poetry will run that command in a virtual environment (which does not include the package itself) that has installed *all the dependancies*.
