### ISSUE TITLE
v1.1.x regression - dependency resolution failures with multiple python constraints

### ISSUE THREAD

**Issue by EvanShenkman-Sonos** [python-poetry/poetry#3398]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: GNU/Linux
- **Poetry version**: 1.1.4

## pyproject.toml

```toml
[tool.poetry.dependencies]
python = "!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,!=3.5.*,>=2.7"

[tool.poetry.dev-dependencies]
pytest = [
    {version = "^6.0", python = ">=3.6"},
    {version = "^4.6", python = "~2.7" }
]
pytest-mock = [
    {version = "^3.3", python = ">=3.6"},
    {version = "^2.0", python = "~2.7"}
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue

I'm in the process of upgrading older poetry projects to use v1.1.x and the new build backend. Some of these projects need to be python 2.7 and python 3.6+ compatible. The above `pyproject.toml` file shows a simple example of how I've managed dependencies for projects with multiple python constraints.

After upgrading from 1.0.10 to 1.1.4, `poetry update` can no longer resolve dependencies using the same `pyproject.toml` file.

### poetry v1.1.4

```
root@0be6ddf3cf4f:/pkg# poetry --version
Poetry version 1.1.4
root@0be6ddf3cf4f:/pkg# poetry update
Creating virtualenv foo-8pompfu2-py3.8 in /root/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (8.8s)

  SolverProblemError

  Because no versions of pytest-mock match >3.3,<3.3.1 || >3.3.1,<4.0
   and pytest-mock (3.3.0) depends on pytest (>=5.0), pytest-mock (>=3.3,<3.3.1 || >3.3.1,<4.0) requires pytest (>=5.0).
  And because pytest-mock (3.3.1) depends on pytest (>=5.0), pytest-mock (>=3.3,<4.0) requires pytest (>=5.0).
  So, because foo depends on both pytest (^4.6) and pytest-mock (^3.3), version solving failed.

  at /usr/local/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

When running with the verbose flags, it appears that the solver is attempting to resolve a combination of dependencies that have conflicting python versions...

```
   0: Retrying dependency resolution with the following overrides ({Package('foo', '0.1.0'): {'pytest': <Dependency pytest (^4.6)>, 'pytest-mock': <Dependency pytest-mock (^3.3)>}}).
```

* pytest (^4.6) is defined for python versions ~2.7
* pytest-mock (^3.3) is defined for python versions >=3.6

I would expect that the solver wouldn't consider this permutation of dependency versions since their python constraints do not overlap at all.

### poetry v1.0.10

```
root@52f9b63b51f4:/pkg# poetry --version
Poetry version 1.0.10
root@52f9b63b51f4:/pkg# poetry update
Creating virtualenv foo-8pompfu2-py3.8 in /root/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (8.2s)

Writing lock file


Package operations: 10 installs, 0 updates, 0 removals

  - Installing pyparsing (2.4.7)
  - Installing six (1.15.0)
  - Installing attrs (20.3.0)
  - Installing iniconfig (1.1.1)
  - Installing packaging (20.4)
  - Installing pluggy (0.13.1)
  - Installing py (1.9.0)
  - Installing toml (0.10.2)
  - Installing pytest (6.1.2)
  - Installing pytest-mock (3.3.1)
```
