### ISSUE TITLE
1.1.4 poetry install command result in Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by raokrutarth** [python-poetry/poetry#3401]
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [- ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate. __It is a duplicate of a partially resolved issue__.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: `Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- **Poetry version**: Poetry version 1.1.4
- **pyproject.toml**:

```toml
[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "^0.11.8"
fastapi = "^0.61.1"
newspaper3k = "^0.2.8"
goose3 = "^3.1.6"
justext = "^2.2.0"
htmldate = "^0.7.1"
dynaconf = "^3.1.2"
gunicorn = "^20.0.4"
clean-text = "^0.3.0"
fuzzywuzzy = {extras = ["speedup"], version = "^0.18.0"}
news-fetch = "^0.2.5"
pytrends = "^4.7.3"
unidecode = "^1.1.1"
autoscraper = "^1.1.9"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
mypy = "^0.790"
autoflake = "^1.4"
isort = "^5.6.4"
black = "^20.8b1"
```

## Issue

`poetry install` command result in Maximum recursion depth exceeded and takes over 5m to do so.
