### ISSUE TITLE
poetry export - should it include optional extras by default?

### ISSUE THREAD

**Issue by dazza-codes** [python-poetry/poetry#3451]
What is the intention for `poetry export` with respect to default behavior for optional dependencies?  It seems to include them in the output requirements.txt file.

```sh
poetry export --without-hashes --format requirements.txt --output requirements.txt
```

For example, if scipy is an optional extra, it should not be in `requirements.txt` (right?)

```toml
scipy = {version = "^1.5.3", optional = true}
```

But, there it is:

```
scipy==1.5.4; python_version >= "3.6"
```

Given there are additional command options to include optional extras, it suggests the default behavior is to exclude all optional dependencies (unless explicitly requested with an `--extras {x}`).

**Comment by sinoroc** [comment]
Can you use `poetry show --tree` to figure out what depends on `scipy`?

**Comment by dazza-codes** [comment]
To replicate it, try

```toml
[tool.poetry]
name = "tmp"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.7"
numpy = {version = "^1.19.4", optional = true}

[tool.poetry.dev-dependencies]
pandas = "^1.1.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

```sh
$ poetry export --without-hashes --format requirements.txt --output requirements.txt
$ grep 'numpy' requirements.txt 
numpy==1.19.4; python_version >= "3.6"
```

Is this desired behavior or should it only include numpy when the export explicitly requests it with an `--extras numpy` option?
