### ISSUE TITLE
AssertionError in mixology/incompatibility.py

### ISSUE THREAD

**Issue by TheButlah** [python-poetry/poetry#3491]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04 LTS
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/TheButlah/53d88f0a4bb7300d97575556ff46345f

## Issue

An Assertion is failing when attempting to add a project that depends via path on another project. The other projects pyproject.toml is the following:

```toml
[build-system]
requires = ["poetry>=1.0.3", "pip>=20.0.2"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "robotics"
version = "0.1.0"
description = "SAIC-NY Codebase"
authors = ["Ben Eisner <ben.eisner@samsung.com>"]

[tool.poetry.dependencies]
python = "^3.6.1"
pip = "^20.0.2"
numpy = "^1.17"
click = "^7.0"
opencv-python = "^4.2.0"  # 4.2 breaks some code. Fix the code then update.
scipy = "^1.3"
scikit-learn = "^0.21.3"
matplotlib = "^3.1"
apriltag = "^0.0.16"
pyrealsense2 = {version = "^2.35", platform = "!= darwin"}
jupyter = "^1.0"
tqdm = "^4.36"
visdom = "^0.1.8"
h5py = "^2.10"
scikit-image = "^0.16.1"
gym = {version = "^0.15.3", extras = ["atari"]}
cython = "^0.29.13"
probscale = "^0.2.3"
progressbar2 = "^3.47"
ninja = "^1.9"
pathos = "^0.2.5"
transitions = "^0.7.1"
pyqt5 = "^5.13"
pyqtdatavisualization = "^5.13"
pyserial = "^3.4"
plotly = "^4.2"
ray = "^0.8.4"  # Ray==0.7.5 doesn't work on mac - fails pytest --cov
psutil = "^5.6"
pandas = "^0.25.1"
mujoco-py = "^2.0"
wandb = "^0.8.29"
torchvision = "^0.7.0"
Jinja2 = "^2.10.3"
tensorflow = "^2.1.0"
tensorboard = "^2.1.0"
torch = "^1.6.0"
jupyterlab = "^2.1.0"
pillow = "^6.1.0"
open3d = "0.10.0"
chart-studio = "^1.0.0"
dask = {version = "^2.12.0", extras = ["complete"]}
numba = "^0.48.0"
colorama = "^0.4.3"
pyyaml = "^5.3.1"
icc_rt = {version = "^2020.0.133", platform = "!= darwin" }
nbstripout = "^0.3.7"
seaborn = "^0.10.0"
ipympl = "^0.5.6"
polyaxon-cli = "^0.6.1"
dv = "^1.0.8"
polyscope = "^0.1.2"
pytorch-lightning = "^1.0.8"
hydra = "^2.5"
omegaconf = "^2.0.0"
zarr = "^2.4.0"
absl-py = "^0.9.0"
pybullet = "^2.8.1"
speechrecognition = "^3.8.1"
pyaudio = "^0.2.11"
nuscenes-devkit = "^1.0.8"
pyquaternion = "^0.9.5"
cachetools = "^4.1.1"
joblib = "^0.16.0"
ipyplot = "^1.0.5"
imutils = "^0.5.3"
pyrender = "^0.1.43"
networkx = "^2.4"
dgl = "^0.5.1"
snakeviz = "^2.1.0"

[tool.poetry.dev-dependencies]
black = {version = "^19.10b0", allow-prereleases = true}
pytest = "^5.2"
mypy = "^0.770"
pylint = "^2.4"
isort = "^4.3.21"
autoflake = "^1.3.1"
pre-commit = "^2.0.1"
rope = "^0.16.0"
coverage = {extras = ["toml"], version = "^5.1"}
pytest-cov = "^2.8.1"

[tool.coverage.run]
source = ["."]
omit = [".venv/*", "third_party/*", "experimental/*"]


[tool.isort]
skip_glob="third_party/*"

# See black's README for the origin of these settings
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=88

# used for pre-commit hook
known_third_party=["Augmentor", "Cython", "DVS_filter", "OmplPlanning", "OpenGL", "PIL", "PyQt5", "TrajTransform", "TrajectoryPlanner", "absl", "agent", "angles", "apriltag", "click", "cloudpickle", "cv2", "dataclasses", "detectron2", "dpumanet", "dv", "dvs_data", "dvs_utils", "dynamixel_sdk", "event_class", "fvcore", "glfw", "gym", "h5py", "hydra", "ik_solver", "imageio", "ipdb", "jinja2", "kortex_api", "logger", "matplotlib", "metaworld", "moviepy", "mpl_toolkits", "mujoco_interface", "mujoco_py", "numcodecs", "numpy", "omegaconf", "ompl", "open3d", "pandas", "pathos", "plotly", "policy", "polyscope", "probscale", "progressbar", "pumanet", "pycocotools", "pygame", "pyglet", "pylab", "pyntcloud", "pyrealsense2", "pyrender", "pytest", "pytorch_lightning", "pytorch_models", "pytorch_utils", "q_functions", "ray", "rosbag", "rospy", "rules_python", "scipy", "seaborn", "skimage", "sklearn", "sum_tree", "t_embed", "tensorboard", "tensorflow", "thinnet", "torch", "torchvision", "tqdm", "transitions", "trimesh", "ttc_dataset", "unet", "utils", "visdom", "wandb", "zarr"]
```
