### ISSUE TITLE
poetry lock --no-update seems fail to list sub-sub-dependency if sub-dependency is a git repostory

### ISSUE THREAD

**Issue by ktns** [python-poetry/poetry#3548]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] ~If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).~

- **OS version and name**: Ubuntu 20.10
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A (because a gist cannot include subdirectories)

## Issue
Firstly, I'm sorry about the complicated title of this issue but I couldn't explain my situation more simply.

I have a repository that contains multiple python packages in sub-directories and a `pyproject.toml` on top of the repository that depends on packages in sub-directories. I noticed that when I run `poetry lock --no-update` on top of the repository, some packages disappear from `poetry.lock`. This seems to happen when a sub-package have a git repository in its dependency and disappearing packages seems to be packages that the package in the repository is dependent.

So, minimum configuration to reproduce my situation boils down like below.

`pyproject.toml`:
```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Katsuhiko Nishimra <ktns.87@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
test-sub = {path = "./test-sub"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

`test-sub/pyproject.toml`:
```toml
[tool.poetry]
name = "test-sub"
version = "0.1.0"
description = ""
authors = ["Katsuhiko Nishimra <ktns.87@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
poetry = {git = "https://github.com/python-poetry/poetry/", tag = "1.1.4"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

With these, `poetry lock` lists dependencies of poetry properly in `poetry.lock` but `poetry lock --no-update` erases them. Also, `poetry update <irrelevant package>` seems to do the same thing. 

I think it's a bug in the resolver of poetry. Any thoughts?
