### ISSUE TITLE
poetry install is not removing existing .dist.info for editable mode

### ISSUE THREAD

**Issue by jules-ch** [python-poetry/poetry#3574]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
~~- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).~~

- **OS version and name**: Windows 10 2004
- **Poetry version**: 1.1.4

```toml
[tool.poetry]
name = "poetry-editable-mode"
version = "0.1.0"
description = ""
authors = ["John Smith <john@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

I'm using `importlib.metadata` to retrieve version number.

```python
# poetry_editable_mode.__version__
from importlib.metadata import version

try:
    __version__ = version("poetry_editable_mode")
except Exception:
    __version__ = "unknown"

```

- Run `poetry install`
- Get version

```python

>>> from poetry_editable_mode.__version__ import __version__
>>> __version__
'0.1.0'
```

- Bump version to 0.2.0 in `pyproject.toml`
- Run `poetry install`
```python

>>> from poetry_editable_mode.__version__ import __version__
>>> __version__
'0.1.0'
```
I expected `0.2.0`

It seems poetry is not clearing out *.dist-info for old version, like pip is doing.
If I remove manually those old *.dist-info, version is correct.
