### ISSUE TITLE
`poetry install` is unusable when a `tool.poetry.build` is used

### ISSUE THREAD

**Issue by 1ace** [python-poetry/poetry#3576]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 33
- **Poetry version**: 1.1.4
- **Contents of your pyproject.toml file**:
```toml
[build-system]
requires = ["poetry-core>=1.0.0", "Cython>=0.29"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
[...]
build = "build.py"
```

where `build.py` contains something like this:
```python
from distutils.command.build_ext import build_ext

def get_modules():
    # Some build logic (eg. cython)
    pass

def build(setup_kwargs):
    setup_kwargs.update({
        'ext_modules': get_modules(),
        'cmdclass': {'build_ext': build_ext}
    })
```

## Issue

When running `poetry install`, poetry doesn't run the build script to install its output, resulting in missing files and a broken installed package :cry:

### Workaround
```sh
poetry build -f wheel
poetry run pip install dist/*.whl
```

## Solution

`poetry install` should produce usable installs, even when a build script is used.

If that's not possible (or until then, if the fix will take a while), an error should be printed explaining why `poetry install` is unusable.
