### ISSUE TITLE
Creating pure Python wheels when using build scripts

### ISSUE THREAD

**Issue by tueda** [python-poetry/poetry#3594]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Is there any way to create [pure Python wheels](https://packaging.python.org/guides/distributing-packages-using-setuptools/#pure-python-wheels) (or [universal wheels](https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels)) when using build scripts?

I know that build scripts are still undocumented (#2740), but if I use `pyproject.toml` like
```toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
generate-setup-file = false
script = "build.py"
```
then `poetry build` creates a [platform wheel](https://packaging.python.org/guides/distributing-packages-using-setuptools/#platform-wheels) like `hello-0.1.0-cp39-cp39-manylinux2014_x86_64.whl`, which makes sense when building C-extensions.

But, when one wants to use `build.py` to generate some platform-*independent* resource files from the source (corresponding to `setup.py build_py`), platform wheels are not needed and pure Python wheels like `hello-0.1.0-py3-none-any.whl` may suffice.

It would be great if one could select pure Python wheels (and possibly also universal wheels) by configuring in `pyproject.toml`, for example,
```toml
[tool.poetry.build]
pure-python-wheel = true
```
