### ISSUE TITLE
Poetry does not install depdendencies.

### ISSUE THREAD

**Issue by connerxyz** [python-poetry/poetry#3611]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.7
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/connerxyz/2b6efff98d98a21d83dd85751580befd

## Issue

I've successfully published a package for Python 3.8, and am now experimenting with being able to also publish the same package for Python 3.6.  Attempting these changes has got me into a situation where Poetry does not seem to install any dependencies at all.

Here's what I did:

- Deleted `.venv` directory that worked for Python 3.8.
- Set `pyenv` to use Python 3.6: `pyenv local 3.6.10`, this updated the `.python-version` file of course.
- Ran `eval "$(pyenv init -)"` I had to do this for the local pyenv to actually use 3.6.10.
- Confirmed: `pyenv which python` => `~/versions/3.6.10/bin/python`
- Created a new environment: `poetry env use ~/versions/3.6.10/bin/python`
- Confirmed: `poetry run python --version` => `Python 3.6.10`
- Removed `python.lock` file, removed listed dependencies from `pyproject.toml`, and added them back in specifying the python version: e.g. `poetry add cleo --python 3.6.10`
- Once complete, `poetry install`
- Attempted to confirm:
```
poetry shell
python 
import my_package
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'shortuuid'
```
- Went back to debug install: `poetry install -vvv`
```
Using virtualenv: ~/git/my-package/my_package/.venv
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 0 installs, 0 updates, 0 removals, 16 skipped

  • Removing cleo (0.8.1): Pending...
  • Removing cleo (0.8.1): Skipped for the following reason: Not currently installed
  • (Same for all the other dependencies)
```

I don't understand why it's not installing any dependencies.

**Comment by sinoroc** [comment]
As one can see in the `pyproject.toml`, all the dependencies are restricted to `python = "3.6.10"` only. Why?

**Comment by connerxyz** [comment]
No particular reason (other than perhaps potential ignorance with regard to how to do this correctly). My only goal is to be able to publish my package for both 3.6 and 3.8.

**Comment by sinoroc** [comment]
This `cleo = {version = "^0.8.1", python = "^3.6"}` means:
* on Python interpreter versions in the range `>=3.6.0 <4.0.0`
* `cleo` will be installed in a version from the range `>=0.8.1 <0.9.0`

So if the Python interpreter version is not in that range, then nothing gets installed.

***References***:
* https://python-poetry.org/docs/dependency-specification/#caret-requirements
* https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies

**Comment by sinoroc** [comment]
@connerxyz Have you opened a GitHub bug ticket regarding https://stackoverflow.com/questions/65945929/poetry-how-to-publish-project-packages-targeting-multiple-python-versions ? Do you want to express that the code is compatible for `3.6` and `3.8` exclusively, in other words: do you want to explicitly exclude `3.7` ?

Reading those 2 threads again, I think there might be some confusion about what you are trying to do exactly...

**Comment by connerxyz** [comment]
Thanks @sinoroc.

## this issue

Being less specific than I was originally like this `cleo = {version = "^0.8.1", python = "^3.6"}` seems to work.

But what I was doing originally (`cleo = {version = "^0.8.1", python = "3.6.10"}`) did not.  I would expect Poetry to identify a `3.6.10` compatible version of `cleo` and install it. That was not the case. I was confused by that (isn't there a `3.6.10` compatible version of `cleo`?), and opened this issue. 

I think `cleo = {version = "^0.8.1", python = "^3.6"}` is what I want anyway.

## stackoverflow post

I did not open a bug ticket for the SO post.  No. I do not need to explicitly exclude 3.7. A `^3.6` compatible package would be great.

I was able to build a package that I seems to work for both 3.6 and 3.8 (and I imagine 3.7 but I didn't test it) with `pyproject.toml` that looks like this.

```
[tool.poetry.dependencies]
python = "^3.6"
cleo = {version = "^0.8.1", python = "^3.6"}
pyyaml = {version = "^5.4.1", python = "^3.6"}
...
```

Where I'm hung up now is that with a dev dependency, `pre-commit`. When I try to add it using the same pattern, I get a resolve failure:

```
poetry add pre-commit --dev --python ^3.6
Using version ^2.10.0 for pre-commit

Updating dependencies
Resolving dependencies... (0.4s)

  SolverProblemError

  The current project's Python requirement (>=3.6,<4.0) is not compatible with some of the required packages Python requirement:
    - pre-commit requires Python >=3.6.1, so it will not be satisfied for Python >=3.6,<3.6.1
...
For pre-commit, a possible solution would be to set the `python` property to ">=3.6.1,<4.0"
```

Okay, so I applied the suggested solution.

```
[tool.poetry.dev-dependencies]
...
pre-commit = {version = "^2.10.0", python =">=3.6.1,<4.0"}
```

This appears to work: `poetry install` and tests pass locally in both `3.6.10` and 3.8.5` environments. The hang up right now is then downstream in CodeBuild, but I'm not sure it's related.

I guess I expected to need to specify two sets of dependencies (one for 3.6 and one for 3.8), and have to publish two packages (one for 3.6 and one for 3.8). It appears instead I can specify one set of dependencies and publish one package that works for both 3.6 and 3.8 (or more specifically `^3.6`).

Is that right?

**Comment by finswimmer** [comment]
Hello @connerxyz,

you just have to defined your desired python compatible here:

```toml
[tool.poetry.dependencies]
python = "^3.6"
```

There is no need, to do this for every single dependency. Poetry will check, if it can find a version for each dependency which is compatible with all defined python version. If not, it will complaint, like it does in your `pre-commit` case.

So in your case your `pyproject.toml` should look like this:

```toml
[tool.poetry]
name = "my-package"

version = "0.5.1"
description = "blah."
authors = [...]
readme = "README.md"

keywords = [...]

# https://pypi.org/pypi?%3Aaction=list_classifiers
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    'Environment :: Console',
    'Operating System :: OS Independent',
    'Intended Audience :: Developers',
    'License :: Other/Proprietary License',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3 :: Only',
    'Topic :: Software Development :: Libraries',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Topic :: Utilities'
]

[tool.poetry.dependencies]
python = "^3.6.1"
cleo = "^0.8.1""
pyyaml = "^5.4.1"
rich = "^9.10.0"
shortuuid = "^1.0.1"
importlib = "^1.0.4"
jinja2 = "^2.11.2"

[tool.poetry.dev-dependencies]
pre-commit = "^2.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

fin swimmer
