### ISSUE TITLE
Namespace package installed in development mode throw ModuleNotFoundError

### ISSUE THREAD

**Issue by alex-oleshkevich** [python-poetry/poetry#3636]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/alex-oleshkevich/4edd4bee8713fb52338a23d9a4d83697

## Issue
Python fails to import the namespace package that installed in editable mode.

File structure:
```
.
├── libs
│   ├── module1_src
│   │   ├── namespace
│   │   └── pyproject.toml
│   ├── module2_src
│   │   ├── namespace
│   │   └── pyproject.toml
│   ├── module3_src
│   │   ├── namespace
│   │   └── pyproject.toml
│   └── namespace_src
│       ├── namespace
│       └── pyproject.toml
├── main.py
├── poetry.lock
├── pyproject.toml
└── src
    ├── myapp
    │   └── __init__.py
    └── myapp_web
        └── __init__.py
```

Python shell:
`> import namespace.module1`

It works perfectly when I don't use `develop = true` in my root pyproject.toml

Root pyproject.toml
```toml
[tool.poetry]
name = "111ns"
version = "0.1.0"
description = ""
authors = ["alex.oleshkevich <alex.oleshkevich@gmail.com>"]
packages = [
    {include = "myapp", from = "./src/"},
    {include = "myapp_web", from = "./src/"}
]

[tool.poetry.dependencies]
python = "^3.8"
"namespace.module1" = {path = "libs/module1_src", develop = true}
"namespace.module2" = {path = "libs/module2_src", develop = true}
"namespace.module3" = {path = "libs/module3_src", develop = true}
"namespace" = {path = "libs/namespace_src"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
