### ISSUE TITLE
Solver can't resolve pylint > 1.9.4 ?

### ISSUE THREAD

**Issue by assuiedmilan** [python-poetry/poetry#3640]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Windows 10**: 
- **1.1.4**: 
- **https://gist.github.com/assuiedmilan/9b18d99ca2f841754cf93aaaa28b06fb**: 

## Issue
When running poetry against this pyproject.toml using python 3.7 or over, the installed pylint version is 1.9.4.

Is replacing the star version by 2.6.0 (which is the current latest version of python), the following error occurs:

> 
>   The current project's Python requirement (>=2.7,<2.8 || >=3.4) is not compatible with some of the required packages Python requirement:
>     - pylint requires Python >=3.5.*, so it will not be satisfied for Python >=2.7,<2.8 || >=3.4,<3.5
> 
>   Because optoolbox depends on pylint (2.6.0) which requires Python >=3.5.*, version solving failed.
> 
>   at d:\opal\tools\optoolbox\.venv3\lib\site-packages\poetry\puzzle\solver.py:241 in _solve
>       237│             packages = result.packages
>       238│         except OverrideNeeded as e:
>       239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
>       240│         except SolveFailure as e:
>     → 241│             raise SolverProblemError(e)
>       242│
>       243│         results = dict(
>       244│             depth_first_search(
>       245│                 PackageNode(self._package, packages), aggregate_package_nodes

However the python version is already > 3.5.

Using the following pyproject.toml, poetry install the correct pylint version: https://gist.github.com/assuiedmilan/14ea89994ced16383debc494b3ee4898

However, my project must also support python 2.7. So my pyproject.toml becomes: https://gist.github.com/assuiedmilan/b2959eec05f340e46ecaa7af87d5efa1

I had trouble figuring out this one because I have other constraints of this kind on other dependencies which are written in the following way:

```
cryptography =  [
	{version = "2.8", python = "~2.7"},
	{version = "3.3.1", python = ">3.6"},
]
pywin32 = [
	{version = "228", python = "^2.7"},
	{version = "300", python = "^3.0"},
]
```

So now I have three different ways of actually writting the same constraint which is: one version for python 2, another version for python 3.

If I try to unify this, such as per example doing:

```
pylint =  [
	{version = "1.9.5", python = "~2.7"},
	{version = "2.6.0", python = ">3.6"},
]
```

The the solver is stuck and simply never ends, on either python version.

What can explain this ?

**Comment by finswimmer** [comment]
Hello @assuiedmilan,

please let me clarify some things first:

1. poetry doesn't care about the currently running python version when it's resolving the dependencies. Instead it's looking for versions of each dependency (and dependencies of these dependency) that is valid for any python version the project is aimed to be compatible.

2. Your `pyproject.toml` files you are showing are missing the desired python versions the project should be compatible to. I guess you accidentally removed them when creating the gists? 

3. Due to point 1 you should define an upper bound for the python versions your project is compatible to. Otherwise poetry will complain very quickly, that you cannot install a dependency because this dependency is only compatible for python < 4.

Putting this together I tried with this `pyproject.toml` without any problems:

```toml
tool.poetry]
name = "i3640"
version = "0.1.0"
description = ""
authors = ["finswimmer <finswimmer@example.com>"]

[tool.poetry.dependencies]
python = "~2.7 || ^3.4"

cryptography =  [
        {version = "2.8", python = "~2.7"},
        {version = "3.3.1", python = ">3.6"},
]
pywin32 = [
        {version = "228", python = "^2.7"},
        {version = "300", python = "^3.0"},
]
pylint = [
        {version = "1.9.5", python = "2.*"},
        {version = "2.6.0", python = ">=3.5"},
]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Be aware that with the python constraints used for the dependencies, `cryptography` would not be installed if a python 3.4 or 3.5 is used and no `pylint` is installed on systems using python 3.4

fin swimmer

PS: All python versions <3.6 have reached their end of life. The EOL for python 3.6 is scheduled for december this year.
