### ISSUE TITLE
Add a project setting to control if and where a project can be published

### ISSUE THREAD

**Issue by J-M0** [python-poetry/poetry#3692]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I would like to propose that `poetry` have a project-level configuration option that would let you restrict which repositories a package gets published to or even prevent it from being published at all.

Rust's package manager `cargo` has a field in its `Cargo.toml` file that does just that. I think the behavior described here is exactly what `poetry` should adopt.

https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field

I work on both public and private projects and this would be a nice addition for my peace of mind. I could make sure a private package doesn't accidentally get published to PyPI or even just prevent a package that is early in development from being published prematurely. It would also make publishing to private repositories easier as you would not need to specify the private repository with `poetry publish -r`.

**Comment by NickleDave** [comment]
The way to do this is to include it in the "classifiers" section

```toml
[tool.poetry]
# ...
classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
```

You want to add
```
        "Private :: Do not Upload"
```
for your private projects
