### ISSUE TITLE
Non-optional dependency referenced in extras is not required by default

### ISSUE THREAD

**Issue by smithfred** [python-poetry/poetry#3718]
Given the below:

```toml
[tool.poetry.dependencies]
foo = "~=1.0"
bar = { version = "~=1.0", optional = false }  # or just bar = "~=1.0"
baz = { version = "~=1.0", optional = true }

[tool.poetry.extras]
extra_stuff = [
    "bar",
    "baz",
]
```

I'd expect foo and bar to be treated as required deps for the core package, and only baz be treated as an extra_stuff-only dep.

Instead, at least when using Poetry via PEP 517 hooks, both bar and baz get extra_stuff-only deps.

So e.g. if calling `prepare_metadata_for_build_wheel()`, the generated `METADATA` will contain:

```
Requires-Dist: foo (>=1.0,<2.0)
Requires-Dist: bar (>=1.0,<2.0); extra == "extra_stuff"  # Unexpected, not installed as dep. for core package.
Requires-Dist: baz (>=1.0,<2.0); extra == "extra_stuff"
```

`poetry.core.packages.dependency.to_pep_508()` isn't looking at the dependency object's optional/active property at all, so it's clear why the above would happen from Poetry's code.

Is this intended behaviour? In which case what is the purpose of the "optional" constraint? And is there some other way to list a package as a requirement for both the core package and an extra group?
