### ISSUE TITLE
Version solving failed for packages from private repository with Poetry > 1.0.10

### ISSUE THREAD

**Issue by itssimon** [python-poetry/poetry#3802]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/itssimon/cd2ee0d6b407cf003cad3630ccb4776d

## Issue
I have two dependencies which need to be installed from private repositories (GitLab). I have configured these two repositories as per the documentation:

```toml
[tool.poetry.dependencies]
# ...
gcds-common = {extras = ["mosaiq"], version = "^0.12.5"}
gcds-ml = {extras = ["lightgbm", "roberta"], version = "^0.4.5"}
# ...

[[tool.poetry.source]]
name = "common"
url = "https://gitlab.com/api/v4/projects/xxx1/packages/pypi/simple"
secondary = true

[[tool.poetry.source]]
name = "ml"
url = "https://gitlab.com/api/v4/projects/xxx2/packages/pypi/simple"
secondary = true
```

However Poetry versions > 1.0.10 are not able to resolve these dependencies. `poetry update -vvv` shows the following output:

```
PyPI: No packages found for gcds-ml >=0.4.5,<0.5.0
   1: fact: no versions of gcds-ml match >=0.4.5,<0.5.0
   1: conflict: no versions of gcds-ml match >=0.4.5,<0.5.0
   1: !  gcds-ml (^0.4.5) is satisfied by  gcds-ml (^0.4.5)
   1: ! which is caused by "gcds-clinex depends on gcds-ml (^0.4.5)"
   1: ! thus: version solving failed
   1: Version solving took 24.006 seconds.
   1: Tried 1 solutions.
...
SolverProblemError

  Because gcds-clinex depends on gcds-ml (^0.4.5) which doesn't match any versions, version solving failed.
```

So it seems that the private repositories are ignored and Poetry tries to resolve these dependencies with the public PyPI. 

Interestingly, this all works as expected in Poetry version 1.0.10, so there must've been a regression a while ago that has not been fixed since.

**Comment by itssimon** [comment]
As indicated in #3807 this issue may be related to the fact that there's more than one secondary repository defined.

**Comment by itssimon** [comment]
@sdispater is this something you could look into for the next release? We're stuck with Poetry 1.0.10 due to this issue but would love to benefit from all the new features and improvements made since that release.

**Comment by abn** [comment]
Your `pyproject.toml` seems to be missing `source`. 

```toml
gcds-common = {extras = ["mosaiq"], version = "^0.12.5", source = "common"}
gcds-ml = {extras = ["lightgbm", "roberta"], version = "^0.4.5", source = "ml"}
``` 

Can you also verify this is still an issue on master pelase? (see below for examples)

### Using pipx
```sh
pipx install --force --suffix=@master 'poetry @ git+https://github.com/python-poetry/poetry.git@master'
```

### Using a container (podman | docker)
```sh
podman run --rm -i --entrypoint bash python:3.8 <<EOF
set -xe
python -m pip install -q git+https://github.com/python-poetry/poetry.git@master
poetry new foobar
pushd foobar
poetry remove pytest
poetry source add --secondary common https://gitlab.com/api/v4/projects/xxx1/packages/pypi/simple
poetry source ml --secondary common https://gitlab.com/api/v4/projects/xxx2/packages/pypi/simple
poetry add --source common gcds-common -E mosaiq
poetry add --source ml gcds-ml -E lightgbm -E roberta
EOF
```
