### ISSUE TITLE
Allow specifying extra_compile_args for dependencies

### ISSUE THREAD

**Issue by cetanu** [python-poetry/poetry#3824]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
I'd like to be able to specify the compile arguments for a dependency.

For example, `google-re2` does not properly install on macos without `extra_compile_args`.  
This is how I imagine it could be specified:
```toml
[tool.poetry.dependencies]
google-re2 = { version = "^0.0.7", extra_compile_args = ['-fvisibility=hidden', '-std=c++11']}
```

I'm not familiar with the codebase, I had a quick glance and I wasn't sure how to add this via a pull-request.

Hopefully this is trivial to add?
