### ISSUE TITLE
Python version specifier ^3.6 interpreters like 3.6 exactly

### ISSUE THREAD

**Issue by voronind** [python-poetry/poetry#3845]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.5
- **Contents of my pyproject.toml file**: 
  ```toml
  [tool.poetry]
  name = "test-pyppeteer"
  version = "0.1.0"
  description = ""
  authors = []

  [tool.poetry.dependencies]
  python = "^3.6"
  pyppeteer = "0.2.5"

  [tool.poetry.dev-dependencies]

  [build-system]
  requires = ["poetry-core>=1.0.0"]
  build-backend = "poetry.core.masonry.api"
  ```

## Issue
I use Python 3.6.8
```console
$ poetry lock
Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  The current project's Python requirement (>=3.6,<4.0) is not compatible with some of the required packages Python requirement:
    - pyppeteer requires Python >=3.6.1,<4.0.0, so it will not be satisfied for Python >=3.6,<3.6.1
  
  Because test-pyppeteer depends on pyppeteer (0.2.5) which requires Python >=3.6.1,<4.0.0, version solving failed.

  at ~/.poetry/lib/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For pyppeteer, a possible solution would be to set the `python` property to ">=3.6.1,<4.0"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers

```
