### ISSUE TITLE
How can i install different version of a package?

### ISSUE THREAD

**Issue by deterok** [python-poetry/poetry#3887]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

Hi! It is possible a bug. I use different versions of a package for dev and no-dev configuration. It worked very well on poetry 1.0. But after update to poetry 1.1 i can't update and install my project anymore.
```Because my-project depends on both my-project-core (0.7 git branch master) and my-project-core (0.9 git branch develop), version solving failed.```
```toml
[tool.poetry.dependencies]
python = "^3.8"
psycopg2 = "^2.8.4"
click = "^7.0"
my-project-core = {git = "git@domain.com/my-project-core.git"}

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
pytest-sugar = "^0.9.2"
pytest-xdist = "^1.31.0"
pytest-watch = "^4.2.0"
pytest-mock = "^2.0.0"
my-project-core = {git = "git@domain.com/my-project-core.git", branch = "develop"}
```
What do I do wrong?
