### ISSUE TITLE
Package dependencies not installed when private PyPi repository present

### ISSUE THREAD

**Issue by michhri** [python-poetry/poetry#4000]
<!--
  Hi there! Thank you for discovering and submitting an issue.

  Before you submit this; let's make sure of a few things.
  Please make sure the following boxes are ticked if they are correct.
  If not, please try and fulfill these first.
-->

<!-- Checked checkbox should look like this: [x] -->
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

<!--
  Once those are done, if you're able to fill in the following list with your information,
  it'd be very helpful to whoever handles the issue.
-->

- **OS version and name**: MacOS Big Sur 11.2.3
- **Poetry version**: 1.1.6

## Issue
<!-- Now feel free to write your issue, but please be descriptive! Thanks again 🙌 ❤️ -->
I encountered an issue with dependencies when using a private repository. I have a `pyproject.toml` like
```toml
[tool.poetry]
name = "my-awesome-package"
version = "0.1.0"
description = "My package."
authors = ["Me"]
packages = [
    { include = "sub_package_1" },
    { include = "sub_package_2" }
]
include = ["path_to_files/**/*.gz"]

[[tool.poetry.source]]
name = 'private_pypi'
url = 'https://mypypi.dom/pypi/simple'

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=1.1.2"]
``` 
And I'd like to add a new package, explicitly `poetry add rasterio`. 
When the private repository (which has nothing to do with the desired package) is present in `pyproject.toml`, only 
the package itself gets installed without its dependencies
```
poetry add rasterio                                                                                                                                                                                                                                                
Using version ^1.2.3 for rasterio

Updating dependencies
Resolving dependencies... (10.2s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing rasterio (1.2.3)
```
When I remove the private repository part
```toml
[[tool.poetry.source]]
name = 'private_pypi'
url = 'https://mypypi.dom/pypi/simple'
```
and try to add the package, all of its dependencies get installed correctly
```
poetry add rasterio
Using version ^1.2.3 for rasterio

Updating dependencies
Resolving dependencies... (3.5s)

Writing lock file

Package operations: 6 installs, 0 updates, 0 removals

  • Installing click (7.1.2)
  • Installing affine (2.3.0)
  • Installing click-plugins (1.1.1)
  • Installing cligj (0.7.1)
  • Installing snuggs (1.4.7)
  • Installing rasterio (1.2.3)
```
It seems that the private repository is somehow interfering with the resolution of the dependencies. 
I have tried to recreate both the `poetry.lock` file and the virtual environment from scratch with no change in this behaviour.  

Initially, I have discovered this issue through a transitive dependency (a dependency on the private pypi repository, which I was trying to install, depends on `rasterio`) when I tried to `poetry update`, the dependencies `affine`, `click-plugins `, `snuggs` and `cligj` got uninstalled, so the issue seemed to be related to #3224 and #3684, but the issue can be reproduced with this minimalistic setup.

I have specified the missing dependencies explicitly in the `pyproject.toml` file for the time being. This however is a suboptimal solution as it bloats `pyproject.toml`.

Thank you for your help!

**Comment by theirix** [comment]
Reproduced with Poetry 1.2.2 / macOS 12.6.1 (21G217) with exactly this package `rasterio`.

The `pyproject.toml`:
```toml
[tool.poetry]
name = "foobar"
version = "0.1.0"
description = ""
authors = ["theirix <theirix@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
rasterio = "1.2.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "REDACTED"
url = "REDACTED"
```

Commands:
```
% export REPOSITORY_USERNAME=REDACTED
% export REPOSITORY_PASSWORD=REDACTED
% poetry new foobar
% cd foobar
% # add a private PyPi repository (GitLab-based if it matters) to the toml
% poetry env use /usr/local/opt/python@3.9/bin/python3.9
Using virtualenv: /Users/irix/.virtualenvs/foobar-w9rLp08K-py3.9
% poetry add rasterio@1.2.10

Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing rasterio (1.2.10)
```

If I don't use a private repository, all dependencies are installed as expected:
```
Package operations: 10 installs, 1 update, 0 removals

  • Installing click (8.1.3)
  • Installing numpy (1.23.5)
  • Installing pyparsing (3.0.9)
  • Installing affine (2.3.1)
  • Installing attrs (22.1.0)
  • Installing certifi (2022.9.24)
  • Installing click-plugins (1.1.1)
  • Installing cligj (0.7.2)
  • Updating setuptools (65.5.1 -> 65.6.3)
  • Installing snuggs (1.4.7)
  • Installing rasterio (1.2.10)
```
