### ISSUE TITLE
Removal of extras within the scope of "poetry install"

### ISSUE THREAD

**Issue by LuzianHahn** [python-poetry/poetry#4010]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I would like to suggest a feature, which enables the user to actively uninstall optional dependencies which were included by the usage of extras.
Let's consider the following example:

```toml
[tool.poetry.dependencies]
mandatory-package = "^1.0"
optional-package = {version = "^0.7", optional = true }

[tool.poetry.dev-dependencies]
some-dev-dep = "^2.0"

[tool.poetry.extras]
collection-of-optional-deps = [ "optional-package", ]
```

Now let's consider the venv to be from within four different states:
1. {mandatory-package}
2. {mandatory-package, optional-package}
3. {mandatory-package, some-dev-dep}
4. {mandatory-package, optional-package, some-dev-dep}

One can easily switch between state 1 and 3 by using either
`poetry install`
and
`poetry install --no-dev`

The same goes for 2 and 4 with
`poetry install -E collection-of-optional-deps`
and
`poetry install --no-dev -E collection-of-optional-deps`

However after installing the extras, it is impossible to remove them from the current environment (transition 2->1 or 4->3) without removing the optional dependencies from the pyproject.toml (or reinstalling all in a new venv).

Would it be possible to get a flag like "--remove-extras" or "--remove-optional" to indicate that optional dependencies should be cleared during an "install" call? (Would be probably similar to the freshly added flag "--remove-untracked")

I think I remember that an older version did this by default when calling `poetry install`, which is ofc also not ideal. I think the best thing would be to have direct control over this.

The motivation behind this, is to avoid reinstalling large mandatory dependencies, if you want to e.g. step from state 2 to 1.
