### ISSUE TITLE
Resolver fails on URL dependencies for different installations

### ISSUE THREAD

**Issue by MetcalfeTom** [python-poetry/poetry#4045]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur 11.2.3
- **Poetry version**: 1.1.6

## Issue
When building a first package with a URL dependency, any other package depending on it fails when specifying a version

Example:
```toml
[tool.poetry]
name = "some_package"
version = "2.0.0"

[tool.poetry.dependencies]
torch = { url = "https://download.pytorch.org/whl/cu110/torch-1.7.1%2Bcu110-cp38-cp38-linux_x86_64.whl" }
```

Now depending on that package and specifying a version of torch:

```toml
[tool.poetry]
name = "some_other_package"
version = "2.0.0"

[tool.poetry.dependencies]
some_package = "2.0.0"
torch = "*"
```

Leads to the following:

```
SolverProblemError

Because some_other_package depends on some_package (2.0.0) which depends on torch (1.7.1+cu110), torch is required.
So, because some_other_package depends on torch (*), version solving failed.
```

This makes it impossible to support multiple-constraint dependencies that contain URLs, which was something I attempted as a solution to https://github.com/python-poetry/poetry/issues/2613
