### ISSUE TITLE
After switching to a new virtualenv, "poetry update" still installs new packages to old virtualenv

### ISSUE THREAD

**Issue by kakyoism** [python-poetry/poetry#4148]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  macOS Big Sur 11.3.1 (20E241)
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

```toml
[tool.poetry]
name = "my app"
version = "0.1.0"
description = "some features"
authors = ["me <me@me.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^6.2.0"
dryable = "*"

[tool.poetry.dev-dependencies]
coverage = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```

## Issue

I switched to a new venv using

```sh
poetry env use /full/path/to/NEW/python3.x/bin/python
```

This works fine in terms of running my scripts under that environment using

```
poetry run python /path/to/my.py
```

However, when I want to add a package to the toml, it breaks because poetry installs the packages to the venv before I switch.

Also, if I try to switch back to the old env using

```sh
poetry env use /full/path/to/OLD/python3.x/bin/python
```

This still gives me

```
Using virtualenv: /full/path/to/NEW/python3.x
```

## Expectation

I expect that 

- the new packages should be installed to the new venv I switch to.
- switching back to OLD env is possible.
