### ISSUE TITLE
poetry show -t breaks --no-dev

### ISSUE THREAD

**Issue by Nieju** [python-poetry/poetry#4204]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

1. Add some dependencies and some dev dependencies
2. Run `poetry show --no-dev` this will only show non-development dependencies
3. Run `poetry show --no-dev -t` this will incorrectly show a tree with all dependencies and not only the `non-development`ones

**Comment by danhje** [comment]
Hope this gets prioritized.

**Comment by mkniewallner** [comment]
Tested on [1.1.13](https://github.com/python-poetry/poetry/releases/tag/1.1.13) and latest version from `master` branch, and it seems to have been fixed.

Used the following `pyproject.toml` file
```toml
[tool.poetry]
name = "foo"
version = "0.1.0"
description = ""
authors = ["Foo Bar"]

[tool.poetry.dependencies]
python = ">=3.10"
orjson = "3.6.8"
starlette = "0.20.0"

[tool.poetry.dev-dependencies]
mypy = "0.960"
pytest = "7.1.2"
```

```console
$ poetry show --no-dev -t
orjson 3.6.8 Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
starlette 0.20.0 The little ASGI library that shines.
└── anyio >=3.4.0,<5
    ├── idna >=2.8 
    └── sniffio >=1.1
```

This only shows non-dev dependencies.
