### ISSUE TITLE
section `tool.poetry.scripts`, installation of scripts if certain extra dependency is specified

### ISSUE THREAD

**Issue by xcodz-dot** [python-poetry/poetry#4208]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I am migrating my project [denver-api](https://github.com/xcodz-dot/denver-api) from setuptools to poetry but I have noticed a problem. I wanted to specify console scripts that are installed only with certain extras dependency group.

Here is my `pyproject.toml`

```toml
[tool.poetry]
name = "denver_api"
version = "3.1.0a0"
description = "Denver API for python full-stack development"
authors = ["xcodz-dot <71920621+xcodz-dot@users.noreply.github.com>"]
license = "MIT"
readme="README.md"
homepage="https://github.com/xcodz-dot/denver-api"
documentation="https://xcodz-dot.github.io/denver"
keywords=[
    "deneverapi",
    "denver",
    "denver-api",
    "python",
    "full-stack"
]
classifiers = [
    "Programming Language :: Python :: 3.6",
    "Operating System :: OS Independent"
]
packages=[
    { include="denverapi" }
]


[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.25.1"
playsound = "^1.2.2"
pygame = {version="^2.0.1", optional=true}
packaging = ">=20.9"
pip = ">=21"
pycryptodomex = {version="^3.10.1", optional=true}
ansiwrap = "^0.8.4"
colorama = "^0.4.4"
Flask = "^2.0.1"

[tool.poetry.extras]
gui-tools = ["pygame"]
encryption = ["pycryptodomex"]

[tool.poetry.scripts]
rmrdir = "denverapi.clineutils.rmrdir:main"
rmr = "denverapi.clineutils.rmr:main"
bdtpserver = "denverapi.tools.bdtpserver:main"
cryptify = "denverapi.tools.cryptify:main [encryption]" # Here, cryptify is only installed if optional dependency encryption is installed.
denverdb = "denverapi.database:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

The specified behaviour already works for setuptools but somehow does not work for poetry. Am I doing something wrong or is it not implemented yet?
