### ISSUE TITLE
poetry.core.masonry.api doesn't use private-repo auth tokens from env variables for development dependencies

### ISSUE THREAD

**Issue by jclerman** [python-poetry/poetry#4215]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option): _N/A, since the error occurs only when calling the API, not when executing a poetry command._

- **OS version and name**: ubuntu 20.04.1 LTS, via CircleCI Docker image (cimg/python:3.7.10)
- **Poetry version**: 1.1.7

## Issue
I am building/testing my project using CircleCI, but to the best of my knowledge, the problem isn't specific to CircleCI.

My `pyproject.toml` file includes (I've replaced the name of my organization with "xyz" for privacy):
```
[tool.poetry.dev-dependencies]
xyz-stuff = {version = "^0.4.0", source = "xyz"}

[[tool.poetry.source]]
name = "xyz"
url = "https://repo.shared.xyz.com/repository/pypi-xyz/simple"

[build-system]
requires = ["poetry-core>=1.0.3"]
build-backend = "poetry.core.masonry.api"

```

I also have a `tox.ini` file which includes:
```
[tox]
envlist = lint,py37
isolated_build = True
```

In my CircleCI environment, I have the proper variables set to provide authentication information (username/password) for a private github repository.  That is, values are set for variables like ("XYZ" replaces private info here):

`POETRY_HTTP_BASIC_XYZ_USERNAME`
`POETRY_HTTP_BASIC_XYZ_PASSWORD`

My CircleCI config.yml file includes:
```
version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/python:3.7.10'
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install default-jre
      - run: pip install poetry
      - run: poetry install
      - run: pip install tox
      - run:
          name: tox testing
          command: |
            mkdir test-results
            tox -p 3 -- --junitxml=test-results/junit.xml
```

Everything (including the `poetry install` step!) succeeds up until the final "tox testing" step, which fails with:
```
  RepositoryError

  401 Client Error: Unauthorized for url: https://repo.shared.xyz.com/repository/pypi-sirona/simple/xyz-stuff/

  at ~/.pyenv/versions/3.7.10/lib/python3.7/site-packages/poetry/repositories/legacy_repository.py:393 in _get
      389│             if response.status_code == 404:
      390│                 return
      391│             response.raise_for_status()
      392│         except requests.HTTPError as e:
    → 393│             raise RepositoryError(e)
      394│ 
      395│         if response.status_code in (401, 403):
      396│             self._log(
      397│                 "Authorization error accessing {url}".format(url=response.url),

ERROR: InvocationError for command /home/********/.pyenv/versions/3.7.10/bin/poetry install -v (exited with code 1)
```

The problem goes away if I do EITHER of these:
* the dependency is listed in `[tool.poetry.dependencies]` instead of `[tool.poetry.dev-dependencies]`
* Run this before the `tox testing` step:
```
poetry config http-basic.xyz $POETRY_HTTP_BASIC_XYZ_USERNAME $POETRY_HTTP_BASIC_XYZ_PASSWORD
```

As far as I understand, that `poetry config http-basic`... step should not be necessary, since it's using the same environment variables that poetry is supposed to be able to use directly.
