### ISSUE TITLE
Use .python-version as version constraint when absent from pyproject.toml

### ISSUE THREAD

**Issue by l0b0** [python-poetry/poetry#4284]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Add a configuration and command-line flag to say whether the contents of `.python-version` should be treated as a version restriction in the same way as the `tool.poetry.dependencies.python` setting. Projects which only support the exact version in `.python-version` could set this flag to `True` and remove `tool.poetry.dependencies.python`. Then they won't have to keep both settings in sync.

Example configuration:

```toml
[tool.poetry.pyenv]
use-version-as-constraint = true
```

or

```toml
[tool.poetry]
use-pyenv-version-as-constraint = true
```

---

This is not the same as #2019 or #2558.
