### ISSUE TITLE
Imposible to run "poetry install"

### ISSUE THREAD

**Issue by Conchylicultor** [python-poetry/poetry#4333]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS
- **Poetry version**: 1.2.0a

## Issue

I have a dummy poetry file:

```toml
[tool.poetry]
name = "my_project"
version = "0.1.0"
description = "Poetry plugin to setup automated release"
authors = ["Sunds team <sunds@google.com>"]

[tool.poetry.dependencies]
python = "^3.7"
```

I'm trying to install this file globally (as this is a `poetry` plugin)

```sh
poetry config virtualenvs.create false
poetry install
```

However this fail with:

```
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/poetry/core/version/pep440/parser.py:67

 InvalidVersion

  Invalid PEP 440 version: '3.2.1-nightly'
```

Full stacktrace: https://gist.github.com/Conchylicultor/d868433147613a1e9cd89d0d15f6b107

I'm quite confused by this error. I'm prevented of installing my project even though my configuration file is perfectly valid.

Somehow I think poetry try to parse the package installed on my system. But I checked with `pip freeze` that no package has `3.2.1` version (https://gist.github.com/Conchylicultor/a0922af93f734de3368208f9044536ee).

Looking at other github issue (#4176), it seems that I'm not the first to have similar issue. Like `pip`, poetry should ignore non-standard packages, rather than failing.
