### ISSUE TITLE
Poetry 1.2.0a2 - discrepancy in lockfile generation (compared to 1.1.x)

### ISSUE THREAD

**Issue by orlevii** [python-poetry/poetry#4384]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS BigSur 11.4
- **Poetry version**: 1.2.0a2

## Issue

For some reason poetry 1.2.0a2 is generating a different lockfile then 1.1.x:
Let's take for for example this `pyproject.toml`:
```toml
[tool.poetry]
name = "setuptools_bug"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "~3.7.1"
google-cloud-core = "^1.7.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
When using poetry 1.1.x - the lockfile looks fine.
But when using poetry 1.2.0a2 - for some reason "setuptools" is added as a dependency.

Also, the content hash comes out different:
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/13447456/129456811-430c40bb-fb82-4370-aa31-30e2e190e1fd.png">

Added the 2 lockfiles here:
**1.1.7:**
https://gist.github.com/orlevii/b56528719277c54492b44515b2efa22c#file-1-1-7-lockfile

**1.2.0a2:**
https://gist.github.com/orlevii/b56528719277c54492b44515b2efa22c#file-1-2-0a2-lockfile
