### ISSUE TITLE
Poetry 1.2.0a2 - Experimental installer: pip install fails for some packages

### ISSUE THREAD

**Issue by orlevii** [python-poetry/poetry#4399]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Poetry version**: 1.2.0a2

## Issue

Reproducible easily with this `pyproject.toml`:
```toml
[tool.poetry]
name = "installer-bug"
version = "0.1.0"
description = ""
authors = ["Or Levi <orlevi128@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.7.1"
pystan = "2.19.1.1"
fbprophet = "^0.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

The experimental installer will fail to install `fbprophet`
The error message is:
```    ERROR: Failed building wheel for fbprophet
  Failed to build fbprophet
  ERROR: Could not build wheels for fbprophet which use PEP 517 and cannot be installed directly
```

After some debugging I've found out the new installer is generating a different pip command then the old one.
**New installer 1.2.0a2:** (fails)
```
/Users/or.levi/projects/poetry/_bug/venv/bin/python \
    /Users/or.levi/projects/poetry/venv/lib/python3.7/site-packages/virtualenv/seed/wheels/embed/pip-21.0.1-py3-none-any.whl/pip install \
    --use-pep517 \
    --disable-pip-version-check \
    --prefix /Users/or.levi/projects/poetry/_bug/venv \
    --no-deps \
    file:/Users/or.levi/Library/Caches/pypoetry/artifacts/9f/c1 \
    /4f/7442d1f86f6dafe5693a8f472a4047ced6db8760c461ddef1645c4f34c/fbprophet-0.7.1.tar.gz
```

Looks like the `--use-pep517` makes some problems here.
Also, the pip commands that works are completely different for some reason.

-----------

**Old Installer 1.2.0a2:** (works)
```
/Users/or.levi/projects/poetry/_bug/venv/bin/python \
    /Users/or.levi/projects/poetry/venv/lib/python3.7/site-packages/virtualenv/seed/wheels/embed/pip-21.0.1-py3-none-any.whl/pip install \
    --no-deps -r /var/folders/t6/b41k4mp537n65jpyld5bffpm0000gq/T/fbprophet-0.7.1ze3ljpywreqs.txt
```

**New Installer 1.1.7:** (works)
```
/Users/or.levi/projects/poetry/_bug/venv/bin/pip install \
    --no-deps \
    file:///Users/or.levi/Library/Caches/pypoetry/artifacts/9f/c1/4f/7442d1f86f6dafe5693a8f472a4047ced6db8760c461ddef1645c4f34c/fbprophet-0.7.1.tar.gz
```

-----------

I guess that removing this flag will solve the problem, why is it needed?
https://github.com/python-poetry/poetry/blob/1.2.0a2/poetry/utils/pip.py#L28-L29

**Edit:** removing this flag fixes the issue (https://github.com/python-poetry/poetry/pull/4400)
