### ISSUE TITLE
Resolving transient editable dependencies with extras fails

### ISSUE THREAD

**Issue by SfinxCZ** [python-poetry/poetry#4423]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 11.5.2
- **Poetry version**: 1.1.8, 1.2.0.a2

**Comment by dimbleby** [comment]
recent code fails with the more helpful error message:
```
Package 'lib-a' is listed as a dependency of itself.
```
which should make it clear what the problem is.

**Comment by SfinxCZ** [comment]
@dimbleby thanks for reply. It seems that the message is not correct (using the latest github version - `Poetry (version 1.2.0b2.dev0)`). The pyproject.toml for the lib-a contains following definition:

```toml
[tool.poetry]
name = "lib-a"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [{include = "lib_a"}]

[tool.poetry.dependencies]
python = "3.8.*"
commons = {path = "../commons", extras=["numeric"], develop = true}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
I cannot see, why poetry would think that `lib-a` has dependency on itself. Plus `poetry show -t` for `lib-a` prints following output:
```
commons 0.1.0
└── numpy ^1.21.2
```
The `poetry show -t` for `project_a` does not work, since there is no `poetry.lock`.
