### ISSUE TITLE
Unable to run on python 3

### ISSUE THREAD

**Issue by jd-0001** [python-poetry/poetry#4450]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:Linux Mint 20.1 Cinnamon
- **Poetry version**:1.1.8
- **Link of a [Gist](https://gist.github.com/)

```toml
[tool.poetry]
name = "ts-tools"
version = "0.1.0"
description = ""
authors = ["jdsolanki0001 <jdsolanki0001@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.68.0"
uvicorn = {extras = ["standard"], version = "^0.15.0"}
pydantic = {extras = ["email"], version = "^1.8.2"}
python-multipart = "^0.0.5"
SQLAlchemy = {extras = ["mypy"], version = "^1.4.23"}
alembic = "^1.6.5"
python-dotenv = "^0.19.0"
psycopg2 = "^2.9.1"
aiofiles = "^0.7.0"
requests = "^2.26.0"
types-requests = "^2.25.6"
dateparser = "^1.0.0"
types-dateparser = "^1.0.1"
types-aiofiles = "^0.1.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.910"
black = {version = "^21.7b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue

I am unable to run poetry under python 3. I added an alias for `python` as `python3` in my Linux mint but that is not working.

Also, I don't want to use workarounds like `python-is-python3`. I wish poetry can detect my python version and don't complain if I use python3. We are already on the verge of python 3.10 and every time a new user uses poetry, poetry fails with their python3.

![Screenshot from 2021-08-29 14-57-36](https://user-images.githubusercontent.com/47495003/131245617-fbf32740-577f-4fbc-994a-530942258741.png)
