### ISSUE TITLE
Poetry install not remove old dist-info in venv

### ISSUE THREAD

**Issue by jean-helsinki** [python-poetry/poetry#4498]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.3 LTS
- **Poetry version**: 1.1.8

## Issue

After bump version in `pyproject.toml` and execute `poetry install` poetry not remove old dist-info folder from project venv:
```
ls ~/.cache/pypoetry/virtualenvs/poetry-bug-w3pEPh55-py3.8/lib/python3.8/site-packages/poetry_bug*
/home/user/.cache/pypoetry/virtualenvs/poetry-bug-w3pEPh55-py3.8/lib/python3.8/site-packages/poetry_bug.pth

/home/user/.cache/pypoetry/virtualenvs/poetry-bug-w3pEPh55-py3.8/lib/python3.8/site-packages/poetry_bug-0.1.0.dist-info:
INSTALLER  METADATA  RECORD

/home/user/.cache/pypoetry/virtualenvs/poetry-bug-w3pEPh55-py3.8/lib/python3.8/site-packages/poetry_bug-0.1.1.dist-info:
INSTALLER  METADATA  RECORD
```

This affect pkg_resources (and maybe other package utils) module behavior - `pkg_resources.get_distribution(module_name)` can take incorrect version for project.

`pyproject.toml` for reproduce bug is very basic:
```toml
[tool.poetry]
name = "poetry_bug"
version = "0.1.1"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
