### ISSUE TITLE
Be able to specify which version of setuptools has to be used

### ISSUE THREAD

**Issue by rvanlaar** [python-poetry/poetry#4511]
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I just ran into this bug: https://github.com/tikitu/jsmin/pull/34
Setuptools >=58 removed functionality jsmin relies on. 
The result is that jsmin can't be installed and our CI/CD pipeline fails.

My solution was to run the following before a build in out CI: `poetry run pip install --upgrade setuptools==57.5.0`
To counter this, it would be great if the setuptools version can be specified in the pyproject.toml.

**Comment by intgr** [comment]
I had the same issue with `demjson` package. Was quite surprised that poetry totally ignores setuptools version pinning.

```shell
% poetry init -n
% poetry shell
% poetry add setuptools==57.2.0
% poetry install
Installing dependencies from lock file
% pip freeze --all |grep setuptools
setuptools==58.0.4
% grep setuptools pyproject.toml
setuptools = "57.2.0"
% poetry add demjson
  • Installing demjson (2.2.4): Failed
[...]
      Complete output (1 lines):
      error in demjson setup command: use_2to3 is invalid.
[...]
```

**Comment by StevenMMortimer** [comment]
Big thanks @rvanlaar! Your suggestion works well in a Docker container. I've implemented by adding the poetry pip install of setuptools before running `poetry install`

```
RUN pip install --no-cache-dir 'poetry==1.1.5'
RUN poetry run pip install 'setuptools==57.5.0'
RUN poetry install --no-root
```

**Comment by finswimmer** [comment]
Hello,

for poetry <1.2 we have marked `setuptools` as "unsafe" to remove or change because poetry relies on it. We removed the limitation in the current preview release. You can now add setuptools to your pyproject.toml like any other dependency.

fin swimmer

**Comment by rvanlaar** [comment]
Hi,

Thank you for your response and confirmation that the issue can be handled in poetry 1.2.

I'm wondering, would it be possible to specify the setuptools version to use in the [build-sytem] part of the configuration?
In this case, the setuptools pin is only needed during builds.

Roland

**Comment by lerouxrgd** [comment]
Still failing on `1.2.0`:

```
Because xxxx depends on setuptools (==57.5.0) which doesn't match any versions, version solving failed.
```

**Comment by intgr** [comment]
Works for me with Poetry 1.2.0

```
% poetry init -n
% poetry shell
% poetry --version
Poetry (version 1.2.0)
% poetry add setuptools==57.2.0
[...]
Package operations: 0 installs, 1 update, 0 removals

  • Updating setuptools (65.3.0 -> 57.2.0)
% pip freeze --all |grep setuptools
setuptools==58.0.4
```

**Comment by heimalne** [comment]
In Poetry 1.4.1 we apparently can't override the setuptools version. Running `poetry install` on an older `gym==0.21.0` version should work with an older `setuptools < 66.0.0` version but fails on
```toml
# file: pyproject.toml
[tool.poetry]
name = "dummy_projectgym"
version = "0.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
poetry = "1.4.1"
setuptools = "65.6.3"         # <-------------- doesn't seem to be used
gym = "0.21"                       # <--------------

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
 with an error 
```
error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
```

Adding `setuptools` to the `build-system` section didn't help either.
```toml
[build-system]
requires = ["poetry-core>=1.0.0", "setuptools==65.6.3"]
```

The only hacky workaround i found was installing the problematic package through pip within poetry beforehand:
```bash
$ poetry run pip install gym==0.21.0
$ poetry install
```
Somehow that pip instance uses an older setuptools version (probably the default 58 one) but no idea why.
