### ISSUE TITLE
Pypoetry tries to clone optional git dependency on default installation.

### ISSUE THREAD

**Issue by golanor** [python-poetry/poetry#4562]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ubuntu 20.04.3 (github workflow)
- **Poetry version**:1.1.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/golanor/e5c21c15b982363a54c1613c81816eec

## Issue
Hi,

I have the  following structure of packages:

```
ppp_helper ---depends_on---> ppp ---optional_dependece---> ppp_c_version
```

all are located on github.
In the `ppp` `pyproject.toml`, I have the following:

```toml
[tool.poetry.dependencies]
ppp_c_version = { git = "git@github.com:golanor/ppp_c_version.git", tag = "0.2.0", optional = true}

[tool.poetry.extras]
cver = ["ppp_c_version"]
```

When I try to install `ppp_helper`, it fails when trying to resolve dependencies, specifically when trying to clone `ppp_c_version` (no permissions on ssh to get in).

Why is poetry trying to clone an optional dependency?
