### ISSUE TITLE
Use poetry-core from master as the build system

### ISSUE THREAD

**Issue by ashnair1** [python-poetry/poetry#4567]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I wanted to see if the recently merged PR python-poetry/poetry-core#192 can solve python-poetry/poetry#4380.
AFAIK the PR hasn’t made it to a release just yet. So how can I specify the build-system in my `pyproject.toml` to use the latest poetry-core i.e from its master branch.

**Comment by stinodego** [comment]
> So how can I specify the build-system in my `pyproject.toml` to use the latest poetry-core i.e from its master branch.

@sinoroc answered this question in issue #3419:

```toml
[build-system]
requires = ["poetry-core @ git+https://github.com/python-poetry/poetry.git"]
build-backend = "poetry.core.masonry.api"
```

I remember having an issue where I needed the master branch of the build system, and the above helped me.

A few months late, but hopefully it helps anyone who lands on this issue.

**Comment by ashnair1** [comment]
Brilliant. Thanks @stinodego.  Minor correction regarding the link. It should be 

```toml
[build-system]
requires = ["poetry-core @ git+https://github.com/python-poetry/poetry-core.git"]
build-backend = "poetry.core.masonry.api"
```
