### ISSUE TITLE
Poetry config hang while reading auth.toml

### ISSUE THREAD

**Issue by huynguyent** [python-poetry/poetry#4602]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.14.6
- **Poetry version**:  1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
Poetry config hang indefinitely while reading auth.toml when `pyproject.toml` has these very specific conditions
* Private repository is configured with `[[tool.poetry.source]]`
* Has at least one dev dependency (for example `mypy`)
* The configuration for this dev dependency is defined in `pyproject.toml` **and before** `[tool.poetry.dev-dependencies]` section
When these conditions are met, any `poetry config` command (with the exception of `poetry config --help`) hang indefinitely
```
❯ poetry config --list -vvv                                            
Loading configuration file /Users/example_user/Library/Application Support/pypoetry/config.toml
Loading configuration file /Users/example_user/Library/Application Support/pypoetry/auth.toml
```
The process just hanged indefinitely after the second log line. Poetry also consumed a lot of my CPU while it hanged as well.

Here is my `pyproject.toml`
```toml
[tool.poetry]
name = "poetry-bug"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.mypy]
disallow_untyped_defs = true
no_implicit_optional = true
pretty = true

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "some_username"
url = "https://private-repository/simple/"
secondary = true
```

Note that this error happen only if `[tool.mypy]` **is before** `[tool.poetry.dev-dependencies]`. `poetry config` works fine if `[tool.mypy]` is after `[tool.poetry.dev-dependencies]`

I use `mypy` as an example here but I believe it's not specific to `mypy`. I got the same error when I used `isort`.
