### ISSUE TITLE
Additional source is being ignored while inheriting dependencies

### ISSUE THREAD

**Issue by velykanov** [python-poetry/poetry#4659]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur 11.6
- **Poetry version**: 1.1.11

## Issue

Hi guys!
I'm using poetry for loading multiple projects and they depend on one another with the following structure:
```
.
├── project_1
│   └── pyproject.toml
└── project_2
    └── pyproject.toml
```

project_1/pyproject.toml
```toml
[[tool.poetry.source]]
name = "artifactory"
url = "https://pypi.example.com"
default = true

[tool.poetry.dependencies]
private_package = {version ="0.0.1", source = "artifactory"}
```

project_2/pyproject.toml
```toml
[tool.poetry.dependencies]
requests = "2.26.0"
fastapi = "0.65.3"

[tool.poetry.dependencies.project_1]
path = "../project_1"
```

And while I'm trying to execute `poetry install` or `poetry update` in `project_2` it fails to find `private_package` (despite the same commands are working well inside `project_1`)
It makes me think that additional source, which was added in `project_1` doesn't affect `project_2`

Can you please tell me if that's working well as designed and I'm trying to do something which is not supported entirely or if I'm misusing a tool and there's a lack of configurations?
