### ISSUE TITLE
Unable to install bokeh with python3.8 Link object as no attribute name

### ISSUE THREAD

**Issue by theelderbeever** [python-poetry/poetry#4681]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Big Sur 11.6
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
```toml
[tool.poetry]
authors = ["Taylor J Beever <me@me>"]
description = ""
name = "app"
version = "0.1.0"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.9"

[tool.poetry.dev-dependencies]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
```
## Issue

I am attempting to install `bokeh==2.4.1` into a new environment. I have upgraded pip to the latest version. After running
```console
poetry add bokeh
```
I receive the error
```console
  • Installing bokeh (2.4.1): Failed

  AttributeError

  'Link' object has no attribute 'name'

  at ~/.poetry/lib/poetry/installation/executor.py:632 in _download_link
      628│                 raise RuntimeError(
      629│                     "Invalid hashes ({}) for {} using archive {}. Expected one of {}.".format(
      630│                         ", ".join(sorted(archive_hashes)),
      631│                         package,
    → 632│                         archive.name,
      633│                         ", ".join(sorted(hashes)),
      634│                     )
      635│                 )
      636│ 


Failed to add packages, reverting the pyproject.toml file to its original content.
```
I can install `bokeh` in a 3.7 environment and can also install it with just `pip` in the 3.8 environment.
