### ISSUE TITLE
Does not store repository credentials

### ISSUE THREAD

**Issue by emistler** [python-poetry/poetry#4685]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur 11.6
- **Poetry version**: 1.1.11

## Issue
Poetry does not store the password for my private repo when using the config command [as outlined in the documentation](https://python-poetry.org/docs/repositories#configuring-credentials).

```bash
poetry config http-basic.gitlab username password
```

This, to no surprise, leads to an authentication error when trying to install a package from that private repo.

I found out that no password is stored by directly checking the configuration in `~/Library/Application Support/pypoetry/auth.toml`, reading simply:

```toml
[http-basic]
[http-basic.gitlab]
username = "username"
```

By adding the following line, I was able to patch the issue:

```toml
password = "password"
```

However, the password disappears every time I run the config command again:

```bash
poetry config http-basic.gitlab username password
```

Relevant section of my `pyproject.toml`:

```toml
[[tool.poetry.source]]
name = "gitlab"
url = "https://gitlab.com/api/v4/groups/1123.../-/packages/pypi/simple"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
