### ISSUE TITLE
RuntimeError poetry==1.1.11 with virtualenv>=20.8.1

### ISSUE THREAD

**Issue by m9810223** [python-poetry/poetry#4712]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: darwin
- **Poetry version**: poetry==1.1.11 poetry-core==1.0.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
```toml
[tool.poetry]
name = "XXX"
version = "0.1.0"
description = ""
authors = ["XXX <XXX@XXX.com>"]

[tool.poetry.dependencies]
python = ">2.7,<3" # only python 2 fail

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
## Issue

- `poetry shell or install`
- `python3.8/site-packages/virtualenv/run/plugin/creators.py:43 in for_interpreter`
- `raise RuntimeError("No virtualenv implementation for {}".format(interpreter))`
- Occurred with `virtualenv>=20.8.1`, but `virtualenv<=20.8.0` has no problem.
