### ISSUE TITLE
Poetry remove removes package.source from unrelated packages

### ISSUE THREAD

**Issue by racinmat** [python-poetry/poetry#4767]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: CentOS 7
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
I have `pyproject.toml` with specified sources
```toml
[[tool.poetry.source]]
name = "***"
url = "***"
secondary = true

[[tool.poetry.source]]
name = "***"
url = "***"
secondary = true
```
and `poetry.lock`. When I remove any package using `poetry remove <packagename>`, poetry removes
```toml
[package.source]
type = "legacy"
url = "***"
reference = "***"
```
section from all packages.
