### ISSUE TITLE
poetry update doesn't respect the change of "develop" attribute

### ISSUE THREAD

**Issue by jaklan** [python-poetry/poetry#4884]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur 11.6
- **Poetry version**: 1.1.12

## Issue
When I change the `develop` attribute of a dependency (from `false` to `true` or vice versa) and run `poetry update`, the change is not respected - I get the following message:
```shell
No dependencies to install or update
```
Removing only `poetry.lock` also doesn't help - I have to uninstall the package. But I can't do it with `poetry remove`, because...  there's no CLI flag for `poetry add` to specify the proper value of `develop` attribute when adding it back. I have to modify the file manually after that, but then package... is already installed, so we get stuck in the loop.

The solution is to run `pip uninstall some_package`, modify manually the `pyproject.toml` to change the `develop` value and then run `poetry install`.

```toml
[tool.poetry.dependencies]
python = "^3.8"
"some_package" = {path = "../some_package"}
```
⬇️ 
```toml
[tool.poetry.dependencies]
python = "^3.8"
"some_package" = {path = "../some_package", develop = true}
```

I see 2 issues here:
1) the one from the title
2) l̶a̶c̶k̶ ̶o̶f̶ ̶`̶d̶e̶v̶e̶l̶o̶p̶`̶ ̶o̶p̶t̶i̶o̶n̶ ̶f̶o̶r̶ ̶`̶p̶o̶e̶t̶r̶y̶ ̶a̶d̶d̶`̶ - seems to be resolved in `1.2.0`
