### ISSUE TITLE
`-E` ignored when using `poetry.group`

### ISSUE THREAD

**Issue by Conchylicultor** [python-poetry/poetry#4891]
- **OS version and name**: Debian
- **Poetry version**: 1.2.0a2

```toml
[tool.poetry]
name = "tmp-poetry"
version = "0.1.0"
description = ""
authors = ["xyz <xyz@gmail.com>"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Bellow is the bug

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.group0]
optional = true

[tool.poetry.group.group0.dependencies]
numpy = "*"

[tool.poetry.extras]
numpy_extra = ["numpy"]
```

## Issue

When `[tool.poetry.extras]` is used to refer to deps defined inside `[tool.poetry.group.group0.dependencies]`, those deps are ignored.

Reproduction instrutions:

```
poetry install -E numpy_extra
```

I would expect the command to install `tmp-poetry[numpy_extra]` which should install `numpy`. However, this silently fail to install the package:

Display:
```
Creating virtualenv tmp-poetry-S27UDbn2-py3.9 in ~/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Installing the current project: tmp-poetry (0.1.0)
```
The extra deps is ignored and not installed, `poetry show` will display nothing.
`poetry run python -c "import numpy"` will fail with `ModuleNotFoundError`

Note: removing the groups and using instead `numpy={version="*", optional=true}` will work.
