### ISSUE TITLE
`-E` ignored when using `poetry.group`

### ISSUE THREAD

**Issue by Conchylicultor** [python-poetry/poetry#4897]
Reposting #4891 with more info, as I don't think the issue has been solved.

- **OS version and name**: Debian
- **Poetry version**: 1.2.0a2

```toml
[tool.poetry]
name = "tmp-poetry"
version = "0.1.0"
description = ""
authors = ["xyz <xyz@gmail.com>"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Bellow is the bug

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.group0]
optional = true

[tool.poetry.group.group0.dependencies]
numpy = "*"
matplotlib = "*"

[tool.poetry.extras]
extra_deps = ["numpy", "matplotlib"]
```

## Issue

When `[tool.poetry.extras]` is used to refer to deps defined inside `[tool.poetry.group.group0.dependencies]`, those deps are ignored.

Reproduction instrutions:

```
poetry install -E extra_deps
```

I would expect the command to install `tmp-poetry[extra_deps]` which should install `numpy`. However, this silently fail to install the package.
The extra deps is ignored and not installed, `poetry show` will display nothing.
`poetry run python -c "import numpy"` will fail with `ModuleNotFoundError`

Note: removing the groups and using instead `numpy={version="*", optional=true}` will work.

## Why using dependency group with extra ?

The reason I'm trying to use dependency group is that it greatly reduce boilerplate of defining deps

Without dependency group:

```toml
[tool.poetry.dependencies]
absl-py = {version="*", optional=true}
importlib_resources = {version="*", optional=true}
jax = {version="*", optional=true}
jupyter = {version="*", optional=true}
matplotlib = {version="*", optional=true}
numpy = {version=">=1.17", optional=true}
tf-nightly = {version="*", optional=true}
tqdm = {version="*", optional=true}
tree = {version="*", optional=true}
zipp = {version="*", optional=true}
```

With dependency group:

```toml
[tool.poetry.group.group0]
optional = true

[tool.poetry.group.group0.dependencies]
absl-py = "*"
importlib_resources = "*"
jax = "*"
jupyter = "*"
matplotlib = "*"
numpy = "*"
tf-nightly = "*"
tqdm = "*"
tree = "*"
zipp ="*"
```

## Resolving this issue

There are 2 ways to resolve this issue:

1) Either `extras` and `group` are incompatible features, in which case `poetry` should raise an explicit error message (rather than silently skipping deps installation)
2) Either `extras` can use deps defined in `group` (best), in which case the deps should be correctly installed.

Of course 2) should be greatly preferred.
