### ISSUE TITLE
Poetry install dependency doesnt work when we use two private repository

### ISSUE THREAD

**Issue by manojnair727** [python-poetry/poetry#4900]
python project has two dependency from our private gitlab repository which i have configured in pyproject.toml as

```toml
[[tool.poetry.source]]
url = "https://gitlab.com/api/v1/projects/24578772/packages/pypi/simple"
name = "mvr"
secondary=true

[[tool.poetry.source]]
url = "https://gitlab.com/api/v1/projects/75328497/packages/pypi/simple"
name = "gcp"

[tool.poetry.dependencies]
mvr = { version = "0.1.4", source = "mvr" }
gcp = { version = "0.0.6", source = "gcp" }
```
i had run 
```
poetry config http-basic.mvr <token> <password> 
poetry config http-basic.gcp <token2> <password2> 
```

then when i execute poetry update, i get this error
```
Because my-project depends on gcp (0.0.6) which doesn't match any versions, version solving failed.

  at ~/.poetry/lib/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

```
if i use only one of the gitlab project either gcp or mvr it works. but if i have two private repo it doesnt. I think gcp is looking into mvr gitlab repo and not able to find the version. Can someone please look intp this
