### ISSUE TITLE
pre-commit hook generate different lockfile than running `poetry lock` manually

### ISSUE THREAD

**Issue by Luxiyalu** [python-poetry/poetry#4978]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) -> no exception

- **OS version and name**: MacOS 12.0.1
- **Poetry version**: 1aa4d5b latest master
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Luxiyalu/7f0ba5ca327f61766ef99c6954eba17e

## Issue

The command `poetry lock --no-update` generates different results for lockfile when it's run in pre-commit hooks, as in:

```yaml
# .pre-commit-config.yaml 

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1aa4d5b'
    hooks:
      - id: poetry-lock
        args: ["--no-update"]
```

So pre-commit in CI always fail.
