### ISSUE TITLE
poetry install with build script fails on 1.2.0

### ISSUE THREAD

**Issue by matteosantama** [python-poetry/poetry#4979]
```sh
❯ poetry --version
Poetry (version 1.2.0a2)
```

I am trying to run `poetry install`. This configuration works on 1.1.12

```toml
# pyproject.toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Matteo Santamaria <XXX@gmail.com>"]
readme = "README.md"
build = "build.py"

[tool.poetry.dependencies]
python = "3.8"

[tool.poetry.dev-dependencies]
numpy = "^1.22.0"

[build-system]
requires = ["poetry-core", "numpy>=1.22.0,<=1.23.0"] 
build-backend = "poetry.core.masonry.api"
```

```python
# build.py
import numpy as np

def build(setup_kwargs):
    return setup_kwargs
```

but fails on 1.2.0a2.

Tested on macOS Monterey Version 12.0.1 Apple M1 Pro
