### ISSUE TITLE
(🎁) Support isolated dependencies that install like pipx

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#5037]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

pseudo pyproject.toml:
```toml
[tool.poetry.dev-dependencies]
pytest = "6.0.0"
black = { version = "^21.12b0", isolated = true }
```
OR:
```toml
[tool.poetry.group.test]
pytest = "6.0.0"
black = { version = "^21.12b0", isolated = true }
```

I have dev dependencies that are never imported by my source code or my test code, they act more as standalone cli applications. I still want to the version to be locked down, and provide a one click install for developers working with my project, but I don't want the possibility of that dependency interfering with dependency resolution or accidentally becoming imported due to it being in the pythonpath.

When declared with the optional `isolated` properties, I want Poetry to install the dependency like [pipx](https://github.com/pypa/pipx) would, completely isolated from the other dependencies.

**Comment by branchvincent** [comment]
There's a draft PR at #5740, feedback is welcome there

**Comment by rockandska** [comment]
This is how I expect to see this feature works and explained it originally in #7421 

```toml
[tool.poetry.dependencies]
python = ">= 3.7, <= 3.11"

[tool.poetry.group.lint]
optional = true
# depends_on by default is [ 'main' ]
depends_on = []
           
[tool.poetry.group.lint.dependencies]
python = ">= 3.7, <= 3.8"
flake8 = "*"

[tool.poetry.group.typing]
optional = true
depends_on = [ 'main' ]

[tool.poetry.group.typing.dependencies]
mypy = "*"
```

In this example :
- lint is only intended to be executed with python 3.7 or 3.8
- typing is intended to be executed with the same python versions the project has
- lint is isolated, so dependencies required by flake8 (`importlib-metadata<5`) doesn't influence other packages in other groups if they don't depend on lint
- `poetry install --with lint` will fail because `lint` does not have main in `depends_on`
- when doing `poetry install --only typing`, it will install `main` too since it depends on it
