### ISSUE TITLE
git depencencies don't have hashes in `poetry.lock` & `poetry update` doesn't work if the version number hasn't changed

### ISSUE THREAD

**Issue by DetachHead** [python-poetry/poetry#5051]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: windows 10
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:
  ```toml
  [tool.poetry.dependencies]
  basedtyping = { git = "https://github.com/KotlinIsland/basedtyping.git", rev = "f2ecd42ab96eaf68c96da6527cb6075d8da3028d" }
  ```

## Issue
1. run `poetry update` with the dependency above
2. change the `rev` to a newer commit, such as `11f7b4c232d68d5bb4c150d3340322548e1feda8`
3. run `poetry update`

### expected result
the new version is installed
### actual result
the old version stays installed, the only thing updated in the lockfile is the commit hash
there is also no hash in `metadata.files`
![image](https://user-images.githubusercontent.com/57028336/149716039-9a03a857-80f1-4af4-9142-647bc93286e2.png)

**Comment by bcm-at-zama** [comment]
We have the same issue with a version of the git repo which doesn't change but with a sha1 which changes: poetry believes nothing is to be done.

**Comment by jabalazs** [comment]
Possibly related to #5021

**Comment by DetachHead** [comment]
it doesn't seem to have resolved it. although the `resolved_reference` gets updated it still doesn't actually update the installed. version. tested with:

```toml
[tool.poetry.dependencies]
basedtyping = { git = "https://github.com/KotlinIsland/basedtyping.git", rev = "a409f4fb70cd49b2db9ba311ffb1cc39d2e7256b" }
```

1. change the `rev` to `0b07cdf96ca1569667b81f759dff330edb736432`
2. run `poetry update`

it changes the `resolved_reference` but doesnt actually update the installed version
