### ISSUE TITLE
New poetry-core release

### ISSUE THREAD

**Issue by dimaqq** [python-poetry/poetry#5056]
Please release the `build_editable` hook: 🙏🏿 

https://github.com/python-poetry/poetry-core/blob/af08f1ce720da467c9bf3d43eed3d9ebaf4ad7fb/src/poetry/core/masonry/api.py#L82-L89

**Comment by edgarrmondragon** [comment]
Hi @dimaqq! Is there a reason you can't use `master` in the meantime?

This should work

```toml
# pyproject.toml

[build-system]
requires = ["poetry-core @ git+https://github.com/python-poetry/poetry-core.git@master"]
build-backend = "poetry.core.masonry.api"
```

https://github.com/python-poetry/poetry/issues/34#issuecomment-997519115
