### ISSUE TITLE
ci: Update matrix to python 3.10 final across projects

### ISSUE THREAD

**Issue by tony** [python-poetry/poetry#5087]
Update CI to use python 3.10 where applicable

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

```yaml
          - os: Ubuntu
            python-version: "3.10.0-alpha - 3.10.0"
            experimental: true
            bootstrap-args: "--git https://github.com/python-poetry/poetry.git"
```
https://github.com/python-poetry/poetry-core/blob/af08f1ce720da467c9bf3d43eed3d9ebaf4ad7fb/.github/workflows/tests.yml#L23-L26
