### ISSUE TITLE
Can't install spacy 3 with a model

### ISSUE THREAD

**Issue by LifeIsStrange** [python-poetry/poetry#5199]
```Unable to find installation candidates for torch (1.10.2)```
zero additional information. It is also implicit that the issue is spacy related.

``` toml
spacy = "^3.2.2"
en_core_web_trf = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.2.0/en_core_web_trf-3.2.0-py3-none-any.whl" }
```

poetry add torch doesn't work btw
