### ISSUE TITLE
Arbitrary environment property for environment markers

### ISSUE THREAD

**Issue by orctom** [python-poetry/poetry#5222]
Say I have an app that have to be runnable on these boxes:
 - Ubuntu, with CUDA 11.4 (which requires the cu111 version)
 - Ubuntu, with CUDA 10.2 (cu111 doesn't work)
 - Ubuntu, CPU only
 - MacOS

If only for Linux and MacOS, we can use environment markers such as:
```toml
torch = [
  {version = "1.8.1", markers = "sys_platform == 'linux'"},
  {version = "1.8.1", markers = "sys_platform == 'darwin'"}
]
```

But there're no options for different CUDA versions.

Can we add an environment property specific markers such as `markers_env`.

PROPOSAL:
Manually set a env property on box, export any_name=any_value
In dependency section: `markers_env = "any_name <= the_condition_value"`

e.g.
```bash
# set env property on box manually
export cuda=10.2
```

```toml
[tool.poetry.dependencies]
#...
torch = [
  {version = "1.8.1", markers = "sys_platform == 'linux'", markers_env = "cuda < 11.1"},
  #{url = "https://download.pytorch.org/whl/cu111/torch-1.8.1%2Bcu111-cp38-cp38-linux_x86_64.whl", markers = "sys_platform == 'linux'", markers_env = "cuda >= 11.1"},
  {version = "1.8.1+cu111", source="pytorch", markers = "sys_platform == 'linux'", markers_env = "cuda >= 11.1"},
  {version = "1.8.1", markers = "sys_platform == 'darwin'"}
]

#...

[[tool.poetry.source]]
name = "pytorch"
url = "https://eternalphane.github.io/pytorch-pypi/"
secondary = true
#...
```
