### ISSUE TITLE
Issue #4201 Persists Despite PR #186

### ISSUE THREAD

**Issue by adam-grant-hendry** [python-poetry/poetry#5244]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Enterprise, 20H2
- **Poetry version**: 1.2.0a2
- **`pyproject.toml` file**:
```toml
[tool.poetry]
name = "problem"
version = "0.1.0"
description = "problem"
authors = ["problem"]

[tool.poetry.dependencies]
pywin32 = "^301"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue
Although [#186](https://github.com/python-poetry/poetry-core/pull/186/files) claims to have fixed `parsing of wildcards dependency constraints` (see [#4095](https://github.com/python-poetry/poetry/issues/4095), [#4201](https://github.com/python-poetry/poetry/issues/4201), and [#4176](https://github.com/python-poetry/poetry/issues/4176)), this issue persists.

By chance, does `py install-poetry.py --preview` not update to latest master branch commit?
