### ISSUE TITLE
Generated script in valid when using extras

### ISSUE THREAD

**Issue by cazador481** [python-poetry/poetry#5297]
- [X ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **linux **: 
- **poetry 2.0.1**: 
- **Link of a [Gist](<script src="https://gist.github.com/cazador481/426247f6285785b100b7c9b9cf76da7b.js"></script>) with the contents of your pyproject.toml file**: 

## Issue
When creating a script with poetry install.  The installed script does not have valid synax, when using an extras in the tool.poetry.source configuration.
Example configuration:
```
[tool.poetry.scripts]
client_tool = {callable="client_tool.app:app",extras = ['cli']}
```
Generated script
```python
#!/home/scratch.eash/ci/ci.git/dev/inf/ci/workspace_manager/mainline/.venv/bin/python
from workspace_manager.main import cli[cli]

if __name__ == '__main__':
    cli[cli]()
```

The script should look like
```python
#!/home/scratch.eash/ci/ci.git/dev/inf/ci/workspace_manager/mainline/.venv/bin/python
from workspace_manager.main import cli

if __name__ == '__main__':
    cli()
```

**Comment by finswimmer** [comment]
Hello @cazador481,

I can reproduce this with Poetry 1.1.14 but no longer with the latest version in `master`. Seems to be fixed.

fin swimmer

**Comment by nilsso** [comment]
Is anyone still having this problem today? I'm on 1.6.1, with a manifest like this (just the details)
```toml
[tool.poetry.scripts]
debt-schedule = { reference = "my_package.cli:main", extras = ["cli"], type = "console" }

[tool.poetry.dependencies]
cappa = { version = "^0.6.0", optional = true }

[tool.poetry.extras]
cli = ["cappa"]
```
And I get the following generated
```py
#!/.../bin/python
import sys
from my_package.cli import main[cli]

if __name__ == '__main__':
    sys.exit(main[cli]())
```
