### ISSUE TITLE
Poetry publish to Azure DevOps Artifacts returning HTTP Error 405

### ISSUE THREAD

**Issue by FilBot3** [python-poetry/poetry#5348]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 35 Kinoite using Toolbox Container
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/FilBot3/c5aa2bc69477af94a70f0a8c1a0d0d6f)

## Issue

After following what I did previously in:

* [StackOverflow: Poetry getting 401 from Azure DevOps](https://stackoverflow.com/questions/63909006/publishing-packages-to-azure-deveops-artifacts-using-python-poetry)
* [GitHub: python-poetry - 401 when using AzDO](https://github.com/python-poetry/poetry/issues/3344)

I am now getting an HTTP Error 405 from Azure DevOps when trying to publish to an Azure DevOps Artifacts Python Feed. Using a freshly generated PAT token with `full access` to `all accessible organizations`, I am having issues publishing my package. I get `HTTP Error 405`. See the output below.

### OS Information

<details>

```bash
➜  cat /etc/os-release 
NAME="Fedora Linux"
VERSION="35 (Container Image)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Container Image)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Container Image"
VARIANT_ID=container
```

</details>

### Python Poetry Version

<details>

```bash
➜  poetry --version
Poetry version 1.1.13
```

</details>

### Python Version

<details>

```bash
➜  python --version
Python 3.10.2
```

</details>

### poetry.toml contents

<details>

The `${..}` is so I am not giving out my organizational information.

```toml
[repositories]
[repositories.azure]
url = "https://pkgs.dev.azure.com/${ADO_ORG}/${ADO_PROJ}/_packaging/python-azure-artifacts/pypi/simple/"
```

</details>

### Poetry Verbose output

<details>

```bash
➜  poetry publish -r azure -u phil -p $(cat ~/.local/azdo-pat.txt)

Publishing snow (0.1.0) to azure
 - Uploading snow-0.1.0-py3-none-any.whl 100%

  UploadError

  HTTP Error 405: Method Not Allowed

  at ~/.local/share/pypoetry/venv/lib64/python3.10/site-packages/poetry/publishing/uploader.py:216 in _upload
      212│                     self._register(session, url)
      213│                 except HTTPError as e:
      214│                     raise UploadError(e)
      215│
    → 216│             raise UploadError(e)
      217│
      218│     def _do_upload(
      219│         self, session, url, dry_run=False
      220│     ):  # type: (requests.Session, str, Optional[bool]) -> None

➜  poetry publish -r azure -u phil -p $(cat ~/.local/azdo-pat.txt) -vvv

Publishing snow (0.1.0) to azure
 - Uploading snow-0.1.0-py3-none-any.whl 100%

  Stack trace:

  7  ~/.local/share/pypoetry/venv/lib64/python3.10/site-packages/clikit/console_application.py:131 in run
      129│             parsed_args = resolved_command.args
      130│
    → 131│             status_code = command.handle(parsed_args, io)
      132│         except KeyboardInterrupt:
      133│             status_code = 1

  6  ~/.local/share/pypoetry/venv/lib64/python3.10/site-packages/clikit/api/command/command.py:120 in handle
      118│     def handle(self, args, io):  # type: (Args, IO) -> int
      119│         try:
    → 120│             status_code = self._do_handle(args, io)
      121│         except KeyboardInterrupt:
      122│             if io.is_debug():

  5  ~/.local/share/pypoetry/venv/lib64/python3.10/site-packages/clikit/api/command/command.py:171 in _do_handle
      169│         handler_method = self._config.handler_method
      170│
    → 171│         return getattr(handler, handler_method)(args, io, self)
      172│
      173│     def __repr__(self):  # type: () -> str

  4  ~/.local/share/pypoetry/venv/lib64/python3.10/site-packages/cleo/commands/command.py:92 in wrap_handle
       90│         self._command = command
       91│
    →  92│         return self.handle()
       93│
       94│     def handle(self):  # type: () -> Optional[int]

  3  ~/.local/share/pypoetry/venv/lib64/python3.10/site-packages/poetry/console/commands/publish.py:77 in handle
      75│         )
      76│
    → 77│         publisher.publish(
      78│             self.option("repository"),
      79│             self.option("username"),

  2  ~/.local/share/pypoetry/venv/lib64/python3.10/site-packages/poetry/publishing/publisher.py:93 in publish
      91│         )
      92│
    → 93│         self._uploader.upload(
      94│             url,
      95│             cert=cert or get_cert(self._poetry.config, repository_name),

  1  ~/.local/share/pypoetry/venv/lib64/python3.10/site-packages/poetry/publishing/uploader.py:119 in upload
      117│
      118│         try:
    → 119│             self._upload(session, url, dry_run)
      120│         finally:
      121│             session.close()

  UploadError

  HTTP Error 405: Method Not Allowed

  at ~/.local/share/pypoetry/venv/lib64/python3.10/site-packages/poetry/publishing/uploader.py:216 in _upload
      212│                     self._register(session, url)
      213│                 except HTTPError as e:
      214│                     raise UploadError(e)
      215│
    → 216│             raise UploadError(e)
      217│
      218│     def _do_upload(
      219│         self, session, url, dry_run=False
      220│     ):  # type: (requests.Session, str, Optional[bool]) -> None
```

</details>

### pyproject.toml

<details>

```toml
[tool.poetry]
name = "snow"
version = "0.1.0"
description = ""
authors = ["Phillip Dudley <Predatorian3@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"
click = "^8.0.4"
jmespath = "^0.10.0"
pyright = "^1.1.230"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.5.4"
flake8 = "^3.8.4"
pycodestyle = "^2.6.0"
pylint = "^2.6.0"
jsonlint = "^0.1"
yamllint = "^1.25.0"
rstcheck = "^3.3.1"
artifacts-keyring = "^0.3.1"
twine = "^3.8.0"
keyring = "^23.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
servicenow = 'snow.cli:start'

[tool.pyright]
include = ["src"]
exclude = ["**/node_modules", "**/__pycache__"]
#strict = ["src"]
#typeCheckingMode = "strict"
```

</details>

**Comment by FilBot3** [comment]
Similar to Issue: https://github.com/python-poetry/poetry/issues/4658

**Comment by abn** [comment]
@FilBot3 can you try the following in your `poetry.toml`?

```toml
[repositories]
[repositories.azure]
url = "https://pkgs.dev.azure.com/${ADO_ORG}/${ADO_PROJ}/_packaging/python-azure-artifacts/pypi/upload"
```

The `/simple` endpoint wont accept `POST` requests.
