### ISSUE TITLE
Allow for intergroup references

### ISSUE THREAD

**Issue by lovesegfault** [python-poetry/poetry#5462]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

It's useful to have granular groups, since they allow your users to not have to install more than what they need. One could picture something like this:

```toml
[tool.poetry]
name = "intergroup"
version=  "0.0.0"

[tool.poetry.dependencies]
python = "^3.8.8,<4.0.0"
foo = "*"

[tool.poetry.group.dev.dependencies]
pylint = "2.12.*"
bar = "*"
baz = "*"
bim = "*"
bam = "*"
mypy = "0.941"
types-foo = "*"
types-bar = "*"
types-baz = "*"
types-bim = "*"
types-bam = "*"

[tool.poetry.group.linting]
optional = true
[tool.poetry.group.linting.dependencies]
pylint = "2.12.*"

[tool.poetry.group.typechecking]
optional = true
[tool.poetry.group.typechecking.dependencies]
mypy = "0.941"
types-foo = "*"
types-bar = "*"
types-baz = "*"
types-bim = "*"
types-bam = "*"

[tool.poetry.group.releasing]
optional = true
[tool.poetry.group.releasing.dependencies]
bim = "*"
bam = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Which could be greatly simplified if, somehow, one group could reference another, for example:

```toml
[tool.poetry]
name = "intergroup"
version=  "0.0.0"

[tool.poetry.dependencies]
python = "^3.8.8,<4.0.0"
foo = "*"

[tool.poetry.group.dev]
implies = [ "linting", "typechecking", "releasing" ]
[tool.poetry.group.dev.dependencies]
bar = "*"

[tool.poetry.group.linting]
optional = true
[tool.poetry.group.linting.dependencies]
pylint = "2.12.*"

[tool.poetry.group.typechecking]
optional = true
[tool.poetry.group.typechecking.dependencies]
mypy = "0.941"
types-foo = "*"
types-bar = "*"
types-baz = "*"
types-bim = "*"
types-bam = "*"

[tool.poetry.group.releasing]
optional = true
[tool.poetry.group.releasing.dependencies]
bim = "*"
bam = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

I know this is served by using `--with`, but I wish there was a way to specify a "default with" for a group.
