### ISSUE TITLE
Reference extras in tool.poetry.extras

### ISSUE THREAD

**Issue by mr-bjerre** [python-poetry/poetry#5471]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Currently we can define `extras` like this

```toml
[tool.poetry]
name = "awesome"

[tool.poetry.dependencies]
# These packages are mandatory and form the core of this package’s distribution.
mandatory = "^1.0"

# A list of all of the optional dependencies, some of which are included in the
# below `extras`. They can be opted into by apps.
psycopg2 = { version = "^2.7", optional = true }
mysqlclient = { version = "^1.3", optional = true }

[tool.poetry.extras]
mysql = ["mysqlclient"]
pgsql = ["psycopg2"]
databases = ["mysqlclient", "psycopg2"]
```

I have a monorepo where I use a single `pyproject.toml` file to describe different runtime options (by using `extras`). It would be cool if the last line in the above could be changed to the following

```toml
databases = ["mysql", "pgsql"]
```

I.e. being able to extend other extras. The same goes for the upcoming `tool.poetry.group` feature.
