### ISSUE TITLE
Documentation on `Multiple constraints dependencies` is misleading

### ISSUE THREAD

**Issue by michaelbrewer** [python-poetry/poetry#5473]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

In the documentation example

```toml
[tool.poetry.dependencies]
foo = [
    {version = "<=1.9", python = "^2.7"},
    {version = "^2.0", python = "^3.4"}
]
```

In practice Python 3.4 will match against `<=1.9`

Where as an example like this would ensure `<=1.9"` is used for Python 2.7 and `^2.0` for Python 3.4+

```toml
[tool.poetry.dependencies]
python = "^2.7"
foo = [
    {version = "<=1.9", python = "2.7"},
    {version = "^2.0", python = "^3.4"}
]
```

Related to https://github.com/awslabs/aws-lambda-powertools-python/issues/1138#issuecomment-1104624859
