### ISSUE TITLE
Solver breaks faced with related dependencies that are both conditional

### ISSUE THREAD

**Issue by anthonymichaelclark** [python-poetry/poetry#5506]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  macOS Monterey 12.3.1
- **Poetry version**:  1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [Here](https://gist.github.com/anthonymichaelclark/dad50a1444e523846d2ccd9dace4f817)

## Issue
The solver breaks when faced with dependencies A and B that are both conditional but where A depends on B only sometimes.

Consider these lines from the attached `pyproject.toml`
```
dbt = { version = "0.19.2", markers = "sys_platform != 'darwin'" }
dbt-bigquery = [
    { version = "0.19.2", markers = "sys_platform != 'darwin'" },
    { version = "^1.0.0", markers = "sys_platform == 'darwin' "},
]
```
The intent here is "Install dbt==0.19.2 and dbt-bigquery==0.19.2 when `sys_platform` is not `'darwin'`; else install `dbt-bigquery==^1.0.0`. When trying to install on a machine using `sys_platform == 'darwin'` I get:

```
Updating dependencies
Resolving dependencies... (12.4s)

  SolverProblemError

  Because analytics-dbt depends on dbt (0.19.2) which depends on dbt-bigquery (0.19.2), dbt-bigquery is required.
  So, because analytics-dbt depends on dbt-bigquery (^1.0.0), version solving failed.

  at /opt/homebrew/Cellar/poetry/1.1.13/libexec/lib/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

```

**Comment by abn** [comment]
cc: @radoering

**Comment by radoering** [comment]
This is quite similar to the issue described in #4695 however not the same. The issue here is that a restricted dependency actually is kind of a hidden multiple constraint dependency that probably has to be handled as such (but isn't yet).

To stay with the concrete example a possible solution might be:

If `dbt = { version = "0.19.2", markers = "sys_platform != 'darwin'" }` would be be treated as a multiple constraint dependency with two overrides

1. not required for `darwin`
2. `0.19.2` for other platforms

#4695 would enter the game and ignore combinations that do not make sense.

I'll have a look into this if I find some time. Not sure yet how complex such a change will be.

**Comment by radoering** [comment]
I implemented the concept mentioned in https://github.com/python-poetry/poetry/issues/5506#issuecomment-1114270248 and it seems to resolve this issue. Unfortunately, it's not mergeable due to performance issues. Nevertheless, I created a (draft) PR that someone who's interested can take as a starting point or inspiration.

**Comment by anthonymichaelclark** [comment]
@radoering Thanks for sharing! I'd be keen to dig deeper and see what I can do.

**Comment by jorenham** [comment]
I have worked around this problem by creating a custom PEP503c-ompliant jax repository that can be used in a `pyproject.toml`, see: https://github.com/jorenham/jax_pep503

**Comment by pdeszynski** [comment]
I have a similar issue for markers, for e.g. having 2 packages: package1 and package2 with following `pyproject.toml` files:

```toml
[tool.poetry]
name = "package1"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10"
torch = [
    { version="^1.13.0", markers = "sys_platform == 'darwin' and platform_machine == 'arm64'", python = "<3.11" },
]
package2 = { path = "../package2" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

```toml
[tool.poetry]
name = "package2"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10"
torch = [
    { version=">=1.12.0", markers = "sys_platform == 'darwin'", python = "<3.11" },
    { version="1.12.0", markers = "sys_platform == 'linux'", python = "<3.11" },
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

when `poetry update` is invoked on MacOS machine it will trigger an error:

```
ecause package2 (0.1.0) @ file:///.../package2 depends on torch (1.12.0)
 and package1 depends on torch (^1.13.0), package2 is forbidden.
So, because package1 depends on package2 (0.1.0) @ file:///.../package2, version solving failed.
```
