### ISSUE TITLE
Namespace packages + pip VCS separated packages installation

### ISSUE THREAD

**Issue by u-hubar** [python-poetry/poetry#5513]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.
- **OS name and version**: Ubuntu 18.04.6 LTS
- **Poetry version**: 1.2.0b1 

## Question

I'm working on library with namespace packaging and possibility to be installed with pip.

Directory structure:
```
repo
├── package
│   ├── subpackage1
│   │   ├── __init__.py
│   │   └── pyproject.toml
│   ├── subpackage2
│   │   ├── __init__.py
│   │   └── pyproject.toml
│   ├── subpackage3
│   │   ├── __init__.py
│   │   └── pyproject.toml
└── pyproject.toml
```

Root pyproject.toml:
```toml
[tool.poetry]
name = "package"
version = "0.1.0"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
subpackage1 = { path = "package/subpackage1/", optional = true }
subpackage2 = { path = "package/subpackage2/", optional = true }
subpackage3 = { path = "package/subpackage3/", optional = true }

[tool.poetry.group.testing]
optional = true

[tool.poetry.group.testing.dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"

[tool.poetry.extras]
subpackage1 = ["subpackage1"]
subpackage2 = ["subpackage2"]
subpackage3 = ["subpackage3"]
testing = ["pytest", "pytest-cov"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Subpackages pyproject.toml:
```toml
[tool.poetry]
name = "subpackageX"
version = "0.1.0"
packages = [
    { include = "__init__.py" },
]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numpy = "^1.21.6"
# ...
# ...
# ...

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Result I want to achieve:
- Possibility to install separated sub-packages from VCS with pip (the main problem is that I don't know how to exclude non-chosen sub-packages)
- Add dependency group to extras (without mentioning every single dependency if it's possible?)

Example:
```bash
pip install repo[subpackage1, subpackage3]
```
Import of **subpackage2** must raise **ModuleNotFound** and dependencies for **subpackage2** must not be installed.

I've managed to handle separate dependencies installation, but I don't know how to completely separate all sub-packages. Additionally, I want to add dependency groups to extras without mentioning all of them once again, if there is such possibility.
