### ISSUE TITLE
Poetry 1.2.0, dependencies with both version and path specifications

### ISSUE THREAD

**Issue by mindstorm38** [python-poetry/poetry#5546]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I need some help with **Poetry 1.2.0b1**, not because it doesn't work, but because I don't understand why it works (compared to Poetry < 1.2).

I'm in a mono-repo architecture with one core module (portablemc v3.0.0) and many submodules, all depending on the core one. In each submodule, I used the following dependencies:
```toml
[tool.poetry.dependencies]
python = ">=3.6.2"
portablemc = "^3"
```

As expected, poetry fails to resolve portablemc version ^3 because it is not yet published, but this is the version I'm locally working on.

So I tried directory dependency:
```toml
[tool.poetry.dependencies]
python = ">=3.6.2"
portablemc = { path = "../core/", develop = false }
```

This worked! But not when building, the output version in METADATA file is a relative path, which is invalid when distributing the archive.

On my third attempt, I tried to mix this using dependency groups:
```toml
[tool.poetry.dependencies]
python = ">=3.6.2"
portablemc = "^3"

[tool.poetry.group.dev.dependencies]
portablemc = { path = "../core/", develop = false }
```

I initially planned to use `poetry install --with/--without dev` but to my surprise it worked without such arguments! By working, I mean METADATA has the correct requirement `>=3,<4` and the `poetry install` successfully add the .pth redirection to site packages.

**EDIT0**: *Note that even with `poetry install --without dev` it works, this is weird because Poetry should ignore the path dependency, and so should be forced to search for an PyPI-available package (which is not available as described for the first code block).*

I also found that in the lock file, the dependency has a custom "directory source"
```toml
[[package]]
name = "portablemc"
version = "3.0.0"
description = "[...]"
category = "main"
optional = false
python-versions = ">=3.6"
develop = false

[package.source]
type = "directory"
url = "../core"
```

So my question is simple: is it expected to work like this? If yes, the documentation must be improved to explain why (if you explain here, I can edit the documentation myself).
