### ISSUE TITLE
Enhancements to become development friendly

### ISSUE THREAD

**Issue by nishantvarma** [python-poetry/poetry#5624]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I would like to know if poetry can support some development usecases in a better way - especially for consumers who use wheels for deployment and source for development.

I would like to explain the enhancements I am looking for with the below pyproject.toml file and example scenarios:

When I do `poetry install --no-dev` it errors out with a conflict; when I make the deps as `^2.1.0` (with a caret), it installs from the source code.

Ideally, I would have expected `--no-dev` to **completely** ignore the `tool.poetry.dependencies` section as the switch says so. In scenario 1 and 2 it should have just installed 2.1.0 and 2.1.2 (the latest available as on date), respectively.

When I do with `poetry install`, it will error out if there is no caret; when there is caret, it will install Flask from source code but without dependencies (?). If I complete remove the Flask section from the `tool.dependencies`, it will install Flask some source code.

Ideally, I would have expected poetry to override the key in the `tool.poetry.dependencies` section. In scenario 1, 2 and 3 it should have just installed Flask from source code with all dependencies.

Does anyone agree with me on the above? Is this an enhancement that can be taken up? If so, I would like to look into it. This is quite similar to https://github.com/python-poetry/poetry/issues/2837, but I thought I will explain the usecase in a better way.

As a small side note, will it be possible to take a deployment environment and just activate the packages that I am interested in? This is similar to https://github.com/python-poetry/poetry/issues/34 but I am really trying to "reuse" an existing environment and convert it to development mode just like `mr.developer` does.

The real goal is to have a single `pyproject.toml` file that covers the entire development/deployment scenario and the declarative way seems to be correct. However, it doesn't execute the way I expect it to. This will also help me reuse docker images for debugging/development etc.

```toml
[tool.poetry]
name = "poetry"
version = "0.1.0"
description = "Poetry"
authors = ["Nishant Varma"]

[tool.poetry.dependencies]
python = "^3.9"
flask = "2.1.0"

[tool.poetry.dev-dependencies]
flask = { git = "https://github.com/pallets/flask.git", branch = "main", develop = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
