### ISSUE TITLE
Make poetry.masonry.api plugin-aware

### ISSUE THREAD

**Issue by mtkennerly** [python-poetry/poetry#5701]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Currently, poetry.masonry.api just re-exports some items from Poetry Core, which means they're not plugin-aware:

https://github.com/python-poetry/poetry/blob/f945937c3a01de380f70a3cbbf3bdbaa902a8c34/src/poetry/masonry/api.py

```py
from poetry.core.masonry.api import build_sdist
...

__all__ = [
    "build_sdist",
    ...
]
```

Would it be feasible to wrap these so that they support plugins? My use case is [poetry-dynamic-versioning-plugin](https://github.com/mtkennerly/poetry-dynamic-versioning), which computes a version from VCS info. However, a PEP 517-based `pip install --no-clean git+ssh://git@github.com/org/repo.git@v1.0.0-pre` won't activate the plugin, even with the following `build-system` configuration:

```toml
[build-system]
requires = ["poetry>=1.2.0b1", "poetry-dynamic-versioning-plugin"]
build-backend = "poetry.masonry.api"
```
