### ISSUE TITLE
requirements.txt  has no content after `poetry run pre-commit run --all-files`

### ISSUE THREAD

**Issue by boeto** [python-poetry/poetry#5713]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 12.4 (21F79)
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [minimal reproduction repo](https://github.com/boeto/test-poetry-pre-commit.git)

## Issue

**requirements.txt  has no content after `poetry run pre-commit run --all-files`**

### steups:

```zsh
poetry install
poetry run pre-commit install
git add  .
poetry run pre-commit run --all-files

# check result -------------------------------------------------------------------

ls
#> README.rst		pre-commit-run.log	requirements.txt	tests
#> poetry.lock		pyproject.toml		test_poetry_pre_commit

cat requirements.txt
#> ## no content

#---------------------------------------------------------------------------------
```

### config:

```yaml
# .pre-commit-config.yaml

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.0b1' #<<< Note here is the latest tag version
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
```

```toml
# pyproject.toml

[tool.poetry]
name = "test-poetry-pre-commit"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pendulum = "^2.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
