### ISSUE TITLE
Solver picks wrong version of numpy

### ISSUE THREAD

**Issue by m1kc** [python-poetry/poetry#5742]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian 11 (amd64)
- **Poetry version**: 1.1.13

## Issue

pyproject.toml:

```toml
[tool.poetry]
name = "test"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.7.3"

[tool.poetry.dev-dependencies]
pandas = "^1.1.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

`poetry update` picks the following versions of packages:

```
  • Installing six (1.16.0)
  • Installing numpy (1.22.4)
  • Installing python-dateutil (2.8.2)
  • Installing pytz (2022.1)
  • Installing pandas (1.3.5)
```

This is wrong because requested Python version is ^3.7.3 and numpy 1.22.4 requires Python >= 3.8. A correct pick would be, for example, 1.21.1.
