### ISSUE TITLE
Optional dependencies of a root package are not respected 

### ISSUE THREAD

**Issue by kfot** [python-poetry/poetry#5753]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I want to achieve the following dependency structure:
* Package A is a dependency of the Package B
* Package X is an optional dependency for Package A and Package B
* Reference and definition of Package X in `pyproject.toml` files in Package A and Package B are the same, as below:
```
[tool.poetry.dependencies]
package-x = {optional = true}
```

but...

Output of `cat poetry.lock | grep package-x` 
for Package A is as expected:
```
category = "main"
optional = true
```
while for Package B is:
```
category = "main"
optional = false
```

Is this expected behavior? I think it is not intuitive. Also, what is the right way to make the optional dependency of the Package A also and optional dependency for the Package B?

Poetry version 1.1.13

**Comment by finswimmer** [comment]
Hey @kfot,

optional dependencies must be grouped into [extras](https://python-poetry.org/docs/pyproject/#extras) to be installable.

```toml
[tool.poetry]
name = "awesome"

[tool.poetry.dependencies]
# These packages are mandatory and form the core of this package’s distribution.
mandatory = "^1.0"

# A list of all of the optional dependencies, some of which are included in the
# below `extras`. They can be opted into by apps.
psycopg2 = { version = "^2.7", optional = true }
mysqlclient = { version = "^1.3", optional = true }

[tool.poetry.extras]
mysql = ["mysqlclient"]
pgsql = ["psycopg2"]
```

```
poetry install --extras "mysql pgsql"
```

fin swimmer
