### ISSUE TITLE
`Multiple constraints dependencies` does not consider the python version

### ISSUE THREAD

**Issue by zen-xu** [python-poetry/poetry#5858]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macos
- **Poetry version**: 1.1.13

## Issue

I am developing a project which compacts with py2 and py3. But py3 depends on a package, which also depends on a package I need. So I use `multiple constraints dependencies` to specify this package. But poetry will solve failed.

This is a little confusing, let me show you an example.

Here is my external package dependency
```toml
[tool.poetry]
name = "module_a"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Here is my project dependency
```toml
[tool.poetry]
name = "my_project"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^2.7 | ^3.7"
requests = [
  {version = "^1.0", python="^2.7"},
  {version = "^2.0", python="^3.7"}
]
module_a = { path = "../module_a", python="^3.7" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

So dependencies of `my_project` should be like
```yaml
py2:
  requests: ^1.0
py3:
  requests: ^2.0
  module_a:
    requests: ^2.0
```

However, poetry thinks `requests` should depend on ^1.0, even though I have specified py2 use ^1.0 and py3 use ^2.0
