### ISSUE TITLE
Check that packages have not been tampered with

### ISSUE THREAD

**Issue by DrgnFireYellow** [python-poetry/poetry#5894]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

### The Issue
When running ```poetry install```  it should show proof that a package has not been tampered with.
### The Solution
When generating ```poetry.lock``` the hashes of each package should be stored. Then, when running ```poetry install``` in that project  a second time Poetry should check that the hashes match the ones in the lock file, otherwise Poetry will abort installation and alert you that the packages may have been tampered with.

**Comment by finswimmer** [comment]
Hello @DrgnFireYellow,

maybe I miss your point, but Poetry is already doing this, isn't it?

**pyproject.toml:**
```toml
[tool.poetry]
name = "i5894"
version = "0.1.0"
description = ""
authors = ["finswimmer <finswimmer@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tomli = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**poetry.lock with manipulated hashes:**
```toml
[[package]]
name = "tomli"
version = "2.0.1"
description = "A lil' TOML parser"
category = "main"
optional = false
python-versions = ">=3.7"

[metadata]
lock-version = "1.1"
python-versions = "^3.10"
content-hash = "d23a7501c78dfa0809e9f5134c1ae5066a6ea1e64ae81a37efd0a1d2edf972a5"

[metadata.files]
tomli = [
    {file = "tomli-2.0.1-py3-none-any.whl", hash = "sha256:839de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc"},
    {file = "tomli-2.0.1.tar.gz", hash = "sha256:de826c12914f0c550d15924c62d72abc48d6fe7364aa87328337a31007fe8a4f"},
]
```

```
$ poetry install

Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing tomli (2.0.1): Failed

  RuntimeError

  Retrieved digest for link tomli-2.0.1.tar.gz(sha256:de526c12914f0c550d15924c62d72abc48d6fe7364aa87328337a31007fe8a4f) not in poetry.lock metadata ['sha256:839de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc', 'sha256:de826c12914f0c550d15924c62d72abc48d6fe7364aa87328337a31007fe8a4f']

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/chooser.py:144 in _get_links
      140│ 
      141│             selected_links.append(link)
      142│ 
      143│         if links and not selected_links:
    → 144│             raise RuntimeError(
      145│                 f"Retrieved digest for link {link.filename}({h}) not in poetry.lock"
      146│                 f" metadata {hashes}"
      147│             )
      148│ 
```

fin swimmer
