### ISSUE TITLE
Lockfile generation hangs indefinitely when `django-cors-headers` included as dependency

### ISSUE THREAD

**Issue by johnthagen** [python-poetry/poetry#5922]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 11.6
- **Poetry version**: 1.1.13
- **Python version**: 3.9.13

## Issue

`poetry lock` will hang indefinitely when trying to resolve a project with [`django-cors-headers`](https://pypi.org/project/django-cors-headers/) as a dependency.

```toml
[tool.poetry]
name = "poetry-test"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9"
django-cors-headers = "^3.13.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

```
$ poetry lock -vvv
Using virtualenv: /Users/user/Library/Caches/pypoetry/virtualenvs/poetry-test-hz2NYSp8-py3.9
Updating dependencies
Resolving dependencies...
   1: fact: poetry-test is 0.1.0
   1: derived: poetry-test
   1: fact: poetry-test depends on django-cors-headers (^3.13.0)
   1: selecting poetry-test (0.1.0)
   1: derived: django-cors-headers (>=3.13.0,<4.0.0)

<sits frozen here forever>
```

I hunted this down after a larger project would never resolve dependencies (#2094), and narrowed it down to this single package.
