### ISSUE TITLE
Python deps not found on path after installing with Poetry (and Poetry installed with pipx)

### ISSUE THREAD

**Issue by ajhynes7** [python-poetry/poetry#5927]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Docker Python image
- **Poetry version**: 1.1.13

## Issue

I'm trying to install Python dependencies with Poetry, after installing Poetry with pipx. The problem is that the Python dependencies installed with Poetry aren't being found on the path.

Here's my demo directory structure:

```
$ tree
.
├── Dockerfile
├── foo.py
├── poetry.lock
├── poetry.toml
└── pyproject.toml
```

I'm installing flake8 as a dev dependency.

```toml
# pyproject.toml

[tool.poetry]
name = "demo"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

I've disabled Poetry's virtualenv creation.

```toml
# poetry.toml

[virtualenvs]
create = false
```

Here's a Dockerfile to provide a minimal working example:

```Dockerfile
# Dockerfile

FROM python:3.8-slim-buster

RUN pip install pipx && \
    pipx install poetry

# Put Poetry on the path.
ENV PATH=/root/.local/bin:$PATH

WORKDIR /app

COPY pyproject.toml poetry.toml poetry.lock ./
RUN poetry install --no-root

COPY . .

ENTRYPOINT []
```

The flake8 command isn't found in the Docker container.

```
❯ docker build -t demo .

❯ docker run demo flake8 --version
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "flake8": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled
```

But Poetry shows that it knows about flake8.

```
❯ docker run demo poetry show flake8
Skipping virtualenv creation, as specified in config file.
name         : flake8
version      : 4.0.1
description  : the modular source code checker: pep8 pyflakes and co

dependencies
 - mccabe >=0.6.0,<0.7.0
 - pycodestyle >=2.8.0,<2.9.0
 - pyflakes >=2.4.0,<2.5.0
```

Running flake8 with `poetry run` works.

```
❯ docker run demo poetry run flake8 --version
Skipping virtualenv creation, as specified in config file.
4.0.1 (mccabe: 0.6.1, pycodestyle: 2.8.0, pyflakes: 2.4.0) CPython 3.8.13 on
Linux
```

But I thought that `poetry run` wasn't required if you disabled Poetry's virtualenv feature.
