### ISSUE TITLE
Poetry is not using Dulwich to read the global git config (particularly the insteadOf option)

### ISSUE THREAD

**Issue by fredrikaverpil** [python-poetry/poetry#5934]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version (master branch)
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: GitHub Actions
- **Poetry version**: master branch

## Issue

:warning: please note that this functionality works fine with Poetry 1.1.13 but is now unsupported in the pre-1.2 master branch  (unless configuring poetry@master to [use the system's git client](https://python-poetry.org/docs/master/configuration/#experimentalsystem-git-client)).

It doesn't seem like poetry is using Dulwich to read the global git config. Should it not do this?
I'm using Poetry in GitHub Actions with private repos and would like to rely on rewriting URLs with `insteadOf`:

```yaml
git config --global --replace-all url.https://github.com/.insteadOf ssh://git@github.com/
git config --global --add url.https://github.com/.insteadOf git@github.com:
```

Dulwich recently added support for rewriting URLs :tada: (PR [here](https://github.com/jelmer/dulwich/pull/982)) this - but this is not picked up by poetry.

I initially raised this with the Dulwich maintainers in https://github.com/jelmer/dulwich/issues/983 but they concluded the issue seems to reside with Poetry.

What is the intent here...?

- Should Poetry use Dulwich to read the global (and the repo's?) git config?
- What is the way forward to make Poetry read the global git config, and the insteadOf option in particular?

Cc @neersighted (as we chatted briefly about this [in discord](https://discord.com/channels/487711540787675139/487711540787675143/989529490449375322))

**Comment by jelmer** [comment]
To mimick the behaviour of C Git, poetry probably wants to call ``Repo.get_config_stack()``, which would read both $REPO/.git/config and ~/.gitconfig

**Comment by dimbleby** [comment]
Oh I see we have crossing updates and I imagine @jelmer is more likely to be right!

**Comment by dimbleby** [comment]
Your implicit proposed fix seems reasonable to me, @fredrikaverpil perhaps you'd like to tests and if all is well put together an MR

```diff
-        client, path = get_transport_and_path(url, **kwargs)
+        config = local.get_config_stack()
+        client, path = get_transport_and_path(url, config=config, **kwargs)
```

**Comment by fredrikaverpil** [comment]
@dimbleby @jelmer @neersighted this works for my use case. 👍 

This is the GHA workflow I used to test this:

```
name: poetry

# this workflow is only for manual / testing to ease the pain when trying to identify
# the outdated dependencies, and how production vs developer dependencies are affected.

on:
  workflow_dispatch:
  
  # temporarily enable this to run as part of the PR, so to verify that "poetry install" completes
  pull_request:

env:
  PYTHON_VERSION: "3.10"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      # REDACTED - custom checkout action

      # REDACTED - custom git config setup

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: fredrikaverpil/setup-pipx@v1.5

      # https://github.com/python-poetry/poetry/pull/5935
      - run: pipx install git+https://github.com/python-poetry/poetry.git@refs/pull/5935/head

      - run: pipx runpip poetry install -U git+https://github.com/jelmer/dulwich.git@master

      - run: poetry install
```
