### ISSUE TITLE
AssertionError when adding a package with same name as project

### ISSUE THREAD

**Issue by Ierezell** [python-poetry/poetry#5954]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:Linux 5.18.7-arch1-1
- **Poetry version**:  1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
```toml
[tool.poetry]
name = "ASuperPackage"
version = "0.1.0"
description = ""
authors = [""]
 
[tool.poetry.dependencies]
python = "~3.9"
 
[tool.poetry.dev-dependencies]
 
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
```bash
poetry add ASuperPackage # like sagemaker (pip) vs sagemaker (the name of my poetry project)
```
## Issue
The error is only an `AssertionError` which does not says why the `add` is failing. 
After banging my head on the wall, I found out that my poetry project name was the same of the pip package I wanted to install (in my case `sagemaker`) 

I don't know how we could solve that, maybe a more descriptive error ? A version check of the packages (sagemaker is 2.97.0, my package 0.1.0) ?

Thanks in advance, 
Have a great day.
