### ISSUE TITLE
No warning when extra dependency of a package does not follow current python version

### ISSUE THREAD

**Issue by vmgustavo** [python-poetry/poetry#6000]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.4 LTS
- **Poetry version**: package poetry 1.1.13, Python 3.8.5

## Issue
A package with extra dependencies but there is one specific dependency that requires a Python version

```toml
[tool.poetry]
name = "pkg"
version = "0.1.0"

[tool.poetry.dependencies]
# mandatory
python = ">=3.7<3.10"
# optional
pyspark = {version = "3.1.2", optional = true, python = "<=3.7.12"}

[tool.poetry.extras]
spark = ["pyspark"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

If I try to install this in an environment with a different version of Python (3.8.5 or 3.9.10):

```bash
poetry build
poetry add pkg-0.1.0-py3-none-any.whl -E spark
```

It simply install the package without the extra dependency and finishes the installation successfully.

If I try to install thisin an environment with Python 3.7.12 it installs `pkg` and its extra dependency.

The behavior of poetry in this situation is confusing, I created a testing environment with 3 different python versions trying to install the same package with the command `poetry add pkg-0.1.0-py3-none-any.whl -E spark`

* Dependency: `pyspark = {version = "3.1.2", optional = true, python = "<=3.7.12"}`
  * `python-3.7.12`: installs `pkg` and `pyspark`
  * `python-3.8.5`: installs `pkg` only with no message about `pyspark`
  * `python-3.9.10`: installs `pkg` only with no message about `pyspark`
* Dependency: `pyspark = {version = "3.1.2", optional = true, python = ">=3.7<3.8"}`
  * `python-3.7.12`: installs `pkg` and `pyspark`
  * `python-3.8.5`: installs `pkg` and `pyspark`
  * `python-3.9.10`: fails to add `pkg` with apparently uncorrelated error that I couldn't find a way to fix (EOFError: Compressed file ended before the end-of-stream marker was reached)
* Dependency: `pyspark = {version = "3.1.2", optional = true, python = "~3.7"}`
  * `python-3.7.12`: installs `pkg` and `pyspark`
  * `python-3.8.5`: installs `pkg` only with no message about `pyspark`
  * `python-3.9.10`: installs `pkg` only with no message about `pyspark`

**Shouldn't the "installs `pkg` only with not warning about `pyspark`" end result be actually an error during installation of the package?**
