### ISSUE TITLE
poetry run does not support --src or other project structures

### ISSUE THREAD

**Issue by cpterry** [python-poetry/poetry#6029]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/cpterry/0061b55fd13a16430c9250c4dd7ee05b

## Issue

`poetry run` does not support the structure of  `poetry new --src` or other project structures. It does not check the `packages` values. You can work around the issue by adding `src` but then installing the script after running `poetry build` will fail looking for the missing `src` folder.

So this works for `poetry build` but not `poetry run`:

```toml
packages = [
    { include = "example", from = "src" }
]

[tool.poetry.scripts]
myapp = "example:hello"
```

This works for `poetry run` but not `poetry build`:

```toml
packages = [
    { include = "example", from = "src" }
]

[tool.poetry.scripts]
myapp = "src.example:hello"
```
