### ISSUE TITLE
Is it possible to install poetry from master with poetry-core from git main branch?

### ISSUE THREAD

**Issue by 10ourto** [python-poetry/poetry#6106]
We could install  `curl -sSL https://install.python-poetry.org | python3 - --git https://github.com/python-poetry/poetry.git@master` poetry from master branch like that. But it uses pinned version of `poetry-core = "^1.1.0b3"`. I need latest fix from main branch in poetry-core. Is it possible at all?

**Comment by ashnair1** [comment]
You can use the latest version of `poetry-core` by specifying the following in your `pyproject.toml`
```toml
[build-system]
requires = ["poetry-core @ git+https://github.com/python-poetry/poetry-core.git"]
build-backend = "poetry.core.masonry.api"
```
