### ISSUE TITLE
Add key to allow fetching submodules for git repos

### ISSUE THREAD

**Issue by bryanforbes** [python-poetry/poetry#611]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Currently, git dependencies do not fetch submodules. This makes dependencies like `mypy` unusable when installing it from git. I don't think fetching submodules should be the default behavior, but it would be nice if git dependencies had the option to fetch them. For instance:

```toml
[tool.poetry.dependencies]
# Submodules would not be fetched for sqlalchemy-stubs
sqlalchemy-stubs = {rev = "8b45fc4345778e3f08e8a3b53ff71aaaa775e632", git = "https://github.com/dropbox/sqlalchemy-stubs.git"}

[tool.poetry.dev-dependencies]
# Submodules would be fetched for mypy because of submodules = true
mypy = {rev = "47c25263694bae2a577c15d70d2988db2e8e8584", git = "https://github.com/python/mypy.git", submodules = true}
```
