### ISSUE TITLE
Specifying a rev released version in pre-commit-config.yaml

### ISSUE THREAD

**Issue by dwsmith1983** [python-poetry/poetry#6174]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Poetry version**: 

## Issue

When using `pre-commit-config.yaml`, only "master" rev is accepted.
```
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "master"
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
```
If I try specifying a version, I get the following
```
[INFO] Initializing environment for https://github.com/python-poetry/poetry.
An error has occurred: InvalidManifestError: 
```

I have tried passing with and without quotes the following as well as string and with v or no v:

- 1.1
- v1.1
- "1.1"
- 1.1.14
- 1.1.13
and so on. How can we specify a released version?
