### ISSUE TITLE
Poetry fails in creating venv

### ISSUE THREAD

**Issue by Enforcer007** [python-poetry/poetry#6189]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Ubuntu 22.04
- **Poetry version**: 1.1.14
- **pyproject.toml**: 
```toml
[tool.poetry]
name = "d"
version = "0.1.0"
description = ""
authors = ["enforcer007 <akhilgodvsdemon@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue

poetry creates broken venv and the python path version is shown as 2.7.18 when python3 is at 3.10

A blank project is created by `poetry new d` with above pyproject.toml file. Below is the result of `poetry env info`
![image](https://user-images.githubusercontent.com/6951100/185387527-95622b7f-e48b-4531-bdcb-2d3040ee0c93.png)

But venv will break after I run `poetry lock`. Below is the result after creating `poetry.lock` file.
![image](https://user-images.githubusercontent.com/6951100/185388002-efe063f3-404a-427a-8afd-1d737aad6a66.png)

`poetry install` fails with below errors:
![image](https://user-images.githubusercontent.com/6951100/185388217-222b0bc0-bc70-48fc-a0a3-e39d05d6bf5f.png)
