### ISSUE TITLE
Regression in namespace package metadata on poetry-core 1.1.0rc1

### ISSUE THREAD

**Issue by ariebovenberg** [python-poetry/poetry#6198]
- [x] ~~I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.~~ n/a
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] ~~If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).~~ n/a

- **OS version and name**: MacOS 12.5.1
- **Poetry version**: poetry-core 1.1.0rc1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: see below

## Issue

An addition in `poetry-core` between 1.1.0a7 and 1.1.0b1 introduced a bug in package metadata name for namespaced packages:

```python
>>> from importlib import metadata
>>> metadata('mynamespace.foomodule')
importlib.metadata.PackageNotFoundError: mynamespace.foomodule
```

The package is instead registered as `mynamespace-foomodule`. This is a particular problem since `importlib.metadata` is the canonical way to single-source the `__version__`

This bug occurs on Python 3.8 and 3.9 (but not 3.10 insterestingly enough). The change that introduced the bug: https://github.com/python-poetry/poetry-core/pull/328/. Ever since this change, `.` is normalized to `-` in package names, which is incorrect for namespace packages. 

### `pyproject.toml`
```toml
[tool.poetry]
name = "mynamespace.foomodule"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [
    { include = "mynamespace"},
]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core==1.1.0rc1"]
build-backend = "poetry.core.masonry.api"
```

### files

```
mynamespace/
├── __init__.py  # contains: __path__ = __import__('pkgutil').extend_path(__path__, __name__)
└── foomodule
    └── __init__.py  # empty
```

### Then, run:

```bash
# make sure you're on python 3.8 or 3.9
pip install .
# this raises an error, but shouldn't
python -c "from importlib import metadata; metadata.version('mynamespace.foomodule')"
```

## What to do?

I don't mind submitting a fix in `poetry-core`, but I'm of course missing a lot of context on why the change was made in the first place.
