### ISSUE TITLE
(🐞) `poetry export --extras ` is inconsistent with other commands

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#6240]
<!--
  Hi there! Thank you for discovering and submitting an issue.

  Before you submit this; let's make sure of a few things.
  Please make sure the following boxes are ticked if they are correct.
  If not, please try and fulfill these first.
-->

<!-- Checked checkbox should look like this: [x] -->
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

<!--
  Once those are done, if you're able to fill in the following list with your information,
  it'd be very helpful to whoever handles the issue.
-->

- **OS version and name**: <!-- Replace with version + name --> Windows 10
- **Poetry version**: <!-- Replace with version --> 1.2.0rc1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: <!-- Gist Link Here -->
```toml
[tool.poetry]
name = "test"
version = "1"
description = ""
authors = []

[tool.poetry.extras]
a = ["urllib3"]
b = ["tomli"]

[tool.poetry.dependencies]
python = "^3.10"
urllib3 = { version ="*", optional=true}
tomli  = { version ="*", optional=true}

```

## Issue
<!-- Now feel free to write your issue, but please be descriptive! Thanks again 🙌 ❤️ -->
```
👉 poetry install
Installing dependencies from lock file

No dependencies to install or update      
👉 poetry install --extras "a b"
Installing dependencies from lock file

Package operations: 2 installs, 0 updates, 0 removals

  • Installing tomli (2.0.1)
  • Installing urllib3 (1.26.12)                                                                                                                                                                                          
👉 poetry export --extras "a b"
                                                                                                                                                                                                                          14:19:47  
👉
