### ISSUE TITLE
(🐞) Unable to install pyrfc with poetry 1.2

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#6261]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Ubuntu 22.04
- **Poetry version**:  1.1.15 / 1.2.0rc2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
```toml
[tool.poetry]
name = "test"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
Cython = "*"
pyrfc = "*"
```
## Issue

Sorry, I really have no idea whats going on here, it installs fine with 1.1.15 and with pip, but when I use poetry 1.2 it fails.
```
👉 poetry@1.1.15 install
success

👉 poetry@1.2.0rc2 install
...
        Cython not installed: https://cython.readthedocs.io/en/latest/src/quickstart/install.html
...
```

Here is the relevant part of the pyrfc's [setup.py](https://github.com/SAP/PyRFC/blob/main/setup.py)
```py
    install_requires=["setuptools"],
    setup_requires=[
        "setuptools-git",
        "cython; platform_system != 'Windows'"
    ],
```
