### ISSUE TITLE
`poetry update` behaves differently on 1.2.0 compared to 1.13.0

### ISSUE THREAD

**Issue by elliotdes** [python-poetry/poetry#6328]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Monterey 12.3, M1
- **Poetry version**: 1.2.0

## Issue

I updated my personal machine to 1.2.0. My CI/CD pipeline still uses 1.13.0 and is running on a `python:3.10-slim` docker container.

I ran `poetry update dparse` on my local machine, with version 1.2.0. When running tmy CI/CD (Poetry 1.13.0), `poetry run bandit application/ -r -c "pyproject.toml"` fails citing:

```shell
ModuleNotFoundError: No module named 'pkg_resources'
```

However, after downgrading my personal machine to poetry 1.13.0 and running `poetry update dparse`(after reverting the previous changes), the CI/CD passes without error.

Any reasons for this behaviour?

**Comment by neersighted** [comment]
This is impossible to reproduce without a `pyproject.toml`, and preferably a container-based reproduction. However, this sounds like your project depended on `pkg_resources`/setuptools and was relying on 1.1's behavior of implicitly including setuptools.

**Comment by roniemartinez** [comment]
We had the same issue but it's always the same `poetry` version in Dockerfile (image is `python:3.10`).

> was relying on 1.1's behavior of implicitly including setuptools

I don't think this behavior was changed or even documented somewhere in 1.2 release. `no-setuptools` was introduced but it means disabling it so I think this behavior is still "implicit" in 1.2: https://python-poetry.org/blog/announcing-poetry-1.2.0/#virtualenvsoptionsno-setuptools

The weird thing that we observed is changing `pip` to `pip3` when doing `pip install -U poetry setuptools` fixed it for us. We also think this could be related to Python 3.10.6 image update.

**Comment by roniemartinez** [comment]
UPDATE: Downgrading python from `python:3.10` (which installs 3.10.6) to `python:3.10.5` also fixed it for us. Poetry 1.2 version probably has issues with 3.10.6

**Comment by neersighted** [comment]
There's still no reproduction here, and the additional context makes this more confusing...

When I refer to implicit inclusion of setuptools, I mean Poetry would basically ignore it in the environment unless it was explicitly configured in pyproject.toml, whereas 1.2 will record it to the lockfile/not special case it. It's a small line item in the changelog that doesn't affect most projects with well-defined dependencies, but some may get tripped up by implicit coupling they did not realize was there.

Anyway, a Dockerfile or reproduction log is still needed to debug this -- if anyone turns one up please post it!

**Comment by msf-dev** [comment]
I also encountered this after upgrading to 1.2.0 on both my development and production machines. For me, simply running `poetry add setuptools` fixed the issue - but I don't quite know why the exception wouldn't have been thrown prior to 1.2.0 if Poetry would _"ignore it in the environment"_. 


  <details>
    <summary>Dependencies in pyproject.toml</summary>
  
  ```toml
  [tool.poetry.dependencies]
  python = "~3.9"
  django = "~4.0.7"
  django-crispy-forms = "^1.14.0"
  numpy = "^1.23.2"
  pandas = "^1.4.4"
  django-constance = "^2.9.1"
  django-dbbackup = "^4.0.1"
  django-extra-views = "^0.14.0"
  django-extensions = "^3.1.3"
  django-import-export = "^2.5.0"
  django-anymail = {extras = ["mailgun"], version = "^8.6"}
  django-filter = "^22.1"
  django-widget-tweaks = "^1.4.12"
  django-simple-history = "^3.0.0"
  django-tinymce = "^3.5.0"
  django-notifications-hq = "^1.6.0"
  django-storages = {extras = ["boto3"], version = "^1.11.1"}
  django-picklefield = "^3.1"
  weasyprint = "^56.1"
  mysqlclient = "^2.1.1"
  django-htmx = "^1.12.2"
  toml = "^0.10.2"
  django-environ = "^0.9.0"
  django-entangled = "^0.5.1"
  django-admin-rangefilter = "^0.8.8"
  setuptools = "^65.3.0"                        # after adding this both machines worked as they did before
  
  [tool.poetry.group.dev.dependencies]
  django-debug-toolbar = "^3.6.0"
  
  [tool.poetry.group.test.dependencies]
  freezegun = "^1.2.2"
  coverage = "^6.4.4"
  isort = "^5.9.3"
  black = "^22.8.0"
  pre-commit = "^2.14.0"
  tblib = "^1.7.0"
  pytest = "^7.1.3"
  pytest-django = "^4.4.0"
  pytest-xdist = {extras = ["psutil"], version = "^2.4.0"}
  flake8 = "^5.0.4"
  djlint = "^1.12.1"
  ```

  </details>

- **development machine**
  - Poetry: 1.2.0 (previously 1.0.7)
  - Python: 3.9.5
  - OS: macOS Monterey 12.5 | Macbook Pro (16-inch, 2019)

- **production machine**
  - Poetry: 1.2.0 (previously 1.12.0)
  - Python: 3.9.5
  - OS: Linux - Ubuntu 20.04.2 LTS
