### ISSUE TITLE
poetry 1.2.0 doesn't write direct_url.json anymore

### ISSUE THREAD

**Issue by konstin** [python-poetry/poetry#6356]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I have a test that diffs against the virtualenv installation created by poetry and found that unlike 1.1.13, the new 1.2.0 doesn't write `direct_url.json` anymore. Is this a design choice or an oversight in the new version? I haven't found anything in the release notes or any pull request about this.

**Comment by neersighted** [comment]
I'm not sure we intend to write a `direct_url.json` for repository packages (see the spec and [pip's behavior](https://peps.python.org/pep-0610/#example-pip-commands-and-their-effect-on-direct-url-json)). Can you provide a specific `pyproject.toml` with packages you expect to receive a `direct_url.json` called out?

**Comment by konstin** [comment]
This happened with a really simple test case:

```toml
[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.2"
pandas = "^1.4.0"
matplotlib = "^3.5.1"
```

But if this an intentional change this perfectly fine! I was mostly confused by not finding anything in the changelog

**Comment by neersighted** [comment]
I don't think it was a change? If we ever wrote `direct_url.json` for repository-sourced deps, it was likely a transient bug in a beta.

**Comment by konstin** [comment]
It changed from 1.1.13 to 1.2.0 (both installed with pipx) for a basic `numpy = "^1.23.2"`:

```toml
[tool.poetry]
name = "a"
version = "0.1.0"
description = ""
authors = ["konstin <konstin@mailbox.org>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.23.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

```
home ~/a ⊤  poetry@1.1.13 install
Creating virtualenv a in /home/konsti/a/.venv
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing numpy (1.23.2) 
home ~/a ⊤  ls .venv/lib/python3.8/site-packages/numpy-1.23.2.dist-info/
direct_url.json  entry_points.txt  INSTALLER  LICENSES_bundled.txt  LICENSE.txt  METADATA  RECORD  REQUESTED  top_level.txt  WHEEL
home ~/a ⊤  rm -rf .venv/
home ~/a ⊤  poetry@1.2.0 install
Creating virtualenv a in /home/konsti/a/.venv
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing numpy (1.23.2)
home ~/a ⊤  ls .venv/lib/python3.8/site-packages/numpy-1.23.2.dist-info/
entry_points.txt  INSTALLER  LICENSES_bundled.txt  LICENSE.txt  METADATA  RECORD  REQUESTED  top_level.txt  WHEEL
```
