### ISSUE TITLE
`poetry lock` (no `poetry.lock`) pins different versions than `poetry update`

### ISSUE THREAD

**Issue by JacobHayes** [python-poetry/poetry#6470]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Monterey
- **Poetry version**: Poetry (version 1.2.0)
- **Contents of your pyproject.toml file**:
<details>
<summary>pyproject.toml</summary>

```toml
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "debug-lock"
version = "0.1.0"
description = ""
authors = ["Jacob Hayes <jacob.r.hayes@gmail.com>"]
readme = "README.md"
packages = [{include = "debug_lock"}]

[tool.poetry.dependencies]
coiled = "*"
python = "^3.9"

[tool.poetry.group.dev.dependencies]
dask-labextension = "*"
jupyter = "*"
jupyterlab = "*"
```

</details>

## Issue

With some sets of dependencies `poetry lock` and `poetry update` result in different `poetry.lock` files with vastly different versions. Running `poetry lock` without a `poetry.lock` will pin some version (eg: `coiled==0.0.56`), then an immediate `poetry update` will pick different versions (eg: `coiled==0.2.27`), and then a subsequent `poetry lock` will pin the old version again (eg: `coiled==0.0.56`).

With the pyproject embedded above, I can reproduce this with:
<details>
<summary>Test script</summary>

```bash
#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

rm poetry.lock
poetry lock
grep -U1 'name = "coiled"' poetry.lock
poetry update
grep -U1 'name = "coiled"' poetry.lock
poetry lock
grep -U1 'name = "coiled"' poetry.lock
```

</details>

```
$ rm poetry.lock
$ poetry lock
Updating dependencies
Resolving dependencies... (6.2s)

Writing lock file
$ grep -U1 'name = "coiled"' poetry.lock
[[package]]
name = "coiled"
version = "0.0.56"
$ poetry update
Updating dependencies
Resolving dependencies... (3.8s)

Writing lock file

No dependencies to install or update
$ grep -U1 'name = "coiled"' poetry.lock
[[package]]
name = "coiled"
version = "0.2.27"
$ poetry lock
Updating dependencies
Resolving dependencies... (6.2s)

Writing lock file
$ grep -U1 'name = "coiled"' poetry.lock
[[package]]
name = "coiled"
version = "0.0.56"
```

I know I can set explicit version ranges in my `pyproject.toml`, but the instability also causes issues when different team members update deps with `poetry lock` vs `poetry update`. Additionally, the `lock` [docs say](https://python-poetry.org/docs/cli/#lock):
> By default, this will lock all dependencies to the latest available compatible versions.

but this must not be true if a `poetry update` gives _newer_ packages without erroring about any incompatibilities.
