### ISSUE TITLE
poetry doesn't include package in pyproject.toml packages

### ISSUE THREAD

**Issue by RalfKow** [python-poetry/poetry#6511]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

#### Environement
- **OS version and name**: Windows 10
- **Poetry version**: Poetry 1.2.0
- **Python**:3.8.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: See the pyproject.toml below

## Issue
If I run the command

1. ```poetry install```
3. ```poetry run python src/eap_sample_pipeline/main.py -feed greeter```

poetry run python src/eap_sample_pipeline/main.py -feed greeter
Traceback (most recent call last):
  File "src/sample_pipeline/main.py", line 4, in <module>
    from sample_pipeline import feed_selector
ImportError: cannot import name 'feed_selector' from 'sample_pipeline' (C:\..\sample-pipeline\tests\sample_pipeline\__init__.py)

## pyproject.toml
```toml
[tool.poetry]
name = "sample-pipeline"
version = "0.0.0" # Version is ignored and set by jenkins. Use pipeline to increase.
description = "Example project for Python"
packages = [
    {include = "sample_pipeline", from = "src"},
    {include = "snowpark_utils", from = "src"},
    {include = "test_cases", from = "tests"}] #TODO: Try to get rid of include local packages
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8.*"
numpy = "^1.22.4"                                   # NumPy is the fundamental package for array computing with Python.
pandas = "1.4.4"                                    # Pandas is a data analysis and manipulation tool.
snowflake-snowpark-python = "0.9.0"                 # The Snowpark library provides intuitive APIs for querying and processing data.

[tool.poetry.dev-dependencies]
black = "^22.3.0"                                   # The uncompromising code formatter.
coverage = {extras = ["toml"], version = "^6.4.1"}  # Code coverage measurement for Python
unittest-xml-reporting = "^3.2.0"                   # unittest-based test runner with Ant/JUnit like XML reporting.
pre-commit = "^2.19.0"                              # A framework for managing and maintaining multi-language pre-commit hooks.
pre-commit-hooks = "^4.2.0"                         # Some out-of-the-box hooks for pre-commit.
pydocstyle = "^6.1.1"                               # Python docstring style checker
pylint = "^2.14.1"                                  # python code static checker
reorder-python-imports = "^3.1.0"                   # Tool for reordering python imports

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.main]
fail-on = "F,E,W"
fail-under = 0.0

[tool.pylint.basic]
good-names = ["i", "j", "k", "n", "s", "d", "ex", "Run", "_", "pk", "x", "y", "df"]

[tool.pylint.format]
max-line-length = 140

[tool.pylint.design]
max-args = 8

[tool.pylint.messages_control]
disable = [
    # pydocstyle takes care of this...
    "missing-module-docstring",
    "missing-function-docstring",
    "missing-class-docstring",
    
    # don't hinder me creating small classes!
    "too-few-public-methods",
    
    # reorder-python-imports should know what it's doing
    "wrong-import-order",

    # can't do much about duplicate imports in two files, I'm afraid...
    "duplicate-code",
]

[tool.pylint.miscellaneous]
notes = []  # don't warn about `TODO` and `FIXME` comments

[tool.pylint.reports]
output-format = "parseable:pylintout,text"

[tool.pydocstyle]
match-dir = "[^\\.][^test].*"
convention = "google"

[tool.coverage.run]
command_line = "-m xmlrunner discover --output-file junittest.xml"
```
