### ISSUE TITLE
poetry install fails when directories for dependencies outside of specified dependency group do not exist

### ISSUE THREAD

**Issue by tobgu** [python-poetry/poetry#6515]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 12.5.1
- **Poetry version**: 1.2.0

## Issue
I want to use dependency groups to group my dependencies into local (libraries located in the same file system as the project using them) and remote (eg. packages found on PyPI).

The main reason for doing this would be to allow me to install external packages early during docker builds and then, at a later stage copy in the local dependencies and install those. This would avoid having to re-install every external package when local packages are updated since the the docker image layer with the external packages could be reused between builds.

This does not work the way I was hoping though. Given the minimal `pyproject.toml` below:
```toml
[tool.poetry]
name = "foo"
version = "0.1.0"
description = ""
authors = ["Tobias Gustafsson <abc@xyz.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.local.dependencies]
bar = {path = "../../libs/bar", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

I get the following behaviour:
```sh
$ poetry install --only main
Directory ../../libs/bar does not exist
```
It is true that the directory does not exist (at this stage), but I would not have expected poetry to care about it since `bar` is not part of the dependency group that was to be installed. Is there a good reason for this?
