### ISSUE TITLE
Poetry fails to install `async-hvac` from PyPi

### ISSUE THREAD

**Issue by mikeymop** [python-poetry/poetry#6518]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Macos 12.5
- **Poetry version**: `1.2.0`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
I cannot share my pyproject.toml verbatim, however here is the gist of what is in my `pyproject.toml`:

```toml
[tool.poetry]
name = "python-service"
version = "0.1.0"
description = ""
authors = <redacted>

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.75.0"
aiobotocore = "^2.2.0"
python-multipart = "^0.0.5"
uvicorn = "^0.18.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "python-service.main:start"

```

## Issue
When attempting to install `async-hvac` the pip subprocess fails with the following:
```
 Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [1 lines of output]
        /var/folders/lg/thktdcw95fsg1xlk024vkll0dz_2b9/T/version is missing
        [end of output]
  PoetryException

  Failed to install /Users/$USER/Library/Caches/pypoetry/artifacts/94/7b/b9/b52af174636e4237922d593ee9d1327e2b6635c4d24048bc9bfc28c91b/async-hvac-0.6.1.tar.gz

  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/utils/pip.py:51 in pip_install
       47│
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       52│
```
