### ISSUE TITLE
self commands including 'add <plugin>' should facilitate using an index URL

### ISSUE THREAD

**Issue by colindean** [python-poetry/poetry#6705]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

I'm preparing for the eventuality of the export plugin not being installed by default. When running `poetry self add poetry-plugin-export`, I noticed that the files were being downloaded from pythonhosted.org instead of my company's repos. I'd prefer that poetry retrieve artifacts from my company's internal repos.

### Expectation

⭐ ⭐ ⭐ ⭐ ⭐  = A command line option would be great:

    poetry self add poetry-plugin-export --index-url https://example.com/proxies/pypi/simple

⭐ ⭐ ⭐ ⭐  = But I could also see this being a one-time setup thing:

    poetry self config pip.global.index-url https://example.com/proxies/pypi/simple

⭐ ⭐ ⭐  = but this _probably_ works for now until something nicer exists:

    ${POETRY_HOME}/bin/pip3 config --site set global.index-url https://example.com/proxies/pypi/simple

But I don't have a good way for `poetry` to tell me its venv path for scripting, e.g. something like

    POETRY_HOME=$(poetry self venv)

or to run something in poetry's venv with a command like

    poetry self run pip config …

### Related:

* https://github.com/python-poetry/poetry/pull/4944
* https://github.com/python-poetry/poetry/issues/6529

**Comment by neersighted** [comment]
Keep in mind that `pip` is an implementation detail that we are slowly removing from the codebase, so any attempt to support this cannot couple to any details of pip directly.

I think in general the aim is going to be allowing plugins to be installed outside the main Poetry environment (e.g. somehow have a `required-plugins` section in pyproject.toml) and make them use the sources configured there. But some facilities to manage sources for the global/instance pyproject.toml certainly wouldn't hurt either.

**Comment by colindean** [comment]
> allowing plugins to be installed outside the main Poetry environment (e.g. somehow have a required-plugins section in pyproject.toml

This is _definitely_ the more desirable solution for me. I think we discussed this on Discord a while back!

Maybe this invocation would adequately hide pip:

    poetry self config plugins.index-url https://example.com/proxies/pypi/simple

but definitely having a `tool.poetry.plugins` that accepts dependency specs like `tool.poetry.dependencies` would be great.

**Comment by neersighted** [comment]
I don't think your last suggestion is sufficiently abstracted either -- we simply don't have infrastructure for a re-implementation of `index-url` in Poetry (even now, we actually download packages for pip with our own logic and only use pip to install files from disk), so what you really want is full-resolution source config like any other `pyproject.toml`.

I actually think that it may even be supported already if you manually edit the file -- but some sort of facility to surface and discover this is still needed.

**Comment by colindean** [comment]
I tested and can confirm that adding the source to the poetry-instance pyproject.toml correctly shifts poetry to using the proxy.

```toml
# $ cat /Users/colin/Library/Application\ Support/pypoetry/pyproject.toml 
[tool.poetry]
name = "poetry-instance"
version = "1.2.1"
description = ""
authors = []
license = ""
[tool.poetry.dependencies]
python = "3.9.11"
poetry = "1.2.1"
[[tool.poetry.source]]
name = "pypi-mirror"
url = "https://stuff.example.com/artifactory/api/pypi/pypi-remote/simple"
default = true
[tool.poetry.group.additional.dependencies]
poetry-plugin-export = "^1.1.1"
```

The plugins are then retrieved as I'd expect when running `poetry self add <plugin>`.

Maybe the `self` command hierarchy could get its own `source add|show|remove` subcommands.
