### ISSUE TITLE
Removal of `master` branch in `poetry-core` on June 1, 2023

### ISSUE THREAD

**Issue by mkniewallner** [python-poetry/poetry#6741]
The main branch of [poetry-core](https://github.com/python-poetry/poetry-core) was renamed from `master` to `main` in [May 2022](https://github.com/python-poetry/poetry-core/commit/79333f7318a5ddcc26d1056a7bc8649f125c28a1). Since this broke some packages explicitly referencing `master`, it was decided to copy the `main` branch into `master` branch to not break those usages.

As `master` is [not updated](https://github.com/python-poetry/poetry-core/tree/master) from `main`, and it is confusing to keep both branches around, there's no point keeping `master` indefinitely.

So this issue acts as a deprecation notice for usages of `master` branch of `poetry-core`, as we are planning to delete the branch on **June 1, 2023**.

This change will impact packages that use git references when defining `poetry-core` as a build-system, for instance by doing:
```toml
[build-system]
requires = ["poetry-core @ git+https://github.com/python-poetry/poetry-core.git@master"]
build-backend = "poetry.core.masonry.api"
```

Once `master` branch is removed, any package still referencing `master` branch as their build system will **not be installable**. Note that using a moving git branch for the build system on published packages is a highly discouraged practice, since:
- update to branches could break usages at any moment, as they represent a development version of the project, and not official releases
- branches are not immutable, and can be deleted in git

If you are a package maintainer and are referencing `poetry-core` by using `master` branch from the git repository (or any other branch, for what it's worth), it is highly recommended to update the build system of the package to rely on versions published to PyPI, for instance:
```toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
