### ISSUE TITLE
poetry tries to reinstall from git, even if it's already installed

### ISSUE THREAD

**Issue by itajaja** [python-poetry/poetry#691]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: MacOS, but also docker (ubuntu)
- **Poetry version**:0.12.10

## Issue

to reproduce, use the following pyproject:

```toml
[tool.poetry]
name = "test"
version = "0.0.0"
authors = ["buh"]

[tool.poetry.dependencies]
python = "^3.6"
Tqp = { git = "git://github.com/4Catalyzer/tqp.git", tag="v0.1.5" }
```

run `poetry install`, disable wifi, run `poetry install` again. the second time it will complain because

```
[CalledProcessError]
Command '['git', 'clone', 'ssh://git@github.com/4Catalyzer/tqp.git', '/var/folders/b2/4b21t4_90pg6rwkbpgdr_l540000gn/T/pypoetry-git-tqpq4geocan']' returned non-zero exit status 128.
```

this segment of the lockfile:

```toml
[metadata.hashes]
boto3 = ["0a0c0f0859a2be56b23823f8c1d50abf3c89d7d4d054019f24de69eeee9ad75c", "b429d48b8e99a9fdd18c3aef68370f779e0aa76cfe275a55e1adff427d44ca9a"]
botocore = ["6b9edd1e18436bce8b28b95b3dec582588080a90b5636abc1b3a795f5a0e6cf3", "9dac7753d81e8a725b9a169fd63b43d2a3caeceb51de3fafd5e5bd10e25589cb"]
docutils = ["02aec4bd92ab067f6ff27a38a38a41173bf01bed8f89157768c1573f53e474a6", "51e64ef2ebfb29cae1faa133b3710143496eca21c530f3f71424d77687764274", "7a4bd47eaf6596e1295ecb11361139febe29b084a87bf005bf899f9a42edc3c6"]
jmespath = ["6a81d4c9aa62caf061cb517b4d9ad1dd300374cd4706997aff9cd6aedd61fc64", "f11b4461f425740a1d908e9a3f7365c3d2e569f6ca68a2ff8bc5bcd9676edd63"]
python-dateutil = ["063df5763652e21de43de7d9e00ccf239f953a832941e37be541614732cdfc93", "88f9287c0174266bb0d8cedd395cfba9c58e87e5ad86b2ce58859bc11be3cf02"]
s3transfer = ["90dc18e028989c609146e241ea153250be451e05ecc0c2832565231dacdf59c1", "c7a9ec356982d5e9ab2d4b46391a7d6a950e2b04c472419f5fdec70cc0ada72f"]
six = ["70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9", "832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"]
tqp = []
urllib3 = ["61bf29cada3fc2fbefad4fdf059ea4bd1b4a86d2b6d15e1c7c0b582b9752fe39", "de9529817c93f27c8ccbfead6985011db27bd0ddfcdb2d86f3f663385c6a9c22"]
```

where tqp doesn't have a hash, could be the culript?
