### ISSUE TITLE
(🐞) `poetry install` keeps installing things that are already installed, when they were previously a git dependency

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#7089]
- **Poetry version**:  1.2.2
- **Python version**:  3.10
- **OS version and name**:  Windows 10 / wsl Ubuntu 22.04
- **pyproject.toml**: 
```toml
[tool.poetry]
name = "poetry-test"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.10"
pendulum = { git = "https://github.com/sdispater/pendulum.git", rev = "9d06ff3c9805869ccfc4163172b658482ec50087" }
#pendulum = "^2"
```

- [🚀] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [🚀] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [🚀] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [🚀] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Steps:
```
👉 poetry update
Updating dependencies
Resolving dependencies... (0.7s)

Package operations: 5 installs, 0 updates, 0 removals

  • Installing six (1.16.0)
  • Installing python-dateutil (2.8.2)
  • Installing time-machine (2.8.2)
  • Installing tzdata (2022.6)
  • Installing pendulum (3.0.0a0 9d06ff3)
```
At this point we update the pendulum dependency to `"^2"`, then continue
```
👉 poetry update
Updating dependencies
Resolving dependencies... (0.7s)

Package operations: 1 install, 1 update, 0 removals

  • Installing pytzdata (2020.1)
  • Updating pendulum (3.0.0a0 9d06ff3 -> 2.1.2)
👉 poetry install
Installing dependencies from lock file

Package operations: 0 installs, 1 update, 0 removals

  • Updating pendulum (2.1.2 9d06ff3 -> 2.1.2)
👉 
```

# What The Glitch❓❓❓❓
`• Updating pendulum (2.1.2 9d06ff3 -> 2.1.2)`
