### ISSUE TITLE
`poetry --install run` to integrate nicely with `pre-commit` + `mypy`

### ISSUE THREAD

**Issue by mattyclarkson** [python-poetry/poetry#7091]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

When using the [mypy](https://github.com/pre-commit/mirrors-mypy) [pre-commit](https://pre-commit.com/) hook is defined like so:

```
- id: mypy
```

However, this often fails because `mypy` does not have access to the types required to do analysis.

The types are often in a Poetry dependencies group (maybe `dev`, maybe `types`).

The are a few ways around this.

Generate a requirements that `pre-commit` can install:
```
- id: poetry-export
  args: ["--only", "test", "-o", ".requirements-mypy.txt"]
- id: mypy
  additional_dependencies:
    - .requirements-mypy.txt
```

Create a script that can install dependencies then run a tool within the Poetry virtual env:
```
- id: mypy
  entry: tools/poetry-install-then-run.py mypy
```

The above could be:
```
- id: mypy
  entry: poetry --install run mypy
```

Which would mean that poetry does an default install and then runs the tool.

This means that `mypy` then has access to the correct dependencies.

---

It might be that this isn't a Poetry concern and that we move the problem to `pre-commit` by adding a new generic installation command:

```
- id: mypy
  install_dependencies: poetry install --only test
  additional_dependencies:
    - poetry==1.2.0
```

@asottile (`pre-commit` maintainer) might have views on that.
