### ISSUE TITLE
Poetry (still) does not use active pyenv when creating virtual environment. Is it possible to write a documentation page about how to make this work?

### ISSUE THREAD

**Issue by lhoupert** [python-poetry/poetry#7095]
- **Poetry**: Poetry (version 1.2.2)
- **Python**: Python:  3.10.8 (using pyenv)
- **OS**: MacOS 12.6.1
- **pyproject.toml**: 
```toml
[tool.poetry]
name = "poetryproj1"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

## Context 
Hi, I am a new users of Poetry and I am working on establishing best practices for python software packaging in our team and I thought about starting introducing Poetry in our workflow. However I may stick to pip and `pyenv-virtualenv` for a little bit longer as it doesnt seem that poetry is compatible with pyenv.

I think my issue is related to several issues about poetry not working as expected with `pyenv` such as
- https://github.com/python-poetry/poetry/issues/5252
- https://github.com/python-poetry/poetry/issues/7075
- https://github.com/python-poetry/poetry/issues/651
- https://github.com/python-poetry/poetry/issues/172

## Issue

poetry doesnt use the active terminal python version defined by `pyenv global 3.10.8`, `pyenv local  3.10.8` or `pyenv shell  3.10.8`, when creating a new project with the command `poetry new projnew1`

### Reproductible example
1. Install [**`Poetry`**] with: 
```shell
curl -sSL https://install.python-poetry.org | python3 -
```

2. Add Poetry to your PATH:
```shell
echo '\n# Add Poetry to PATH\nexport PATH="$HOME/.local/bin:$PATH"' >> ~/.zshrc
```

3. Restart the shell with  `exec $SHELL`

4. Test the installation by running:
```shell
poetry --version
```

5. Update Poetry:
```shell
poetry self update
```

6. Install pyenv environment 3.10.4:
 ```shell
 pyenv install 3.10.4
 ```

7. Activate pyenv environment
 ```shell
 pyenv global 3.10.4
 ```

8. Verify active python version
```shell
pyenv which python
```
returns `/Users/loic.houpert/.pyenv/versions/3.10.4/bin/python`

9. Set virtualenvs to true:
```shell
poetry config virtualenvs.prefer-active-python true
```

 11. Create a new poetry project
 ```shell
poetry new poetryproj1
```

12. Read the `project.toml` 
```shell
ccat poetryproj1/pyproject.toml
```
which returns the wrong python version:

```toml
[tool.poetry]
name = "poetryproj1"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

## Notes
- I used the official installer, 
- I also tried `poetry config virtualenvs.prefer-active-python false` or `poetry config virtualenvs.prefer-active-python true` before creating a new project.
- Does the integration `pyenv+poetry` worked in the past? If yes what poetry version was it? 
- I happy to write some doc about pyenv+poetry integration if we manage to make this work
