### ISSUE TITLE
pre-commit autoupdate pulls incorrect Poetry version 1.2.2 -> 1.2.0rc1

### ISSUE THREAD

**Issue by danjac** [python-poetry/poetry#7139]
- **Poetry version**: 1.2.2
- **Python version**: 3.11.0
- **OS version and name**: Fedora Linux 37

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Running pre-commit version 2.20.0:

I currently have this pre-commit hook to do poetry checks and export requirements in my project, along with multiple other pre-commit hooks (Black, prettier etc):

```
    - repo: https://github.com/python-poetry/poetry
      rev: 1.2.2
      hooks:
          - id: poetry-check
          - id: poetry-export
            args: ["--without-hashes"]
```
Running `pre-commit autoupdate` all hook dependencies are updated correctly to the latest tagged versions, with the exception of Poetry:

```
Updating https://github.com/python-poetry/poetry ... updating 1.2.2 -> 1.2.0rc1
```

Of course `1.2.0rc1` is a broken and outdated earlier version. 

This may be an issue with pre-commit but would like to clarify if there is a problem first on the Poetry side, given all other hooks are updating correctly.
