### ISSUE TITLE
`poetry install` exits after summarizing the execution plan

### ISSUE THREAD

**Issue by FranzForstmayr** [python-poetry/poetry#7148]
- **Poetry version**: 1.2.2
- **Python version**: 3.9.15
- **OS version and name**: Ubuntu 20.04.5 LTS
- **pyproject.toml**: 

```toml
[tool.poetry]
name = "test_app"
version = "1.1.0"
description = "Test Application"
authors = [
    "Name Surname <name@mail.com>",
]
license = "proprietary"

[tool.poetry.dependencies]
python = "~3.9"
openpyxl = "^3.0.9"
pandas = "^1.4.1"
dash-extensions = "^0.1.6"
scipy = "^1.9.3"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
flake8-bugbear = "^22.1.11"
flake8-docstrings = "^1.6.0"
pep8-naming = "^0.12.1"
flake8-formatter-junit-xml = "^0.0.6"
pytest = "^7.1.0"
nox = "^2022.1.7"
flake8-annotations = "^2.7.0"
Sphinx = "^4.4.0"
sphinx-rtd-theme = "^1.0.0"
sphinx-autodoc-typehints = "^1.17.0"
black = "^22.1.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
When I try to install this project on this certain machine, nothing happens.
Verbose option does not show anything useful. Is there another way to debug this issue?

```
(test-app-py3.9) host@HOST:~/apps/test-app$ poetry install -vvv
Loading configuration file /home/host/.config/pypoetry/config.toml
Loading configuration file /home/host/.config/pypoetry/auth.toml
Using virtualenv: /home/host/apps/test-app/.venv
Project environment contains an empty path in sys_path, ignoring.
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 81 installs, 0 updates, 0 removals
```
