### ISSUE TITLE
Lockfile diffs between Linux and macOS in `[package.extras]`

### ISSUE THREAD

**Issue by intgr** [python-poetry/poetry#7207]
- **Poetry version**: 1.3.1
- **Python version**: 3.11.1
- **OS version and name**: `python:3.11` Docker image vs macOS 12.6
- **pyproject.toml**: (see below)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.

## Issue
Starting with following `pyproject.toml`:

```toml
[tool.poetry]
name = "tmp"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pynacl = "^1.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Running `poetry lock` in macOS or Linux respectively, the lock file will have different contents:

```diff
% diff -u poetry.lock poetry.lock.linux
--- poetry.lock	2022-12-16 17:16:10.000000000 +0200
+++ poetry.lock.linux	2022-12-16 17:15:49.000000000 +0200
@@ -113,7 +113,7 @@
 cffi = ">=1.4.1"

 [package.extras]
-docs = ["sphinx (>=1.6.5)", "sphinx_rtd_theme"]
+docs = ["sphinx (>=1.6.5)", "sphinx-rtd-theme"]
 tests = ["hypothesis (>=3.27.0)", "pytest (>=3.2.1,!=3.3.0)"]

 [metadata]
```
