### ISSUE TITLE
Old version installed when adding wildcard dependency

### ISSUE THREAD

**Issue by u1735067** [python-poetry/poetry#7220]
- **Poetry version**: Poetry (version 1.3.1)
- **Python version**: Python:  3.10.9
- **OS version and name**: Alpine Linux 3.17
- **pyproject.toml**: 

```toml
[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = [""]

# ------------------------------------------------------------------------------
[tool.poetry.dependencies]
python = "^3.10.1"
Django = "~4.0.4"
django-redis = "~5.2.0"
channels = "*"
channels-redis = "^3.4.1"
daphne = "*"  # required to trigger

# ------------------------------------------------------------------------------

[tool.poetry.scripts]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] ~~If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.~~

## Issue

Hello, first, I hope this is not me misunderstanding/misusing Poetry or misreading docs (please close then, and sorry for the noise).

When creating `pyproject.toml`, I encountered behavior that seemed unintuitive: the pyproject mentioned above is creating a lock file with `daphne=4.0.0` and especially `channels=1.1.1` (an old version from 2017), while when the `daphne = "*"` line is commented, the lock file is created with `daphne=3.0.2` and `channels=3.0.5`, as I would expect.

Is this the normal behavior? Is there a way to prevent this (like specifying a different dependency resolution strategy)? And while explicitly indicate `daphne` is required, whatever it's version?

NB: a feedback from using poetry in an entreprise environment with an internal mirror of pypi, a way to generically override the official pypi url without specifying another source in `pyproject.toml` would be useful :)

## Repro

```sh
docker run --rm -it --entrypoint sh python:3.10-alpine
# image python:3.10-alpine=2527f31628e7
apk add curl
curl -sSL https://install.python-poetry.org | python3 -
# Poetry (1.3.1) is installed now. Great!
export PATH="/root/.local/bin:$PATH"
cd
cat > pyproject.toml <<'EOF'
((((file above))))
EOF
poetry lock
```

Resulting lock files in https://gist.github.com/u1735067/70982c7e8d4e19bf1d35b63b04e8257a
