### ISSUE TITLE
Only the first author and maintainer are included in metadata of packages built with poetry when multiple are listed

### ISSUE THREAD

**Issue by mhamiltonj** [python-poetry/poetry#7229]
- **Poetry version**: 1.3.1
- **Python version**: poetry: 3.10.6; venv:  3.8.3
- **OS version and name**: Windows 10 build 19044
- **pyproject.toml**: https://gist.github.com/mhamiltonj/b69bce33995561bb71cefc477f06659b

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below. - No exception raised

## Issue
I have defined multiple `authors` and `maintainers` under `[tool.poetry]`, (see below) but after building with `poetry build`, only the first of each is listed in METADATA in the wheel, and in `PKG-DATA` in the sdist. I can find only one other reference to this problem, in this stack overflow question with no resolution: https://stackoverflow.com/questions/72003628/why-cant-i-have-multiple-authors-after-build-with-poetry-in-pkg-info

```toml
[tool.poetry]
    name="our-project"
    readme = "README.md"
    license = "LGPL-3.0-only"
    version = "0.1.0.post3"
    authors = [
        "Author 1 <a.one@example.com>",
        "Author 2 <a.two@example.com>",
        "Author 3 <a.three@acme-corp.com>"
    ]

    maintainers = [
        "Maintainer 1 <m.one@example.com>",
        "Author 3 <a.three@acme-corp.com>"
    ]
```
Reults in this METADATA
```
Metadata-Version: 2.1
Name: our-project
Version: 0.1.0.post3
Summary: ...
License: LGPL-3.0-only
Author: Author 1
Author-email: a.one@example.com
Maintainer: Maintainer 1
Maintainer-email: m.one@example.com
Requires-Python: >=3.8,<3.9
Classifier: License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.8
...
````

full (sanitised) pyproject.toml here: https://gist.github.com/mhamiltonj/b69bce33995561bb71cefc477f06659b
