### ISSUE TITLE
[FR] Strict dependencies by groups

### ISSUE THREAD

**Issue by rockandska** [python-poetry/poetry#7421]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Seems that poetry, even if in dedicated groups, build the dependencies tree based on all groups.
Seems fair since, depending on your needs, you install just "lint" group, or "formatter" group or two groups, with main, without main, run those groups with only one python version in contrary to the package itself etc...
But, sometimes, it constrains the users and hit dependency hell even if they use a group only for test/lint etc... or doesn't let them use a recent version of a package because one of the packages require an old version for a cross dependency.
As an example, flake8 and its dependency on `importlib-metadata < 5` who constrains many packages.

Having something similar as `depends_on = []` for groups to let the lock file be built based on group dependency and let users have more flexibility would be really convenient.

As an example :
```toml
[tool.poetry.dependencies]
python = ">= 3.7, <= 3.11"

[tool.poetry.group.lint]
optional = true
# depends_on by default is [ 'main' ]
depends_on = []
           
[tool.poetry.group.lint.dependencies]
python = ">= 3.7, <= 3.8"
flake8 = "*"

[tool.poetry.group.typing]
optional = true
depends_on = [ 'main' ]

[tool.poetry.group.typing.dependencies]
mypy = "*"
```

In this example :
- lint / typing are optional and not included in build
- lint is only intended to be executed with python 3.7 or 3.8
- typing is intended to be executed with the same python versions the project has
- lint is isolated, so dependencies required by flake8 (`importlib-metadata<5`) doesn't influence other packages in other groups if they don't depend on lint
- `poetry install --with lint` will fail because `lint` does not have main in `depends_on`
- when doing `poetry install --only typing`, it will install `main` too since it depends on it

Hope it will see the light in poetry someday and other users will welcome this Feature Request.

Regards,
