### ISSUE TITLE
Issues with local-path (vendored) wheel dependency and pypi using conditional environment markers

### ISSUE THREAD

**Issue by hozn** [python-poetry/poetry#7452]
- **Poetry version**: 1.3.2
- **Python version**: 3.10.2
- **OS version and name**: MacOS/Darwin 13.1, M1 (arm64)
- **pyproject.toml**: https://gist.github.com/hozn/e7c67bcc7a4639fff3d2cd6638d6ace8

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below. (N/A)

### Updated Issue Description
(Based on thread below, updating this to articulate the *actual* problem, which the original did not correctly pinpoint.)

The **order** of the dependencies and whether `source` is specified (or left at default value) seems to be a factor when creating the `poetry.lock` file.

`pyproject.toml` (snippet):

```toml
[tool.poetry.dependencies]
Python = "^3.10"
# <snip>
grpcio = [
    {markers="sys_platform == 'darwin' and platform_machine=='arm64'", path='./vendored/grpcio-1.51.1-cp310-cp310-macosx_11_0_arm64.whl'},
    {version="==1.51.1", markers="sys_platform != 'darwin' or platform_machine != 'arm64'"},
]
```

Generates a `poetry.lock` file that only includes information about the vendored macos-specific gprcio wheel.
Broken poetry.lock file: https://gist.github.com/hozn/c2ae7bbadec0437261a0b92b4fd07508

Ways to fix this:
1. Change the order of the two lines.
2. Or add `source="pypi"` to the non-vendored dependency.

### Original Issue Description
On MacOS M1  (arm64) it is notoriously painful to install grpcio.  For that reason, I need to install from a prebuilt local (vendored) path dependency when the environment markers indicate darwin+arm64.  This is how I'm attempting to achieve this in the `pyproject.toml`:

```toml
[tool.poetry.dependencies]
Python = "^3.10"
# <snip>
grpcio = [
    {version="==1.51.1", markers="sys_platform != 'darwin' or platform_machine != 'arm64'", source="pypi"},
    {markers="sys_platform == 'darwin' and platform_machine=='arm64'", path='./vendored/grpcio-1.51.1-cp310-cp310-macosx_11_0_arm64.whl'},
]
```

1. With the code above, `poetry lock` will generate a lockfile that only includes the package instances / hashes from pypi -- not the locally vendored version.
2. If I remove the `source="pypi"` from the first dep line, running `poetry lock` will generate a lockfile that *only* includes the hash for the vendored dependency.

I have not managed to get poetry to create a `poetry.lock` file that includes hashes for both the vendored package and the pypi packages.
