### ISSUE TITLE
Follow-up to #3368 Poetry install fails for nested local dependencies and develop = false

### ISSUE THREAD

**Issue by fiahil** [python-poetry/poetry#7539]
- **Poetry version**: 1.3.2 (also tested on 1.4.0.dev0) 
- **Python version**: 3.9.16
- **OS version and name**: macOS 13.1
- **pyproject.toml**: https://github.com/fiahil/poetry-localdep-issue-2

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hi,

I'm following up on #3368 and #4245.

While it appears the issue was resolved for local path dependencies, it still happens when the top-most dependency is a VCS dependency.

I attached a repo for a painless reproduction.

Cheers !

**Comment by fiahil** [comment]
Hi,

I just identified a regression in v1.4.0. Same setup over git version was working in v1.3.2 after patching the poetry.lock. Now, v1.4.0, can't resolve subdirectory properly.

Do you want me to create another issue for that (similar) problem ?

**Comment by dimbleby** [comment]
not before searching harder for duplicates #7575

**Comment by alvaromerinog** [comment]
Hello there!,
i have the same problem with remote git repositories. I have reproduced it with the following pyproject.toml.


```toml
[tool.poetry]
name = "dummy-project"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
packages = [{include = "dummy_project"}]

[tool.poetry.dependencies]
python = "^3.8"
zulip = {git = "https://github.com/zulip/python-zulip-api.git", rev = "0.8.2", subdirectory = "zulip"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

With poetry 1.3.2 this dependency is installed correctly. I hope it can help to solve the problem. Have a nice day!

## Log error

```python
  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  error: Multiple top-level packages discovered in a flat-layout: ['zulip', 'stubs', 'zulip_bots', 'zulip_botserver', 'packaged_helloworld'].
  
  To avoid accidental inclusion of unwanted files or directories,
  setuptools will not proceed with this build.
  
  If you are trying to create a single distribution with multiple packages
  on purpose, you should not rely on automatic discovery.
  Instead, consider the following options:
  
  1. set up custom discovery (`find` directive with `include` or `exclude`)
  2. use a `src-layout`
  3. explicitly set `py_modules` or `packages` with a list of names
  
  To find more information, look for "package discovery" on setuptools docs.
  

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
```

**Poetry version**: v1.4.0
**Poetry-core version**: v1.5.1
**Python version**: v3.8.12
**System**: Ubuntu 22.04.02 WSL2
