### ISSUE TITLE
default pyproject.toml from poetry init -n improperly handles src layout; reports installation success even though it cannot actually be imported

### ISSUE THREAD

**Issue by ckp95** [python-poetry/poetry#7609]
- **Poetry version**: 1.4.0
- **Python version**:
```
Poetry
Version: 1.4.0
Python:  3.10.9

Virtualenv
Python:         3.9.11
```
- **OS version and name**: 5.13.19-2-MANJARO
- **pyproject.toml** (see below)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Trying to make simple hello-word package in src layout. The default pyproject.toml created with `poetry init -n` does not let me install it properly.

To begin with, my file structure is like this:

```
$ tree
.
├── README.md
└── src
    └── fancy_project
        ├── __init__.py
        └── something.py

3 directories, 3 files
```

The `__init__.py` file is blank. The `something.py` file contains this:

```python
def hello():
    print("this is a fancy project!")
```

When I run `poetry init -n`, it generates the following (sanitized) `pyproject.toml`.

```toml
[tool.poetry]
name = "fancy-project"
version = "0.1.0"
description = ""
authors = ["aaaa <aaaa@bbbb.com>"]
readme = "README.md"
packages = [{include = "fancy_project"}]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

When I run `poetry install`, I get this error:

```
$ poetry install
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

/tmp/fancy-project/fancy_project does not contain any element
```

When I amend `pyproject.toml` to change the `include = "fancy_project"` to `include = "src"`, the `poetry install` command seems to succeed:

```
$ poetry install
Installing dependencies from lock file

Installing the current project: fancy-project (0.1.0)
```

However, the package is not actually importable:

```bash
$ poetry run python -c 'from fancy_project.something import hello; hello()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'fancy_project'
```

I tried changing the include line to say `include = "src/fancy_project"`. It similarly reports a successful install, but the import fails just the same.

I tried removing the `packages` line from `pyproject.toml` entirely. This time it works:

```
$ poetry install
Installing dependencies from lock file

Installing the current project: fancy-project (0.1.0)
$ poetry run python -c 'from fancy_project.something import hello; hello()'
this is a fancy project!
```

But I don't understand why. I don't remember ever having to muck around with the `packages` line; everything "just worked" the last time I tried this with a src layout.

I believe this is at least one bug here:

- the default `poetry init -n` should make a pyproject.toml that can work with src layout
- `poetry install` should not say that an installation succeeded when it actually didn't
- the docs for `packages` don't clear up any of this confusion
- the "does not contain any element" error message does not make any sense

(PS: I ran `rm -rf .venv` before every `poetry install` command, to start fro ma clean slate each time)

**Comment by dimbleby** [comment]
```toml
packages = [
    { include = "poetry", from = "src" }
]
```
per poetry's own usage

It's impossible for `poetry init -n` to produce a pyproject.toml that works for both src and not-src layouts: so it has to choose one.  I don't see that as a bug.

I expect docs improvements explaining this would be welcome, please contribute!

**Comment by ckp95** [comment]
Okay, was that changed recently? I must have done this sequence of commands dozens of times and I never ran into this problem before.

**Comment by dimbleby** [comment]
not so far as I know

**Comment by ckp95** [comment]
Okay I'm not crazy, I tested it and the following works on Poetry version 1.1.15:

```bash
#! /usr/bin/bash
set -euo pipefail

cd /tmp
rm -rf fancy-project
mkdir fancy-project
cd fancy-project

touch README.md
mkdir -p src/fancy_project
touch src/fancy_project/__init__.py
echo 'def hello():' >> src/fancy_project/something.py
echo '    print("this is a fancy project!")' >> src/fancy_project/something.py

poetry init -n

poetry install
poetry run python -c 'from fancy_project.something import hello; hello()'
```

The culprit seems to be that 1.1.15 doesn't populate the `packages` line in `pyproject.toml` when you run `poetry init -n`. It just makes this:

```toml
[tool.poetry]
name = "fancy-project"
version = "0.1.0"
description = ""
authors = ["aaaa <aaaa@bbbb.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
