### ISSUE TITLE
source does not support the use of html as the source entry

### ISSUE THREAD

**Issue by StringKe** [python-poetry/poetry#7631]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

source does not support the use of html as the source entry, the spliced file address is wrong!

The correct URL should be https://modelscope.oss-cn-beijing.aliyuncs.com/releases/v1.3/modelscope-1.3.1-py3-none-any.whl

```bash
➜ poetry lock
Updating dependencies
Resolving dependencies... (2.6s)

404 Client Error: Not Found for url: https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html/v1.3/modelscope-1.3.1-py3-none-any.whl
```

```toml
[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.93.0"
uvicorn = { version = "^0.20.0", extras = ["standard"] }
modelscope = { version = "^1", extras = ["cv"], source = "modelscope" }

[[tool.poetry.source]]
name = "modelscope"
url = "https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html"
secondary = true
```
