### ISSUE TITLE
How can vscode auto-resolve path dependencies in monorepo 

### ISSUE THREAD

**Issue by Tseian** [python-poetry/poetry#7677]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
The follow content is from pyproject.toml in this [monorepo](https://github.com/dermidgen/python-monorepo) . 
```toml
[tool.poetry]
name = "service-ml-common"
version = "0.1.0"
description = ""
authors = ["Danny Graham <good.midget@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
libml = "*"
libtelemetry = "*"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
libml = {path = "../../libs/libml", develop = true}
libtelemetry = {path = "../../libs/libtelemetry", develop = true}

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
After I run `poetry install`, libtelemetry and libml are installed succeed .  And launch program with `poetry run python -m service_ml_common.main` is OK.
![image](https://user-images.githubusercontent.com/13184460/226114826-1fe88ae0-e3b6-484f-a105-5f01a34da596.png)

But there is an warning **Import "libtelemetry.main" could not be resolvedPylance[reportMissingImports]**
![image](https://user-images.githubusercontent.com/13184460/226114774-971c8f31-e0ff-4dc7-958b-377e7041c911.png).

I have to soft link source file to the site-packages in service-ml-common .venv.  Then the vscode works.
```sh
ln -s /Users/admin/Downloads/projects/python/python-monorepo/libs/libtelemetry /Users/admin/Downloads/projects/python/python-monorepo/stack/service-ml-common/.venv/lib/python3.10/site-packages/libtelemetry
```

Can poetry auto-soft link to source file for path dependencies?
