### ISSUE TITLE
poetry add with --index-url option

### ISSUE THREAD

**Issue by alanwilter** [python-poetry/poetry#7685]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

I do this with pip:

```bash
pip3 install torch --index-url https://download.pytorch.org/whl/cpu
```

I can't find an equivalent in `poetry`. Suggestion:

```bash
poetry add torch --index-url https://download.pytorch.org/whl/cpu
```

**Comment by dimbleby** [comment]
https://python-poetry.org/docs/repositories/, please close

**Comment by alanwilter** [comment]
Thanks!

**Comment by alanwilter** [comment]
Ok, I got it, I just have to wait it searches...

I was having difficult to understand this bit:

> Any package source not marked as secondary will take precedence over PyPI.

I still don't understand that statement, but I glad I got it to work as I wanted.

```toml
[tool.poetry.dependencies]
torch = {version = "^2.0.0+cpu", source = "pytorch-cpu"}
...

[tool.poetry.group.dev.dependencies]
torch = {version = "^2.0.0", source = "pypi"}
...
```
