### ISSUE TITLE
Optional dependencies within groups

### ISSUE THREAD

**Issue by austinmw** [python-poetry/poetry#7712]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Hi, I can't seem to find out how to add optional dependencies within a group. 

For example I'd like the last dependency to be an optional / extra install within the `group_a`:

```toml
[tool.poetry.group.group_a.dependencies]
ipython = "^8.4.0"
cython = "^0.29.33"
numpy = "^1.22.3"
statsmodels = "^0.13.2"
mxnet = {version = "^1.9.1", optional = true} # Doesn't work with M1 Macs
```

I only want this to be optionally installable if `group_a` is installed.

---
I tried adding 

```toml
[tool.poetry.extras]
group_a = ["mxnet"]
```

And installing with `poetry install -E group_a`  but this didn't work.
