### ISSUE TITLE
How to specify the same package with different extras for different extras

### ISSUE THREAD

**Issue by danielgafni** [python-poetry/poetry#7738]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I'm trying to achieve something like: 

```toml
my-package = { extras = ["cpu", "gpu"], version = "^0.1.0", optional = true, source = "my-source"}

[tool.poetry.extras]
cpu = [
    "my-package[cpu]",
]
gpu = [
    "my-package[gpu]"
]
```

To clarify, this is *not* my-package's `pyproject.toml`, but another package's (let's call it `my-downstream-package`) `pyproject.toml`. 

Obviously, this config doesn't work. I'm just trying to illustrate what I want to achieve. 

I wonder if it's possible to do with Poetry at all?

Perhaps something like an alias can solve this? 

```toml
my-package-cpu = { extras = ["cpu"], version = "^0.1.0", optional = true, source = "my-source", name = "my-package" }
my-package-gpu = { extras = ["gpu"], version = "^0.1.0", optional = true, source = "my-source", name = "my-package" }

[tool.poetry.extras]
cpu = [
    "my-package-cpu",
]
gpu = [
    "my-package-gpu"
]
```
