### ISSUE TITLE
problem of resolving nested dependencies with private repositories

### ISSUE THREAD

**Issue by ct-jby** [python-poetry/poetry#7813]
- **Poetry version**: 1.4.1
- **Python version**: 3.11.1
- **OS version and name**: macOS 13.3.1
- **pyproject.toml**: 

```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = "poetry issue - problem of resolving nested dependencies with private repositories"
authors = ["ct-jby"]
readme = "README.md"
packages = [{include = "test", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
httpclient = { version="1.0.0", source = "private-libraries" }

[[tool.poetry.source]]
name = "private-libraries"
url = "https://my-gitlab.example.com/api/v4/groups/100/-/packages/pypi/simple"
default = false
secondary = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

### problem of resolving nested dependencies with private repositories

My current project has a private dependency on my gitlab and the httpclient dependency itself has a dependency on the same gitlab (logger 1.0.0)

When running the poetry install command, the logger 1.4.0 package from PyPi is installed instead of mine.

## current project with my default non functional configuration
```toml
...
[tool.poetry.dependencies]
python = "^3.11"
httpclient = { version="1.0.0", source = "private-libraries" }

[[tool.poetry.source]]
name = "private-libraries"
url = "https://my-gitlab.example.com/api/v4/groups/100/-/packages/pypi/simple"
default = false
secondary = true
...
```

## package httpclient project with my default non functional configuration
```toml
...
[tool.poetry.dependencies]
python = "^3.11"
logger = { version="1.0.0", source = "private-libraries" }

[[tool.poetry.source]]
name = "private-libraries"
url = "https://my-gitlab.example.com/api/v4/groups/100/-/packages/pypi/simple"
default = false
secondary = true
...
```

**After rereading the poetry documentation I tried to set the 'secondary' parameter of the 'private-libraries' source to false on the 'httpclient' package and in my current project.**

**poetry documentation on this parameter (according to the documentation, this should have fixed the problem but it didn't):**

https://python-poetry.org/docs/repositories/#default-package-source
<img width="820" alt="image" src="https://user-images.githubusercontent.com/108006482/233145465-2387939b-8e19-44cd-888f-0ed896141671.png">

## current project with secondary parameter set to false
```toml
...
[tool.poetry.dependencies]
python = "^3.11"
httpclient = { version="1.0.0", source = "private-libraries" }

[[tool.poetry.source]]
name = "private-libraries"
url = "https://my-gitlab.example.com/api/v4/groups/100/-/packages/pypi/simple"
default = false
secondary = false
...
```

## package httpclient project with secondary parameter set to false
```toml
...
[tool.poetry.dependencies]
python = "^3.11"
logger = { version="1.0.0", source = "private-libraries" }

[[tool.poetry.source]]
name = "private-libraries"
url = "https://my-gitlab.example.com/api/v4/groups/100/-/packages/pypi/simple"
default = false
secondary = false
...
```

**I was able to solve the problem by setting this source to default in my current project and in the httpclient library, but the documentation specifies that setting a source to 'default', disables the default pypi source.**

**poetry documentation on this parameter:**

https://python-poetry.org/docs/repositories/#default-package-source
![image](https://user-images.githubusercontent.com/108006482/233151092-ddd7e4a5-ae4a-42a3-bc73-b4fd95d3460b.png)

Despite what the documentation says, the packages coming from pypi are well resolved and my packages even if they have the same name as a package coming from pypi are installed in priority.

So my private package logger 1.0.0 (dependence of the package httpclient) is well installed instead of the one from pypi.

This behavior is surprising and contrary to the configuration explained in the official documentation.

## current project with private source as default (functional)
```toml
...
[tool.poetry.dependencies]
python = "^3.11"
httpclient = { version="1.0.0", source = "private-libraries" }

[[tool.poetry.source]]
name = "private-libraries"
url = "https://my-gitlab.example.com/api/v4/groups/100/-/packages/pypi/simple"
default = true
secondary = false
...
```

## package httpclient project with private source as default (functional)
```toml
...
[tool.poetry.dependencies]
python = "^3.11"
logger = { version="1.0.0", source = "private-libraries" }

[[tool.poetry.source]]
name = "private-libraries"
url = "https://my-gitlab.example.com/api/v4/groups/100/-/packages/pypi/simple"
default = true
secondary = false
...
```

**Is it a bug? Is the documentation correct?**

**Any help is welcome :)**
