### ISSUE TITLE
git dependency does not work with commit hash given through "rev"

### ISSUE THREAD

**Issue by FionaDmello** [python-poetry/poetry#7844]
- **Poetry version**: Poetry (version 1.4.2)
- **Python version**: Python:  3.8.10
- **OS version and name**: Ubuntu 20.04.5 LTS
- **pyproject.toml**: 

```toml
[tool.poetry]
name = "dummy"
version = "0.1.0"
description = ""
authors = ["JaneDoe <JaneDoe@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
flask = { git = "https://github.com/pallets/flask.git", rev = "38eb5d3b" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Basically, did `poetry install` on the toml file above and got the following error 
```
Unable to determine package info for path: /local/home/j.doe/.cache/pypoetry/virtualenvs/dummy-b9si7OGS-py3.8/src/flask

Command ['/tmp/tmpiuko3z72/.venv/bin/python', '-'] errored with the following return code 1

Output:
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/tmp/tmpiuko3z72/.venv/lib/python3.8/site-packages/build/__init__.py", line 290, in __init__
    _validate_source_directory(srcdir)
  File "/tmp/tmpiuko3z72/.venv/lib/python3.8/site-packages/build/__init__.py", line 158, in _validate_source_directory
    raise BuildException(f'Source {srcdir} does not appear to be a Python project: no pyproject.toml or setup.py')
build.BuildException: Source /local/home/j.doe/.cache/pypoetry/virtualenvs/dummy-b9si7OGS-py3.8/src/flask does not appear to be a Python project: no pyproject.toml or setup.py


Input:
import build
import build.env
import pyproject_hooks

source = '/local/home/j.doe/.cache/pypoetry/virtualenvs/dummy-b9si7OGS-py3.8/src/flask'
dest = '/tmp/tmpiuko3z72/dist'

with build.env.IsolatedEnvBuilder() as env:
    builder = build.ProjectBuilder(
        srcdir=source,
        scripts_dir=env.scripts_dir,
        python_executable=env.executable,
        runner=pyproject_hooks.quiet_subprocess_runner,
    )
    env.install(builder.build_system_requires)
    env.install(builder.get_requires_for_build('wheel'))
    builder.metadata_path(dest)

No fallback setup.py file was found to generate egg_info.

```
This is a minimal working example that reproduces the problem. The flask dependency is exactly as stated in the Poetry documentation. We used this feature in earlier version of Poetry and it worked.
