### ISSUE TITLE
Hang when trying to resolve dependencies for `faust-large-message-serializer = "^2.0.1"`

### ISSUE THREAD

**Issue by mathieu-lemay** [python-poetry/poetry#7875]
- **Poetry version**: 1.4.2
- **Python version**: 3.11.3
- **OS version and name**: Arch Linux
- **pyproject.toml**: See below

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Poetry hangs when trying to resolve dependencies for `faust-large-message-serializer = "^2.0.1"`. The issue can be reproduced with this pyproject.toml file, by running `poetry lock`.
```toml
[tool.poetry]
name = "faust-bug"
version = "0.1.0"
description = ""
authors = ["Mathieu Lemay <acidrain1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
faust-large-message-serializer = "^2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

It seems to be related to urllib3 now being at version 2.0.2 (versions 2.0.0 and 2.0.1 have been yanked). If I add the following dependency, everything works as expected: `urllib3 = "<2"`.
