### ISSUE TITLE
poetry build wheel does not include Requires-Dist for extra with optional dependency

### ISSUE THREAD

**Issue by bsdz** [python-poetry/poetry#7887]
- **Poetry version**: Poetry (version 1.4.2)
- **Python version**: 3.10.4
- **OS version and name**:  Ubuntu 22.04 
- **pyproject.toml**: See below

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

First create a blank project under temp, eg.

```bash
$ mkdir -p /tmp/pkg1/pkg1/
$ touch /tmp/pkg1/pkg1/__init__.py 
$ cd /tmp/pkg1
```

Then create following pyproject.toml

```toml
[tool.poetry]
name = "pkg1"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.group1]
optional = false

[tool.poetry.group.group1.dependencies]
requests = "^2.30.0"

[tool.poetry.extras]
group1 = ["requests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Then build and examine METADATA within generated wheel.

```bash
$ poetry build
$ unzip -p dist/pkg1-0.1.0-py3-none-any.whl pkg1-0.1.0.dist-info/METADATA
```

Outputs METADATA with missing "Requires-Dist", i.e.

```
Metadata-Version: 2.1
Name: pkg1
Version: 0.1.0
Summary: 
Author: Your Name
Author-email: you@example.com
Requires-Python: >=3.10,<4.0
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.10
Classifier: Programming Language :: Python :: 3.11
Provides-Extra: group1
```

Changing "optional" to true doesn't help. However if one moves the dependency into the main dependenices group, then the METADATA looks correct. i.e.

```toml
...

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.30.0"

[tool.poetry.group.group1]
optional = false

[tool.poetry.group.group1.dependencies]

[tool.poetry.extras]
group1 = ["requests"]

...
```

then after poetry build provides following METADATA:

```
Metadata-Version: 2.1
Name: pkg1
Version: 0.1.0
Summary: 
Author: Your Name
Author-email: you@example.com
Requires-Python: >=3.10,<4.0
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.10
Classifier: Programming Language :: Python :: 3.11
Provides-Extra: group1
Requires-Dist: requests (>=2.30.0,<3.0.0) ; extra == "group1"
```
