### ISSUE TITLE
Sources used as repositories to publish to need a different URL to sources to download from

### ISSUE THREAD

**Issue by couling** [python-poetry/poetry#7889]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

### Background

It's currently possible to add a repository to publish to in a `pyproject.toml` by declaring it as a [secondary] source and then referencing it's name as a `--repository` in the `poetry publish` command.  This does work in poetry 1.4.

However the URL needed may be different to the URL required to us the same repo as a source.  Eg:  When using AWS codeartifact as a source, the URL ends `/simple` but to publish to codeartifact this needs to be removed from the URL.  IE: This works:

```toml
[[tool.poetry.source]]
name = "codeartifact"
url = "https://acmecorp-1234567.d.codeartifact.eu-west-2.amazonaws.com/pypi/acmecorp/simple/"

[[tool.poetry.source]]
name = "codeartifact"
url = "https://acmecorp-1234567.d.codeartifact.eu-west-2.amazonaws.com/pypi/acmecorp/"
```

```shell
poetry publish --repository target 
```

[This comment ](https://github.com/python-poetry/poetry/issues/5348#issuecomment-1082191382) suggests that I shouldn't even be using a source to publish to but a repository defined poetry.toml and indeed this is hinted at by the [documentation](https://python-poetry.org/docs/repositories/).

But adding it as a source to the project **does work**.  It's hard to tell why.  I don't know if:
 - this a deliberate, yet undocumented feature?
 - this a side effect of the way poetry sources and repositories work?
 - this a depreciated feature?
 - something else?

So I guess, at the very least, #4658 is right to suggest that this needs better documentation.

### The Request

Could sources in pyproject.toml have two URLs (a push URL and a pull URL) so that repositories to available to publish to can be managed from the project instead of just each individual's workstation.

This would be particularly useful for larger organisations with more than one private PyPi repository.  Would it be possible to have the configuration something like:

```toml
[[tool.poetry.source]]
name = "codeartifact"
url = "https://acmecorp-1234567.d.codeartifact.eu-west-2.amazonaws.com/pypi/acmecorp/simple/"
# Only used by poetry publish
publish_url = "https://acmecorp-1234567.d.codeartifact.eu-west-2.amazonaws.com/pypi/acmecorp/"
```
