### ISSUE TITLE
Poetry seems to ignore dependencies of pytorch 2.0.1 but correctly installs them from local whl file

### ISSUE THREAD

**Issue by twoertwein** [python-poetry/poetry#7902]
- **Poetry version**:  1.4.2
- **Python version**:  3.11.3
- **OS version and name**:  Fedora 38

The following pyproject.toml does not install pytorch's dependecies. When manually downloading the whl from pipy, poetry correctly installs all dependecies.

```toml
[tool.poetry]
name = "foo"
version = "0.1.0"
description = ""
authors = ["Foo Bar <foo@bar.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "2.0.1"  # does NOT install nvidia-cublas-cu11
# torch = { file = "path/to/torch-2.0.1-cp311-cp311-manylinux1_x86_64.whl"}  # installs nvidia-cublas-cu11


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

xref https://github.com/pytorch/pytorch/issues/100974
