### ISSUE TITLE
Ability to have optional extra dependencies

### ISSUE THREAD

**Issue by matt035343** [python-poetry/poetry#7911]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
With pandas 2.0 also comes optional dependencies. However, I only sometimes need some of the extras, depending on the selected extras in my own project, to avoid bloating of the installation. For example, in my Poetry project I always need pandas, but only when my database extra is installed, the pandas SQL extra dependencies (postgresql, mysql, sql-other) should be installed.
I currently have not found a way to do this that the installed extra dependencies of a dependency can depend on the extra chosen for my own project.

I believe there are multiple ways of going about this, I have two suggestions below.

### Being able to label dependency specifications and use those in the extra specification
```toml
[tool.poetry]
name = "packagename"
version = "0.0.0"
description = "..."
authors = ["..."]
maintainers = ['...']
license = 'Apache 2.0'
readme = "README.md"
repository = 'https://github.com/...'

[tool.poetry.dependencies]
python = ">=3.9, <3.12"
pandas = { version = "^2.0.0"}
pandas = { version = "^2.0.0", extras = ["performance", "postgresql", "mysql", "sql-other"], label="pandas-databases", optional=true }


[tool.poetry.extras]
databases = [
    'SQLAlchemy',
    'pyodbc',
    'pandas-databases'
]
```

### Use a notation similar to pip in the extra specification, potentially with declaration of optional extras
```toml
[tool.poetry]
name = "packagename"
version = "0.0.0"
description = "..."
authors = ["..."]
maintainers = ['...']
license = 'Apache 2.0'
readme = "README.md"
repository = 'https://github.com/...'

[tool.poetry.dependencies]
python = ">=3.9, <3.12"
pandas = { version = "^2.0.0", optional_extras=["performance", "postgresql", "mysql", "sql-other"]}


[tool.poetry.extras]
databases = [
    'SQLAlchemy',
    'pyodbc',
    'pandas[performance,postgresql,mysql,sql-other]'
]
```
