### ISSUE TITLE
Existence(?) of [tool.poetry.extra-scripts] is undocumented

### ISSUE THREAD

**Issue by raxod502** [python-poetry/poetry#7925]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I've been trying for quite some time to understand how to get Poetry to copy a binary into my built package (i.e., to the bin directory of the virtualenv).

This feature was supposedly added in https://github.com/python-poetry/poetry-core/pull/40 to address https://github.com/python-poetry/poetry/issues/241, but there is no mention of the capability in documentation at https://python-poetry.org/docs/pyproject#scripts, and I have been unable to make it work no matter what I do. See https://github.com/python-poetry/poetry-core/pull/40#issuecomment-1547034922.

Does this feature exist? If so, what is the correct usage? It seems to have changed many times (`source` versus `reference`, `scripts` versus `extra-scripts` versus `script-table` versus `script-legacy` versus `extra-script-legacy`, `tools` versus `tool`), yet no documentation on any of the variations appears anywhere that I can find. And then there is https://github.com/python-poetry/poetry/issues/2310 which is saying maybe poetry and poetry-core are different from each other and it works in one but not the other? And maybe some subcommands of Poetry are broken but not others?

If my Python package needs to have a binary am I able to use Poetry or do I need to use setuptools exclusively instead?

**Comment by dimbleby** [comment]
`extra-scripts` is not and so far as I can see never has been a valid key.

If you've found https://github.com/python-poetry/poetry-core/pull/40 then you can see that the code all is still there, and that there are testcases demonstrating both how to use the function that was added and what it does

All that's left is that this was undocumented and should have follow up in poetry proper - which duplicates #2310.  Please close.

**Comment by raxod502** [comment]
I see that there are unit tests, but when I tested it myself, it didn't work, hence this issue.

Here's an example `pyproject.toml` that I just created:

```toml
[tool.poetry]
name = "poetry-repro"
version = "0.1.0"
description = "https://github.com/python-poetry/poetry/issues/7925"
authors = ["Radon Rosborough <radon@intuitiveexplanations.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
foo = {reference = "foo.bash", type = "file"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

With the following executable file `foo.bash` in the same directory:

```
#!/usr/bin/env

echo Foo
```

When running `poetry install`, no file called `foo` is created in the `bin` directory of the virtualenv. Did I misunderstand?
