### ISSUE TITLE
Local-only configuration

### ISSUE THREAD

**Issue by YodaEmbedding** [python-poetry/poetry#8107]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

(Of course, I may have missed something.)

## Feature Request

Read from a local-only `pyproject.local.toml` file containing user-specific configuration/overrides.
Also create a local-only `poetry.local.lock` lockfile.

## Motivation

For instance, Spongebob writes the following in `pyproject.toml`:
```toml
[tool.poetry.dependencies]
package-name = {path = "/home/spongebob/package-name", develop = true}
```
Spongebob runs `git add pyproject.toml && git push`.

Squidward clones the repo, and is annoyed that Spongebob was inconsiderate enough to pollute the shared `pyproject.toml` with his username. Squidward changes it to this:
```toml
[tool.poetry.dependencies]
package-name = {path = "/home/squidward/package-name", develop = true}
```
...then runs `git commit -am "i hate spongebob" && git push`.

Spongebob runs `git pull` and his pineapple blows up.
