### ISSUE TITLE
Add common dependency specification per group

### ISSUE THREAD

**Issue by ealap** [python-poetry/poetry#8138]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

It would be handy to have the option to define a common dependency specification for a group.

Instead of
```toml
[tool.poetry.group.private.dependencies]
package1 = [ { version = "^2.1.288", source = "PRIVATE_REPO" } ]
package2 = [ { version = "^0.7.0.64", source = "PRIVATE_REPO" } ]
package3 = [ { version = "^0.0.47", source = "PRIVATE_REPO" } ]

[tool.poetry.group.windows.dependencies]
package4 = [ { version = "^1.0.0", platform = "windows", source = "PRIVATE_REPO" } ]
package5 = [ { version = "^1.0.0", platform = "windows", source = "PRIVATE_REPO" } ]
package6 = [ { version = "^1.0.0", platform = "windows", source = "PRIVATE_REPO" } ]
```

Do this
```toml
[tool.poetry.group.private]
source = "PRIVATE_REPO"

[tool.poetry.group.private.dependencies]
package1 = "^2.1.288"
package2 = "^0.7.0.64"
package3 = "^0.0.47"

[tool.poetry.group.windows]
platform = "windows"
source = "PRIVATE_REPO"

[tool.poetry.group.windows.dependencies]
package4 = "^1.0.0"
package5 = "^1.0.0"
package6 = "^1.0.0"
```
