### ISSUE TITLE
Different extras on different platforms fails

### ISSUE THREAD

**Issue by NeilGirdhar** [python-poetry/poetry#8225]
This is what I'm doing:
```toml
[tool.poetry.dependencies]
jax = [
    {version = '>=0.4.13', extras = ['cuda'], platform = 'linux', source="jax_pep503"},
    {version = '>=0.4.13', platform = 'darwin', source="PyPI"}  # Fails all the same if the same source is given, which does contain non-cuda wheels.
]
jaxlib = [
    {version = '>=0.4.13', platform = 'linux', source="jax_pep503"},
    {version = '>=0.4.13', platform = 'darwin', source="PyPI"}  # Fails all the same if the same source is given, which does contain non-cuda wheels.
]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "jax_pep503"
url = "https://jorenham.github.io/jax_pep503/"
priority = "explicit"
```
But Poetry insists on trying to install the `cuda` extra on Darwin.  Is there any way to make this work?
