### ISSUE TITLE
Optional groups and extras installed if explicit source given

### ISSUE THREAD

**Issue by faemmi** [python-poetry/poetry#8238]
- **Poetry version**: 1.5.1
- **Python version**: 3.8
- **OS version and name**: Ubuntu 22.04 LTS
- **pyproject.toml**: https://github.com/faemmi/vissl/blob/4be1e0c703f57fbc03d1c643589232a5066505d1/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I have two groups of optional dependencies (`cpu` and `jupyter`) that I don't want to get installed by default. Since they're set to `optional = true`, when using `poetry install` I would expect neither of the two to be installed, but only when using `poetry install --with=cpu,jupyter`. When I run `poetry install`, the `jupyter` group does not get installed as expected. The `cpu` group, though, does.

My only guess is that the explicit source causes the group dependencies to be installed, which is not what I would expect.

I also tried organizing the dependencies as extras, i.e. 

```toml
[tool.poetry.dependencies]
...
torch = {version = "1.10.1", optional = true, source = "pytorch-cpu"}
torchvision = {version = "0.11.2", optional = true, source = "pytorch-cpu"}
ipykernel = {version = "^6.24.0", optional = true}

[tool.poetry.extras]
cpu = ["torch", "torchvision"]
jupyter = ["ipykernel"]

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"
```

and from my understanding according to the docs, this should also not install these extras by default when using `poetry install`, but only with `poetry install -E cpu -E jupyter`. Again, this works as expected for the `jupyter` extras, but not for the `cpu` extras.

Also, when I add another dependency to the `cpu` group which doesn't declare a source, or declares `source = "pypi"`, e.g.

```toml
[tool.poetry.group.cpu.dependencies]
torch = {version = "1.10.1", source = "pytorch-cpu"}
torchvision = {version = "0.11.2", source = "pytorch-cpu"}
dask = {version = "*", source = "pypi"}
```

the installation behavior is as expected for this dependency, but not for the other two dependencies.

Thanks for your help.
