### ISSUE TITLE
Feature request: activate extras in group dependencies

### ISSUE THREAD

**Issue by jeertmans** [python-poetry/poetry#8279]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Hello! I cannot believe someone did not ask it before, but I really couldn't find, so here is my question / feature question: *is it possible to activate extra dependencies in groups*?

To my knowledge, it seems like it is not possible, but I would love to see this feature (but maybe this is not possible due to how pip and Poetry are implemented).

## Example

Let say a have some package with extras dependencies. I also have a `test` group, that must activate all extras since I want to test the main package with all its features.

```toml
[tool.poetry.dependencies]
a = "1"
b = {version = "1", optional = "b"}

[tool.poetry.extras]
extra-feature = ["b"]

[tool.poetry.group]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "1"
b = "1"
```

Instead of duplicating all my extra dependencies, I'd love to just say that group `test` needs `extra-feature`.

For example:

```toml
[tool.poetry.dependencies]
a = "1"
b = {version = "1", optional = "b"}

[tool.poetry.extras]
extra-feature = ["b"]

[tool.poetry.group]
optional = true
extras = ["extra-feature"]

[tool.poetry.group.test.dependencies]
pytest = "1"
```

For people that know, Rust actually does that (extras are called features) very well.
