### ISSUE TITLE
Local or git-referenced poetry packages are not installed with mandatory non-main dependency groups

### ISSUE THREAD

**Issue by apirogov** [python-poetry/poetry#8283]
- **Poetry version**: 1.5.1
- **Python version**: any

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Say I want to add my poetry-based package **X** into a non-poetry-based package **Y**, i.e. which will be installed by `pip` through (I guess) poetry build backend. Now either I misunderstand something or do something wrong, but my problem is the following.

If I separate my deps in package **X** into different groups (which are **not** optional, and **not** the special `dev` group), I was expecting they should be installed. However, if I add a package **Z** as a dependency to **X** in a group named, say, `custom`, it won't be installed.

Now let this be the `pyproject.toml` of the poetry package **X**:

```toml
[tool.poetry]
name = "parent-proj"
version = "0.1.0"
description = ""
authors = ["a.b <a.b@example.com>"]
readme = "README.md"
packages = [{include = "parent_proj"}]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.3.2"

[tool.poetry.group.custom.dependencies]
child-proj = {path = "../child-proj"}
typer = "^0.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

If I run `pip install path/to/parent-proj`, the trace is 

```
Processing /local/home/a.pirogov/poetry-test/parent-proj
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting flask<3.0.0,>=2.3.2
  Using cached Flask-2.3.2-py3-none-any.whl (96 kB)
Collecting click>=8.1.3
  Using cached click-8.1.6-py3-none-any.whl (97 kB)
Collecting Werkzeug>=2.3.3
  Using cached Werkzeug-2.3.6-py3-none-any.whl (242 kB)
Collecting blinker>=1.6.2
  Using cached blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting itsdangerous>=2.1.2
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting Jinja2>=3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Building wheels for collected packages: parent-proj
  Building wheel for parent-proj (pyproject.toml) ... done
  Created wheel for parent-proj: filename=parent_proj-0.1.0-py3-none-any.whl size=1091 sha256=63232a8cf410eb4f8b03230748f8e5e5492af9c29a22ed2209285f8d0ca76cf1
  Stored in directory: /local/home/a.pirogov/.cache/pip/wheels/bf/67/fc/09965818f4945e55b232b92d69cb31034bea3d637f983d7f53
Successfully built parent-proj
Installing collected packages: MarkupSafe, itsdangerous, click, blinker, Werkzeug, Jinja2, flask, parent-proj
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.3 Werkzeug-2.3.6 blinker-1.6.2 click-8.1.6 flask-2.3.2 itsdangerous-2.1.2 parent-proj-0.1.0
```

And `pip list` shows:

```
Package      Version
------------ -------
blinker      1.6.2
click        8.1.6
Flask        2.3.2
itsdangerous 2.1.2
Jinja2       3.1.2
MarkupSafe   2.1.3
parent-proj  0.1.0
pip          22.1.2
setuptools   62.3.3
Werkzeug     2.3.6
wheel        0.37.1
```

**Expected:** `child-proj` (**Z**) should be installed too!

Or are the groups only different flavors of "dev deps"? because I'd like to logically separate feature-specific *runtime* deps into groups (say, group dependencies needed for a certain feature to work, i.e. things I'd also expose as an `extra` to pip)

I was expecting I can use
* mandatory groups for structuring my core deps,
*  for optional "extras" I'd make the poetry groups optional + duplicate the deps as installable extras.
