### ISSUE TITLE
Single-file or env-only packages not allowed?

### ISSUE THREAD

**Issue by con-f-use** [python-poetry/poetry#8292]
Don't actually know if it's a bug, nothing at all (because already implemented) or a feature; request.

Assuming my project to be packaged is a single file next to `pyproject.toml` in the file system hierarchy (i.e. in the same directory as `pyproject.toml`).

```console
tree ./
./
├── myproject.py
└── pyproject.toml
```

can I get poetry to accept that? I.e. what does the `package` attribute have to look like?

```toml
[tool.poetry]
name = "myproject"
version = "0.1.0"
description = "Single file project"
authors = ["confus"]
packages = [{include = "myproject", from = "."}]   # and similar don't work

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Related: what if I just wanted to use poetry for the dependency pinning functionality, i.e. just to distribute a reliably reproducible virtual environment? Does that work? If not, consider this a issue a feature request.
