### ISSUE TITLE
pkgconfig support

### ISSUE THREAD

**Issue by domenkozar** [python-poetry/poetry#8296]
# Background

Python has historically used runtime functions like `ctypes.util.find_library` by invoking ldconfig and gcc to get the flags and libraries for native dependencies.

Not only that causes performance issues on startup, it's extremely inconvenient to provide such information at runtime
while it's a configure thing.

There are [tons of patches](https://github.com/search?q=repo%3ANixOS%2Fnixpkgs+ctypes.util.find_library&type=code) in nixpkgs to support this and most important, it makes the whole Python development experience on Nix(OS) unusable.

# Proposal

Support [pkgconfig](https://www.freedesktop.org/wiki/Software/pkg-config/) section in `pyproject.toml` itself, inspired by [autotools](https://autotools.info/pkgconfig/pkg_check_modules.html) interface.

```toml 
[tool.poetry.pkgconfig]
gtk-2.0 = {version = "^3.0", platform = "darwin"}
zlib = *
```

## Dependency alternatives

Sometimes there's a fallback to another library, so we can support that:

```toml
[tool.poetry.pkgconfig]
libsodium = {version = "*", alternative = "openssl" }
```

## Runtime querying

`importlib_metadata` would be extended with pkgconfig metadata.

## Open Questions

How to handle the cases where `pkg-config` is not available? See how that impacted [cabal](https://github.com/haskell/cabal/issues/7448) implementation.

cc @rgommers (packaging roundable discussion followup)
