### ISSUE TITLE
(🎁) Support `{project-dir}` in `certificate` config values

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#8313]
- [🚀] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [🚀] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

`poetry.toml`:
```toml
repositories.nexus.url = "https://nexus.url.com/repository/pypi/simple/"
certificates.nexus.cert = "cacert.pem"  # works, but only when wd is project root
# certificates.nexus.cert = "{project-dir}/cacert.pem"  # doesn't work :(
```

```
👉 cd src
👉 poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing AMONGUS (1.2.3): Failed

  OSError

  Could not find a suitable TLS CA certificate bundle, invalid path: cacert.pem

  at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\requests\adapters.py:261 in cert_verify
      257│             if not cert_loc:
      258│                 cert_loc = extract_zipped_paths(DEFAULT_CA_BUNDLE_PATH)
      259│
      260│             if not cert_loc or not os.path.exists(cert_loc):
    → 261│                 raise OSError(
      262│                     f"Could not find a suitable TLS CA certificate bundle, "
      263│                     f"invalid path: {cert_loc}"
      264│                 )
      265│
```

With `"{project-dir}/cacert.pem"`:
```
Could not find a suitable TLS CA certificate bundle, invalid path: {project-dir}\cacert.pem
```
