### ISSUE TITLE
Poetry ignores extras from another local Poetry project

### ISSUE THREAD

**Issue by erezinman** [python-poetry/poetry#8350]
- **Poetry version**: 1.4.2
- **Python version**: 3.9.16
- **OS version and name**: Ubuntu 20.04
- **pyproject.toml**: https://gist.github.com/erezinman/17df2afcb00a5b37837c68fb68010957

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I have two projects. Both of which use Poetry, and one is dependent on the other. Until recently, the "dependee" project had a `setup.py`, and I migrated from `setup.py` to Poetry. The problem is that during development I alter both packages, and so I use a local version of the dependee package as well as for the dependent. It means that instead of:

```toml
[tool.poetry.dependencies]
python = "3.9.*"
my_package = { version = "^2023.5.0", extras = ['google'] }
```

I use 

```toml
[tool.poetry.dependencies]
python = "3.9.*"
my_package = { path = "../my_package", develop = true, extras = ['google'] }
```

The error is that when using `poetry install`, the dependent project does not pick up the `extras` of the `dependee` project. When I use the published package, it does work. Also, I'm pretty much sure that when the dependee project had `setup.py` file, the dependent project did pick up those dependencies on `lock` and/or `install`.
