### ISSUE TITLE
`assert term is not None` in poetry lock/update

### ISSUE THREAD

**Issue by david26694** [python-poetry/poetry#8405]
- **Poetry version**: 
- **Python version**: 
- **OS version and name**: 
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I do poetry update and I get the following error (using internal libraries, so can't share the toml):

```python
Updating dependencies
Resolving dependencies... (53.3s)

  AssertionError

  

  at ~/.local/pipx/venvs/poetry/lib/python3.11/site-packages/poetry/mixology/partial_solution.py:160 in _register
      156│         old_negative = self._negative.get(name)
      157│         term = (
      158│             assignment if old_negative is None else assignment.intersect(old_negative)
      159│          )
    → 160│         assert term is not None
      161│ 
      162│         if term.is_positive():
      163│             if name in self._negative:
      164│                 del self._negative[name]
```

what does this mean?

this is the partial toml (removed some internal libraries):
```toml

[tool.poetry.dependencies]
python = ">=3.8.6,<3.10"
pandas="~1.2.2"
lightgbm="~2.2.2"
numpy="^1.19.5"
scipy="~1.5.4"
pytest="^5.4.3"
boto3="^1.16.57"
injector="^0.18.4"
locust="^1.4.1"
scikit_learn="^0.22.1"
Shapely="^1.7.1"
scikit-optimize="^0.7.2"
PyMySQL="^1.0.2"
psycopg2-binary="^2.8.6"
distributed="==2.30.*"
pytz="*"
Ipython="^7.19.0"
dill=">=0.3.1, <1"
jupyter_client="^5.3.4"
ipykernel="^5.1.3"
nbconvert="^5.6.1"
geotiler=">=0.14.3, <1"
nest_asyncio="^1.2.3"
Unidecode="^1.1.1"
numba="==0.50.0"
llvmlite="^0.33"
jinja2 = "3.0.3"
smart-open = "*"
slackclient = "*"
py-dagger = "^0.4.2"
google-api-python-client = "^2.0.2"
matrixprofile = "==1.1.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```
