### ISSUE TITLE
Repeated runs of `poetry update` will cause a package to be upgraded and downgraded

### ISSUE THREAD

**Issue by pyoor** [python-poetry/poetry#8420]
- **Poetry version**: 1.6.1
- **Python version**: 3.10.12
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: 
```toml
[tool.poetry]
name = "poetry-bug"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
gitlint = "^0.19.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

Using the minimal pyproject.toml above, when calling `poetry update` repeatedly, the click package is upgraded or downgraded depending on the previous state.  I'm not sure if this is an issue with poetry or gitlint.

```
➜  poetry-bug poetry update
Updating dependencies
Resolving dependencies... (0.2s)

Package operations: 0 installs, 2 updates, 0 removals

  • Updating click (8.1.3 -> 8.1.7)
  • Updating sh (1.14.3 -> 2.0.6)
➜  poetry-bug poetry update
Updating dependencies
Resolving dependencies... (0.2s)

Package operations: 0 installs, 2 updates, 0 removals

  • Downgrading click (8.1.7 -> 8.1.3)
  • Downgrading sh (2.0.6 -> 1.14.3)
```
