### ISSUE TITLE
Why poetry install --only <group> not working?

### ISSUE THREAD

**Issue by devenliu** [python-poetry/poetry#8439]
- **Poetry version**: 1.6.1
- **Python version**: 3.10.9
- **OS version and name**: Windows11
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
1. poetry new <project>
2. poetry shell
3. poetry install --only feed

```toml
[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"

[tool.poetry.group.feed.dependencies]
keyring = "^24.2.0"
artifacts-keyring = "^0.3.4"
twine = "^4.0.2"
```

I want to install the dependencies of the `feed` group first, 
but the dependencies of the `test` group are also installed, 
which means the `--only` option does not work.

**Comment by dimbleby** [comment]
this works fine, please close

(or provide a way to reproduce what you are seeing eg wrapping it up in a dockerfile would work)

**Comment by devenliu** [comment]
```toml
[tool.poetry.dependencies]
python = "^3.10"
PRIVATE_PACKAGE = { version = "*", source = "PRIVATE_SOURCE" }


[tool.poetry.group.dev]
optional = true


[tool.poetry.group.dev.dependencies]
keyring = "^24.2.0"
artifacts-keyring = "^0.3.4"
twine = "^4.0.2"
pytest = "^7.4.2"
```

1. `poetry shell`
2. `poetry install --only dev`

output:

```plain
Updating dependencies
Resolving dependencies...
Source (azure): Authorization error accessing https://pkgs.dev.azure.com/<ORG>/<PROJECT>/_packaging/<FEED>/pypi/simple/<PRIVATE_PACKAGE>/

Because <PROJECT> depends on <PRIVATE_PACKAGE> (*) which doesn't match any versions, version solving failed.
```


According to the documentation, the `poetry install --only dev` command should only install the `dev` dependency group and not any other dependency groups.

However, it can be seen from the output that the authorization of the private repository was accessed when the command was executed, indicating that an attempt is made to install the private package at this time.

is it right? If not, how should I understand it?
