### ISSUE TITLE
Poetry silently ignores non-optional dependencies that appear in extras

### ISSUE THREAD

**Issue by adriangb** [python-poetry/poetry#8564]
Example: https://github.com/adriangb/misc/tree/poetry-bug

```toml
[tool.poetry]
name = "misc"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
pgpq = "*"

[tool.poetry.extras]
test = ["pgpq"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

If you try to `pip install` this you won't get the `pgpq` dependency even if it's not optional.

I think in this case the right behavior would be to always install it even if no extra is specified.
At the very least poetry should emit some sort of warning.
It's very easy to end up in this scenario by accident and very hard to figure out what's going on.
