### ISSUE TITLE
Unable to install cuda-python 12.3.0

### ISSUE THREAD

**Issue by mmoya91** [python-poetry/poetry#8606]
- **Poetry version**:  1.4.2
- **Python version**: 3.11.3
- **OS version and name**:  macOS 13.4 
- **pyproject.toml**: 
```toml
[tool.poetry.dependencies]
python = ">=3.11.3,<3.12"
cuda-python = {url = "https://files.pythonhosted.org/packages/3f/ac/c9eebb4996e0e69efa0258008f07a65e93ff582e4729e63f4bad8750563f/cuda_python-12.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"}
spacy-transformers = "^1.3.2"
```

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hello, I'm running into the following issues anytime I try installing `cuda-python` via poetry.  I also tried considering

```toml
cuda-python = {url = "https://files.pythonhosted.org/packages/bb/3f/0c38c8716a3a15d71c94696fd43290ed4d4f0361d36409f68ffb15478593/cuda_python-12.3.0-cp311-cp311-win_amd64.whl"}

```
but no luck. I would greatly appreciate any advice around this

```python
Package operations: 1 install, 3 updates, 0 removals

  • Updating urllib3 (1.26.18 -> 2.0.7)
  • Updating protobuf (3.20.3 -> 4.24.4)
  • Updating types-requests (2.31.0.6 -> 2.31.0.10)
  • Installing cuda-python (12.3.0): Failed

  RuntimeError

  Unable to find installation candidates for cuda-python (12.3.0)

  at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/poetry/installation/chooser.py:109 in choose_for
      105│ 
      106│             links.append(link)
      107│ 
      108│         if not links:
    → 109│             raise RuntimeError(f"Unable to find installation candidates for {package}")
      110│ 
      111│         # Get the best link
      112│         chosen = max(links, key=lambda link: self._sort_key(package, link))
```
