### ISSUE TITLE
The current project's Python requirement (>=3.11,<4.0) is not compatible with numpy requires Python <3.13,>=3.9

### ISSUE THREAD

**Issue by azataiot** [python-poetry/poetry#8616]
- **Poetry version**: 
- **Python version**: 
- **OS version and name**: 
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

**Comment by azataiot** [comment]
This is a brand new project: 

```
❯ poetry add numpy
Using version ^1.26.1 for numpy

Updating dependencies
Resolving dependencies... (0.0s)

The current project's Python requirement (>=3.11,<4.0) is not compatible with some of the required packages Python requirement:
  - numpy requires Python <3.13,>=3.9, so it will not be satisfied for Python >=3.13,<4.0

Because no versions of numpy match >1.26.1,<2.0.0
 and numpy (1.26.1) requires Python <3.13,>=3.9, numpy is forbidden.
So, because pycharm depends on numpy (^1.26.1), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For numpy, a possible solution would be to set the `python` property to ">=3.11,<3.13"
```


contents of the `pyproject.toml`: 
```toml
[tool.poetry]
name = "pycharm"
version = "0.1.0"
description = ""
authors = ["Azat <8280770+azataiot@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
matplotlib = "^3.8.1"
backtrader = "^1.9.78.123"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
