### ISSUE TITLE
Broken verbose/debug logging for poetry build with a custom build script

### ISSUE THREAD

**Issue by vit-zikmund** [python-poetry/poetry#8756]
- **Poetry version**: 1.7.1
- **Python version**: 3.11
- **OS version and name**: Fedora 38
- **pyproject.toml**: 
  <details><summary>hidden here</summary>

  ```toml
  [tool.poetry]
  name = "poetry-custom-build"
  version = "0.1.0"

  [tool.poetry.dependencies]
  python = "^3.10"

  [tool.poetry.build]
  script = "build.py"  # there's nothing in it

  [build-system]
  requires = ["poetry-core>=1.0.0", 'tomli; python_version < "3.11"']
  build-backend = "poetry.core.masonry.api"
  ```
</details>

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I'm not getting any debug `-vvv` logs from the `poetry build` command when using a custom build script with additional dependencies. The wheel builder source code obviously has some `logger.debug()` calls, but they're not getting  through.

Note, I was able to pinpoint the root cause. PR is on its way.
