### ISSUE TITLE
Cannot include '.pyc' files despite having them in includes

### ISSUE THREAD

**Issue by vit-zikmund** [python-poetry/poetry#8762]
- **Poetry version**: 1.7.1
- **Python version**: 3.10
- **OS version and name**: Fedora 38
- **pyproject.toml**:
  <details><summary>hidden here</summary>

  ```toml
  [tool.poetry]
  name = "poetry-custom-build"
  version = "0.1.0"
  include = ["poetry_custom_build/**/*.pyc"]
  exclude = ["poetry_custom_build/**/*.py"]
  [tool.poetry.dependencies]
  python = "^3.10"

  [tool.poetry.build]
  script = "build.py"  # this runs compileall and produces .pyc files along all the .py files

  [build-system]
  requires = ["poetry-core>=1.0.0"]
  build-backend = "poetry.core.masonry.api"
  ```
</details>

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
It's pretty much summed in the title :) I'd like to create a wheel package containing only compiled files, but poetry prevents me from doing so. And I guess [I know why](https://github.com/python-poetry/poetry-core/blob/3b08d1301b97fa727e58e9d41598b12fc3c0d942/src/poetry/core/masonry/builders/builder.py#L210-L211) ;)
