### ISSUE TITLE
Bug: `poetry install` fails with transitive path dependencies via git

### ISSUE THREAD

**Issue by jpugliesi** [python-poetry/poetry#8765]
- **Poetry version**: 1.7.1
- **Python version**: 3.10.12
- **OS version and name**: macOS 13.4
- **pyproject.toml**: https://github.com/jpugliesi/poetry-git-local-dep-bug

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Poetry fails to correctly install when it has a transitive path dependency, via a git subdirectory dependency.

For example, see https://github.com/jpugliesi/poetry-git-local-dep-bug where the `example` package's pyproject.toml contains a git dependency:
```toml
[tool.poetry]
name = "example"
version = "0.1.0"
description = ""
authors = ["John Pugliesi <john@viaduct.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
namespace-cli = {git = "https://github.com/adriangb/python-monorepo.git", subdirectory = "poetry/workspaces/cli"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

The dependency `namespace-cli` in turn refers to a git dependency on the [`namespace-cli` package](https://github.com/adriangb/python-monorepo/tree/9bb66f4af012b29a7fd706eac3a09f47975dffed/poetry/workspaces/cli). This package. [Finally, that `namespace-cli` package has a relative path dependency on another project in the corresponding repo (`namespace-lib`)](https://github.com/adriangb/python-monorepo/tree/9bb66f4af012b29a7fd706eac3a09f47975dffed/poetry/workspaces/cli):
```toml
[tool.poetry]
name = "namespace-cli"
version = "0.0.0"
description = ""
authors = []
packages = [{include = "namespace", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
rich = "^12.6.0"
namespace-lib = { path = "../lib"} # relative path dependency

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Installing the original `example` package will produce an error:
```
git clone https://github.com/jpugliesi/poetry-git-local-dep-bug && cd poetry-git-local-dep-bug
pipx install poetry==1.7.1
poetry install
```

Produces the following error:
```
➜  poetry install
Configuration file exists at /Users/x/Library/Preferences/pypoetry, reusing this directory.

Consider moving TOML configuration files to /Users/x/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
The currently activated Python version 3.9.16 is not supported by the project (~3.10).
Trying to find and use a compatible version.
Using python3.10 (3.10.12)
Creating virtualenv example in /private/tmp/poetry-git-local-dep-bug/.venv
Installing dependencies from lock file
Path /private/tmp/lib for namespace-lib does not exist
Path /private/tmp/poetry-git-local-dep-bug/.venv/src/python-monorepo/poetry/workspaces/lib for namespace-lib does not exist

Path /private/tmp/lib for namespace-lib does not exist
```

It seems poetry is resolving the path of the transitive `namespace-lib` relative to the root directory of the poetry-managed virtualenv, whereas it should be resolving the path _relative to the `subdirectory` of the git dependency.

**Comment by dimbleby** [comment]
layered path dependencies are pretty much always a bad idea - if you search this issue tracker you will find plenty of examples.

In this case you can see that what poetry has put into its lockfile for `namespace-lib` is this:
```toml
  [package.dependencies]
  namespace-lib = {path = "../lib"}
```
which is indeed what `namespace-cli` told it.  But what should it have put instead?  there is no way to express "wherever namespace-cli turns out to get installed, start from there..."

This is doomed.  Find some other way!
