### ISSUE TITLE
Not respecting priority for wildcard/inequality requirements

### ISSUE THREAD

**Issue by tkutcher** [python-poetry/poetry#8866]
- **Poetry version**: 1.7.1
- **Python version**: 3.11.6
- **OS version and name**: macOS Sonoma 14.2.1
- **pyproject.toml**: https://gist.github.com/tkutcher/70d67b0897017cf10f451d0e57f9ed2c

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

It is mostly self-explanatory in the gist, but I've found that when I have a dependency with a non-pypi source, where that source is specified with priority "default", if I use a more relaxed constraint (wildcard or inequality), then it goes to pypi if there is a naming clash and downloads a pypi package:

```toml
[[tool.poetry.source]]
name = "custom-1"
url = "some-url-to-gitlab-private-registry"
priority = "default"


[[tool.poetry.source]]
name = "custom-2"
url = "some-url-to-another-gitlab-private-registry"
priority = "primary"


[tool.poetry.dependencies]
python = "^3.10"
store = ">=0.28.0"   # "store" is in "custom-1", but defined like this goes to pypi...
# This also works: store = "^0.28.0"
# This works: store = { version = ">=0.28.0", source = "anvilorsolutions-tech-gitlab" }
```

Poetry install with that setup downloads a package from pypi with the name "store" at a version 2020.2.10.

Explicitly listing the source it is fine: `store = { version = ">=0.28.0", source = "anvilorsolutions-tech-gitlab" }`, and using tilde/caret requirements is also fine: `store = "^0.28.0"`

One of the things I considered was that the caret requirement didn't match anything on pypi hence why it would download the package from gitlab - however I have other scenarios where using the caret requirement does successfully download from my gitlab registry even though both the name and version numbers clash with something on pypi.

Thanks!
