### ISSUE TITLE
poetry install generates invalid python code for console scrips dependent on extras

### ISSUE THREAD

**Issue by couling** [python-poetry/poetry#8899]
- **Poetry version**: 1.7.1
- **Python version**: 3.11.14
- **OS version and name**: MacOS
- **pyproject.toml**: Documented example under [scripts](https://python-poetry.org/docs/pyproject/#scripts).  Eg:

```toml
[tool.poetry]
name = "poetry-example"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

# Documented code
[tool.poetry.scripts]
devtest = { reference = "poetry_example:test.run_tests", extras = ["test"], type = "console" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
`poetry install` generates invalid python for console scrips dependent on extras.  If you create a project with the documented toml example and then try to run the script:

```console
% poetry install
Installing dependencies from lock file

Installing the current project: poetry-example (0.1.0)

% source .venv/bin/activate

% devtest
Traceback (most recent call last):
  File "/Users/philip/Documents/Development/scratch/venv/bin/devtest", line 6, in <module>
    sys.exit(test.run_tests[test]())
TypeError: 'function' object is not subscriptable
```

It seems the generated script is wrong.  Eg:
```python
#!/Users/philip/Documents/Development/scratch/venv/bin/python
import sys
from poetry_example import test

if __name__ == '__main__':
    sys.exit(test.run_tests[test]())
```

This should have been:

```python
    sys.exit(test.run_tests())
```
