### ISSUE TITLE
lazy-wheel causes poetry to use all the RAM

### ISSUE THREAD

**Issue by dimbleby** [python-poetry/poetry#8929]
```toml
[tool.poetry]
name = "repro"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ruff = "^0.1.15"

[tool.poetry.group.jax.dependencies]
jaxlib = { extras = [
    "cuda12-pip",
], version = "^0.4.21+cuda12.cudnn89", source = "jax-releases" }
jax = { extras = ["cuda12-pip"], version = "^0.4.21" }

[[tool.poetry.source]]
name = "jax-releases"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
if we do not disable lazy wheel then trying to `poetry install` this (with an empty cache) causes poetry to use all the RAM until the OS kills it
