### ISSUE TITLE
poetry add results in "no versions of 'package match version'

### ISSUE THREAD

**Issue by dvorst** [python-poetry/poetry#8954]
### poetry debug info
```
Poetry
Version: 1.7.1
Python:  3.12.1

Virtualenv
Python:         3.12.1
Implementation: CPython
Path:           /Users/dennis.van.de.vorst/Documents/projects/poetr-bug/.venv
Executable:     /Users/dennis.van.de.vorst/Documents/projects/poetr-bug/.venv/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.12.1
Path:       /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12
Executable: /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/bin/python3.12
```

### pyproject.toml
``` TOML
[tool.poetry]
name = "poetry-bug-report"
version = "0.1.0"
description = ""
authors = ["dvorst <87502756+dvorst@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### System info
MacBook Pro 2022
Apple silicon M2 processor 
macOs 14.2
