### ISSUE TITLE
`poetry install` try to download macos wheel in my Linux machine

### ISSUE THREAD

**Issue by Freed-Wu** [python-poetry/poetry#8960]
- **Poetry version**: 1.7.1
- **Python version**: 3.11
- **OS version and name**: GNU/Linux 6.7.2
- **pyproject.toml**: 

```toml
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "XXX"
version = "0.1.2"  # DO NOT EDIT THIS LINE MANUALLY. LET bump2version UTILITY DO IT
authors = ["foo <foo@bar.edu>"]

[tool.poetry.plugins."mdformat.codeformatter"]
"python" = "mdformat_ruff:format_python"

[tool.poetry.dependencies]
python = "^3.7"
ruff = "*"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

```sh
$ poetry install
Updating dependencies
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/00/a1/618f1dbf5fc66c27221b1ede09a8b07ad4796cdf6cf9a8f8e4b20bb5987b/ruff-0.2.1-py3-none
...
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/00/a1/618f1dbf5fc66c27221b1ede09a8b07ad4796cdf6cf9a8f8e4b20bb5987b/ruff-0.2.1-py3-none
-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl  67% (296.5s)

HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

However, my machine is GNU/Linux, whatever it shouldn't download macosx's wheel.
