### ISSUE TITLE
`poetry lock` creates wrong lockfile for dependencies from custom source with extras - while `poetry add` works correctly

### ISSUE THREAD

**Issue by vkuhnde** [python-poetry/poetry#8997]
- **Poetry version**: 1.7.1
- **Python version**: 3.10.12 (with 3.11.1 in that specific virtualenv)
- **OS version and name**: Ubuntu 22.04.3 LTS in WSL2 on Windows 11 Pro 23H2
- **pyproject.toml**:

```toml
[tool.poetry]
name = "my_package"
version = "0.0.1"
description = "..."
readme = "README.md"
packages = [{ include = "my_package" }]

[[tool.poetry.source]]
name = "my-source"
url = "https://my.pypi.source/packages/pypi/simple"
priority = "explicit"

[tool.poetry.dependencies]
python = "~3.11.0"
my-lib = { version = "1.2.3", extras=["all"], source = "my-source" }

[build-system]
requires = ["poetry-core^1.0.0"]
build-backend = "poetry.core.masonry.api"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I ran across an issue when specifying a dependency that has a custom source **and** some extras to be installed.

`poetry add --source "my-source" "my-lib[all]==1.2.3"` works correctly. The generated poetry.lock is also correct and can be used to recreate the environment.

But, whenever I try to run `poetry lock` afterwards, the poetry.lock breaks in a way that makes `poetry install` fail. `poetry lock && poetry install` works without any issues if the dependency is defined without extras, i.e.,:
```toml
my-lib = { version = "1.2.3", source = "my-source" }
```
But, whenever extras are specified for installation (no matter which ones or how many), it fails. The git diff shows, that `poetry lock` adds the specified packages
```diff
[package.dependencies]
+ flask = {version = ">=1.0.2", optional = true, markers = "python_version >= \"3.7\" and python_version < \"4.0\" and (extra == \"flask\" or extra == \"all\")"}
```
but it also removes the package extras and source section (which are present after running above `poetry add` command and after running poetry lock when there are no extras specified for my-lib):
```diff
- [package.extras]
- all = ["flask (>=1.0.2)", "flask (>=1.0.2,<2.1.0)", "redis[hiredis] (>=4.0.2,<5.0.0)"]
- flask = ["flask (>=1.0.2)", "flask (>=1.0.2,<2.1.0)"]
- redis = ["redis[hiredis] (>=4.0.2,<5.0.0)"]
-
- [package.source]
- type = "legacy"
- url = "https://my.pypi.source/packages/pypi/simple"
- reference = "my-source"
```
On `poetry install --all-extras` this leads to:
```plain
Installing dependencies from lock file

Repository "my-source" does not exist.
```
with an IndexError in `poetry/repositories/repository_pool.py:136` when running with `-vvv`. But I guess, the error isn't really here but in the previous `poetry lock` command.
