### ISSUE TITLE
Backend 'poetry_dynamic_versioning.backend' is not available

### ISSUE THREAD

**Issue by justinTM** [python-poetry/poetry#8998]
- **Poetry version**: 1.6.1 (also tried 1.7.1)
- **Python version**: 3.11.6
- **OS version and name**: macOS 14.1.2
- **pyproject.toml**: https://gist.github.com/justinTM/7351e95eae3f7b8576884167977a8518

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
```console
poetry update > bug-report.txt
```

```console
# bug-report.txt
poetry update
Updating dependencies
Resolving dependencies... (3.0s)

Package operations: 0 installs, 1 update, 0 removals

  • Downgrading trz-py-utils (0.0.0.post9.dev0+180a9bd 180a9bd -> 0.0.0 7ef0ed8): Failed

  ChefBuildError

  Backend 'poetry_dynamic_versioning.backend' is not available.

  at /nix/store/7i5h0pfkg3qv0b97dkhgq53i2bb2s4sw-python3.11-poetry-1.6.1/lib/python3.11/site-packages/poetry/installation/chef.py:154 in _prepare
      150│ 
      151│                 error = ChefBuildError("\n\n".join(message_parts))
      152│ 
      153│             if error is not None:
    → 154│                 raise error from None
      155│ 
      156│             return path
      157│ 
      158│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
```

**Comment by justinTM** [comment]
fixed by changing [line 44 in gist](https://gist.github.com/justinTM/7351e95eae3f7b8576884167977a8518#file-gistfile1-txt-L44) to:
```toml
# pyproject.toml

[build-system]
# requires = ["poetry-core>=1.0.0", "setuptools>=40.9.0", "wheel"]            # bad, no-no
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]  # use me instead
```
