### ISSUE TITLE
Lock file contains an absolute path when using extras

### ISSUE THREAD

**Issue by FelixDQ** [python-poetry/poetry#9128]
### Description

When a path dependency uses extras with another path dependency, the resulting lock files contains an absolute path even though all the paths in `pyproject.toml` are relative.

I created a simple reproduction example here https://github.com/FelixDQ/poetry-lock-file-repro which contains 3 projects.

proj2 pyproject.toml:
```toml
[tool.poetry.dependencies]
python = "^3.8"
proj3 = {path = "../proj3", optional = true}

[tool.poetry.extras]
example = ["proj3"]
```

proj1 pyprojct.toml:
```toml
[tool.poetry.dependencies]
python = "^3.8"
proj2 = {path = "../proj2", extras = ["example"]}
```

This results in the following getting added to the lock file for proj1:
```toml
[package.extras]
example = ["proj3 @ file:///Users/felix/Projects/tmrow/poetry-lock-file-repro/proj3"]
```

This causes problems for us because the lock file is updated every time a developer runs `poetry lock—- no-update` even though nothing has changed. I would expect the file path to be relative as well

### Workarounds

Not as far as i know.

### Poetry Installation Method

pipx

### Operating System

MacOs

### Poetry Version

1.8.0

### Poetry Configuration

```bash session
cache-dir = "/Users/felix/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/felix/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
.
```

**Comment by FelixDQ** [comment]
I found this PR, so I'm a bit unsure if this is actually a bug as it seems like it was changed to this intentionally: https://github.com/python-poetry/poetry-core/pull/512

I would appreciate any workarounds for not having the lockfile change depending on the users absolute path!

**Comment by eamanu** [comment]
Hi!

Please also see https://github.com/python-poetry/poetry/issues/5273 and https://github.com/pypa/pip/issues/9127.

I think that we can add a new option to use relatives paths

**Comment by FelixDQ** [comment]
From reading the issues, it seems like it needs to use the absolute `file:///` URL to be compatible with PEP 508. The poetry commands however seem to still work just fine after manually changes the path to a relative one.

Would it be possible for us to create a poetry plugin or similar to that converts the path to a relative one?

**Comment by neersighted** [comment]
As noted, this is intentional, and this is not specific at all to extras. If you are not intending to build distributable content (wheels) from this package, I suggest you instead use dependency groups, which do not create metadata.

If you intend to create wheels and install them on another system, then you need to refer to the other package by name, even if you have a locally available copy on disk. 

If it's not quite either of those (that is, you want a path dependency during development and a dependency by name at build time), this is a duplicate of https://github.com/python-poetry/poetry/issues/1168.

**Comment by FelixDQ** [comment]
Thank you @neersighted! I guess that we've only seen this in our lockfiles after we started using extras. We don't intend to distribute wheels. We have a monorepo setup and would just like better control over which dependencies we are including in different projects.

Maybe I'm misunderstanding dependency groups, but is there a way to install optional ones when importing the project in another project. For example:

proj2:
```toml
[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.example]
optional = true

[tool.poetry.group.example.dependencies]
proj3 = {path = "../proj3"}
```

proj1:
```toml
[tool.poetry.dependencies]
python = "^3.8"
proj2 = {path = "../proj2"}
```

How can I specify in proj1 that it should include the optional group `example` and thereby install `proj3`?
