### ISSUE TITLE
Poetry doesn't lock for multi-architecture multi-sources

### ISSUE THREAD

**Issue by samskiter** [python-poetry/poetry#9145]
### Description

I'm trying to run poetry lock for a project I want to be able to install on macos and on RPi.

I've added the piwheels index to my pyproject.toml. I expect that with this (or with some flag I can pass to poetry) that poetry will now scan for all available architectures for each dependency and transient dependency. And place the results into the lock file.

However I seem to only be able to use EITHER piwheels OR PyPI and I can't find a way to 'force' poetry to go looking for other architectures.

I'm therefore unable to get a single working lock file for both OSs that doesn't resort to compiling deps.

### Workarounds

Others have mentioned having to recreate the lock file on each install (bad) or going back to pip/requirements.txt

### Poetry Installation Method

pipx

### Operating System

macos and raspbian

### Poetry Version

1.8.2

### Poetry Configuration

```bash session
cache-dir = "/home/sam/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/sam/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Example pyproject.toml

```TOML
# https://github.com/python-poetry/poetry/issues/5205
[[tool.poetry.source]]
name = "piwheels"
url = "https://www.piwheels.org/simple"
priority = "primary"

[tool.poetry.dependencies]
python = "~3.9.0"
adafruit-circuitpython-ads1x15 = "2.2.25"
aiochannel = "1.2.1"
aioconsole = "0.6.2"
aiomqtt = "1.2.1"
aiotools = "1.7.0"
async-timeout = "4.0.3"
asyncwebsockets = "0.9.4"
black = "23.9.1"
deptree = "0.0.12"
firebase-admin = "6.2.0"
google-cloud-pubsub = "2.18.4"
minimalmodbus = "2.1.1"
mypy = "1.8.0"
numpy = "1.26.4"
```

### Poetry Runtime Logs

```bash session
N/A
```
