### ISSUE TITLE
Allow extras to specify different versions of dependencies

### ISSUE THREAD

**Issue by Gattocrucco** [python-poetry/poetry#9194]
### Issue Kind

Brand new capability

### Description

I want to define an extra for my package that pins specific versions of some dependencies, without affecting dependency resolution when it is not used.

My use case: I'm writing a library that depends on [jax](https://github.com/google/jax). I want to define an extras `metal` that installs [jax-metal](https://pypi.org/project/jax-metal) to support Apple GPUs. However, `jax-metal` requires a specific version of `jaxlib`. Since `jax` updates frequently, it is limiting to force a certain version of `jax` even when the extra is not used.

Possible way the thing could look like:

```toml
[tool.poetry.dependencies]
jax = "^0.4.22"
jaxlib = "^0.4.22"
jax-metal = { version = "0.0.6", optional = true }

[tool.poetry.extras]
metal = [
    "jax-metal",
    { change-dependency = "jaxlib", version = "0.4.22" },
]
```

Would it be possible at all to do this? Or is it blocked by the way pip itself handles extras in packages it installs?

### Impact

I've found someone having a similar problem on [this stackoverflow thread](https://stackoverflow.com/questions/67476031/poetry-install-different-package-version-based-on-extras). They made a plugin, but 1) it seems unmaintained and a bit messy, so I don't trust depending on it, 2) it works at the level of installing groups, so not for the extras in my final released package.

I guess there are other people with similar needs, but I don't know how many.

### Workarounds

Workarounds I know of:

- Create a separate package for my library with different dependencies
    - Time-consuming for me
- Ask users to install jax-metal themselves following instructions
    - Time-consuming for users
    - Annoying for me because I can't use poetry to install things on my development copy
