### ISSUE TITLE
Extras with packages from groups other than main are not locked/installed correctly

### ISSUE THREAD

**Issue by swssl** [python-poetry/poetry#9274]
### Description

When adding an extra to the current project as stated in the docs, everything works. When adding the packages as optional to another dependency group, the lock file contains an empty array for that extra, so `poetry install  -E myextra` runs without error but doesnt install the extra as defined in pyproject.toml. Possibly, locking the extra could either raise an error (which the docs should help to avoid) or support extras containing packages from other groups

### Workarounds

Moving package to main group.

### Poetry Installation Method

pipx

### Operating System

Ubuntu (WSL)

### Poetry Version

1.8.2

### Poetry Configuration

```bash session
cache-dir = "/home/swssl/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Example pyproject.toml

```TOML
[tool.poetry]
name = "awesome"
version = "0.1.0"
authors = ["Developer <dev@example.org>"]
description = "Awesome package"

[tool.poetry.dependencies]
# These packages are mandatory and form the core of this package’s distribution.
python = "^3.8"
requests = "^2.31.0"

[tool.poetry.group.foo.dependencies]
pydantic = "^2.0.0"
mysqlclient = { version = "^1.3", optional = true }
psycopg2 = { version = "^2.9", optional = true }

[tool.poetry.extras]
mysql = ["mysql-connector-python"]
pgsql = ["psycopg2"]
```

### Poetry Runtime Logs

On `poetry install --extras mysql --no-root`, both packages extras are skipped without error:
```bash session
- Installing mysqlclient (1.4.6): Pending...
- Installing mysqlclient (1.4.6): Skipped for the following reason: Not required
- Installing psycopg2 (2.9.9): Pending...
- Installing psycopg2 (2.9.9): Skipped for the following reason: Not required
```

Afterwards, the poetry.lock contains this:
 ```toml
[extras]
mysql = []
pgsql = []
```
