### ISSUE TITLE
`pre-commit autoupdate` not pulling in 1.8.2 with `poetry-check` hook

### ISSUE THREAD

**Issue by jamesbraza** [python-poetry/poetry#9312]
### Description

I have this `.pre-commit-config.yaml`:

```yaml
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
```

Running `pre-commit autoupdate` does not pull in 1.8.2 (current release). Furthermore, with this config:

```yaml
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-check
```

Then running `pre-commit autoupdate` will actually backdate the `rev` to `1.8.0`.

The issue is that `pre-commit autoupdate` should be pulling in `1.8.2` as the `rev`.

### Workarounds

n/a

### Poetry Installation Method

other

### Operating System

macOS  Sonoma 14.3

### Poetry Version

3.12

### Poetry Configuration

```bash session
n/a
```

### Poetry Runtime Logs

```bash session
n/a
```
