### ISSUE TITLE
Poetry check virtual environment command for git hooks

### ISSUE THREAD

**Issue by maederm** [python-poetry/poetry#9313]
### Issue Kind

Brand new capability

### Description

I'd like to have a `poetry check` command for the virtual environment that basically does `poetry install --sync --dry-run` with the following changes:

- Prints only the summary `Package operations: 1 install, 0 updates, 0 removals, 56 skipped`
- Exit 0 if no operations would have been done
- Exit 1 otherwise

This was requested in https://github.com/python-poetry/poetry/issues/3599 as well but was dropped due to lack of interest.

I can try to create a Pull Request but I'd need some guidance regarding calling the [Executor](src/poetry/installation/executor.py) from [check command](src/poetry/console/commands/check.py). It's probably easier to implement it in poetry install but it feels wrong from a UX perspective.

### Impact

This feature can be used in a pre-commit post-checkout and post-merge hook to notify a developer if their current virtual environment isn't up to date. It saves troubleshooting time when other developers update dependencies and your current venv isn't up to date.

It also doesn't force the developer to use the workaround mentioned below that forces the developer to always scroll again to see the relevant output. 

### Workarounds

You can use this snippet, but it prints all the dependencies and doesn't exit with a failure reason.

```yaml
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
    - id: poetry-check
    - id: poetry-install
      args:
      - --dry-run
      - --sync
      verbose: true
      stages:
        - post-checkout
        - post-merge
      always_run: true # needed for post-checkout and post-merge
```
