### ISSUE TITLE
The abnormal poetry shell exit led to a sustained 100% CPU utilization.

### ISSUE THREAD

**Issue by ymcy** [python-poetry/poetry#9395]
### Description

When I connect to the server via SSH, activate a virtual environment with poetry shell in the project, and then disconnect the SSH link, it leads to a 100% utilization of the poetry shell.
![image](https://github.com/python-poetry/poetry/assets/63272165/fa6c83e4-8d89-4640-a85e-30a5d6d0b954)

### Workarounds

none

### Poetry Installation Method

pip

### Operating System

Ubuntu 24.04 LTS

### Poetry Version

1.8.2

### Poetry Configuration

```bash session
cache-dir = "/home/www/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/www/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Example pyproject.toml

```TOML
[tool.poetry]
name = "***"
version = "0.1.0"
description = ""
authors = ["***"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^5.0.4"
djangorestframework = "^3.15.1"
ipython = "^8.24.0"
django-redis = "^5.4.0"
Faker = "^24.14.0"
python-dotenv = "^1.0.1"
django-filter = "^24.2"
drf-spectacular = {extras = ["sidecar"], version = "^0.27.2"}
django-debug-toolbar = "^4.3.0"
django-extensions = "^3.2.3"
mysqlclient = "^2.2.4"
levenshtein = "^0.25.1"
bs4 = "0.0.1"
django-mdeditor = "0.1.20"
markdown = "3.4.4"
beautifulsoup4 = "4.12.2"
mistune = "^3.0.2"
pandas = "^2.2.2"
numpy = "^1.26.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

```bash session
none
```
