### ISSUE TITLE
Prevent Poetry from changing conda-installed dependency

### ISSUE THREAD

**Issue by gabe-microsoft** [python-poetry/poetry#9437]
### Issue Kind

Brand new capability

### Description

I propose an additional field to the poetry [dependency specification](https://python-poetry.org/docs/dependency-specification) which prevents poetry from updating the package. If the solve engine decides that the package must be updated, then the solve can fail, but under no circumstances will poetry uninstall the existing version of the package and replace it with another. This would allow users to install conda packages and instruct poetry not to update them (see motivation below).

Suggested dependency specification:
```toml
[tool.poetry.dependencies]
numpy = {version = "1.26.4", prevent-update = true}
```

### Impact

It is common to use poetry to manage dependencies within a conda environment, as described in several articles [[1](https://medium.com/@silvinohenriqueteixeiramalta/conda-and-poetry-a-harmonious-fusion-8116895b6380), [2](https://hackticdad.dev/combining-poetry-and-conda), [3](https://stackoverflow.com/questions/70851048/does-it-make-sense-to-use-conda-poetry), [4](https://michhar.github.io/2023-07-poetry-with-conda/), [5](https://felix11h.github.io/notes/ops/poetry.html)]. The commonly accepted best practice is to only use conda to manage dependencies which cannot be managed via poetry and to use poetry for everything else.

The most common example of this is installing `numpy` and `scipy` using conda because the conda versions of these packages are compiled using the Intel MKL optimizations. If conda installs `numpy` and none of the packages managed by poetry use `numpy` then this works fine. However, if any package managed by poetry has a dependency on `numpy`, poetry will remove the conda-installed version of `numpy` and replace it with the wheel from PyPI which does not have the Intel MKL optimizations. See example below:

Using the following conda `environment.yml`:
```yaml
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy==1.26.4
```

Using the following dependencies in `pyproject.toml`:
```toml
[tool.poetry.dependencies]
python = "~3.10"
pandas = "^2.2.2"
```

Poetry will remove the conda-installed version of `numpy` and replace it with a version from PyPI:
```text
Package operations: 5 installs, 1 update, 0 removals

  - Installing six (1.16.0)
  - Updating numpy (1.26.4 /croot/numpy_and_numpy_base_1708638617955/work/dist/numpy-1.26.4-cp310-cp310-linux_x86_64.whl -> 1.26.4)
  - Installing python-dateutil (2.9.0.post0)
  - Installing pytz (2024.1)
  - Installing tzdata (2024.1)
  - Installing pandas (2.2.2)
```

To prevent this, [some users have recommended](https://stackoverflow.com/questions/70851048/does-it-make-sense-to-use-conda-poetry#:~:text=it%20is%20best%20to%20specify%20the%20package%27s%20exact%20version%20in%20environment.yml%2C%20and%20after%20it%27s%20installed%2C%20to%20add%20an%20entry%20with%20the%20same%20version%20specification%20to%20Poetry%27s%20pyproject.toml%20(without%20%5E%20or%20~%20before%20the%20version%20number).%20This%20will%20let%20Poetry%20know%20that%20the%20package%20is%20there%20and%20should%20not%20be%20upgraded.) pinning the exact version used in conda within the `pyproject.toml` file to prevent poetry from upgrading the package, but in practice this does not work. See example below:

Using the following conda `environment.yml`:
```yaml
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy==1.26.4
```

Using the following dependencies in `pyproject.toml`:
```toml
[tool.poetry.dependencies]
python = "~3.10"
numpy = "1.26.4"
```

Poetry will remove the conda-installed version of `numpy` and replace it with the same version number, but from PyPI:
```text
Package operations: 0 installs, 1 update, 0 removals

  - Updating numpy (1.26.4 /croot/numpy_and_numpy_base_1708638617955/work/dist/numpy-1.26.4-cp310-cp310-linux_x86_64.whl -> 1.26.4)
```

### Workarounds

No known workarounds.
