### ISSUE TITLE
Poetry Dependency Specification: platform manylinux2014_x86_64 not supported

### ISSUE THREAD

**Issue by joeyhage** [python-poetry/poetry#9458]
### Description

Installing packages with platform option ignores manylinux2014_x86_64 and similar such as manylinux_2_17_x86_64. It instead installs manylinux_2_28_x86_64 which is supported by my system but not AWS lambda where I am trying to deploy.

I couldn’t find any documentation stating that manylinux* platforms are or aren’t supported by poetry and I couldn’t find any other GitHub issues related to this.

This AWS article explains the pip command needed for this to work: https://repost.aws/knowledge-center/lambda-python-package-compatible

### Workarounds

Using pip. 

`pip install --platform manylinux2014_x86_64 --only-binary=:all: cryptography`

### Poetry Installation Method

pipx

### Operating System

Debian 11

### Poetry Version

1.8.3

### Poetry Configuration

```bash session
cache-dir = "/home/joeyhage/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/joeyhage/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = true
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Example pyproject.toml

```TOML
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["..."]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
cryptography = {version="42.0.7", platform="manylinux2014_x86_64"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

No failure, just unexpected results. Even with poetry install -vvv, it only outputs the wheels it skips not the one it installed. Upon deploying to AWS and attempting to invoke the lambda function, it fails at runtime because glibc 2.28 is not supported.

```bash session

`cat .venv/lib/python3.11/site-packages/cryptography-42.0.7.dist-info/WHEEL`

Results in:
`
...
Tag: cp39-abi3-manylinux_2_28_x86_64
`

With pip, `pip install —-target . --platform manylinux2014_x86_64 --only-binary=:all: cryptography`

Results in:
`
...
Tag: cp39-abi3-manylinux_2_17_x86_64
Tag: cp39-abi3-manylinux2014_x86_64
`
```
