### ISSUE TITLE
Local lib depencency is not being installed correctly after upgrading poetry version

### ISSUE THREAD

**Issue by deivydaslipskis** [python-poetry/poetry#9480]
### Description

This issue started after upgrading from poetry **1.3.2 -> 1.8.2** version. `poetry install` fails to install one of the libs in my monolithic type project.

I have a monolithic type project structure for my project `weather`. It has a structure like this:
_libs/weather
libs/weatest
projects/ (all projects that use these libs), for example, england-weather project._

Here is the **england-weather** `pyproject.toml` file:
```
[tool.poetry]
name = "england"
version = "0.1.0"
description = "England weather app"
authors = ["Weather team"]

[tool.poetry.dependencies]
python = "^3.10"
weather = {path = "../../libs/weather", develop=true}
weatest = {path = "../../libs/weatest", develop=true}
```
Whenever I run poetry install in my **england-weather** project it installs the `weather` project correctly, but not `weatest`. `weatest` project version in the `pyproject.toml` file is **0.1.0**, but each time I run poetry install it shows it upgrading from **0.0.0 -> 0.1.0** version.

```
poetry install
Installing dependencies from lock file

Package operations: 0 installs, 1 update, 0 removals

  - Updating weatest (0.0.0 /Users/dave/projects/weather/libs/weatest -> 0.1.0 /Users/dave/projects/weather/libs/weatest)

Installing the current project: angel (0.1.0)
➜  england-weather ✗ poetry install
Installing dependencies from lock file

Package operations: 0 installs, 1 update, 0 removals

  - Updating weatest (0.0.0 /Users/dave/projects/weather/libs/weatest -> 0.1.0 /Users/dave/projects/weather/libs/weatest)

Installing the current project: england (0.1.0)

poetry run weatest
Command not found: weatest

```
Also, when installing **weatest** project a directory named `weatest.egg-info` is created and one of the files contains incorrect version number of the project:

**PKG-INFO**
```
Metadata-Version: 2.1
Name: weatest
Version: 0.0.0
```
Here is a crucial part of the `pyproject.toml` from the `weatest` project:

```
[tool.poetry]
name = "weatest"
version = "0.1.0"
description = "Lib for testing weather app"
authors = ["Weatest testers"]

[tool.poetry.dependencies]
python = "^3.10"
weather = {path = "../../libs/weather", develop=true}

[tool.poetry.scripts]
weatest = "weatest.cli:main"
```

Here is `weatest` cli file that is used as the entrypoint `cli.py` :

```
import pathlib

import pytest
import typer

app = typer.Typer()


@app.command()
def execute(entity: str) -> None:
    # Required for gitlab ci/cd to trigger assertion as error
    raise SystemExit(pytest.main(["-vv", str(pathlib.Path(__file__).parent.resolve() / "tests"), "--entity", entity]))


def main() -> None:
    app()
```

Am I incorrectly setting up the `weatest` library? What is the correct way to reference it and install it in my **england-weather** project?

### Workarounds

Use poetry 1.3.2, with it it installs the lib correctly

### Poetry Installation Method

install.python-poetry.org

### Operating System

MacOS

### Poetry Version

Poetry (version 1.8.2)

### Poetry Configuration

```bash session
cache-dir = "/Users/dave/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/dave/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Example pyproject.toml

```TOML
[tool.poetry]
name = "england"
version = "0.1.0"
description = "England weather app"
authors = ["Weather team"]

[tool.poetry.dependencies]
python = "^3.10"
weather = {path = "../../libs/weather", develop=true}
weatest = {path = "../../libs/weatest", develop=true}

[tool.poetry.group.dev.dependencies]
black = "~23.12.0"
mypy = "~1.0"
pylint = "~3.1.0"
isort = "~5.13.0"
pytest = "~8.2.0"
pytest-cov = "~5.0.0"

[[tool.poetry.source]]
name = "weather_validator"
url = "https://personal_repo....."
priority = "supplemental"
```

### Poetry Runtime Logs

```bash session
[build:build] Building editable...
  - Updating weatest (0.0.0 /Users/dave/projects/weather/libs/weatest -> 0.1.0 /Users/dave/projects/weather/libs/weatest): Installing...
  - Updating weatest (0.0.0 /Users/dave/projects/weather/libs/weatest -> 0.1.0 /Users/dave/projects/weather/libs/weatest)
```
