### ISSUE TITLE
`poetry update` locks one version, but installs another

### ISSUE THREAD

**Issue by jacek-jablonski** [python-poetry/poetry#9486]
[1st_poetry_update.log](https://github.com/user-attachments/files/15817597/1st_poetry_update.log)
[2nd_poetry_update.log](https://github.com/user-attachments/files/15817598/2nd_poetry_update.log)
### Description

Performing `poetry update` command sometimes results in locking one version, but installing other version.

1. On empty environment `poetry install --sync` installs:
```
...
  - Installing xxx-linters (2.0.1)
...
```

2. Then `poetry update` updates some packages, but not `xxx-linters`. But in `poetry.lock` it bumped version of `xxx-linters` to `.devX` version!
```
[[package]]
name = "xxx-linters"
version = "2.0.2.dev0+renovate.python.all"
description = "xxx-linters"
optional = false
python-versions = ">=3.11,<3.12"
files = [
    {file = "xxx_linters-2.0.2.dev0+renovate.python.all-py3-none-any.whl", hash = "sha256:2e5b77245d5ceb8c5e7b1d30a80aec728355faf20032068d485dc0654549f84c"},
    {file = "xxx_linters-2.0.2.dev0+renovate.python.all.tar.gz", hash = "sha256:570547179bf3f933a9df33ce2b2979c1e26f59b170e8aee6112dc2fcc0c31012"},
]
```

3. Another `poetry update` updates installed version to `.devX` version:
```
...
  - Updating xxx-linters (2.0.1 -> 2.0.2.dev0+renovate.python.all)
...
```

4. Third `poetry update` does nothing:
```
No dependencies to install or update
```

So, there are 2 problems I can see: 
1. `poetry update` updates to `.devX` version.
2. `poetry update` locks one version, but doesn't install it. At least 2 executions of `poetry update` is required to be sure that environment is in sync with `poetry.lock`

### Workarounds

1. Perform `poetry update` command until `No dependencies to install or update` is shown (Usually 2 times).
2. No workaround for installing `.dev` packages.

### Poetry Installation Method

pipx

### Operating System

MacOS Sonoma 14.5

### Poetry Version

Poetry (version 1.8.3)

### Poetry Configuration

```bash session
cache-dir = "/Users/jacek/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
repositories.rtbhouse-apps-internal.url = "https://europe-west4-python.pkg.dev/xxx/python-internal/simple/"
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/jacek/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Example pyproject.toml

```TOML
[tool.poetry]
name = "jobs-python"
version = "0.1.0"
description = ""

packages = [{ include = "jobs", from = "." }]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "xxx-internal"
url = "https://europe-west4-python.pkg.dev/xxx/python-internal/simple/"
priority = "supplemental"

[tool.poetry.dependencies]
python = "~3.11"

click = "^8.0.3"
dictdiffer = "^0.9.0"
google-api-python-client = "^2.36.0"
google-cloud-secret-manager = "^2.8.0"
httpx = { extras = ["http2"], version = "^0.25.0" }
pandas = "^2.0.0"
pg-stream-copy = "^1.5.4"
premailer = "^3.7.0"
pynacl = "^1.5.0"
python-dateutil = "^2.8.1"
python-redis-lock = "^4.0.0"
pyyaml = "^6.0"
redash-api-client = "^0.3.0"
requests = "^2.25.1"
xxx-config = { version = "^1.6.0", extras = ["secrets"] }
xxx-db-models = "^24.0.0"
xxx-dev = "^1.0.0"
xxx-extras = { version = "^8.0.0", extras = ["sentry"] }
xxx-google = { version = "^6.5.7", extras = ["dataframe"] }
xxx-logic = "^18.0.0"
xxx-services = { version = "^10.0.0", extras = ["redis"] }
xxx-sql = { version = "^6.0.0", extras = ["sqlalchemy-sync"] }
xxx-utils = { version = "^7.1.0", extras = [
    "click",
    "dateutil",
    "jinja",
    "voluptuous",
] }
tabulate = "^0.9.0"

[tool.poetry.group.dev.dependencies]
xxx-linters = "^2.0.0"
sqlalchemy-stubs = "^0.4"
types-pyyaml = "^6.0.1"
types-redis = "^4.0.3"
types-requests = "^2.26.1"
types-tabulate = "^0.8.3"
pytest = "^8.0.0"
pytest-mock = "^3.8.2"
```

### Poetry Runtime Logs

```bash session
(attached as files, message is too long)
```
