### ISSUE TITLE
Incorrect path definiton upon `-C`/`--directory` usage in `publish --build`

### ISSUE THREAD

**Issue by caniko** [python-poetry/poetry#9526]
### Description

I have a poetry project, and I would like to refer to it from another location using `Just`:
```shell
poetry -C openapi-client/ publish --build
```
Any subsequent paths generated by this command should be using `/data/can/Projects/SynDB/backend/syndb-api/openapi-client/` as root; however, I am getting an error:
```shell
[Errno 2] No such file or directory: '/data/can/Projects/SynDB/backend/syndb-api/openapi-client/openapi-client/syndb_api_client/__init__.py'
```
Notice that `openapi-client/` is repeated two times, this is wrong.

### Workarounds

Don't use `poetry -C`.

### Poetry Installation Method

pipx

### Operating System

Arch Linux

### Poetry Version

Poetry (version 1.8.3)

### Poetry Configuration

```bash session
cache-dir = "/home/can/.cache/pypoetry"
experimental.system-git-client = true
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/can/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Example pyproject.toml

```TOML
[tool.poetry]
name = "syndb_api_client"
version = "0.2.3"
description = "Synapse DB"
authors = ["OpenAPI Generator Community <team@openapitools.org>"]
license = "NoLicense"
readme = "README.md"
repository = "https://github.com/GIT_USER_ID/GIT_REPO_ID"
keywords = ["OpenAPI", "OpenAPI-Generator", "Synapse DB"]
include = ["syndb_api_client/py.typed"]

[tool.poetry.dependencies]
python = "^3.7"

urllib3 = ">= 1.25.3"
python-dateutil = ">=2.8.2"
pydantic = ">=2"
typing-extensions = ">=4.7.1"

[tool.poetry.dev-dependencies]
pytest = ">=7.2.1"
tox = ">=3.9.0"
flake8 = ">=4.0.0"
types-python-dateutil = ">=2.8.19.14"
mypy = "1.4.1"


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.mypy]
files = [
  "syndb_api_client",
  #"test",  # auto-generated tests
  "tests", # hand-written tests
]
# TODO: enable "strict" once all these individual checks are passing
# strict = true

# List from: https://mypy.readthedocs.io/en/stable/existing_code.html#introduce-stricter-options
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true

## Getting these passing should be easy
strict_equality = true
strict_concatenate = true

## Strongly recommend enabling this one as soon as you can
check_untyped_defs = true

## These shouldn't be too much additional work, but may be tricky to
## get passing if you use a lot of untyped libraries
disallow_subclassing_any = true
disallow_untyped_decorators = true
disallow_any_generics = true

### These next few are various gradations of forcing use of type annotations
#disallow_untyped_calls = true
#disallow_incomplete_defs = true
#disallow_untyped_defs = true
#
### This one isn't too hard to get passing, but return on investment is lower
#no_implicit_reexport = true
#
### This one can be tricky to get passing if you use a lot of untyped libraries
#warn_return_any = true
```

### Poetry Runtime Logs

```bash session
- Adding: openapi-client/syndb_api_client/__init__.py
  - Adding: openapi-client/syndb_api_client/api/__init__.py
  - Adding: openapi-client/syndb_api_client/api/auth_api.py
  - Adding: openapi-client/syndb_api_client/api/dataset_api.py
  - Adding: openapi-client/syndb_api_client/api/default_api.py
  - Adding: openapi-client/syndb_api_client/api/external_api.py
  - Adding: openapi-client/syndb_api_client/api/github_api.py
  - Adding: openapi-client/syndb_api_client/api/google_api.py
  - Adding: openapi-client/syndb_api_client/api/io_api.py
  - Adding: openapi-client/syndb_api_client/api/metadata_api.py
  - Adding: openapi-client/syndb_api_client/api/neurodata_api.py
  - Adding: openapi-client/syndb_api_client/api/oauth_api.py
  - Adding: openapi-client/syndb_api_client/api/tag_api.py
  - Adding: openapi-client/syndb_api_client/api/user_api.py
  - Adding: openapi-client/syndb_api_client/api_client.py
  - Adding: openapi-client/syndb_api_client/api_response.py
  - Adding: openapi-client/syndb_api_client/configuration.py
  - Adding: openapi-client/syndb_api_client/exceptions.py
  - Adding: openapi-client/syndb_api_client/models/__init__.py
  - Adding: openapi-client/syndb_api_client/models/animal_model_create_read.py
  - Adding: openapi-client/syndb_api_client/models/animal_model_just_read.py
  - Adding: openapi-client/syndb_api_client/models/bearer_response.py
  - Adding: openapi-client/syndb_api_client/models/body_verify_request_token_user_auth_request_verify_token_post.py
  - Adding: openapi-client/syndb_api_client/models/body_verify_verify_user_auth_verify_post.py
  - Adding: openapi-client/syndb_api_client/models/brain_region_create_read.py
  - Adding: openapi-client/syndb_api_client/models/brain_region_just_read.py
  - Adding: openapi-client/syndb_api_client/models/brain_structure.py
  - Adding: openapi-client/syndb_api_client/models/create_read_dataset_collection_model.py
  - Adding: openapi-client/syndb_api_client/models/dataset_search_model.py
  - Adding: openapi-client/syndb_api_client/models/detail.py
  - Adding: openapi-client/syndb_api_client/models/error_model.py
  - Adding: openapi-client/syndb_api_client/models/filter_datasets.py
  - Adding: openapi-client/syndb_api_client/models/gene_expression.py
  - Adding: openapi-client/syndb_api_client/models/http_validation_error.py
  - Adding: openapi-client/syndb_api_client/models/id2_label_response.py
  - Adding: openapi-client/syndb_api_client/models/id_response.py
  - Adding: openapi-client/syndb_api_client/models/ids_response.py
  - Adding: openapi-client/syndb_api_client/models/location_inner.py
  - Adding: openapi-client/syndb_api_client/models/microscopy_create_read.py
  - Adding: openapi-client/syndb_api_client/models/mutation_model_create_read.py
  - Adding: openapi-client/syndb_api_client/models/mutation_model_just_read.py
  - Adding: openapi-client/syndb_api_client/models/neuroanatomical_direction.py
  - Adding: openapi-client/syndb_api_client/models/new_dataset.py
  - Adding: openapi-client/syndb_api_client/models/o_auth2_authorize_response.py
  - Adding: openapi-client/syndb_api_client/models/pre_signed_s3_schema.py
  - Adding: openapi-client/syndb_api_client/models/publication_create_read.py
  - Adding: openapi-client/syndb_api_client/models/s3_instance.py
  - Adding: openapi-client/syndb_api_client/models/s3_pre_signed_download_request.py
  - Adding: openapi-client/syndb_api_client/models/search_result_data_download.py
  - Adding: openapi-client/syndb_api_client/models/syndb_table.py
  - Adding: openapi-client/syndb_api_client/models/universal_metadata_response.py
  - Adding: openapi-client/syndb_api_client/models/uploaded_single_dataset.py
  - Adding: openapi-client/syndb_api_client/models/user_create.py
  - Adding: openapi-client/syndb_api_client/models/user_metadata_response.py
  - Adding: openapi-client/syndb_api_client/models/user_profile.py
  - Adding: openapi-client/syndb_api_client/models/user_read.py
  - Adding: openapi-client/syndb_api_client/models/validation_error.py
  - Adding: openapi-client/syndb_api_client/py.typed
  - Adding: openapi-client/syndb_api_client/rest.py
  - Adding: openapi-client/syndb_api_client/py.typed
  - Adding: pyproject.toml
  - Adding: README.md

  Stack trace:

  16  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py:327 in run
       325│ 
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

  15  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py:190 in _run
       188│         self._load_plugins(io)
       189│ 
     → 190│         exit_code: int = super()._run(io)
       191│         return exit_code
       192│ 

  14  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│ 
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│ 

  13  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py:473 in _run_command
       471│ 
       472│         if error is not None:
     → 473│             raise error
       474│ 
       475│         return terminate_event.exit_code

  12  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py:457 in _run_command
       455│ 
       456│             if command_event.command_should_run():
     → 457│                 exit_code = command.run(io)
       458│             else:
       459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

  11  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/commands/base_command.py:117 in run
       115│         io.input.validate()
       116│ 
     → 117│         return self.execute(io) or 0
       118│ 
       119│     def merge_application_definition(self, merge_args: bool = True) -> None:

  10  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/commands/command.py:61 in execute
        59│ 
        60│         try:
     →  61│             return self.handle()
        62│         except KeyboardInterrupt:
        63│             return 1

   9  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/commands/publish.py:77 in handle
        75│                 return 1
        76│ 
     →  77│             self.call("build", args=f"--output {dist_dir}")
        78│ 
        79│         files = publisher.files

   8  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/commands/command.py:78 in call
        76│         command = self.application.get(name)
        77│ 
     →  78│         return self.application._run_command(
        79│             command, self._io.with_input(StringInput(args or ""))
        80│         )

   7  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py:473 in _run_command
       471│ 
       472│         if error is not None:
     → 473│             raise error
       474│ 
       475│         return terminate_event.exit_code

   6  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py:457 in _run_command
       455│ 
       456│             if command_event.command_should_run():
     → 457│                 exit_code = command.run(io)
       458│             else:
       459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

   5  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/commands/base_command.py:117 in run
       115│         io.input.validate()
       116│ 
     → 117│         return self.execute(io) or 0
       118│ 
       119│     def merge_application_definition(self, merge_args: bool = True) -> None:

   4  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/commands/command.py:61 in execute
        59│ 
        60│         try:
     →  61│             return self.handle()
        62│         except KeyboardInterrupt:
        63│             return 1

   3  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/commands/build.py:66 in handle
        64│             if not dist_dir.is_absolute():
        65│                 dist_dir = self.poetry.pyproject_path.parent / dist_dir
     →  66│             self._build(fmt, executable=env.python, target_dir=dist_dir)
        67│ 
        68│         return 0

   2  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/commands/build.py:49 in _build
        47│ 
        48│         for builder in builders:
     →  49│             builder(self.poetry, executable=executable).build(target_dir)
        50│ 
        51│     def handle(self) -> int:

   1  ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/core/masonry/builders/sdist.py:83 in build
        81│ 
        82│             for file in sorted(files_to_add, key=lambda x: x.relative_to_source_root()):
     →  83│                 tar_info = tar.gettarinfo(
        84│                     str(file.path),
        85│                     arcname=pjoin(tar_dir, str(file.relative_to_source_root())),

  FileNotFoundError

  [Errno 2] No such file or directory: '/data/can/Projects/SynDB/backend/syndb-api/openapi-client/openapi-client/syndb_api_client/__init__.py'

  at /usr/lib/python3.12/tarfile.py:2037 in gettarinfo
      2033│ 
      2034│         # Use os.stat or os.lstat, depending on if symlinks shall be resolved.
      2035│         if fileobj is None:
      2036│             if not self.dereference:
    → 2037│                 statres = os.lstat(name)
      2038│             else:
      2039│                 statres = os.stat(name)
      2040│         else:
      2041│             statres = os.fstat(fileobj.fileno())
```
