### ISSUE TITLE
Pre-Commit Hooks not working

### ISSUE THREAD

**Issue by kharigardner** [python-poetry/poetry#9544]
### Description

Recently, my pre-commit hooks for poetry have stopped working, no matter if i do a `pre-commit gc`, `pre-commit clean` etc:

Config:
```yaml
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-install
        args: [--sync, --with, "dev,docs,iac", -E, datascience]
```

Output:
```bash
poetry-install...........................................................Failed
- hook id: poetry-install
- exit code: 1

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Khari.Gardner\.cache\pre-commit\repot2z2bkud\py_env-python3.11\Scripts\poetry.EXE\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'poetry.console'
```

### Workarounds

None - if i wipe the cache, the poetry install hook on the next run will fail saying its installing packages

### Poetry Installation Method

pipx

### Operating System

Windows 11

### Poetry Version

1.8.3

### Poetry Configuration

```bash session
cache-dir = "C:\\Users\\Khari.Gardner\\AppData\\Local\\pypoetry\\Cache"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true  
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
repositories.gitlab_private.url = "xxxxxxxxxxx"
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}\\virtualenvs"  # C:\Users\Khari.Gardner\AppData\Local\pypoetry\Cache\virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```
```


### Python Sysconfig

_No response_

### Example pyproject.toml

_No response_

### Poetry Runtime Logs

```bash session
N/A
```
