### ISSUE TITLE
How to inherit extra package index from other directory in poetry?

### ISSUE THREAD

**Issue by young-hun-jo** [python-poetry/poetry#9555]
### Issue Kind

Brand new capability

### Description

I am currently using Poetry with the following project structure:

```
root
ㄴ app1
    ㄴ pyproject.toml
ㄴ app2
    ㄴ pyproject.toml
ㄴ common
    ㄴ component
        ㄴ utils.py
        ㄴ functions.py
    ㄴ pyproject.toml
```
common is a package that is used by both app1 and app2. In app1, I want to use the packages defined in common as well as the packages defined in the `pyproject.toml` file within the app1 directory. you note that there is package from extra package index in `pyproject.toml` file in `common` directory.

For example, content of two `pyproject.toml` files is below.
- `pyproject.toml` file in `common` directory
```toml
[tool.poetry]
name = "component"
version = "1.0.0"
description = "common utils"

[tool.poetry.dependencies]
numpy = "1.26.0"
pandas = ">=1.4.3,<2"
google-api-core = "2.17"
extra-pkg = { version = "1.0.0", source = "extra-private-pypi"}

[[tool.poetry.source]]
name = "extra-private-pypi"
url = "https://extra-private-pypi.com"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
- `pyproject.toml` file in `app1` directory
```toml
[tool.poetry]
package-mode = false
description = "app1"

[tool.poetry.dependencies]
python = "3.10.14"
scikit-learn = "1.3.2"
component = { path = "../common"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonary.api"
```

After defining above files, move `app1` directory and run `poetry install`, but below error occured. 
```
Repository "extra-private-pypi" does not exist.
```
I think the error means that `pyproject.toml` in `app1` directory can't recognize extra package defined `pyproject.toml` in `common` directory. How to do for `pyproject.toml` in `app1` directory to  recognize extra package defined `pyproject.toml` in `common` directory? 

I try to move only extra package index source(`tool.poetry.source` in TOML file) in `pyproject.toml` from `common` to `app1`, this probelm is solved. A example `pyproject.toml` file in `app1` directory is below. 
```toml
[tool.poetry]
package-mode = false
description = "app1"

[tool.poetry.dependencies]
python = "3.10.14"
scikit-learn = "1.3.2"
component = { path = "../common"}

[[tool.poetry.source]]
name = "extra-private-pypi"
url = "https://extra-private-pypi.com"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonary.api"
```
This is the only solution for this error? 

### Impact

I think that anyone who has structure of project like me. this issue is useful for them.

### Workarounds

No
