### ISSUE TITLE
Enable extracting individual dependencies

### ISSUE THREAD

**Issue by paduszyk** [python-poetry/poetry#9703]
### Issue Kind

Brand new capability

### Description

I have recently come up with the idea that a useful feature would be to have the possibility of "extracting" individual dependencies with the versions read from either `pyproject.toml` or `package.lock`.

```console
poetry install --extract PACKAGE
```

### Impact

Sometimes, one needs to install a single package, preferably with the version consistent with Poetry's files.

For example, one may need `ruff` to lint and format their codebase in CI. `ruff` does not need anything except the codebase and itself.

If you put it to `dev` dependencies:

```toml
[tool.poetry.group.dev.dependencies]
# ...
ruff = "^0.6.7"
# ...
```

then you can install it by:

```console
poetry install --only dev
```

but this will unnecessarily install other `dev` dependencies if any.

### Workarounds

A workaround here is to define a separate group for a single dependency one would to "extract":

```toml
[tool.poetry.group.ruff.dependencies]
# ...
ruff = "^0.6.7"
# ...
```

Then:

```console
poetry install --only ruff
```

handles the issue.
