### ISSUE TITLE
poetry search does not use private repository

### ISSUE THREAD

**Issue by ifelsefi** [python-poetry/poetry#9771]
### Description

poetry search wont use private repo but tries pypi on an airgapped server.  

### Workarounds

None

### Poetry Installation Method

pipx

### Operating System

Rocky Linux

### Poetry Version

$ poetry --version Poetry (version 1.8.4)

### Poetry Configuration

```bash session
$ poetry config --list
cache-dir = "/home/user/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
repositories.ql.url = "https://artifactory/artifactory/api/pypi/pypi/simple/"
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/user/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Example pyproject.toml

```TOML
$ cat pyproject.toml
[tool.poetry]
name = "env"
version = "0.1.0"
description = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyqt5-qt5 = "5.15.2"
pyzmq = "^26.0.3"
pyqtwebengine-qt5 = "5.15.2"
spyder = "^5.5.5"
numpy = "^2.0.0"
torch = "2.3.1"
torchvision = "0.18.1"
torchaudio = "2.3.1"
pandas = "^2.2.2"
scikit-learn = "^1.5.1"
optuna = "^3.6.1"
seaborn = "^0.13.2"

[[tool.poetry.source]]
name = "repo"
url = "https://artifactoryartifactory/api/pypi/pypi/simple/"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

```bash session
$ poetry -vvv --no-cache search xgboost
Loading configuration file /home/user/.config/pypoetry/config.toml
[urllib3:urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443

  Stack trace:

  2  ~/.local/share/pipx/venvs/poetry/lib/python3.11/site-packages/urllib3/connection.py:198 in _new_conn
      196│         """
      197│         try:
    → 198│             sock = connection.create_connection(
      199│                 (self._dns_host, self.port),
      200│                 self.timeout,

  1  ~/.local/share/pipx/venvs/poetry/lib/python3.11/site-packages/urllib3/util/connection.py:85 in create_connection
       83│     if err is not None:
       84│         try:
    →  85│             raise err
       86│         finally:
       87│             # Break explicitly a reference cycle

  TimeoutError

  timed out

  at ~/.local/share/pipx/venvs/poetry/lib/python3.11/site-packages/urllib3/util/connection.py:73 in create_connection
       69│             if timeout is not _DEFAULT_TIMEOUT:
       70│                 sock.settimeout(timeout)
       71│             if source_address:
       72│                 sock.bind(source_address)
    →  73│             sock.connect(sa)
       74│             # Break explicitly a reference cycle
       75│             err = None
       76│             return sock
       77│


$ poetry -vvv source show
Loading configuration file /home/user/.config/pypoetry/config.toml
Adding repository ql (https://artifactory/artifactory/api/pypi/pypi/simple) and setting it as primary
Deactivating the PyPI repository
 name      : repo
 url       : https://artifactory/artifactory/api/pypi/pypi/simple/
 priority  : primary



```
