### ISSUE TITLE
Cannot install <random lib>

### ISSUE THREAD

**Issue by JohnConnor123** [python-poetry/poetry#9778]
### Description

I've been trying to install cuml for about 2 days, but with poetry it's not possible :(

[Poetry Runtime Logs.txt](https://github.com/user-attachments/files/17422033/Poetry.Runtime.Logs.txt)

### Poetry Installation Method

pipx

### Operating System

WSL Ubuntu 20.04

### Poetry Version

Poetry (version 1.8.4)

### Poetry Configuration

```bash session
cache-dir = "/home/john/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
repositories.rapids.url = "https://pypi.nvidia.com"
repositories.torch-repo.url = "https://download.pytorch.org/whl/cu121"
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/john/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Python Sysconfig
[python-sysconf.txt](https://github.com/user-attachments/files/17422056/python-sysconf.txt)

### Example pyproject.toml

```TOML
[tool.poetry]
name = "skoltech"
version = "0.1.0"
description = ""
authors = ["JohnConnor123 <ivan.eudokimoff2014@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.10"
torch = {version = "^2.4.1+cu121", source = "torch-repo"}
torchaudio = {version = "^2.4.1+cu121", source = "torch-repo"}
torchvision = {version = "^0.19.1+cu121", source = "torch-repo"}
pandas = "^2.2"
matplotlib = "^3.9.2"
seaborn = "^0.13.2"
openpyxl = "^3.1.5"
transformers = "^4.45.1"
tqdm = "^4.66.5"
ipywidgets = "^8.1.5"
datasets = "^3.0.1"
plotly = "^5.24.1"
nbformat = "^5.10.4"
llvmlite = "^0.43.0"
umap-learn = "^0.5.6"
scikit-learn = "^1.5.2"
cuml-cu12 = { version="^24", source="rapids" }
cudf-cu12 = { version="^24" , source="rapids" }
dask-cudf-cu12 = { version="^24", source="rapids" }


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "torch-repo"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[[tool.poetry.source]]
name="rapids"
url="https://pypi.nvidia.com"
priority = "explicit"
```
