### ISSUE TITLE
segmentation fault during poetry lock

### ISSUE THREAD

**Issue by JohannesMessner** [python-poetry/poetry#9796]
### Description

Hi poetry team!
I'm observing the following error:

```console
inception-py3.12johannes_messner@dev-01:/home/johannes_messner/inception$ poetry lock -vvv
Loading configuration file /home/johannes.messner/.config/pypoetry/config.toml
Loading configuration file /home/johannes.messner/.config/pypoetry/auth.toml
Adding repository gitlab-package-695 (https://gitlab.aleph-alpha.de/api/v4/projects/695/packages/pypi/simple) and setting it as supplemental
Using virtualenv: /home/johannes_messner/.cache/pypoetry/virtualenvs/inception-1q-aUeiC-py3.12
Updating dependencies
Resolving dependencies...
   1: fact: inception is 0.1.0
   1: derived: inception
[virtualenv] find interpreter for spec PythonSpec(path=/home/johannes_messner/.local/share/pypoetry/venv/bin/python)
[virtualenv] filesystem is case-sensitive
[filelock:filelock] Attempting to acquire lock 139844274873520 on /home/johannes_messner/.local/share/virtualenv/py_info/1/ef932dbae9e246f82fbad7f0401af39b204164019d6d6042543849f901bde796.lock
[filelock:filelock] Lock 139844274873520 acquired on /home/johannes_messner/.local/share/virtualenv/py_info/1/ef932dbae9e246f82fbad7f0401af39b204164019d6d6042543849f901bde796.lock
[virtualenv] got python info of %s from (PosixPath('/home/johannes_messner/miniconda3/bin/python'), PosixPath('/home/johannes_messner/.local/share/virtualenv/py_info/1/ef932dbae9e246f82fbad7f0401af39b204164019d6d6042543849f901bde796.json'))
[filelock:filelock] Attempting to release lock 139844274873520 on /home/johannes_messner/.local/share/virtualenv/py_info/1/ef932dbae9e246f82fbad7f0401af39b204164019d6d6042543849f901bde796.lock
[filelock:filelock] Lock 139844274873520 released on /home/johannes_messner/.local/share/virtualenv/py_info/1/ef932dbae9e246f82fbad7f0401af39b204164019d6d6042543849f901bde796.lock
[virtualenv] proposed PythonInfo(spec=CPython3.12.4.final.0-64, system=/home/johannes_messner/miniconda3/bin/python, exe=/home/johannes_messner/.local/share/pypoetry/venv/bin/python, platform=linux, version='3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]', encoding_fs_io=utf-8-utf-8)
[virtualenv] accepted PythonInfo(spec=CPython3.12.4.final.0-64, system=/home/johannes_messner/miniconda3/bin/python, exe=/home/johannes_messner/.local/share/pypoetry/venv/bin/python, platform=linux, version='3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]', encoding_fs_io=utf-8-utf-8)
Segmentation fault (core dumped)
```

Interestingly, this only happens on my linux (Ubuntu 22.04.5 LTS) machine, on my Mac everything works fine.

The pyproject.toml is attached below.

Not sure if it is related, but this error started to occur some time after adding the `agent_utils` is a local dependency, which has the follpwing pyproject.toml:

```toml
[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "agent_utils" 
version = "0.1.0"

[tool.setuptools]
packages = ["agent_utils"]
```

I appreciate that it's probably hard to reproduce the error from the information given here, but I'd be grateful for any help or pointers!

### Workarounds

none that i know of

### Poetry Installation Method

install.python-poetry.org

### Operating System

Ubuntu 22.04.5 LTS

### Poetry Version

Poetry (version 1.8.3)

### Poetry Configuration

```bash session
cache-dir = "/home/johannes.messner/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
repositories.gitlab.url = "https://gitlab.aleph-alpha.de/api/v4/projects/885/packages/pypi"
repositories.gitlab-package-695.url = "https://gitlab.aleph-alpha.de/api/v4/projects/695/packages/pypi/simple"
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/johannes.messner/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Example pyproject.toml

```TOML
[tool.poetry]
name = "inception"
version = "0.1.0"
description = "xxx"
authors = ["xxx"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">= 3.10, <3.13"
pydantic = "^2.7.1"
aleph-alpha-client = "^7.1.0"
datasets = "^2.19.2"
openai = "^1.31.0"
python-dotenv = "^1.0.1"
typer = "^0.12.3"
uvloop = "^0.19.0"
pytest-asyncio = "^0.23.7"
wandb = "^0.17.5"
transformers = "^4.44.2"
scikit-learn = "^1.5.1"
huggingface-hub = "0.23.3"
seaborn = "^0.13.2"
determined = "0.26.4"
xformers = "^0.0.27.post2"
tensorboard = "^2.17.1"
plotly = "^5.24.1"
agent_utils = {path="./src/agent_utils", develop=true}


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pre-commit = "^3.7.1"
mypy = "^1.9.0"
ipykernel = "^6.29.5"

[tool.poetry.scripts]
start = "src.inception.inception:main"

[[tool.poetry.source]]
name = "gitlab-package-695"
url = "https://gitlab.aleph-alpha.de/api/v4/projects/695/packages/pypi/simple"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["F401"]


[tool.mypy]
plugins = "pydantic.mypy"
disallow_untyped_defs = false
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "aleph_alpha_project_template.*"
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["./tests", "src/agent_utils/tests"]
asyncio_mode="auto"
```

### Poetry Runtime Logs

```bash session
inception-py3.12johannes_messner@dev-01:/home/johannes_messner/inception$ poetry lock -vvv
Loading configuration file /home/johannes.messner/.config/pypoetry/config.toml
Loading configuration file /home/johannes.messner/.config/pypoetry/auth.toml
Adding repository gitlab-package-695 (https://gitlab.aleph-alpha.de/api/v4/projects/695/packages/pypi/simple) and setting it as supplemental
Using virtualenv: /home/johannes_messner/.cache/pypoetry/virtualenvs/inception-1q-aUeiC-py3.12
Updating dependencies
Resolving dependencies...
   1: fact: inception is 0.1.0
   1: derived: inception
[virtualenv] find interpreter for spec PythonSpec(path=/home/johannes_messner/.local/share/pypoetry/venv/bin/python)
[virtualenv] filesystem is case-sensitive
[filelock:filelock] Attempting to acquire lock 139844274873520 on /home/johannes_messner/.local/share/virtualenv/py_info/1/ef932dbae9e246f82fbad7f0401af39b204164019d6d6042543849f901bde796.lock
[filelock:filelock] Lock 139844274873520 acquired on /home/johannes_messner/.local/share/virtualenv/py_info/1/ef932dbae9e246f82fbad7f0401af39b204164019d6d6042543849f901bde796.lock
[virtualenv] got python info of %s from (PosixPath('/home/johannes_messner/miniconda3/bin/python'), PosixPath('/home/johannes_messner/.local/share/virtualenv/py_info/1/ef932dbae9e246f82fbad7f0401af39b204164019d6d6042543849f901bde796.json'))
[filelock:filelock] Attempting to release lock 139844274873520 on /home/johannes_messner/.local/share/virtualenv/py_info/1/ef932dbae9e246f82fbad7f0401af39b204164019d6d6042543849f901bde796.lock
[filelock:filelock] Lock 139844274873520 released on /home/johannes_messner/.local/share/virtualenv/py_info/1/ef932dbae9e246f82fbad7f0401af39b204164019d6d6042543849f901bde796.lock
[virtualenv] proposed PythonInfo(spec=CPython3.12.4.final.0-64, system=/home/johannes_messner/miniconda3/bin/python, exe=/home/johannes_messner/.local/share/pypoetry/venv/bin/python, platform=linux, version='3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]', encoding_fs_io=utf-8-utf-8)
[virtualenv] accepted PythonInfo(spec=CPython3.12.4.final.0-64, system=/home/johannes_messner/miniconda3/bin/python, exe=/home/johannes_messner/.local/share/pypoetry/venv/bin/python, platform=linux, version='3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]', encoding_fs_io=utf-8-utf-8)
Segmentation fault (core dumped)
```
