### ISSUE TITLE
Using License EPL-2.0 results in errors when publishing to pypi.org

### ISSUE THREAD

**Issue by netomi** [python-poetry/poetry#9803]
### Description

When specifyingEPL-2.0 as license in the pyproject.toml file, the following classifier is added automatically:

```
License :: OSI Approved :: Eclipse Public License 2.0
```

however, when publishing the wheel to pypi, the publishing fails with an error as the classifier is unknown.

Looking at the currently listed classifiers, you see that the name for EPL licenses slightly changed:

![image](https://github.com/user-attachments/assets/9f291f99-1105-43e0-ab6a-3f3c9be622b9)

### Workarounds

There is no acceptable workaround right now, as there seems to be no way to disable or skip the automatic generation of classifiers from the license.

A workaround is to specify a license like that:

```
license       = "Eclipse Public License 2.0 (EPL-2.0)"
```

however this leads to an classifier added automatically like that:

```
Classifier: License :: Other/Proprietary License
```

which is not really what you want.

### Poetry Installation Method

pipx

### Operating System

Ubuntu 22.04

### Poetry Version

1.8.4

### Poetry Configuration

```bash session
cache-dir = "/home/tn/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/tn/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Example pyproject.toml

```TOML
[tool.poetry]
name          = "otterdog"
version       = "0.8.0-dev"
description   = "Tool to manage GitHub organizations and their repositories."
authors       = ["Thomas Neidhart <thomas.neidhart@eclipse-foundation.org>"]
readme        = "README.md"
license       = "EPL-2.0"
```

### Poetry Runtime Logs

```bash session
N/A
```
