### ISSUE TITLE
Improve debug logging for "Skipping wheel xxx-7.7.2-cp310-cp310-manylinux_2_35_x86_64.whl as this is not supported by the current environment"

### ISSUE THREAD

**Issue by alexanderilyin** [python-poetry/poetry#9837]
### Issue Kind

Change in current behaviour

### Description

There is `partcad` package which depends on `cadquery-ocp`. Wheels for which are provided by:

* https://github.com/CadQuery/ocp-build-system

And poetry ignores compatible wheel which has platform specified as `manylinux`

Give the following configuration:

```toml
[tool.poetry.dependencies]
cadquery-ocp = { version = "^7.7.2" }
```
`poetry install` will fail: [output.txt](https://github.com/user-attachments/files/17673451/output.txt).

When it's running on:

```
⬢ [Docker] ❯ python -c "import sys; print(sys.platform)"
linux
```
```
⬢ [Docker] ❯ lsb_release -d
Description:    Debian GNU/Linux 11 (bullseye)
```

According to the following:

* https://github.com/pypa/manylinux

`cadquery_ocp-7.7.2-cp310-cp310-manylinux_2_35_x86_64.whl` should be selected but in reality it's `not supported by the current environment`

### Impact

It will allow to use Poetry with packages which are distributed for `manylinux` platform.

### Workarounds

Override `sys_platform` using `markers`:

```toml
[tool.poetry.dependencies]
python = "^3.10"
partcad = { version = "^0.7.16", markers = "sys_platform == 'manylinux'" }
```
