### ISSUE TITLE
Poetry very slow while downloading some packages

### ISSUE THREAD

**Issue by BexTuychiev** [python-poetry/poetry#9880]
### Description

So, I encountered this issue with many packages but the one I am experiencing right now is with `streamlit`. After the dependencies are resolved, it takes ages to download `pyarrow`. In fact, I opened and started this issue when the download hit about 40% and didn't even finish when I completed writing this issue. That doesn't seem like normal behavior. 

Can you please suggest what to do?

### Workarounds

I tried `poetry run pip install streamlit` but for this one, the command slows down when downloading Streamlit itself, which is just an 8MB package. I checked my Internet speed and I can watch a 1080p YouTube video without lags. 

### Poetry Installation Method

system package manager (eg: dnf, apt etc.)

### Operating System

macOS Sequoia

### Poetry Version

Poetry (version 1.8.4)

### Poetry Configuration

```bash session
cache-dir = "/Users/bexgboost/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = 10
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/bexgboost/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Example pyproject.toml

```TOML
[tool.poetry]
name = "firecrawl-articles"
version = "0.1.0"
description = "Articles for firecrawl.dev"
authors = ["BexTuychiev <bex@ibexprogramming.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
firecrawl-py = "^1.5.0"
tqdm = "^4.67.0"
websockets = "^14.1"
boto3 = "^1.35.63"
langchain = "^0.3.7"
langchain-community = "^0.3.7"
langchain-openai = "^0.2.8"
onnxruntime-silicon = "^1.16.3"
langchain-anthropic = "^0.3.0"
rich = "^13.9.4"
pydantic = "^2.9.2"
plotly = "^5.24.1"
pandas = "^2.2.3"
seaborn = "^0.13.2"
matplotlib = "^3.9.2"


[tool.poetry.group.deploy.dependencies]
toml = "^0.10.2"
notebook = "6.4.12"
nbconvert = "^7.16.4"



[tool.poetry.group.scraping.dependencies]
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"
schedule = "^1.2.2"
asyncio = "^3.4.3"


[tool.poetry.group.dev.dependencies]
pipreqs = "^0.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

```bash session
See description as no command is failing.
```
