### ISSUE TITLE
poetry 2.0, adding `source` section fails if there is no pre-existing `[tool.poetry]` section in the pyproject.toml

### ISSUE THREAD

**Issue by sandrinesuire** [python-poetry/poetry#9913]
### Description

with poetry 2.0.0 in main branche

`poetry list`

return   
  ```
...
source add         Add source configuration for project.
source remove      Remove source configured for the project.
source show        Show information about sources configured for the project.
```

`
C:\git\....>poetry source add foo https://my_private_repos/api/pypi/common-pypi/simple/
`

return this error

`[tool.poetry] section not found in C:/git/..../pyproject.toml`

### Workarounds

nothing

### Poetry Installation Method

pipx

### Operating System

windows 10

### Poetry Version

branch main 2.0.0

### Poetry Configuration

```bash session
nothing
```

### Python Sysconfig

```bash session
nothing
```

### Example pyproject.toml

```TOML
[project]
name = "crude..."
version = "0.1.0"
description = ""
authors = [
    {name = "...",email = "sandrine....@....com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "websockets (<=12.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

```bash session
nothing
```
