### ISSUE TITLE
build-system does not work with peotry

### ISSUE THREAD

**Issue by nnsay** [python-poetry/poetry#9955]
### Description

I want to build my project with poetry. The steps like below:
1. config the pyproject.toml
```toml
[tool.poetry.group.dev.dependencies]
autopep8 = "2.0.2"
pytest = "7.2.0"
pytest-sugar = "0.9.7"
pytest-cov = "4.1.0"
pytest-html = "3.2.0"
pre-commit = "^3.6.0"
ruff = "^0.2.0"
python-semantic-release = "^9.1.0"
build = "^1.2.1"
cython = "^3.0.10"
setuptools = "^69.5.1"
wheel = "^0.43.0"
coverage = "^7.5.0"
mypy = "^1.10.0"

[build-system]
requires = ["poetry-core", "Cython", "setuptools", "mypy"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
script = "build.py"
generate-setup-file = false
```
2.  custom build.py
```python
import os
import shutil
import subprocess

from Cython.Build import cythonize
from setuptools import setup
from setuptools.command.build_ext import build_ext


class CustomBuildExt(build_ext):
  """Custom build_ext command to run stubgen and cython extensions."""

  def run(self):
    module_path = 'object_storage'
    stub_dir = '.types'
    subprocess.run(['stubgen', '-o', stub_dir, '-p', module_path])
    generated_stub_dir = os.path.join(stub_dir, module_path)
    shutil.copytree(generated_stub_dir, module_path, dirs_exist_ok=True)
    super().run()


setup(
  name='object-storage',
  ext_modules=cythonize('object_storage/*.py'),
  cmdclass={
    'build_ext': CustomBuildExt,
  },
  script_args=['build_ext', '--inplace'],
)
```
3. build and test
```bash
➜  object-storage git:(cython) poetry build                                                  
Preparing build environment with build-system requirements poetry-core, Cython, setuptools, mypy
Building object-storage (1.0.2)
  - Building sdist
  - Built object_storage-1.0.2.tar.gz
  - Building wheel
running build_ext
error: [Errno 2] No such file or directory: 'stubgen'

Command '['/var/folders/yt/3470fws56wqck_qkbkd3jyx80000gn/T/tmpnvicv39y/.venv/bin/python', 'build.py']' returned non-zero exit status 1.

```
I expect the build step could find the `stubgen` and generate the pyi files, but the `stubgen` could not found in mypy. I have add the `mypy` in `build-system`, so why not it doesn't work?

### Workarounds

yes, install a global `mypy` package.

### Poetry Installation Method

pipx

### Operating System

macOS 15.2

### Poetry Version

Poetry (version 2.0.0)

### Poetry Configuration

```bash session
cache-dir = "/Users/wangjian/Library/Caches/pypoetry"
installer.max-workers = null
installer.no-binary = null
installer.only-binary = null
installer.parallel = true
installer.re-resolve = true
keyring.enabled = true
requests.max-retries = 0
solver.lazy-wheel = true
system-git-client = false
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/wangjian/Library/Caches/pypoetry/virtualenvs
virtualenvs.prompt = "{project_name}-py{python_version}"
virtualenvs.use-poetry-python = false
```

### Example pyproject.toml

```TOML
[tool.coverage.run]
branch = true
source = ["object_storage"]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report html:'coverage/packages/object-storage/html' --cov-report json:'coverage/packages/object-storage/coverage-summary.json'"

[tool.poetry]
name = "object-storage"
version = "1.0.2"
description = "Automatically generated by Nx."
authors = ["Jimmy Wang <jimmy.w@aliyun.com>"]
license = 'Proprietary'
readme = 'README.md'
include = ["object_storage/**/*.so", "object_storage/**/*.pyi"]
exclude = ["object_storage/**/*.py"]


[tool.poetry.dependencies]
python = ">=3.9"
boto3 = "^1.34.65"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.0.2"
pytest = "7.2.0"
pytest-sugar = "0.9.7"
pytest-cov = "4.1.0"
pytest-html = "3.2.0"
pre-commit = "^3.6.0"
ruff = "^0.2.0"
python-semantic-release = "^9.1.0"
build = "^1.2.1"
cython = "^3.0.10"
setuptools = "^69.5.1"
wheel = "^0.43.0"
coverage = "^7.5.0"
mypy = "^1.10.0"

[build-system]
requires = ["poetry-core", "Cython", "setuptools", "mypy"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
script = "build.py"
generate-setup-file = false

[tool.ruff]
line-length = 110
indent-width = 2

[tool.ruff.lint]
preview = true
select = ["E", "F", "UP", "B", "SIM", "I"]
ignore = ["E111", "E114"]

[tool.ruff.format]
preview = true
quote-style = "single"
docstring-code-format = true

[tool.semantic_release]
assets = []
version_toml = ["pyproject.toml:tool.poetry.version"]
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
tag_format = "{version}"

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = []

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[tool.semantic_release.commit_parser_options]
allowed_tags = [
"build",
"chore",
"ci",
"docs",
"feat",
"fix",
"perf",
"style",
"refactor",
"test",
]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
default_bump_level = 0

[tool.semantic_release.remote]
name = "origin"
type = "github"
```

### Poetry Runtime Logs

```bash session
running build_ext
error: [Errno 2] No such file or directory: 'stubgen'

  Stack trace:

  12  ~/.local/share/uv/tools/poetry/lib/python3.13/site-packages/cleo/application.py:327 in run
       325│ 
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

  11  ~/.local/share/uv/tools/poetry/lib/python3.13/site-packages/poetry/console/application.py:236 in _run
       234│ 
       235│         with directory(self._working_directory):
     → 236│             exit_code: int = super()._run(io)
       237│ 
       238│         return exit_code

  10  ~/.local/share/uv/tools/poetry/lib/python3.13/site-packages/cleo/application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│ 
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│ 

   9  ~/.local/share/uv/tools/poetry/lib/python3.13/site-packages/cleo/application.py:473 in _run_command
       471│ 
       472│         if error is not None:
     → 473│             raise error
       474│ 
       475│         return terminate_event.exit_code

   8  ~/.local/share/uv/tools/poetry/lib/python3.13/site-packages/cleo/application.py:457 in _run_command
       455│ 
       456│             if command_event.command_should_run():
     → 457│                 exit_code = command.run(io)
       458│             else:
       459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

   7  ~/.local/share/uv/tools/poetry/lib/python3.13/site-packages/cleo/commands/base_command.py:117 in run
       115│         io.input.validate()
       116│ 
     → 117│         return self.execute(io) or 0
       118│ 
       119│     def merge_application_definition(self, merge_args: bool = True) -> None:

   6  ~/.local/share/uv/tools/poetry/lib/python3.13/site-packages/cleo/commands/command.py:61 in execute
        59│ 
        60│         try:
     →  61│             return self.handle()
        62│         except KeyboardInterrupt:
        63│             return 1

   5  ~/.local/share/uv/tools/poetry/lib/python3.13/site-packages/poetry/console/commands/build.py:93 in handle
        91│                 remove_directory(path=dist_dir, force=True)
        92│ 
     →  93│             self._build(fmt, executable=env.python, target_dir=dist_dir)
        94│ 
        95│         return 0

   4  ~/.local/share/uv/tools/poetry/lib/python3.13/site-packages/poetry/console/commands/build.py:72 in _build
        70│ 
        71│         for builder in builders:
     →  72│             builder(self.poetry, executable=executable).build(target_dir)
        73│ 
        74│     def handle(self) -> int:

   3  ~/.local/share/uv/tools/poetry/lib/python3.13/site-packages/poetry/core/masonry/builders/wheel.py:130 in build
       128│                 self._build(zip_file)
       129│             else:
     → 130│                 self._build(zip_file)
       131│                 self._copy_module(zip_file)
       132│ 

   2  ~/.local/share/uv/tools/poetry/lib/python3.13/site-packages/poetry/core/masonry/builders/wheel.py:179 in _build
       177│                 try:
       178│                     os.chdir(self._path)
     → 179│                     self._run_build_script(self._package.build_script)
       180│                 finally:
       181│                     os.chdir(current_path)

   1  ~/.local/share/uv/tools/poetry/lib/python3.13/site-packages/poetry/core/masonry/builders/wheel.py:300 in _run_build_script
       298│     def _run_build_script(self, build_script: str) -> None:
       299│         logger.debug(f"Executing build script: {build_script}")
     → 300│         subprocess.check_call([self.executable.as_posix(), build_script])
       301│ 
       302│     def _copy_module(self, wheel: zipfile.ZipFile) -> None:

  CalledProcessError

  Command '['/var/folders/yt/3470fws56wqck_qkbkd3jyx80000gn/T/tmp16rwevmi/.venv/bin/python', 'build.py']' returned non-zero exit status 1.

  at /opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py:419 in check_call
       415│     if retcode:
       416│         cmd = kwargs.get("args")
       417│         if cmd is None:
       418│             cmd = popenargs[0]
    →  419│         raise CalledProcessError(retcode, cmd)
       420│     return 0
       421│ 
       422│ 
       423│ def check_output(*popenargs, timeout=None, **kwargs):
```
