### ISSUE TITLE
Can not install package in CI

### ISSUE THREAD

**Issue by PythonFZ** [python-poetry/poetry#9957]
### Description

All my poetry projects CI fails with the latest release.
They are using

```yaml
   steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install package
        run: |
          poetry install --no-interaction
```

and just fail with 

```
Installing the current project: znsocket (0.2.8)

'Repository'
Error: Process completed with exit code 1.
```

This seems more or less independent of the requirements as different packages are affected, e.g.:
- https://github.com/zincware/ZnSocket
- https://github.com/zincware/ZnDraw
- https://github.com/zincware/rdkit2ase
- https://github.com/zincware/ZnTrack
- ...
 

### Workarounds

-

### Poetry Installation Method

other

### Operating System

ubuntu-latest

### Poetry Version

v2

### Poetry Configuration

```bash session
see https://github.com/snok/install-poetry
```

### Python Sysconfig

```bash session
3.9 to 3.12
```

### Example pyproject.toml

```TOML
-
```

### Poetry Runtime Logs

```bash session
see e.g. https://github.com/zincware/ZnSocket/actions/runs/12626057845/job/35178634129
```
