### ISSUE TITLE
poetry-core 2.0.0 Ignores include directive

### ISSUE THREAD

**Issue by iago1460** [python-poetry/poetry#9984]
### Description

Hello, I have noticed a silent side-effect after the poetry-core 2.0.0  release.
When including files, these files are not longer carried over.

sample project:

```toml
[tool.poetry]
name = "sample-project"
version = "0.1.0"
description = ""
authors = ["iveloso"]
readme = "README.md"
include = ["certificates/pem", "certificates/key"]

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
``` 

before the command `poetry run pip install -t tmp .` created the certificates directory and its files:

```
% tree tmp 
tmp
├── certificates
│   ├── key
│   └── pem
├── sample_project
│   ├── __init__.py
│   └── __pycache__
│       └── __init__.cpython-311.pyc
└── sample_project-0.1.0.dist-info
    ├── INSTALLER
    ├── METADATA
    ├── RECORD
    ├── REQUESTED
    ├── WHEEL
    └── direct_url.json

5 directories, 10 files
```

### Workarounds

Specify a version lower than 2:

```toml
[build-system]
requires = ["poetry-core<2"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Installation Method

pipx

### Operating System

Darwin

### Poetry Version

1.6.1

### Poetry Configuration

```bash session
cache-dir = "/Users/iveloso/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/iveloso/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
```

### Poetry Runtime Logs

```bash session
Using virtualenv: /Users/iveloso/Library/Caches/pypoetry/virtualenvs/sample-project-o55RxkRM-py3.11
Processing /Users/iveloso/projects/smart-topics/sample_project
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: sample-project
  Building wheel for sample-project (pyproject.toml) ... done
  Created wheel for sample-project: filename=sample_project-0.1.0-py3-none-any.whl size=1076 sha256=7212a09b710b16d4b6582f84666e7156c696032cc5795b8fe8d93f7b9cf74f54
  Stored in directory: /private/var/folders/2y/g7vzfqys5jb296bd2fq6rl_w0000gn/T/pip-ephem-wheel-cache-oj0lpn2l/wheels/8f/a5/56/0b00db8286f2fdfc3676862c77daf310e8625f95c373a05516
Successfully built sample-project
Installing collected packages: sample-project
Successfully installed sample-project-0.1.0
```
